$[ set.mm $]

$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  Constructible numbers
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  This section defines the set of constructible points as complex numbers which
  can be drawn starting from two points (we take ` 0 ` and ` 1 ` ), and taking
  intersections of circles and lines.

  We initially define two sets:
  <UL>
  <LI>geometrically, by recursively adding the intersection points : this is
    ` Constr ` .</LI>
  <LI>algebraically, by using field extensions : this is ` ConstrAlg ` . </LI>
  </UL>

  We then proceed by showing that those two sets are equal.

  This construction is useful for proving the impossibility of doubling the
  cube ( ~ imp2cube ), and of angle trisection ( ~ imp3ang )
$)

$(
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
  Constructible points
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
$)

  ${
    $d e f $.
    isfldext2.1 $e |- .< = { <. e , f >. | ( e /FldExt f /\ ( e [:] f ) = 2 ) } $.
    isfldext2.e $e |- ( ph -> E e. V ) $.
    isfldext2.f $e |- ( ph -> F e. W ) $.
    $( Property of being a quadratic field extension.  Quadratic field
       extensions are field extensions of degree 2.  $)
    isfldext2 $p |- ( ph -> ( F .< E ) <-> ( E /FldExt F /\ ( E [:] F ) = 2 ) ) $=
      ? $.
  $}

  ${
    constrtow2.1 $e |- .< = { <. e , f >. | ( e /FldExt f /\ ( e [:] f ) = 2 ) } $.
    constrtow2.q $e |- Q = ( CCfld |`s QQ ) $.
    constrtow2.a $e |- ( ph -> A e. Constr ) $.
    constrtow2.f $e |- F = ( CCfld fldGen ( QQ u. { A } ) ) $.
    $( If a point ` A ` is geometrically constructible, then there is a
       tower of quadratic field extensions from ` QQ ` to the field ` F `
       generated by ` QQ` and ` A ` . $)
    constrtow2 $p |- ( ph -> E. t e. ( .< Chain Field ) ( ( t ` 0 ) = Q
      /\ ( lastS ` t ) = F ) ) $= ? $.

    $( If a point ` A ` is geometrically constructible, then the degree of the
       field extension ` ( F / QQ ) ` , with ` F ` being the field ` F `
       generated by ` QQ` and ` A ` , is a power of ` 2 ` . $)
    constrtopow2 $p |- ( ph -> E. n e. NN ( F [:] Q ) = ( 2 ^ N ) ) $=
      ? $.
  $}


$(
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
  Impossible constructions
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
$)

  $( Impossibility of doubling the cube.  This is expressed by stating that the
    cubic root of 2, which is the side length of a cube of volume ` 2 ` ,  is
    not constructible. $)
  imp2cube $p |- -. ( 2 ^c ( 1 / 3 ) ) e. Constr $= ? $.

  $( Impossibility of trisecting angles.  This is expressed by stating that the
     cosine of an angle of ` ( _pi / 9 ) ` which would be the third of the
     constructible angle ` ( _pi / 3 ) ` , is not constructible. $)
  imp3ang $p |- -. ( cos ` ( _pi / 9 ) ) e. Constr $= ? $.
