$[ set-main.mm $]
$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  Mathbox for Kunhao Zheng
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
$)


$(
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  Weighted AM-GM inequality
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
$)

  ${
    $d A a b s u v $.  $d A k y $.  $d F a b s u v w $.  $d F k w y $.
    $d F x a b u v w y $.  $d W a b s u v w $.  $d W k w y $.
    $d W x a b u v w y $.  $d a ph b s t u v w $.  $d k ph w y $.
    $d ph x t u v w y $.
    amgmwlem.0 $e |- M = ( mulGrp ` CCfld ) $.
    amgmwlem.1 $e |- ( ph -> A e. Fin ) $.
    amgmwlem.2 $e |- ( ph -> A =/= (/) ) $.
    amgmwlem.3 $e |- ( ph -> F : A --> RR+ ) $.
    amgmwlem.4 $e |- ( ph -> W : A --> RR+ ) $.
    amgmwlem.5 $e |- ( ph -> ( CCfld gsum W ) = 1 ) $.
    $( Weighted version of ~ amgmlem .  (Contributed by Kunhao Zheng,
       19-Jun-2021.) $)
    amgmwlem $p |-
          ( ph -> ( M gsum ( F oF ^c W ) ) <_ ( CCfld gsum ( F oF x. W ) ) ) $=
      ( vk co clog cfv ccnfld cmul crp wcel cr vx vy vw vu vv vs va vb ccxp cof
      vt cgsu ce cle wbr cv cneg cmpt csu wa ffvelcdmda relogcld recnd gsumfsum
      ccom sumeq2dv renegcld negeqd rpcnd mulneg2d eqcomd cfn cvv negex feqmptd
      3eqtrd a1i eqidd offval2 oveq2d negcld eqtrd wf relogf1o ax-mp adantl syl
      wceq off fvres ffnd fveq2d 3eqtr4d crefld cress c1 csubmnd cc0 wss oveq1i
      cc csubg subgsubm crg wb cnring cnfldbas cnfld0 eqid simpli c0g ccmn cmnd
      mp1i syl2anc df-refld ringmnd fdmfifsupp fco gsumsubm gsumsubmcl rpmulcld
      1red rpssre fss sylancl 0red cdiv simpr cpnf cioo ioorp eleqtrrdi clt w3a
      fmpttd caddc 3ad2ant3 fveq2 fvmpt3i cres rpcxpcld negnegd fsumneg logcxpd
      rpred 3eqtr2rd mulcld wf1o f1of anim2i rpcxpcl inidm fcompt sylancr ofval
      rpre mpteq2dva cbs csn cdif cmgp rpmsubg cndrng drngui unitsubm mp2b mpbi
      subsubm submbas cnfld1 ringidval subm0 ccrg cncrng crngmgp submmnd subcmn
      eqtri csubrg cdr resubdrg subrgring cghm cmhm cgim reloggim gimghm ghmmhm
      gsummhm subrgsubg simprl simprr mulcomd caofcom fsumrpcl eqeltrd eqeltrrd
      ringcmn remulcl cicc simpl iccssioo2 sseqtrdi cico ioossico eqsstrri 0lt1
      breqtrrid logccv 3adant1 elioore simp21 remulcld resubcld simp22 readdcld
      cmin eliooord simpld elrpd simprd 1m0e1 breqtrrdi ltsub13d rpaddcl ltnegd
      mpbid fvmptd oveq12d negdid eqtr4d 3brtr4d jensen div1d submid mulcl rpcn
      scvxcvx ssriv fssd fmptco 3brtr3d lenegcon1d eqbrtrrd efle reeflogd ) ADC
      EUIUJMZULMZNOZUMOZPCEQUJZMZULMZNOZUMOZVUIVUNUNAVUJVUOUNUOZVUKVUPUNUOZAPEL
      BLUPZCOZNOZUQZURZVULMZULMZUQZVUJVUOUNAVVFPNRUUAZVUHVEZULMZVUIVVGOZVUJABVU
      SEOZVVBQMZLUSZUQZPLBVUTVVKUIMZNOZURZULMZVVFVVIAVVRBVVPLUSBVVPUQZUQZLUSZVV
      NABVVPLGAVUSBSUTZVVPVWBVVOVWBVUTVVKABRVUSCIVAZVWBVVKABRVUSEJVAZUUFZUUBVBZ
      VCZVDABVVTVVPLVWBVVPVWGUUCVFAVWABVVSLUSZUQBVVKVVAQMZUQZLUSZUQVVNABVVSLGVW
      BVVSVWBVVPVWFVGVCUUDAVWHVWKABVVSVWJLVWBVVPVWIVWBVUTVVKVWCVWEUUEVHVFVHAVWK
      VVMABVWJVVLLVWBVVLVWJVWBVVKVVAVWBVVKVWDVIZVWBVVAVWBVUTVWCVBZVCZVJVKVFVHVP
      UUGAVVEVVMAVVEPLBVVLURZULMVVMAVVDVWOPULALBVVKVVBQEVVCVLRVMGVWDVVBVMSVWBVV
      AVNVQALBREJVOZAVVCVRVSVTABVVLLGVWBVVKVVBVWLVWBVVAVWNWAUUHVDWBVHAVVHVVQPUL
      AVVHLBVUSVUHOZVVGOZURZVVQARTVVGWCZBRVUHWCZVVHVWSWHRTVVGUUIZVWTWDRTVVGUUJZ
      WEAUAUBBBBUIRRRCEVLVLAUAUPZRSZUBUPZRSZUTZUTZVXEVXFTSZUTZVXDVXFUIMRSVXHVXK
      AVXGVXJVXEVXFUUQUUKWFVXDVXFUULWGIJGGBUUMZWIZLVVGVUHBRTUUNUUOALBVWRVVPVWBV
      WRVWQNOZVVPVWBVWQRSVWRVXNWHABRVUSVUHVXMVAVWQRNWJWGVWBVWQVVONABBVUTVVKUIBC
      EVLVLVUSABRCIWKABREJWKGGVXLVWBVUTVRVWBVVKVRUUPWLWBUURWBVTWMAWNVVHULMDRWOM
      ZVUHULMZVVGOVVIVVJABRVUHVXOWNVVGVLWPRDWQOZSZRVXOUUSOWHVXRRXAWRUUTUVAZWSZR
      DVXSWOMZWQOSZVXRVXTUTZRVYAXBOSVYBVYADPUVBOZVXSWOFWTUVCRVYAXCWEPXDSZVXSVXQ
      SVYBVYCXEXFPVXSDXAPWRXGXHUVDUVEFUVFRVXSDVYAVYAXIUVIUVGUVHXJZRVXODVXOXIZUV
      JWEWPDXKOZVXOXKOZPWPDFUVKUVLZVXRVYHVYIWHVYFRVXODVYHVYGVYHXIUVMWEUVSADXLSZ
      VXOXMSZVXOXLSPUVNSVYKAUVOPDFUVPXNZVXRVYLAVYFRVXODVYGUVQXNRDVXOVYGUVRXOWNX
      DSZWNXMSATPUVTOSZVYNVYOWNUWASUWBXJZTPWNXPUWCWEWNXQXNGVVGVXOWNUWDMSZVVGVXO
      WNUWEMSAVVGVXOWNUWFMSVYQVXODVYDRWOFWTUWGVXOWNVVGUWHWEVXOWNVVGUWIXNVXMABRV
      UHTWPVXMGAYCXRZUWJABTVVHPWNVLGTPWQOZSZATPXBOSZVYTVYOWUAVYPTPUWKWETPXCWEVQ
      ZAVWTVXABTVVHWCVXBVWTAWDVXCXNVXMBRTVVGVUHXSXOXPXTAVUIVXPVVGABRVUHDVXOVLGV
      XRAVYFVQZVXMVYGXTWLWMAVUIRSVVJVUJWHABRVUHDVLWPVYJVYMGWUCVXMVYRYAZVUIRNWJW
      GVPAVUOVVEAVUNAPECVULMZULMZVUNRAWUEVUMPULAUAUBBQRECVLGJIVXIVXDVXFVXIVXDAV
      XEVXGUWLVIVXIVXFAVXEVXGUWMVIUWNUWOVTZAWUFBVVKVUTQMZLUSZRAWUFPLBWUHURZULMW
      UIAWUEWUJPULALBVVKVUTQECVLRRGVWDVWCVWPALBRCIVOZVSVTABWUHLGVWBWUHVWBVVKVUT
      VWDVWCYBZVIVDWBABWUHLGHWULUWPUWQZUWRZVBZABTVVDPVLWRXHVYEPXLSAXFPUWSXNZGWU
      BAUAUBBBBQTTTEVVCVLVLVXDTSVXJUTVXDVXFQMZTSAVXDVXFUWTWFABREWCZRTWSZBTEWCJY
      DBRTEYEYFALBVVBTVWBVVAVWMVGYPGGVXLWIZABTVVDTWRWUTGAYGZXRYAAWUFPEULMZYHMZU
      CRUCUPZNOZUQZURZOZPEWVGCVEZVULMZULMZWVBYHMZVUOUQZVVEUNAWVCRSWVHWVLUNUOAUD
      UEUFBREWVGCUGUHWUSAYDVQZAUCRWVFTAWVDRSZUTZWVEWVPWVDAWVOYIVBZVGYPZUGUPZRSZ
      UHUPZRSZUTZWVSWWAUXAMZRWSAWWCWWDWRYJYKMZRWWCWVSWWESWWAWWESWWDWWEWSWWCWVSR
      WWEWVTWWBUXBYLYMWWCWWARWWEWVTWWBYIYLYMWRYJWVSWWAUXCXOYLUXDWFZGAWURRWRYJUX
      EMZWSBWWGEWCJRWWEWWGYLWRYJUXFUXGBRWWGEYEYFIAWRWPWVBYNUXHKUXIAUAUBUKRUFUPW
      VGUDUPUEUPUGUHWVNWVRWWFAVXEVXGVXDVXFYNUOZYOZUKUPZWRWPYKMSZYOZWWJVXDQMZWPW
      WJUXRMZVXFQMZYQMZNOZUQZWWJVXDNOZQMZWWNVXFNOZQMZYQMZUQZWWPWVGOWWJVXDWVGOZQ
      MZWWNVXFWVGOZQMZYQMZYNWWLWXCWWQYNUOZWWRWXDYNUOWWIWWKWXJAVXDVXFWWJUXJUXKWW
      LWXCWWQWWLWWTWXBWWLWWJWWSWWKAWWJTSWWIWWJWRWPUXLZYRZWWLVXDAVXEVXGWWHWWKUXM
      ZVBZUXNZWWLWWNWXAWWKAWWNTSWWIWWKWPWWJWWKYCZWXKUXOZYRWWLVXFAVXEVXGWWHWWKUX
      PZVBZUXNZUXQWWLWWPWWLWWMRSWWORSWWPRSWWLWWJVXDWWKAWWJRSWWIWWKWWJWXKWWKWRWW
      JYNUOZWWJWPYNUOZWWJWRWPUXSZUXTUYAYRWXMYBWWLWWNVXFWWKAWWNRSWWIWWKWWNWXQWWK
      WWJWPWRWXKWXPWWKYGWWKWWJWPWPWRUXRMYNWWKWYAWYBWYCUYBUYCUYDUYEUYAYRZWXRYBWW
      MWWOUYFXOZVBUYGUYHWWLUCWWPWVFWWRRWVGVMWWLWVGVRWWLWVDWWPWHZUTWVEWWQWYFWVEW
      WQWHWWLWVDWWPNYSWFVHWYEWWRVMSWWLWWQVNVQUYIWWLWXIWWTUQZWXBUQZYQMWXDWWLWXFW
      YGWXHWYHYQWWLWXFWWJWWSUQZQMWYGWWLWXEWYIWWJQWWLVXEWXEWYIWHWXMUCVXDWVFWYIRW
      VGWVDVXDWHWVEWWSWVDVXDNYSVHWVGXIZWVEVNZYTWGVTWWLWWJWWSWWLWWJWXLVCWWLWWSWX
      NVCVJWBWWLWXHWWNWXAUQZQMWYHWWLWXGWYLWWNQWWLVXGWXGWYLWHWXRUCVXFWVFWYLRWVGW
      VDVXFWHWVEWXAWVDVXFNYSVHWYJWYKYTWGVTWWLWWNWXAWWLWWNWYDVIWWLWXAWXSVCVJWBUY
      JWWLWWTWXBWWLWWTWXOVCWWLWXBWXTVCUYKUYLUYMUYSUYNUYBAWVHWUFWPYHMZWVGOWUFWVG
      OZWVMAWVCWYMWVGAWVBWPWUFYHKVTWLAWYMWUFWVGAWUFAWUFWUMVIUYOWLAWYNWUFNOZUQZW
      VMAWUFRSWYNWYPWHWUMUCWUFWVFWYPRWVGWVDWUFWHWVEWYOWVDWUFNYSVHWYJWYKYTWGAWYO
      VUOAWUFVUNNWUGWLVHWBVPAWVLWVKWPYHMWVKVVEAWVBWPWVKYHKVTAWVKABXAWVJPVLWRXHW
      UPGPXMSZXAVYSSAVYEWYQXFPXQWEXAPXGUYPXNAUAUBBBBQXAXAXAEWVIVLVLVXDXASVXFXAS
      UTWUQXASAVXDVXFUYQWFABRXAEJRXAWSAUARXAVXDUYRUYTVQVUAARXAWVGWCBRCWCBXAWVIW
      CAUCRWVFXAWVPWVEWVPWVEWVQVCWAYPIBRXAWVGCXSXOGGVXLWIZABXAWVJTWRWYRGWVAXRYA
      UYOAWVJVVDPULAWVIVVCEVULALUCBRVUTWVFVVBCWVGVWCWUKAWVGVRWVDVUTWHWVEVVAWVDV
      UTNYSVHVUBVTVTVPVUCVUDVUEAVUJTSVUOTSVUQVURXEAVUIWUDVBWUOVUJVUOVUFXOUYHAVU
      KVUIAVUIWUDVUGVKAVUPVUNAVUNWUNVUGVKUYM $.
  $}

  ${
    $d A k x y $.  $d F k x $.  $d M k x y $.  $d k ph x y $.
    amgmlemALT.0 $e |- M = ( mulGrp ` CCfld ) $.
    amgmlemALT.1 $e |- ( ph -> A e. Fin ) $.
    amgmlemALT.2 $e |- ( ph -> A =/= (/) ) $.
    amgmlemALT.3 $e |- ( ph -> F : A --> RR+ ) $.
    $( Alternate proof of ~ amgmlem using ~ amgmwlem .  (Contributed by Kunhao
       Zheng, 20-Jun-2021.)  (Proof modification is discouraged.)
       (New usage is discouraged.) $)
    amgmlemALT $p |- ( ph -> ( ( M gsum F ) ^c ( 1 / ( # ` A ) ) ) <_
                                          ( ( CCfld gsum F ) / ( # ` A ) ) ) $=
      ( vk c1 cfv co ccxp cgsu ccnfld cmul crp wcel wceq cc vx vy vw chash cdiv
      csn cxp cof cle wf cn c0 wne cfn wb hashnncl syl mpbird rpreccld fconst6g
      nnrpd csu fconstmpt a1i oveq2d nnrecred recnd wa simpl cv simplr gsumfsum
      cmpt syl2anc fsumconst nncnd nnne0d recidd eqtrd 3eqtrd amgmwlem ccom wss
      cress cbs cr rpssre ax-resscn sstri cnfldbas mgpbas ressbas2 ax-mp cnfld1
      eqid c0g ringidval csubmnd cdif csubg cmgp oveq1i rpmsubg subgsubm cnring
      cc0 crg cnfld0 cndrng drngui unitsubm subsubm mpbi simpli subm0 ccmn cmnd
      eqtri ccrg cncrng crngmgp submmnd mp1i subcmn sylancr cghm cmhm cvv ssexi
      adantr rpcxpcld fmptd wbr rprege0d oveq1 fvmpt3i 3eqtr4d gsumsubm offval2
      oveq1d cplusg reex cnfldmul mgpplusg ressplusg cgrp cnex rpcndif0 ressabs
      difss ssriv mp2an eqtr4i subggrp simpr simprl simprr syl3anc rpmulcl ovex
      mulcxp adantl oveq12d isghmd ghmmhm fdmfifsupp gsummhm ffvelcdmda feqmptd
      1red cbvmptv fmptco 3eqtr4rd gsumcl eqtr4d 3eqtr3d rpcnd fsumcl fsummulc1
      divrecd eqtr2d mulcld 3brtr3d ) ADCBJBUDKZUELZUFUGZMUHLZNLZOCUWFPUHLZNLZD
      CNLZUWEMLZOCNLZUWDUELZUIABCDUWFEFGHAUWEQRZBQUWFUJAUWDAUWDAUWDUKRZBULUMZGA
      BUNRZUWPUWQUOFBUPUQURZVAUSZBUWEQUTUQAOUWFNLOIBUWEVMZNLZBUWEIVBZJAUWFUXAON
      UWFUXASAIBUWEVCVDZVEAUWRUWETRZUXBUXCSFAUWEAUWDUWSVFZVGZUWRUXEVHBUWEIUWRUX
      EVIUWRUXEIVJZBRZVKVLVNAUXCUWDUWEPLZJAUWRUXEUXCUXJSFUXGBUWEIVOVNAUWDAUWDUW
      SVPZAUWDUWSVQZVRVSVTWAADQWDLZIQUXHUWEMLZVMZCWBZNLZUXMCNLZUXOKZUWHUWLABQCU
      XMUXMUXOUNJQTWCQUXMWEKSQWFTWGWHWIQTUXMDUXMWOZTODEWJWKWLWMZJDWPKZUXMWPKZOJ
      DEWNWQQDWRKZRZUYBUYCSUYEQTXFUFZWSZWCZQDUYGWDLZWRKRZUYEUYHVHZQUYIWTKRUYJUY
      IDOXAKZUYGWDEXBXCQUYIXDWMUYGUYDRZUYJUYKUOOXGRUYMXEOUYGDTOXFWJXHXIXJEXKWMQ
      UYGDUYIUYIWOXLWMXMXNZQUXMDUYBUXTUYBWOXOWMXRZADXPRZUXMXQRZUXMXPROXSRUYPXTO
      DEYAWMUYEUYQAUYNQUXMDUXTYBYCZQDUXMUXTYDYEZUYRFAUXOUXMUXMYFLRUXOUXMUXMYGLR
      AUAUBPPUXMUXMUXOQQUYAUYAQYHRPUXMUUAKSQWFUUBWGYIQPDUXMYHUXTOPDEUUCUUDUUEWM
      ZUYTQUYLUYGWDLZWTKRUXMUUFRAVUAVUAWOXCQVUAUXMUXMUYLQWDLZVUAQWDLZDUYLQWDEXB
      UYGYHRUYHVUCVUBSUYGTUUGTUYFUUJYIUCQUYGUCVJUUHUUKUYGQUYLYHUUIUULUUMUUNYCZV
      UDAIQUXNQUXOAUXHQRZVHUXHUWEAVUEUUOAUWEWFRZVUEUXFYJYKUXOWOZYLAUAVJZQRZUBVJ
      ZQRZVHZVHZVUHVUJPLZUWEMLZVUHUWEMLZVUJUWEMLZPLZVUNUXOKZVUHUXOKZVUJUXOKZPLV
      UMVUHWFRXFVUHUIYMVHVUJWFRXFVUJUIYMVHUXEVUOVURSVUMVUHAVUIVUKUUPZYNVUMVUJAV
      UIVUKUUQZYNAUXEVULUXGYJVUHVUJUWEUVAUURVUMVUNQRZVUSVUOSVULVVDAVUHVUJUUSUVB
      IVUNUXNVUOQUXOUXHVUNUWEMYOVUGUXHUWEMUUTZYPUQVUMVUTVUPVVAVUQPVUMVUIVUTVUPS
      VVBIVUHUXNVUPQUXOUXHVUHUWEMYOZVUGVVEYPUQVUMVUKVVAVUQSVVCIVUJUXNVUQQUXOUXH
      VUJUWEMYOVUGVVEYPUQUVCYQUVDUXMUXMUXOUVEUQHABQCWFJHFAUVJUVFZUVGADIBUXHCKZU
      WEMLZVMZNLUXMVVJNLUWHUXQABQVVJDUXMUNFUYEAUYNVDZAIBVVIQVVJAUXIVHZVVHUWEABQ
      UXHCHUVHZAVUFUXIUXFYJYKVVJWOYLUXTYRAUWGVVJDNAIBVVHUWEMCUWFUNQQFVVMAUWOUXI
      UWTYJAIBQCHUVIZUXDYSVEAUXPVVJUXMNAIUABQVVHVUPVVICUXOVVMVVNUXOUAQVUPVMSAIU
      AQUXNVUPVVFUVKVDVUHVVHUWEMYOUVLVEUVMAUXSUXRUWEMLZUWLAUXRQRUXSVVOSABQCUXMU
      NJUYAUYOUYSFHVVGUVNIUXRUXNVVOQUXOUXHUXRUWEMYOVUGVVEYPUQAUWKUXRUWEMABQCDUX
      MUNFVVKHUXTYRYTUVOUVPAOIBVVHUWEPLZVMZNLZOIBVVHVMZNLZUWDUELZUWJUWNABVVPIVB
      ZBVVHIVBZUWDUELZVVRVWAAVWDVWCUWEPLVWBAVWCUWDABVVHIFVVLVVHVVMUVQZUVRUXKUXL
      UVTABVVHUWEIFUXGVWEUVSUWAABVVPIFVVLVVHUWEVWEAUXEUXIUXGYJZUWBVLAVVTVWCUWDU
      EABVVHIFVWEVLYTYQAUWIVVQONAIBVVHUWEPCUWFUNQTFVVMVWFVVNUXDYSVEAUWMVVTUWDUE
      ACVVSONVVNVEYTYQUWC $.
  $}

  ${
    amgmw2d.0 $e |- ( ph -> A e. RR+ ) $.
    amgmw2d.1 $e |- ( ph -> P e. RR+ ) $.
    amgmw2d.2 $e |- ( ph -> B e. RR+ ) $.
    amgmw2d.3 $e |- ( ph -> Q e. RR+ ) $.
    amgmw2d.4 $e |- ( ph -> ( P + Q ) = 1 ) $.
    $( Weighted arithmetic-geometric mean inequality for ` n = 2 ` (compare
       ~ amgm2d ).  (Contributed by Kunhao Zheng, 20-Jun-2021.) $)
    amgmw2d $p |-
       ( ph -> ( ( A ^c P ) x. ( B ^c Q ) ) <_ ( ( A x. P ) + ( B x. Q ) ) ) $=
      ( ccnfld co cgsu cmul cc0 c2 wcel crp cc rpcnd cmgp cfv cs2 cof caddc cle
      ccxp cfzo eqid cfn fzofi a1i c0 wne cn lbfzo0 mpbir ne0i mp1i chash cword
      2nn wf s2cld wrdf syl s2len oveq2i feq2i sylib c1 cmnd crg cnring ringmnd
      wceq cnfldbas cnfldadd gsumws2 syl3anc eqtrd amgmwlem wa jca ofs2 syl2anc
      oveq2d ringmgp rpred rpcxpcld mgpbas cnfldmul mgpplusg rpmulcld 3brtr3d )
      AKUAUBZBCUCZDEUCZUGUDLZMLZKWQWRNUDLZMLZBDUGLZCEUGLZNLZBDNLZCENLZUELZUFAOP
      UHLZWQWPWRWPUIZXIUJQAOPUKULOXIQZXIUMUNAXKPUOQVBPUPUQXIOURUSAOWQUTUBZUHLZR
      WQVCZXIRWQVCAWQRVAZQXNABCRFHVDRWQVEVFXMXIRWQXLPOUHBCVGVHVIVJAOWRUTUBZUHLZ
      RWRVCZXIRWRVCAWRXOQXRADERGIVDRWRVEVFXQXIRWRXPPOUHDEVGVHVIVJAKWRMLZDEUELZV
      KAKVLQZDSQESQXSXTVPKVMQZYAAVNKVOUSZADGTAEITSUEDEKVQVRVSVTJWAWBAWTWPXCXDUC
      ZMLZXEAWSYDWPMABRQZCRQZWCZDRQZERQZWCZWSYDVPAYFYGFHWDZAYIYJGIWDZBCDEUGRRWE
      WFWGAWPVLQZXCSQXDSQYEXEVPYBYNAVNKWPXJWHUSAXCABDFADGWIWJTAXDACEHAEIWIWJTSN
      XCXDWPSKWPXJVQWKKNWPXJWLWMVSVTWAAXBKXFXGUCZMLZXHAXAYOKMAYHYKXAYOVPYLYMBCD
      ENRRWEWFWGAYAXFSQXGSQYPXHVPYCAXFABDFGWNTAXGACEHIWNTSUEXFXGKVQVRVSVTWAWO
      $.
  $}

  ${
    young2d.0 $e |- ( ph -> A e. RR+ ) $.
    young2d.1 $e |- ( ph -> P e. RR+ ) $.
    young2d.2 $e |- ( ph -> B e. RR+ ) $.
    young2d.3 $e |- ( ph -> Q e. RR+ ) $.
    young2d.4 $e |- ( ph -> ( ( 1 / P ) + ( 1 / Q ) ) = 1 ) $.
    $( Young's inequality for ` n = 2 ` , a direct application of ~ amgmw2d .
       (Contributed by Kunhao Zheng, 6-Jul-2021.) $)
    young2d $p |-
         ( ph -> ( A x. B ) <_ ( ( ( A ^c P ) / P ) + ( ( B ^c Q ) / Q ) ) ) $=
      ( ccxp co c1 cdiv cmul caddc rpred rpcxpcld rpreccld rpcnd amgmw2d rpne0d
      recidd oveq2d reccld cxpmuld cxp1d 3eqtr3d oveq12d divrecd eqcomd 3brtr3d
      cle ) ABDKLZMDNLZKLZCEKLZMENLZKLZOLUNUOOLZUQUROLZPLZBCOLUNDNLZUQENLZPLZUM
      AUNUQUOURABDFADGQZRZADGSACEHAEIQZRZAEISJUAAUPBUSCOABDUOOLZKLBMKLUPBAVJMBK
      ADADGTZADGUBZUCUDABDUOFVFADVKVLUEUFABABFTUGUHACEUROLZKLCMKLUSCAVMMCKAEAEI
      TZAEIUBZUCUDACEURHVHAEVNVOUEUFACACHTUGUHUIAVEVBAVCUTVDVAPAUNDAUNVGTVKVLUJ
      AUQEAUQVITVNVOUJUIUKUL $.
  $}

$( (End of Kunhao Zheng's mathbox.) $)
