$[ set-main.mm $]
$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  Mathbox for Jon Pennant
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
$)

  $( Split an open interval into two pieces at point B, Co-author TA.
     (Contributed by Jon Pennant, 8-Jun-2019.) $)
  iocunico $p |- ( ( ( A e. RR* /\ B e. RR* /\ C e. RR* ) /\
                       ( A < B /\ B < C ) ) ->
                              ( ( A (,] B ) u. ( B [,) C ) ) = ( A (,) C ) ) $=
    ( cxr wcel w3a clt wbr wa cioo co csn cun cioc cico un23 unundir uncom wceq
    syl3anc uneq2i 3eqtrri simpl1 simpl2 simprl ioounsn snunioo uneq12d ioojoin
    simpl3 simprr 3eqtr3a ) ADEZBDEZCDEZFZABGHZBCGHZIZIZABJKZBLZMZVBBCJKZMZMZVC
    VDMZABNKZBCOKZMACJKVGVAVDMVBMVCVDVBMZMVFVAVBVDPVAVDVBQVJVEVCVDVBRUAUBUTVCVH
    VEVIUTUMUNUQVCVHSUMUNUOUSUCUMUNUOUSUDZUPUQURUEABUFTUTUNUOURVEVISVKUMUNUOUSU
    JUPUQURUKBCUGTUHABCUIUL $.

  ${
    $d A x $.  $d B x $.  $d C x $.
    $( The intersection of two sets that meet at a point is that point.
       (Contributed by Jon Pennant, 12-Jun-2019.) $)
    iocinico $p |- ( ( ( A e. RR* /\ B e. RR* /\ C e. RR* ) /\
     ( A < B /\ B < C ) ) ->
                                   ( ( A (,] B ) i^i ( B [,) C ) ) = { B } ) $=
      ( vx cxr wcel w3a clt wbr wa co cab cle wb elioc1 3adant3 biimtrdi elico1
      3adant1 adantr cioc cico cin csn cicc wss cv 3simpb 3simpa anim12d simpll
      df-in simprr simplr elicc1 anidms 3ad2ant2 sylibrd ss2abdv eqsstrid abid2
      3jca syl6 sseqtrdi wceq iccid sseqtrd simpl2 simprl mpbir3and elind snssd
      xrleidd eqssd ) AEFZBEFZCEFZGZABHIZBCHIZJZJZABUAKZBCUBKZUCZBUDZWBWEBBUEKZ
      WFVRWEWGUFWAVRWEDUGZWGFZDLZWGVRWEWHWCFZWHWDFZJZDLWJDWCWDULVRWMWIDVRWMWHEF
      ZBWHMIZWHBMIZGZWIVRWMWNWPJZWNWOJZJZWQVRWKWRWLWSVRWKWNAWHHIZWPGZWRVOVPWKXB
      NVQABWHOPWNXAWPUHQVRWLWNWOWHCHIZGZWSVPVQWLXDNVOBCWHRSWNWOXCUIQUJWTWNWOWPW
      NWPWSUKWRWNWOUMWNWPWSUNVBVCVPVOWIWQNZVQVPXEBBWHUOUPUQURUSUTDWGVAVDTVRWGWF
      VEZWAVPVOXFVQBVFUQTVGWBBWEWBWCWDBWBBWCFZVPVSBBMIZVOVPVQWAVHZVRVSVTVIWBBXI
      VMZVRXGVPVSXHGNZWAVOVPXKVQABBOPTVJWBBWDFZVPXHVTXIXJVRVSVTUMVRXLVPXHVTGNZW
      AVPVQXMVOBCBRSTVJVKVLVN $.
  $}

  $( An open-below, closed-above real interval is measurable.  (Contributed by
     Jon Pennant, 12-Jun-2019.) $)
  iocmbl $p |- ( ( A e. RR* /\ B e. RR ) -> ( A (,] B ) e. dom vol ) $=
    ( cxr wcel cr wa clt wbr cioc cvol cdm w3a cioo wceq syl3an2 eqeltrrd 3expa
    co biimp3ar c0 csn cun rexr ioounsn ioombl iccid iccmbl anidms adantl unmbl
    cicc syl sylancr 3adant3 wn cle xrlenlt syl2anr ioc0 0mbl eqeltrdi syld3an3
    wb id pm2.61dan ) ACDZBEDZFZABGHZABIRZJKZDZVFVGVIVLVFVGVILABMRZBUAZUBZVJVKV
    GVFBCDZVIVOVJNBUCZABUDOVFVGVOVKDZVIVHVMVKDVNVKDZVRABUEVGVSVFVGBBUKRZVNVKVGV
    PVTVNNVQBUFULVGVTVKDBBUGUHPUIVMVNUJUMUNPQVFVGVIUOZVLVFVGWABAUPHZVLVFVGWBWAV
    GVPVFWBWAVCVFVQVFVDBAUQURSVFVGWBLVJTVKVGVFVPWBVJTNZVQVFVPWCWBABUSSOUTVAVBQV
    E $.

  ${
    $d x y $.  $d F x $.  $d F y $.
    cnioobibld.1 $e |- ( ph -> A e. RR ) $.
    cnioobibld.2 $e |- ( ph -> B e. RR ) $.
    cnioobibld.3 $e |- ( ph -> F e. ( ( A (,) B ) -cn-> CC ) ) $.
    cnioobibld.4 $e |- ( ph ->
                         E. x e. RR A. y e. dom F ( abs ` ( F ` y ) ) <_ x ) $.
    $( A bounded, continuous function on an open bounded interval is
       integrable.  The function must be bounded.  For a counterexample,
       consider ` F = ( x e. ( 0 (,) 1 ) |-> ( 1 / x ) ) ` .  See ~ cniccibl
       for closed bounded intervals.  (Contributed by Jon Pennant,
       31-May-2019.) $)
    cnioobibld $p |- ( ph -> F e. L^1 ) $=
      ( cmbf wcel cdm cvol cfv cr cv cabs co cc cle wral wrex cibl ccncf ioombl
      wbr cioo cnmbf sylancr wf wceq cncff 3syl fveq2d ioovolcl syl2anc eqeltrd
      fdm bddibl syl3anc ) AFKLZFMZNOZPLCQFOROBQUAUGCVCUBBPUCFUDLADEUHSZNMLFVET
      UESLZVBDEUFIVEFUIUJAVDVENOZPAVCVENAVFVETFUKVCVEULIVETFUMVETFUSUNUOADPLEPL
      VGPLGHDEUPUQURJBCFUTVA $.
  $}

  ${
    $d A x $.  $d B x $.  $d C x $.  $d D x $.  $d S x $.
    arearect.1 $e |- A e. RR $.
    arearect.2 $e |- B e. RR $.
    arearect.3 $e |- C e. RR $.
    arearect.4 $e |- D e. RR $.
    arearect.5 $e |- A <_ B $.
    arearect.6 $e |- C <_ D $.
    arearect.7 $e |- S = ( ( A [,] B ) X. ( C [,] D ) ) $.
    $( The area of a rectangle whose sides are parallel to the coordinate axes
       in ` ( RR X. RR ) ` is its width multiplied by its height.  (Contributed
       by Jon Pennant, 19-Mar-2019.) $)
    arearect $p |- ( area ` S ) = ( ( B - A ) x. ( D - C ) ) $=
      ( vx cfv cr cvol wcel wceq cc0 c0 carea cv csn cima citg cmin co cmul cdm
      cxp wss ccnv wral cmpt cibl cicc iccssre mp2an xpss12 eqsstri cif imaeq1i
      iftrue xpimasn eqtr4d wn disjsn xpima1 sylbir eqtr4i fveq2i fveq2d eqtrid
      iffalse cin pm2.61i covol iccmbl mblvol ax-mp cle wbr ovolicc mp3an eqtri
      eqtrdi 0mbl ovol0 eqcomi a1i resubcli ifcli eqeltrdi wfun wb cpnf wf volf
      0re ffun eqeltri fvimacnv sylib rgen rembl adantl cdif eldifn mpteq2ia cc
      ccncf recni ax-resscn sstri ssid cncfmptc cniccibl iblss2 dmarea mpbir3an
      syl areaval itgeq2 mprg itgconst itgss2 oveq2i 3eqtr3i mulcomi 3eqtri ) E
      UANZMOEMUBZUCZUDZPNZUEZDCUFUGZBAUFUGZUHUGZYRYQUHUGEUAUIQZYKYPRYTEOOUJZUKY
      NPULOUDQZMOUMMOYOUNUOQZEABUPUGZCDUPUGZUJZUUALUUDOUKZUUEOUKZUUFUUAUKAOQZBO
      QZUUGFGABUQURZCOQZDOQZUUHHICDUQURUUDOUUEOUSURUTUUBMOYLOQZYOOQZUUBUUNYOYLU
      UDQZYQSVAZOYOUUQRZUUNUUQYOUUPUUQYORUUPUUQYQYOUUPYQSVCUUPYOUUEPNZYQUUPYOUU
      PUUETVAZPNZUUSYNUUTPYNUUFYMUDZUUTEUUFYMLVBUUPUUTUVBRUUPUUTUUEUVBUUPUUETVC
      ZUUDUUEYLVDVEUUPVFZUUTTUVBUUPUUETVNZUVDUUDYMVOTRUVBTRUUDYLVGUUDUUEYMVHVIV
      EVPVJZVKZUUPUUTUUEPUVCVLVMUUSUUEVQNZYQUUEPUIZQZUUSUVHRUULUUMUVJHICDVRURZU
      UEVSVTUULUUMCDWAWBUVHYQRHIKCDWCWDWEWFZVEUVDUUQSYOUUPYQSVNUVDYOTPNZSUVDYOU
      VAUVMUVGUVDUUTTPUVEVLVMUVMTVQNZSTUVIQUVMUVNRWGTVSVTWHWEWFZVEVPWIWJZUUPYQS
      ODCIHWKZWSWLWMPWNZYNUVIQUUOUUBWOUVISWPUPUGZPWQUVRWRUVIUVSPWTVTYNUUTUVIUVF
      UUPUUETUVIUVKWGWLXAYNOPXBURXCXDSOQZUUCWSUVTMUUDOYOOUUGUVTUUKWJOUVIQUVTXEW
      JUUPUUOUVTUUPYOYQOUVLUVQWMXFYLOUUDXGQZYOSRZUVTUWAUVDUWBYLOUUDXHUVOYAXFMUU
      DYOUNZUOQUVTUWCMUUDYQUNZUOMUUDYOYQUVLXIUUIUUJUWDUUDXJXKUGQZUWDUOQFGYQXJQZ
      UUDXJUKXJXJUKUWEYQUVQXLZUUDOXJUUKXMXNXJXOMYQUUDXJXPWDABUWDXQWDXAWJXRVTMEX
      SXTMEYBVTYPMOUUQUEZYSUURYPUWHRMOMOYOUUQYCUVPYDMUUDYQUEZYQUUDPNZUHUGZUWHYS
      UUDUVIQZUWJOQUWFUWIUWKRUUIUUJUWLFGABVRURZUWJYROUWJUUDVQNZYRUWLUWJUWNRUWMU
      UDVSVTUUIUUJABWAWBUWNYRRFGJABWCWDWEZBAGFWKZXAUWGMUUDYQYEWDUUGUWIUWHRUUKMU
      UDOYQYFVTUWJYRYQUHUWOYGYHWEYQYRUWGYRUWPXLYIYJ $.
  $}

  ${
    $d x y $.  $d A x $.  $d A y $.  $d B x $.  $d B y $.  $d C x $.  $d D x $.
    $d E x $.  $d F x $.  $d S x $.  $d U y $.  $d V y $.
    areaquad.1 $e |- A e. RR $.
    areaquad.2 $e |- B e. RR $.
    areaquad.3 $e |- C e. RR $.
    areaquad.4 $e |- D e. RR $.
    areaquad.5 $e |- E e. RR $.
    areaquad.6 $e |- F e. RR $.
    areaquad.7 $e |- A < B $.
    areaquad.8 $e |- C <_ E $.
    areaquad.9 $e |- D <_ F $.
    areaquad.10 $e |- U = ( C + ( ( ( x - A ) / ( B - A ) ) x. ( D - C ) ) ) $.
    areaquad.11 $e |- V = ( E + ( ( ( x - A ) / ( B - A ) ) x. ( F - E ) ) ) $.
    areaquad.12 $e |- S =
                  { <. x , y >. | ( x e. ( A [,] B ) /\ y e. ( U [,] V ) ) } $.
    $( The area of a quadrilateral with two sides which are parallel to the
       y-axis in ` ( RR X. RR ) ` is its width multiplied by the average height
       of its higher edge minus the average height of its lower edge.
       Co-author TA. (Contributed by Jon Pennant, 31-May-2019.) $)
    areaquad $p |- ( area ` S ) =
                  ( ( ( ( F + E ) / 2 ) - ( ( D + C ) / 2 ) ) x. ( B - A ) ) $=
      ( carea cfv cr cv cima cvol citg caddc co c2 cdiv cmin cmul cdm wcel wceq
      wss cmpt cibl cicc wa copab iccssre mp2an sseli c1 cc a1i cc0 wne subne0d
      recni mulcld addsub12d subdid oveq2d eqtrid subdird mullidi oveq1i eqtrdi
      ax-mp recnd 3eqtr4d 1red resubcld addcomd mulcomd oveq12d 3eqtrd remulcld
      readdcld eqeltrd syl2anc syl covol nfcv mblvol cle wbr lesub1dd eqtr4d c0
      eqtri eqeltrid adantl wtru cncfmptc mp3an divcli cncfmpt2f mptru cniccibl
      clt itgeq2 mprg addcli 2cnne0 div32 oveq12i 2ne0 divcan4i mulcli itgconst
      eqtr3i oveq2i subcld itgmulc2 cexp 1p1e2 subcli 3eqtr2i pncan3oi 3eqtr3ri
      2cn times2i 3eqtri csn cxp ccnv wral adantr resubcl mpan2 resubcli gtneii
      recn redivcld sselda jca ssopab2i df-xp 3sstr4i cif iftrue nfopab2 nfcxfr
      1cnd nfv nfima cop vex elimasn eleq2i opabidw 3bitri fveq2d iccmbl subidd
      baib eqrd rexri iccleub mp3an12 wb sylancl subidi ltsub1d mpbii eqbrtrrid
      cxr lediv1 syl112anc mpbid dividi breqtrdi eqbrtrrd elrpd iccgelb divge0d
      lemul1ad le2addd 3brtr4d ovolicc syl3anc wn iffalse simplbi noel pm5.21ni
      pm2.21i 0mbl ovol0 pm2.61i eqcomi ifcl wfun cpnf volf ffun ifcld fvimacnv
      0re wf sylancr rgen rembl cdif eldifn mpteq2ia ccncf ccnfld ctopn ctx ccn
      eqid subcn mpteq2i addcn ax-resscn sstri ssid divsubdird mpteq2dva resmpt
      cres divccncf rescncf mp2 eqeltrri mulcncf eqeltri iblss2 dmarea mpbir3an
      areaval itgss2 subdiri itgsub itgadd ltleii divrec2d cncfmptid 1nn0 exp1d
      itgpowd 3eqtr3i reccld sqcli subdii iblsub mulcomi divreci subsqi divassi
      divsubdir addsubassi subsub2 adddiri 3eqtr4i addsub12 itgeq2dv 3eqtr4ri
      cn0 ) GUDUEZAUFGAUGZUUAZUHZUIUEZUJZJIUKULZUMUNULZFEUKULZUMUNULZUOULDCUOUL
      ZUPULZGUDUQURZVVRVWCUSVWJGUFUFUUBZUTVWAUIUUCUFUHURZAUFUUDAUFVWBVAVBURZVVS
      CDVCULZURZBUGZHKVCULZURZVDZABVEZVVSUFURZVWPUFURZVDZABVEGVWKVWSVXCABVWSVXA
      VXBVWOVXAVWRVWNUFVVSCUFURZDUFURZVWNUFUTZLMCDVFVGZVHZUUEVWOVWQUFVWPVWOVXAV
      WQUFUTZVXHVXAHUFURZKUFURZVXIVXAHEVIVVSCUOULZVWHUNULZUOULZUPULZFVXMUPULZUK
      ULZUFVXAHVXMFUPULZVXNEUPULZUKULZVXSVXRUKULVXQVXAEVXRVXMEUPULZUOULZUKULZVX
      REVYAUOULZUKULHVXTVXAEVXRVYAEVJURZVXAENVOZVKZVXAVXMFVXAVXMVXAVXLVWHVXAVXD
      VXLUFURZLVVSCUUFZUUGVWHUFURZVXADCMLUUHZVKVWHVLVMZVXAVXDVYLLVXDDCDVJURZVXD
      DMVOZVKCUUJDCVMZVXDCDLRUUIZVKVNWEZVKUUKZWFZFVJURZVXAFOVOZVKZVPZVXAVXMEVYS
      VYGVPVQVXAHEVXMFEUOULZUPULZUKULZVYCUAVXAWUEVYBEUKVXAVXMFEVYSWUBVYGVRVSVTV
      XAVXSVYDVXRUKVXAVXSVIEUPULZVYAUOULVYDVXAVIVXMEVXAUVAZVYSVYGWAWUGEVYAUOEVY
      FWBWCWDVSWGVXAVXRVXSWUCVXAVXNEVXAVXNVXAVIVXMVXAWHVYRWIZWFZVYGVPWJVXAVXSVX
      OVXRVXPUKVXAVXNEWUJVYGWKVXAVXMFVYSWUBWKWLWMZVXAVXOVXPVXAEVXNEUFURZVXANVKW
      UIWNZVXAFVXMFUFURZVXAOVKVYRWNZWOWPZVXAKIVXNUPULZJVXMUPULZUKULZUFVXAKVXMJU
      PULZVXNIUPULZUKULZWVAWUTUKULWUSVXAIWUTVXMIUPULZUOULZUKULZWUTIWVCUOULZUKUL
      KWVBVXAIWUTWVCIVJURZVXAIPVOZVKZVXAVXMJVYSJVJURZVXAJQVOZVKZVPZVXAVXMIVYSWV
      IVPVQVXAKIVXMJIUOULZUPULZUKULZWVEUBVXAWVOWVDIUKVXAVXMJIVYSWVLWVIVRVSVTVXA
      WVAWVFWUTUKVXAWVAVIIUPULZWVCUOULWVFVXAVIVXMIWUHVYSWVIWAWVQIWVCUOIWVHWBWCW
      DVSWGVXAWUTWVAWVMVXAVXNIWUJWVIVPWJVXAWVAWUQWUTWURUKVXAVXNIWUJWVIWKVXAVXMJ
      VYSWVLWKWLWMZVXAWUQWURVXAIVXNIUFURZVXAPVKWUIWNZVXAJVXMJUFURZVXAQVKVYRWNZW
      OWPZHKVFWQWRUULUUMUUNUCABUFUFUUOUUPVWLAUFVXAVWBUFURZVWLVXAVWBVWOKHUOULZVL
      UUQZUFWWFVWBVWOWWFVWBUSVWOWWFWWEVWBVWOWWEVLUURVWOVWBVWQUIUEZVWQWSUEZWWEVW
      OVWAVWQUIVWOBVWAVWQVWOBUVBBGVVTBGVWTUCVWSABUUSUUTBVVTWTUVCZBVWQWTVWPVWAUR
      ZVWOVWRWWJVVSVWPUVDZGURWWKVWTURVWSGVVSVWPAUVEBUVEUVFGVWTWWKUCUVGVWSABUVHU
      VIZUVMUVNZUVJVWOVWQUIUQZURZWWGWWHUSVWOVXJVXKWWOVWOVXAVXJVXHWUPWRZVWOVXAVX
      KVXHWWCWRZHKUVKZWQVWQXAWRVWOVXJVXKHKXBXCWWHWWEUSWWPWWQVWOVXQWUSHKXBVWOVXO
      VXPWUQWURVWOVXAVXOUFURVXHWUMWRVWOVXAVXPUFURVXHWUOWRVWOVXAWUQUFURVXHWVTWRV
      WOVXAWURUFURVXHWWBWRVWOEIVXNWULVWONVKWVSVWOPVKVWOVXAVXNUFURVXHWUIWRVWOVXM
      VXMUOULVLVXNXBVWOVXMVWOVXMVWOVXAVXMUFURZVXHVYRWRZWFZUVLVWOVXMVIVXMWWTVWOW
      HWWTVWOVXMVWHVWHUNULZVIXBVWOVXLVWHXBXCZVXMWXBXBXCZVWOVVSDCVXHVXEVWOMVKZVX
      DVWOLVKZCUWDURZDUWDURZVWOVVSDXBXCCLUVOZDMUVOZCDVVSUVPUVQXDVWOVYHVYJVYJVLV
      WHXQXCWXCWXDUVRVWOVXAVXDVYHVXHLVYIUVSZVYJVWOVYKVKZWXLVWOVLCCUOULZVWHXQCCL
      VOZUVTZVWOCDXQXCWXMVWHXQXCRVWOCDCWXFWXEWXFUWAUWBUWCZVXLVWHVWHUWEUWFUWGVWH
      VWHVYKVOZVYQUWHUWIXDUWJEIXBXCVWOSVKUWNVWOFJVXMWUNVWOOVKWWAVWOQVKWWTVWOVXL
      VWHWXKVWOVWHWXLWXPUWKVWOVLWXMVXLXBWXOVWOCVVSCWXFVXHWXFWXGWXHVWOCVVSXBXCWX
      IWXJCDVVSUWLUVQXDUWCUWMFJXBXCVWOTVKUWNUWOVWOVXAHVXQUSVXHWUKWRVWOVXAKWUSUS
      VXHWVRWRUWPHKUWQUWRWMZXEVWOUWSZWWFVLVWBVWOWWEVLUWTWXSVWBXFUIUEZVLWXSVWAXF
      UIWXSBVWAXFWXSBUVBWWIBXFWTWWJVWOVWPXFURZWWJVWOVWRWWLUXAWYAVWOVWPUXBUXDUXC
      UVNZUVJWXTXFWSUEZVLXFWWNURZWXTWYCUSUXEXFXAWEUXFXGWDZXEUXGUXHZVXAWWEUFURVL
      UFURZWWFUFURVXAKHWWCWUPWIUXPVWOWWEVLUFUXIUVSXHVXAUIUXJZVWAWWNURWWDVWLUVRW
      WNVLUXKVCULZUIUXQWYHUXLWWNWYIUIUXMWEVXAVWAVWOVWQXFUUQZWWNVWOVWAWYJUSVWOVW
      AVWQWYJWWMVWOVWQXFUURXEWXSVWAXFWYJWYBVWOVWQXFUWTXEUXGVXAVWOVWQXFWWNVXAVXJ
      VXKWWOWUPWWCWWRWQWYDVXAUXEVKUXNXHVWAUFUIUXOUXRUWGUXSWYGVWMUXPWYGAVWNUFVWB
      UFVXFWYGVXGVKUFWWNURWYGUXTVKVWOWWDWYGVWOVWBWWEUFWXRVWOKHWWQWWPWIWPXIVVSUF
      VWNUYAURZVWBVLUSZWYGWYKWXSWYLVVSUFVWNUYBWYEWRXIAVWNVWBVAZVBURWYGWYMAVWNWW
      EVAZVBAVWNVWBWWEWXRUYCVXDVXEWYNVWNVJUYDULZURZWYNVBURLMWYPXJAKHUOUYEUYFUEZ
      VWNWYQUYIZUOWYQWYQUYGULWYQUYHULZURXJWYQWYRUYJVKZXJAVWNKVAZAVWNWVPVAWYOAVW
      NKWVPUBUYKXJAIWVOUKWYQVWNWYRUKWYSURXJWYQWYRUYLVKZAVWNIVAZWYOURZXJWVGVWNVJ
      UTZVJVJUTZXUDWVHVWNUFVJVXGUYMUYNZVJUYOZAIVWNVJXKXLZVKZXJAVXMWVNVWNXJAVWNV
      XMVAZAVWNVVSVWHUNULZCVWHUNULZUOULZVAWYOXJAVWNVXMXUNVWOVXMXUNUSXJVWOVVSCVW
      HVWNVJVVSXUGVHZCVJURZVWOWXNVKVWHVJURZVWOWXQVKZVYLVWOVYQVKZUYPXIUYQXJAXULX
      UMUOWYQVWNWYRWYTAVWNXULVAZWYOURXJAVJXULVAZVWNUYSZXUTWYOXUEXVBXUTUSXUGAVJV
      WNXULUYRWEXUEXVAVJVJUYDULURZXVBWYOURXUGXUQVYLXVCWXQVYQAVWHXVAXVAUYIUYTVGV
      JVJVWNXVAVUAVUBVUCVKAVWNXUMVAWYOURZXJXUMVJURXUEXUFXVDCVWHWXNWXQVYQXMXUGXU
      HAXUMVWNVJXKXLVKXNWPZXJAJIUOWYQVWNWYRWYTAVWNJVAWYOURZXJWVJXUEXUFXVFWVKXUG
      XUHAJVWNVJXKXLVKXUJXNVUDZXNXHZXJAVWNHVAZAVWNWUFVAWYOAVWNHWUFUAUYKXJAEWUEU
      KWYQVWNWYRXUBAVWNEVAZWYOURZXJVYEXUEXUFXVKVYFXUGXUHAEVWNVJXKXLZVKZXJAVXMWU
      DVWNXVEXJAFEUOWYQVWNWYRWYTAVWNFVAWYOURZXJVYTXUEXUFXVNWUAXUGXUHAFVWNVJXKXL
      VKXVMXNVUDZXNXHZXNXOCDWYNXPXLVUEVKVUFWEAGVUGVUHAGVUIWEVWCAUFWWFUJZAVWNWWE
      UJZVWIVWBWWFUSZVWCXVQUSAUFAUFVWBWWFXRXVSVXAWYFVKXSVXFXVRXVQUSVXGAVWNUFWWE
      VUJWEVWEVWHUPULZVWGVWHUPULZUOULVWDVWHUMUNULZUPULZVWFXWBUPULZUOULZVWIXVRXV
      TXWCXWAXWDUOVWDVJURUMVJURUMVLVMVDZXUQXVTXWCUSJIWVKWVHXTZYAWXQVWDUMVWHYBXL
      VWFVJURXWFXUQXWAXWDUSFEWUAVYFXTZYAWXQVWFUMVWHYBXLYCVWEVWGVWHVWDUMXWGYRYDX
      MVWFUMXWHYRYDXMWXQVUKXVRAVWNKUJZAVWNHUJZUOULZXWEXVRXWKUSXJAVWNKHUFVWOVXKX
      JWWQXIXUAVBURZXJVXDVXEXUAWYOURZXWLLMXWMXVHXOCDXUAXPXLVKVWOVXJXJWWPXIXVIVB
      URZXJVXDVXEXVIWYOURZXWNLMXWOXVPXOCDXVIXPXLVKVULXOXWIXWCXWJXWDUOXWIIUMUPUL
      ZWVNUKULZXWBUPULZXWCIVWHUPULZWVNXWBUPULZUKULZXWPXWBUPULZXWTUKULXWIXWRXWSX
      XBXWTUKXWPUMUNULZVWHUPULZXWSXXBXXCIVWHUPIUMWVHYRYDYEWCXWPVJURZXWFXUQXXDXX
      BUSIUMWVHYRYFZYAWXQXWPUMVWHYBXLYHWCXWIAVWNWVPUJZAVWNIUJZAVWNWVOUJZUKULZXX
      AKWVPUSZXWIXXGUSAVWNAVWNKWVPXRXXKVWOUBVKXSXXGXXJUSXJAVWNIWVOUFWVSXJVWOVDZ
      PVKZXUCVBURZXJVXDVXEXUDXXNLMXUICDXUCXPXLVKXXLVXMWVNVWOWWSXJWWTXIZXXLJIWWA
      XXLQVKXXMWIWNAVWNWVOVAZVBURZXJVXDVXEXXPWYOURZXXQLMXXRXVGXOCDXXPXPXLVKVUMX
      OXXHXWSXXIXWTUKXXHIVWNUIUEZUPULZXWSVWNWWNURZXXSUFURZWVGXXHXXTUSVXDVXEXYAL
      MCDUVKVGZXXSVWHUFXXSVWNWSUEZVWHXYAXXSXYDUSXYCVWNXAWEVXDVXECDXBXCZXYDVWHUS
      LMCDLMRVUNZCDUWQXLXGZVYKVUEZWVHAVWNIYGXLXXSVWHIUPXYGYIXGWVNAVWNVXMUJZUPUL
      ZAVWNWVNVXMUPULZUJZXWTXXIXYJXYLUSXJAVWNVXMWVNUFXJJIWVJXJWVKVKWVGXJWVHVKYJ
      XXOXUKVBURZXJVXDVXEXUKWYOURZXYMLMXYNXVEXOCDXUKXPXLVKZYKXOXYIXWBWVNUPXYIVI
      VWHUNULZDUMYLULZCUMYLULZUOULZUMUNULZUPULZCUOULZDCUKULZUMUNULZCUOULZXWBXYI
      AVWNXYPVXLUPULZUJZYUBVXMYUFUSXYIYUGUSAVWNAVWNVXMYUFXRVWOVXLVWHVWOVXLWXKWF
      XURXUSVUOXSXYPAVWNVXLUJZUPULZYUAXYPCVWHUPULZUPULZUOULZYUGYUBYUIXYPXYTYUJU
      OULZUPULYULYUHYUMXYPUPYUHAVWNVVSUJZAVWNCUJZUOULZYUMYUHYUPUSXJAVWNVVSCUFVW
      OVXAXJVXHXIZAVWNVVSVAZVBURZXJVXDVXEYURWYOURZYUSLMXUEXUFYUTXUGXUHAVWNVJVUP
      VGCDYURXPXLVKZVXDXXLLVKZAVWNCVAZVBURZXJVXDVXEYVCWYOURZYVDLMXUPXUEXUFYVEWX
      NXUGXUHACVWNVJXKXLCDYVCXPXLVKZVULXOYUNXYTYUOYUJUOAVWNVVSVIYLULZUJZDVIVIUK
      ULZYLULZCYVIYLULZUOULZUMUNULZYUNXYTYVHYVLYVIUNULZYVMYVHYVNUSXJACDVIVXDXJL
      VKVXEXJMVKXYEXJXYFVKVIVVQURXJVUQVKVUSXOYVIUMYVLUNYMYIXGYVGVVSUSYVHYUNUSAV
      WNAVWNYVGVVSXRVWOVVSXUOVURXSYVLXYSUMUNYVJXYQYVKXYRUOYVIUMDYLYMYIYVIUMCYLY
      MYIYCWCVUTYUOCXXSUPULZYUJXYAXYBXUPYUOYVOUSXYCXYHWXNAVWNCYGXLXXSVWHCUPXYGY
      IXGYCXGYIXYPXYTYUJXYPVJURXJVWHXJDCVYMXJVYNVKZXUPXJWXNVKZYJXJDCYVPYVQVYOXJ
      VYPVKVNVVAZXOZXYSUMXYQXYRDVYNVVBCWXNVVBYNZYRYDXMCVWHWXNWXQYFZVVCXGYUIYUGU
      SXJAVWNVXLXYPUFYVRVWOVYHXJWXKXIXJAVWNVVSCUFYUQYVAYVBYVFVVDYKXOYUKCYUAUOYU
      KYUJXYPUPULYUJVWHUNULCXYPYUJYVSYWAVVEYUJVWHYWAWXQVYQVVFCVWHWXNWXQVYQYEYOY
      IVUTXGYUAYUDCUOYUAXYPYUCVWHUPULZUMUNULZUPULXYPYWBUPULZUMUNULYUDXYTYWCXYPU
      PXYSYWBUMUNDCVYNWXNVVGZWCYIXYPYWBUMYVSXYSYWBVJYWEYVTVUCZYRYDVVHYWDYUCUMUN
      YWDYWBXYPUPULYWBVWHUNULYUCXYPYWBYVSYWFVVEYWBVWHYWFWXQVYQVVFYUCVWHDCVYNWXN
      XTZWXQVYQYEYOWCYOWCYUCCUMUPULZUOULZUMUNULZYUDYWHUMUNULZUOULZXWBYUEYUCVJUR
      YWHVJURZXWFYWJYWLUSYWGCUMWXNYRYFZYAYUCYWHUMVVIXLYWIVWHUMUNYWIDCYWHUOULUKU
      LZDYWHCUOULZUOULZVWHDCYWHVYNWXNYWNVVJVYMYWMXUPYWQYWOUSVYNYWNWXNDYWHCVVKXL
      YWPCDUOYWPCCUKULZCUOULCYWHYWRCUOCWXNYSWCCCWXNWXNYPXGYIYOWCYWKCYUDUOCUMWXN
      YRYDYEYIYQYTZYIXYKWVOUSXYLXXIUSAVWNAVWNXYKWVOXRVWOWVNVXMWVNVJURVWOJIWVKWV
      HYNZVKWXAWKXSYQYCYTXWPWVNXWBXXFYWTVWHUMWXQYRYDXMZVVLVVMXWQVWDXWBUPJXWPIUO
      ULZUKULZXWQVWDWVJXXEWVGYXCXWQUSWVKXXFWVHJXWPIVVNXLYXBIJUKYXBIIUKULZIUOULI
      XWPYXDIUOIWVHYSWCIIWVHWVHYPXGYIYHWCXGXWJEUMUPULZWUDUKULZXWBUPULZXWDEVWHUP
      ULZWUDXWBUPULZUKULZYXEXWBUPULZYXIUKULXWJYXGYXHYXKYXIUKYXEUMUNULZVWHUPULZY
      XHYXKYXLEVWHUPEUMVYFYRYDYEWCYXEVJURZXWFXUQYXMYXKUSEUMVYFYRYFZYAWXQYXEUMVW
      HYBXLYHWCXWJAVWNWUFUJZAVWNEUJZAVWNWUEUJZUKULZYXJXWJYXPUSXJAVWNHWUFHWUFUSX
      XLUAVKVVOXOYXPYXSUSXJAVWNEWUEUFWULXXLNVKZXVJVBURZXJVXDVXEXVKYYALMXVLCDXVJ
      XPXLVKXXLVXMWUDXXOXXLFEWUNXXLOVKYXTWIWNAVWNWUEVAZVBURZXJVXDVXEYYBWYOURZYY
      CLMYYDXVOXOCDYYBXPXLVKVUMXOYXQYXHYXRYXIUKYXQEXXSUPULZYXHXYAXYBVYEYXQYYEUS
      XYCXYHVYFAVWNEYGXLXXSVWHEUPXYGYIXGWUDXYIUPULZAVWNWUDVXMUPULZUJZYXIYXRYYFY
      YHUSXJAVWNVXMWUDUFXJFEVYTXJWUAVKVYEXJVYFVKYJXXOXYOYKXOXYIXWBWUDUPYWSYIYYG
      WUEUSYYHYXRUSAVWNAVWNYYGWUEXRVWOWUDVXMWUDVJURVWOFEWUAVYFYNZVKWXAWKXSYQYCY
      TYXEWUDXWBYXOYYIYXAVVLVVMYXFVWFXWBUPFYXEEUOULZUKULZYXFVWFVYTYXNVYEYYKYXFU
      SWUAYXOVYFFYXEEVVNXLYYJEFUKYYJEEUKULZEUOULEYXEYYLEUOEVYFYSWCEEVYFVYFYPXGY
      IYHWCXGYCXGVVPYOXG $.
  $}

$( (End of Jon Pennant's mathbox.) $)
