$[ set-main.mm $]
$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  Mathbox for Luke Murphy
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
$)


$(
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  Solutions of quadratic equations
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
$)

  ${
    quadfac.a $e |- ( ph -> A e. CC ) $.
    quadfac.z $e |- ( ph -> A =/= 0 ) $.
    quadfac.b $e |- ( ph -> B e. CC ) $.
    quadfac.c $e |- ( ph -> C e. CC ) $.
    quadfac.x $e |- ( ph -> X e. CC ) $.
    quadfac.m $e |- ( ph -> M e. CC ) $.
    quadfac.n $e |- ( ph -> N e. CC ) $.
    quadfac.mpn $e |- ( ph -> ( M + N ) = -u ( B / A ) ) $.
    quadfac.mtn $e |- ( ph -> ( M x. N ) = ( C / A ) ) $.
    $( The solution of a quadratic equation via factoring.  (Contributed by
       Luke Murphy, 10-Jul-2026.) $)
    quadfac $p |- ( ph -> ( ( ( A x. ( X ^ 2 ) ) + ( ( B x. X ) + C ) ) = 0
                      <-> ( X = M \/ X = N ) ) ) $=
      ( co cmul caddc cdiv cmin cc0 wceq wo cexp subcld mul0ord olc wfal neneqd
      c2 wn wb id falim pm5.21ni syl orbi1d wi jaoi sylbid impbid2 cneg mulsubd
      sqvald eqcomd mulcomd eqtr3d oveq12d addcomd oveq1d joinlmuladdmuld eqtrd
      3eqtr3d eqeq1d divcld mulneg1d oveq2d sqcld addcld mulcld subnegd 3bitr4d
      a1i 3bitrd adddid divcan2d mulassd addassd subeq0ad orbi12d 3bitr3d ) AGE
      UAQGFUAQRQUBUCGEUAQUBUCGFUAQUBUCUDBGUKUEQRQCGRQDSQSQUBUCGEUCGFUCUDAGEUAQG
      FUAQAGELMUFAGFLNUFUGAGEUAQGFUAQRQUBUCBGUKUEQRQDSQCGRQSQUBUCBGUKUEQRQDCGRQ
      SQSQUBUCBGUKUEQRQCGRQDSQSQUBUCAGEUAQGFUAQRQUBUCBGUKUEQDBTQSQCBTQGRQSQRQUB
      UCBGUKUEQDBTQSQRQBCBTQGRQRQSQUBUCBGUKUEQRQDSQCGRQSQUBUCAGUKUEQDBTQSQCBTQG
      RQSQUBUCBUBUCGUKUEQDBTQSQCBTQGRQSQUBUCUDGEUAQGFUAQRQUBUCBGUKUEQDBTQSQCBTQ
      GRQSQRQUBUCAGUKUEQDBTQSQCBTQGRQSQUBUCBUBUCGUKUEQDBTQSQCBTQGRQSQUBUCUDGUKU
      EQDBTQSQCBTQGRQSQUBUCBUBUCUHABUBUCGUKUEQDBTQSQCBTQGRQSQUBUCUDUIGUKUEQDBTQ
      SQCBTQGRQSQUBUCUDGUKUEQDBTQSQCBTQGRQSQUBUCABUBUCUIGUKUEQDBTQSQCBTQGRQSQUB
      UCABUBUCULBUBUCUIUMABUBIUJBUBUCBUBUCUIBUBUCUNBUBUCUOUPUQURUIGUKUEQDBTQSQC
      BTQGRQSQUBUCUDGUKUEQDBTQSQCBTQGRQSQUBUCUSAUIGUKUEQDBTQSQCBTQGRQSQUBUCGUKU
      EQDBTQSQCBTQGRQSQUBUCGUKUEQDBTQSQCBTQGRQSQUBUCUOGUKUEQDBTQSQCBTQGRQSQUBUC
      UNUTWDVAVBAGEUAQGFUAQRQUBUCGUKUEQDBTQSQCBTQVCGRQUAQUBUCGUKUEQDBTQSQCBTQGR
      QVCUAQUBUCGUKUEQDBTQSQCBTQGRQSQUBUCAGEUAQGFUAQRQGUKUEQDBTQSQCBTQVCGRQUAQU
      BAGEUAQGFUAQRQGGRQFERQSQGFRQGERQSQUAQGUKUEQDBTQSQCBTQVCGRQUAQAGEGFLMLNVDA
      GGRQFERQSQGUKUEQDBTQSQGFRQGERQSQCBTQVCGRQUAAGGRQGUKUEQFERQDBTQSAGUKUEQGGR
      QAGLVEVFAEFRQFERQDBTQAEFMNVGPVHVIAFESQGRQEFSQGRQGFRQGERQSQCBTQVCGRQAFESQE
      FSQGRAFENMVJVKAFGEGFRQGERQSQNLMAFGRQGFRQEGRQGERQSAFGNLVGAEGMLVGVIVLAEFSQC
      BTQVCGROVKVNVIVMVOAGUKUEQDBTQSQCBTQVCGRQUAQGUKUEQDBTQSQCBTQGRQVCUAQUBACBT
      QVCGRQCBTQGRQVCGUKUEQDBTQSQUAACBTQGACBJHIVPLVQVRVOAGUKUEQDBTQSQCBTQGRQVCU
      AQGUKUEQDBTQSQCBTQGRQSQUBAGUKUEQDBTQSQCBTQGRQAGUKUEQDBTQAGLVSADBKHIVPVTAC
      BTQGACBJHIVPLWAWBVOWEABGUKUEQDBTQSQCBTQGRQSQHAGUKUEQDBTQSQCBTQGRQAGUKUEQD
      BTQAGLVSADBKHIVPVTACBTQGACBJHIVPLWAVTUGWCABGUKUEQDBTQSQCBTQGRQSQRQBGUKUEQ
      DBTQSQRQBCBTQGRQRQSQUBABGUKUEQDBTQSQCBTQGRQHAGUKUEQDBTQAGLVSADBKHIVPVTACB
      TQGACBJHIVPLWAWFVOABGUKUEQDBTQSQRQBCBTQGRQRQSQBGUKUEQRQDSQCGRQSQUBABGUKUE
      QDBTQSQRQBGUKUEQRQDSQBCBTQGRQRQCGRQSABGUKUEQDBTQSQRQBGUKUEQRQBDBTQRQSQBGU
      KUEQRQDSQABGUKUEQDBTQHAGLVSADBKHIVPWFABDBTQRQDBGUKUEQRQSADBKHIWGVRVMABCBT
      QRQGRQBCBTQGRQRQCGRQABCBTQGHACBJHIVPLWHABCBTQRQCGRACBJHIWGVKVHVIVOWEABGUK
      UEQRQDSQCGRQSQBGUKUEQRQDCGRQSQSQUBABGUKUEQRQDCGRQABGUKUEQHAGLVSWAKACGJLWA
      WIVOABGUKUEQRQDCGRQSQSQBGUKUEQRQCGRQDSQSQUBADCGRQSQCGRQDSQBGUKUEQRQSADCGR
      QKACGJLWAVJVRVOWEAGEUAQUBUCGEUCGFUAQUBUCGFUCAGELMWJAGFLNWJWKWL $.
  $}


$(
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  April Fool's theorem
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
$)

  ${
    25or6to4.a $e |- ( ph -> A = 1 ) $.
    25or6to4.b $e |- ( ph -> B = -u ( ; 5 3 / 2 ) ) $.
    25or6to4.c $e |- ( ph -> C = ( ; 7 5 / 2 ) ) $.
    25or6to4.x $e |- ( ph -> X e. CC ) $.
    $( Question 67 of 68 from a lecture Prof.  Loof Lirpa held last Saturday in
       Lincoln Park.  When asked why the smaller root wasn't reduced to 3/2,
       Lirpa responded "It really doesn't matter anyhow."  (Contributed by Luke
       Murphy, 10-Jul-2026.) $)
    25or6to4 $p |- ( ph -> ( ( ( A x. ( X ^ 2 ) ) + ( ( B x. X ) + C ) ) = 0
                       <-> ( X = ; 2 5 \/ X = ( 6 / 4 ) ) ) ) $=
      ( c2 c5 cdc c4 cdiv co c1 cc0 c3 caddc cmul c6 cc ax-1cn eqeltrdi ax-1ne0
      wne a1i eqnetrd cneg c9 df-dec 9cn addcli 5cn mulcli 3cn eqeltri 2cn 2ne0
      divcli negcli c7 7cn wcel 6cn 4cn 4ne0 divcan4i 2nn0 5nn0 eqid 0nn0 2t2e4
      1nn0 oveq1i 4p1e5 5t2e10 decmul1c eqtr3i 6t2e12 4t3e12 mulcomli eqtr4i wa
      eqtri wb pm3.2i 2cnne0 divmuleq ax-mp mpbir oveq12i dfdec10 dec0u divdiri
      wceq negnegi negeqi div1i oveq12d negeqd eqtr4id divassi 3nn0 2t3e6 6p1e7
      0cn 5t3e15 oveq2i eqcomi 3eqtr2ri quadfac ) ABCDJKLUAMNOEABPUBFUCUDABPQFP
      QUFAUEUGUHACKRLJNOUIUBGKRLJNOKRLJKRLUJPSOKTORSOUBKRUKUJPSOKTORUJPSOKUJPUL
      UCUMUNUOUPUMUQURUSUTVAUDADVBKLJNOUBHVBKLJVBKLUJPSOVBTOKSOUBVBKUKUJPSOVBTO
      KUJPSOVBUJPULUCUMVCUOUNUMUQURUSUTUDIJKLUBVDAJKLUJPSOJTOKSOUBJKUKUJPSOJTOK
      UJPSOJUJPULUCUMURUOUNUMUQUGUAMNOUBVDAUAMVEVFVGUTUGAJKLUAMNOSOKRLJNOUIPNOU
      ICBNOUIJKLUAMNOSOUIUIJKLUAMNOSOKRLJNOUIPNOUIJKLUAMNOSOJKLUAMNOSOKRLJNOUBJ
      KLUAMNOSOKQLJNORJNOSOKRLJNOJKLKQLJNOUAMNORJNOSJKLJTOJNOJKLKQLJNOJKLJJKLUJ
      PSOJTOKSOUBJKUKUJPSOJTOKUJPSOJUJPULUCUMURUOUNUMUQURUSVHJKLJTOKQLJNJKKQJPJ
      KLVIVIVJJKLVKVLVNJJTOPSOMPSOKJJTOMPSVMVOVPWEVQVRVOVSUAMNORJNOWPUAJTORMTOW
      PUAJTOPJLRMTOVTMRPJLVFUPWAWBWCUAUBVDRUBVDWDMUBVDMQUFWDJUBVDJQUFWDWDWDUAMN
      ORJNOWPUAJTORMTOWPWFUAUBVDRUBVDWDMUBVDMQUFWDJUBVDJQUFWDWDUAUBVDRUBVDVEUPW
      GMUBVDMQUFWDJUBVDJQUFWDMUBVDMQUFVFVGWGWHWGWGUARMJWIWJWKWLKRLJNOKQLRSOJNOK
      QLJNORJNOSOKRLKQLRSOJNKRLPQLKTORSOKQLRSOKRWMPQLKTOKQLRSKVJWNVOWEVOKQLRJKQ
      LUJPSOKTOQSOUBKQUKUJPSOKTOQUJPSOKUJPULUCUMUNUOXGUMUQUPURUSWOWEWCKRLJKRLUJ
      PSOKTORSOUBKRUKUJPSOKTORUJPSOKUJPULUCUMUNUOUPUMUQURUSUTUQWQJKLUAMNOSOUIKR
      LJNOUIPNOJKLUAMNOSOUIKRLJNOUIKRLJNOUIPNOJKLUAMNOSOKRLJNOJKLUAMNOSOKQLJNOR
      JNOSOKRLJNOJKLKQLJNOUAMNORJNOSJKLJTOJNOJKLKQLJNOJKLJJKLUJPSOJTOKSOUBJKUKU
      JPSOJTOKUJPSOJUJPULUCUMURUOUNUMUQURUSVHJKLJTOKQLJNJKKQJPJKLVIVIVJJKLVKVLV
      NJJTOPSOMPSOKJJTOMPSVMVOVPWEVQVRVOVSUAMNORJNOWPUAJTORMTOWPUAJTOPJLRMTOVTM
      RPJLVFUPWAWBWCUAUBVDRUBVDWDMUBVDMQUFWDJUBVDJQUFWDWDWDUAMNORJNOWPUAJTORMTO
      WPWFUAUBVDRUBVDWDMUBVDMQUFWDJUBVDJQUFWDWDUAUBVDRUBVDVEUPWGMUBVDMQUFWDJUBV
      DJQUFWDMUBVDMQUFVFVGWGWHWGWGUARMJWIWJWKWLKRLJNOKQLRSOJNOKQLJNORJNOSOKRLKQ
      LRSOJNKRLPQLKTORSOKQLRSOKRWMPQLKTOKQLRSKVJWNVOWEVOKQLRJKQLUJPSOKTOQSOUBKQ
      UKUJPSOKTOQUJPSOKUJPULUCUMUNUOXGUMUQUPURUSWOWEWCWRKRLJNOUIKRLJNOKRLJKRLUJ
      PSOKTORSOUBKRUKUJPSOKTORUJPSOKUJPULUCUMUNUOUPUMUQURUSUTVAWSWCWRVSACBNOKRL
      JNOUIPNOACKRLJNOUIBPNGFWTXAXBAJKLUAMNOTOVBKLJNOPNODBNOVBKLJNOPNOVBKLJNOJK
      LRJNOTOJKLUAMNOTOVBKLJNOVBKLJVBKLUJPSOVBTOKSOUBVBKUKUJPSOVBTOKUJPSOVBUJPU
      LUCUMVCUOUNUMUQURUSUTWSJKLRTOJNOJKLRJNOTOVBKLJNOJKLRJJKLUJPSOJTOKSOUBJKUK
      UJPSOJTOKUJPSOJUJPULUCUMURUOUNUMUQUPURUSXCJKLRTOVBKLJNJKVBKRPJKLXDVIVJJKL
      VKVJVNJRTOPSOUAPSOVBJRTOUAPSXEVOXFWEXHVRVOVSJKLUAMNOTOJKLRJNOTOUAMNORJNOJ
      KLTUAMNORJNOWPUAJTORMTOWPUAJTOPJLRMTOVTMRPJLVFUPWAWBWCUAUBVDRUBVDWDMUBVDM
      QUFWDJUBVDJQUFWDWDWDUAMNORJNOWPUAJTORMTOWPWFUAUBVDRUBVDWDMUBVDMQUFWDJUBVD
      JQUFWDWDUAUBVDRUBVDVEUPWGMUBVDMQUFWDJUBVDJQUFWDMUBVDMQUFVFVGWGWHWGWGUARMJ
      WIWJWKXIXJXKADVBKLJNOBPNHFWTXBXL $.
  $}

$( (End of Luke Murphy's mathbox.) $)
