$[ set-main.mm $]
$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  Mathbox for Igor Ieskov
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
$)

  ${
    cu3addd.1 $e |- ( ph -> A e. CC ) $.
    cu3addd.2 $e |- ( ph -> B e. CC ) $.
    cu3addd.3 $e |- ( ph -> C e. CC ) $.
    $( Cube of sum of three numbers.  (Contributed by Igor Ieskov,
       14-Dec-2023.) $)
    cu3addd $p |- ( ph -> ( ( ( A + B ) + C ) ^ 3 ) =
                ( ( ( ( ( A ^ 3 ) + ( 3 x. ( ( A ^ 2 ) x. B ) ) )
                + ( ( 3 x. ( A x. ( B ^ 2 ) ) ) + ( B ^ 3 ) ) )
                + ( ( ( 3 x. ( ( A ^ 2 ) x. C ) )
                + ( ( ( 3 x. 2 ) x. ( A x. B ) ) x. C ) )
                + ( 3 x. ( ( B ^ 2 ) x. C ) ) ) )
                + ( ( ( 3 x. ( A x. ( C ^ 2 ) ) )
                + ( 3 x. ( B x. ( C ^ 2 ) ) ) ) + ( C ^ 3 ) ) ) ) $=
      ( caddc co c3 cexp c2 cmul cc wcel addcld oveq1d eqtrd oveq2d mulcld wceq
      wa jca wi binom3 a1i mpd syl2anc binom2d sqcld adddird 3cn adddid mulassd
      2cnd eqcomd ) ABCHIZDHIJKIZBJKIJBLKIZCMIMIHIJBCLKIZMIMICJKIHIHIZJUSDMIZMI
      ZJLMIBCMIZMIZDMIZHIZJUTDMIZMIZHIZHIZJBDLKIZMIZCVLMIZHIZMIZDJKIZHIZHIZVKJV
      MMIJVNMIHIZVQHIZHIAURVKJUQVLMIZMIZVQHIZHIZVSAURVAVCJLVDMIZDMIZMIZHIZVIHIZ
      HIZWDHIZWEAURVAJVBWGHIZMIZVIHIZHIZWDHIZWLAURVAJWMVHHIZMIZHIZWDHIZWQAURVAJ
      USWFHIZDMIZVHHIZMIZHIZWDHIZXAAURVAJXBUTHIZDMIZMIZHIZWDHIZXGAURVAJUQLKIZDM
      IZMIZHIZWDHIZXLAURUQJKIZXOHIZWDHIZXQAUQNOZDNOZUBZURXTUAZAYAYBABCEFPGUCYCY
      DUDAUQDUEUFUGAXSXPWDHAXRVAXOHABNOCNOXRVAUAEFBCUEUHQQRAXPXKWDHAXOXJVAHAXNX
      IJMAXMXHDMABCEFUIQSSQRAXKXFWDHAXJXEVAHAXIXDJMAXBUTDAUSWFABEUJZALVDAUOZABC
      EFTZTZPACFUJZGUKSSQRAXFWTWDHAXEWSVAHAXDWRJMAXCWMVHHAUSWFDYEYHGUKQSSQRAWTW
      PWDHAWSWOVAHAJWMVHJNOAULUFZAVBWGAUSDYEGTZAWFDYHGTZPAUTDYIGTUMSQRAWPWKWDHA
      WOWJVAHAWNWIVIHAJVBWGYJYKYLUMQSQRAWKVKWDHAVKWKAVJWJVAHAVGWIVIHAVFWHVCHAVF
      JWFMIZDMIWHAVEYMDMAJLVDYJYFYGUNQAJWFDYJYHGUNRSQSUPQRAWDVRVKHAWCVPVQHAWBVO
      JMABCVLEFADGUJZUKSQSRAVRWAVKHAVPVTVQHAJVMVNYJABVLEYNTACVLFYNTUMQSR $.
  $}

  ${
    negexpidd.1 $e |- ( ph -> A e. RR ) $.
    negexpidd.2 $e |- ( ph -> N e. NN0 ) $.
    negexpidd.3 $e |- ( ph -> -. 2 || N ) $.
    $( The sum of a real number to the power of N and the negative of the
       number to the power of N equals zero if N is a nonnegative odd integer.
       (Contributed by Igor Ieskov, 21-Jan-2024.) $)
    negexpidd $p |- ( ph -> ( ( A ^ N ) + ( -u A ^ N ) ) = 0 ) $=
      ( cexp co cneg caddc cc0 wceq recnd cmul mulm1d oveq1d wcel wi a1i mpd c1
      reexpcld negidd eqcomd cz c2 cdvds wbr wn wa nn0z jctird m1expo eqtr2d cc
      cn0 neg1cn mulexpd eqtr4d oveq2d eqeq1d mpbird ) ABCGHZBIZCGHZJHZKLVCVCIZ
      JHZKLAVCAVCABCDEUBMZUCAVFVHKAVEVGVCJAVEUAIZBNHZCGHZVGAVDVKCGAVKVDABABDMZO
      UDPAVGVJCGHZVCNHZVLAVOVJVCNHVGAVNVJVCNACUEQZUFCUGUHUIZUJZVNVJLZACUPQZVREA
      VTVPVQVTVPRACUKSFULTVRVSRACUMSTPAVCVIOUNAVJBCVJUOQAUQSVMEURUSUSUTVAVB $.
  $}

  ${
    $d B z $.  $d A y z $.  $d ph x y z $.  $d ch x y z $.
    rexlimdv3d.1 $e |- ( ph ->
      ( ( x e. A /\ y e. B /\ z e. C ) -> ( ps -> ch ) ) ) $.
    $( An extended version of ~ rexlimdvv to include three set variables.
       (Contributed by Igor Ieskov, 21-Jan-2024.) $)
    rexlimdv3d $p |- ( ph -> ( E. x e. A E. y e. B E. z e. C ps -> ch ) ) $=
      ( wrex cv wcel wa wi 3expd imp4d expdimp rexlimdvv rexlimdva ) ABFIKEHKCD
      GADLGMZNBCEFHIAUAELHMZFLIMZNBCOZAUAUBUCUDAUAUBUCUDJPQRST $.
  $}

  ${
    3cubeslem1.a $e |- ( ph -> A e. QQ ) $.
    $( Lemma for ~ 3cubes .  (Contributed by Igor Ieskov, 22-Jan-2024.) $)
    3cubeslem1 $p |- ( ph -> 0 < ( ( ( A + 1 ) ^ 2 ) - A ) ) $=
      ( c1 caddc co c2 cexp clt wbr cc0 wceq wcel cr syl 0red wa wi simpl a1i
      cmin w3o cq qre lttri4d peano2re adantr resqcld simpr sqge0d ltletrd 0lt1
      mpand id sq1 3brtr4d 0cnd 1cnd oveq1d comraddd 1p0e1 eqtrdi breqtrrd cmul
      ax-1rid cle 1red readdcld ltle syl2anc ltp1d jctird mpd jca 0le1 ltadd1dd
      1e0p1 eqbrtrid jca32 ltmul12a syl1111anc recnd sqvald 3jaod posdifd mpbid
      eqbrtrrd ) ABBDEFZGHFZIJZKWIBUAFIJABKIJZBKLZKBIJZUBWJABKABUCMBNMZCBUDOZAP
      UEAWKWJWLWMAWNWKWJWOWNWKQZWJRAWPBKWIWNWKSWPPWPWHWNWHNMZWKBUFZUGZUHWNWKUIW
      PWHWSUJUKTUMWLWJRAWLBDGHFZWIIWLKDBWTIKDIJWLULTWLUNZWTDLWLUOTUPWLWHDGHWLWH
      DKEFDWLWHKDWLUQWLURWLBKDEXAUSUTVAVBUSVCTAWNWMWJWOWNWMQZWJRAXBBWHWHVDFZWII
      XBBDVDFZBXCIWNXDBLWMBVEUGXBWNWQKBVFJZBWHIJZQZDNMZWQQZKDVFJZDWHIJZQQXDXCIJ
      WNWMSZXBBDXLXBVGZVHZXBWMXGWNWMUIZXBWMXEXFXBKNMWNWMXERXBPZXLKBVIVJXBBXLVKV
      LVMXBXIXJXKXBXHWQXMXNVNXJXBVOTXBDKDEFWHIVQXBKBDXPXLXMXOVPVRVSBWHDWHVTWAWG
      XBWHXBWHXNWBWCVCTUMWDVMABWIWOAWHAWNWQWOWROUHWEWF $.

    $( Lemma for ~ 3cubes .  Used to show that the denominators in ~ 3cubeslem4
       are nonzero.  (Contributed by Igor Ieskov, 22-Jan-2024.) $)
    3cubeslem2 $p |- ( ph ->
      -. ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) ) + 3 ) = 0 ) $=
      ( c3 cexp co c2 cmul caddc cc0 c1 cmin wcel a1i recnd oveq2d oveq1d eqtrd
      cr 3eqtr4rd 3re mullidd sqcld qre syl resqcld mulcld 1cnd adddird mulassd
      cq addcld mulcomd wceq df-3 expp1d sqvald 3eqtr4d mulridd binom2d 2timesd
      cn0 2nn0 sq1 addcomd cc sqmuld eqeltrd addassd addsubassd subidd remulcld
      addridd eqtr2d peano2re resubcld 3nn nnq ax-mp sylancr 3cubeslem1 gt0ne0d
      cn qmulcl wne 3ne0 mulne0d eqnetrd neneqd ) ADDEFZBGEFZHFZDGEFZBHFZIFZDIF
      ZJAWPDBHFZKIFZGEFZWQLFZDHFZJAWPWMWKHFZWQIFZKIFZDHFZXAAXCDHFZKDHFZIFXFDIFZ
      XEWPAXGDXFIADADDSMAUANZOZUBPAXCKDAXBWQAWMWKADXJUCZAWKABABUKMZBSMCBUDUEZUF
      OZUGZADBXJABXMOZUGZULZAUHZXJUIAXBDHFZWQDHFZIFZDIFXTDBDHFZHFZIFZDIFZXHWPAY
      BYEDIAYAYDXTIADBDXJXPXJUJPQAXFYBDIAXBWQDXOXQXJUIQAXTDDHFZBHFZIFZDIFZXTDWQ
      HFZIFZDIFWPYFAYIYLDIAYHYKXTIADDBXJXJXPUJPQAWMWKDHFZHFZYHIFZDIFWMDWKHFZHFZ
      YHIFZDIFZYJWPAYOYRDIAYNYQYHIAYMYPWMHAWKDXNXJUMPQQAYIYODIAXTYNYHIAWMWKDXKX
      NXJUJQQAWPWMDHFZWKHFZYHIFZDIFZYSAWPUUAWNIFZDIFZUUCAWPDGKIFZEFZWKHFZWNIFZD
      IFUUEAWOUUIDIAWLUUHWNIAWJUUGWKHADUUFDEDUUFUNAUONPQQQAUUIUUDDIAUUHUUAWNIAU
      UGYTWKHADGXJGVBMAVCNUPQQQRAUUDUUBDIAWNYHUUAIAWMYGBHADXJUQQPQRAUUBYRDIAUUA
      YQYHIAWMDWKXKXJXNUJQQRTAYEYLDIAYDYKXTIAYCWQDHABDXPXJUMPPQURTTAXDWTDHAWQGE
      FZGWQKHFZHFZIFZKGEFZIFZWQLFUUJGWQHFZIFZUUNIFZWQLFZWTXDAUUOUURWQLAUUMUUQUU
      NIAUULUUPUUJIAUUKWQGHAWQXQUSPPQQAWSUUOWQLAWQKXQXSUTQAUUQKIFZWQLFUUJWQWQIF
      ZIFZKIFZWQLFZUUSXDAUUTUVCWQLAUUQUVBKIAUUPUVAUUJIAWQXQVAPQQAUURUUTWQLAUUNK
      UUQIUUNKUNAVDNPQAXDUUJWQIFZWQIFZKIFZWQLFZUVDAUVEWRIFZWQLFUVEKWQIFZIFZWQLF
      ZUVHXDAUVIUVKWQLAWRUVJUVEIAWQKXQXSVEPQAUVGUVIWQLAUVEWQKAUUJWQAUUJXBVFADBX
      JXPVGZXOVHZXQULZXQXSVIQAXDUVEKIFZWQIFZWQLFZUVLAXDWQIFZWQLFXDWQWQLFZIFZUVR
      XDAXDWQWQAXCKXRXSULZXQXQVJAUVQUVSWQLAUVPXDWQIAUVEXCKIAUUJXBWQIUVMQQQQAUWA
      XDJIFXDAUVTJXDIAWQXQVKPAXDUWBVMVNTAUVQUVKWQLAUVEKWQUVOXSXQVIQRTAUVGUVCWQL
      AUVFUVBKIAUUJWQWQUVNXQXQVIQQRTTQRAWTDAWTAWSWQAWRAWQSMWRSMADBXIXMVLZWQVOUE
      UFUWCVPOXJAWTAWQADUKMZXLWQUKMDWCMUWDVQDVRVSCDBWDVTWAWBDJWEAWFNWGWHWI $.

    $( Lemma for ~ 3cubes .  (Contributed by Igor Ieskov, 22-Jan-2024.) $)
    3cubeslem3l $p |- ( ph ->
        ( A x. ( ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) )
          + ( ( 3 ^ 2 ) x. A ) ) + 3 ) ^ 3 ) )
      = ( ( ( A ^ 7 ) x. ( 3 ^ 9 ) )
          + ( ( ( A ^ 6 ) x. ( 3 ^ 9 ) )
          + ( ( ( A ^ 5 ) x. ( ( 3 ^ 8 ) + ( 3 ^ 8 ) ) )
          + ( ( ( A ^ 4 ) x. ( ( ( 3 ^ 7 ) x. 2 ) + ( 3 ^ 6 ) ) )
          + ( ( ( A ^ 3 ) x. ( ( 3 ^ 6 ) + ( 3 ^ 6 ) ) )
          + ( ( ( A ^ 2 ) x. ( 3 ^ 5 ) )
          + ( A x. ( 3 ^ 3 ) ) ) ) ) ) ) ) ) $=
      ( c3 cexp co c2 caddc a1i expcld mulcld oveq2d addcld oveq1d eqtrd eqtr4d
      cmul c1 mulcomd mulassd c7 c6 c9 c5 c8 c4 cc wcel 3cn cn0 3nn0 cq qcn syl
      sqcld cu3addd 2nn0 nn0mulcld nn0cnd adddid addassd addcomd eqcomd expaddd
      sqvald nn0addcld expp1d wceq 2p2e4 4p1e5 2p1e3 5p1e6 mulexpd 6nn0 expmuld
      ax-1cn 1nn0 2t2e4 3p1e4 3p2e5 5nn0 6p1e7 2t3e6 4nn0 7nn0 3p3e6 7p1e8 8nn0
      3t2e6 6p2e8 8p1e9 3t3e9 ) ABDDEFZBGEFZQFZDGEFZBQFZHFDHFDEFZQFZBUAEFZDDDQF
      ZEFZQFZBUBEFZDUCEFZQFZBUDEFZDUEEFZXHHFQFZBUFEFZDUAEFZGQFZDUBEFZHFQFZBDEFZ
      XMXMHFZQFZWNDUDEFZQFZBWMQFZHFZHFZHFZHFZHFZHFZWTXEQFZYEHFAWSWTWMDEFZQFZYEH
      FZYFAWSBWODEFZQFZYEHFZYJAWSYLBDWOGEFZWQQFZQFZQFZYDHFZHFZYMAWSYLYQBDWOWQGE
      FZQFZQFZQFZBDYNDQFZQFZQFZHFZYCHFZHFZHFZYSAWSYLYQUUGBDGQFZWOWQQFZQFZDQFZQF
      ZBWQDEFZQFZHFZYBHFZHFZHFZHFZUUJAWSYLYQUUGUURBDWOWPQFZQFZQFZBDYTDQFZQFZQFZ
      HFZYAHFZHFZHFZHFZHFZUVBAWSYLYQUUGUURUVIBDWQWPQFZQFZQFZXTHFZHFZHFZHFZHFZHF
      ZUVNAWSYLYQUUCUUFUUOUUQUVEUVHUVRHFZHFZHFZHFZHFZHFZHFZHFZUWCAWSYLYQHFZUUCU
      UQHFZHFZUUFUUOHFZUVHHFZHFZUVEUVQHFZXTHFZHFZUWKAWSBYKYPHFZUUBUUPHFZHFZUUEU
      UNHFZUVGHFZHFZUVDUVPHFZWMHFZHFZQFZUWTAWRUXIBQAWOWQDAWMWNADDDUGUHAUIIZDUJU
      HAUKIZJZABABULUHBUGUHCBUMUNZUOZKZAWPBADUXKUOZUXNKZUXKUPLAUXJUWQBUXGQFZXTH
      FZHFZUWTAUXJUWQBUXHQFZHFZUYAAUXJUWNBUXDQFZUVHHFZHFZUYBHFZUYCAUXJUWNBUXEQF
      ZHFZUYBHFZUYGAUXJUWLBUXBQFZHFZUYHHFZUYBHFZUYJAUXJBUXAQFZUYKHFZUYHHFZUYBHF
      ZUYNAUXJBUXCQFZUYHHFZUYBHFZUYRAUXJBUXFQFZUYBHFVUAABUXFUXHUXNAUXCUXEAUXAUX
      BAYKYPAWODUXPUXLJZADYOUXKAYNWQAWOUXPUOZUXRKKZMZAUUBUUPADUUAUXKAWOYTUXPAWQ
      UXRUOZKKZAWQDUXRUXLJZMZMZAUXDUVGAUUEUUNADUUDUXKAYNDVUDUXKKKZAUUMDAUUKUULA
      UUKADGUXLGUJUHAUQIZURZUSZAWOWQUXPUXRKZKUXKKZMZADUVFUXKAYTDVUGUXKKKZMZMAUX
      GWMAUVDUVPADUVCUXKAWOWPUXPUXQKZKZADUVOUXKAWQWPUXRUXQKZKZMZUXMMUTAVUBUYTUY
      BHABUXCUXEUXNVUKVUTUTNOAUYTUYQUYBHAUYSUYPUYHHABUXAUXBUXNVUFVUJUTNNOAUYQUY
      MUYBHAUYPUYLUYHHAUYOUWLUYKHABYKYPUXNVUCVUEUTNNNOAUYMUYIUYBHAUYLUWNUYHHAUY
      KUWMUWLHABUUBUUPUXNVUHVUIUTLNNOAUYIUYFUYBHAUYHUYEUWNHABUXDUVGUXNVURVUSUTL
      NOAUYFUWQUYBHAUYEUWPUWNHAUYDUWOUVHHABUUEUUNUXNVULVUQUTNLNOAUYBUXTUWQHABUX
      GWMUXNVVEUXMUTLOAUXTUWSUWQHAUXSUWRXTHABUVDUVPUXNVVBVVDUTNLOOAUWTYLYQUUCUU
      FUUOUUQUVEUVHXTUVQHFZHFZHFZHFZHFZHFZHFZHFZHFZUWKAUWTYLYQUUCUUFUUOUUQUVEUV
      HXTHFZUVQHFZHFZHFZHFZHFZHFZHFZHFZVVNAUWTYLYQUUCUUFUUOUUQUVEXTUVHHFZUVQHFZ
      HFZHFZHFZHFZHFZHFZHFZVWCAUWTYLYQUUCUUFUUOUUQUVEUVQVWDHFZHFZHFZHFZHFZHFZHF
      ZHFZVWLAUWTYLYQUUCUUFUUOUUQUWRVWDHFZHFZHFZHFZHFZHFZHFZVWTAUWTYLYQUUCUUFUU
      OUUQUWSUVHHFZHFZHFZHFZHFZHFZHFZVXGAUWTYLYQUUCUUFUUOUUQUWSHFZUVHHFZHFZHFZH
      FZHFZHFZVXNAUWTYLYQUUCUUFUUOUWSUUQHFZUVHHFZHFZHFZHFZHFZHFZVYAAUWTYLYQUUCU
      UFUUOUVHVYBHFZHFZHFZHFZHFZHFZVYHAUWTYLYQUUCUWOVYIHFZHFZHFZHFZVYNAUWTYLYQU
      UCUWPVYBHFZHFZHFZHFZVYRAUWTYLYQUUCUWPUWSHFZUUQHFZHFZHFZHFZWUBAUWTYLYQUUCU
      UQWUCHFZHFZHFZHFZWUGAUWTYLYQUWMWUCHFZHFZHFZWUKAUWTUWLWULHFZWUNAUWTUWNWUCH
      FWUOAUWNUWPUWSAUWLUWMAYLYQABYKUXNVUCKZABYPUXNVUEKZMZAUUCUUQABUUBUXNVUHKZA
      BUUPUXNVUIKZMZMAUWOUVHAUUFUUOABUUEUXNVULKZABUUNUXNVUQKZMZABUVGUXNVUSKZMZA
      UWRXTAUVEUVQABUVDUXNVVBKZABUVPUXNVVDKZMZABWMUXNUXMKZMZVAAUWLUWMWUCWURWVAA
      UWPUWSWVFWVKMZVAOAYLYQWULWUPWUQAUWMWUCWVAWVLMVAOAWUMWUJYLHAWULWUIYQHAUUCU
      UQWUCWUSWUTWVLVALLOAWUJWUFYLHAWUIWUEYQHAWUHWUDUUCHAUUQWUCWUTWVLVBLLLOAWUF
      WUAYLHAWUEVYTYQHAWUDVYSUUCHAUWPUWSUUQWVFWVKWUTVALLLOAWUAVYQYLHAVYTVYPYQHA
      VYSVYOUUCHAUWOUVHVYBWVDWVEAUWSUUQWVKWUTMZVALLLOAVYQVYMYLHAVYPVYLYQHAVYOVY
      KUUCHAUUFUUOVYIWVBWVCAUVHVYBWVEWVMMVALLLOAVYMVYGYLHAVYLVYFYQHAVYKVYEUUCHA
      VYJVYDUUFHAVYIVYCUUOHAUVHVYBWVEWVMVBLLLLLOAVYGVXTYLHAVYFVXSYQHAVYEVXRUUCH
      AVYDVXQUUFHAVYCVXPUUOHAVYBVXOUVHHAUWSUUQWVKWUTVBNLLLLLOAVXTVXMYLHAVXSVXLY
      QHAVXRVXKUUCHAVXQVXJUUFHAVXPVXIUUOHAUUQUWSUVHWUTWVKWVEVALLLLLOAVXMVXFYLHA
      VXLVXEYQHAVXKVXDUUCHAVXJVXCUUFHAVXIVXBUUOHAVXHVXAUUQHAUWRXTUVHWVIWVJWVEVA
      LLLLLLOAVXFVWSYLHAVXEVWRYQHAVXDVWQUUCHAVXCVWPUUFHAVXBVWOUUOHAVXAVWNUUQHAU
      VEUVQVWDWVGWVHAXTUVHWVJWVEMZVALLLLLLOAVWSVWKYLHAVWRVWJYQHAVWQVWIUUCHAVWPV
      WHUUFHAVWOVWGUUOHAVWNVWFUUQHAVWMVWEUVEHAUVQVWDWVHWVNVBLLLLLLLOAVWKVWBYLHA
      VWJVWAYQHAVWIVVTUUCHAVWHVVSUUFHAVWGVVRUUOHAVWFVVQUUQHAVWEVVPUVEHAVWDVVOUV
      QHAXTUVHWVJWVEVBNLLLLLLLOAVWBVVMYLHAVWAVVLYQHAVVTVVKUUCHAVVSVVJUUFHAVVRVV
      IUUOHAVVQVVHUUQHAVVPVVGUVEHAUVHXTUVQWVEWVJWVHVALLLLLLLOAVVMUWJYLHAVVLUWIY
      QHAVVKUWHUUCHAVVJUWGUUFHAVVIUWFUUOHAVVHUWEUUQHAVVGUWDUVEHAVVFUVRUVHHAXTUV
      QWVJWVHVBLLLLLLLLOOAUWKYLYQUUGUURUWEHFZHFZHFZHFZUWCAUWKYLYQUUGUWGHFZHFZHF
      ZWVRAWWAUWKAWVTUWJYLHAWVSUWIYQHAUUCUUFUWGWUSWVBAUUOUWFWVCAUUQUWEWUTAUVEUW
      DWVGAUVHUVRWVEAUVQXTWVHWVJMZMMZMMVALLVCAWVQWVTYLHAWVPWVSYQHAWVOUWGUUGHAUU
      OUUQUWEWVCWUTWWCVALLLPAUWBWVQYLHAUWAWVPYQHAUVTWVOUUGHAUVSUWEUURHAUVEUVHUV
      RWVGWVEWWBVALLLLPOAUWBUVMYLHAUWAUVLYQHAUVTUVKUUGHAUVSUVJUURHAUVRYAUVIHAUV
      QXSXTHAUVQWNDUFRHFZEFZQFZXSAUVQWNDGGHFZRHFZEFZQFZWWFAUVQWNWPWPQFZDQFZQFZW
      WJAUVQBBQFZWWLQFZWWMAUVQBBWPWPDQFZQFZQFZQFZWWOAUVQBBWPQFZWWPQFZQFZWWSAUVQ
      BWWTWPQFZDQFZQFZWXBAUVQBUVODQFZQFWXEAUVPWXFBQADUVOUXKVVCSLAWXFWXDBQAUVOWX
      CDQAWQWWTWPQAWPBUXQUXNSZNNLOAWXDWXABQAWWTWPDABWPUXNUXQKZUXQUXKTLOAWXAWWRB
      QABWPWWPUXNUXQAWPDUXQUXKKZTLOAWWSWWNWWQQFZWWOAWXJWWSABBWWQUXNUXNAWPWWPUXQ
      WXIKTVCAWWLWWQWWNQAWPWPDUXQUXQUXKTLPOAWWNWNWWLQAWNWWNABUXNVEVCNOAWWLWWIWN
      QAWWLDWWGEFZDQFZWWIAWXLWWLAWXKWWKDQADGGUXKVUMVUMVDNVCADWWGUXKAGGVUMVUMVFZ
      VGPLOAWWIWWEWNQAWWHWWDDEAWWGUFRHWWGUFVHAVIINZLLOAWWEXRWNQAWWDUDDEWWDUDVHA
      VJIZLLONLLLLLOAUVMUVAYLHAUVLUUTYQHAUVKUUSUUGHAUVJYBUURHAUVIXQYAHAUVIXOXMD
      UDRHFZEFZHFZQFZXQAUVIXOXMDWWDRHFZEFZHFZQFZWXSAUVIXOXMDGGQFZRHFZRHFZEFZHFZ
      QFZWYCAUVIXOXMDDWPGEFZQFZQFZHFZQFZWYIAUVIXOXMQFZXOWYLQFZHFZWYNAUVIWYOBGRH
      FZEFZWYLQFZHFZWYQAUVIWYOWNBQFZWYLQFZHFZXUAAUVIWYOWNBWYLQFZQFZHFZXUDAUVIWY
      OBDWYJWNQFZDQFZQFZQFZHFZXUGAUVIWYOUVHHFZXULAUVIXOWXQQFZUVHHFZXUMAUVIXOWYA
      QFZUVHHFZXUOAUVIXODWWHRHFZEFZQFZUVHHFZXUQAUVIXODGWYRHFZRHFZEFZQFZUVHHFZXV
      AAUVIXODGDHFZRHFZEFZQFZUVHHFZXVFAUVIXODWPWMQFZQFZQFZUVHHFZXVKAUVIWYSXVMQF
      ZUVHHFZXVOAUVIXUBXVMQFZUVHHFZXVQAUVIWNBXVMQFZQFZUVHHFXVSAUVEXWAUVHHAUVEWN
      BDQFZXVLQFZQFZXWAAUVEWNXWBWPQFZWMQFZQFZXWDAUVEWNDBQFZWPQFZWMQFZQFZXWGAUVE
      WNWPXWHQFZWMQFZQFZXWKAUVEWNWMXWLQFZQFZXWNAUVEWNWMQFZXWLQFZXWPAUVEXWQWPQFZ
      XWHQFZXWRAUVEXWSDQFZBQFZXWTAUVEUVCDQFZBQFZXXBAUVEUVDBQFXXDABUVDUXNVVBSAUV
      DXXCBQADUVCUXKVVASNOAXXCXXABQAUVCXWSDQAWOXWQWPQAWMWNUXMUXOSZNNNOAXWSDBAXW
      QWPAWNWMUXOUXMKZUXQKUXKUXNTOAXWQWPXWHXXFUXQADBUXKUXNKZTOAWNWMXWLUXOUXMAWP
      XWHUXQXXGKZTOAXWOXWMWNQAWMXWLUXMXXHSLOAXWMXWJWNQAXWLXWIWMQAWPXWHUXQXXGSNL
      OAXWJXWFWNQAXWIXWEWMQAXWHXWBWPQADBUXKUXNSZNNLOAXWFXWCWNQAXWBWPWMABDUXNUXK
      KZUXQUXMTLOAXWCXVTWNQABDXVLUXNUXKAWPWMUXQUXMKZTLONAXVRXWAUVHHAWNBXVMUXOUX
      NADXVLUXKXXKKTNPAXVRXVPUVHHAXUBWYSXVMQAWYSXUBABGUXNVUMVGVCZNNOAXVPXVNUVHH
      AWYSXOXVMQAWYRDBEWYRDVHAVKIZLZNNOAXVNXVJUVHHAXVMXVIXOQAXVMDXVGEFZDQFZXVIA
      XVMDXXOQFZXXPAXXQXVMAXXOXVLDQADGDUXKUXLVUMVDLVCADXXOUXKADXVGUXKAGDVUMUXLV
      FZJSOADXVGUXKXXRVGPLNOAXVEXVJUVHHAXVDXVIXOQAXVCXVHDEAXVBXVGRHAWYRDGHXXMLN
      LLNPAXUTXVEUVHHAXUSXVDXOQAXURXVCDEAWWHXVBRHAGGRAGVUMUSZXXSRUGUHAVPIZVANLL
      NPAXUTXUPUVHHAXUSWYAXOQAXURWXTDEAWWHWWDRHWXNNLLNOAXUPXUNUVHHAWYAWXQXOQAWX
      TWXPDEAWWDUDRHWXONZLZLNOAXUNWYOUVHHAWXQXMXOQAWXPUBDEWXPUBVHAVLIZLZLNOAUVH
      XUKWYOHAUVGXUJBQAUVFXUIDQAYTXUHDQAWPBGUXQUXNVUMVMZNLLLOAXUKXUFWYOHAXUKWNX
      WBWYKQFZQFZXUFAXUKWNXWBDQFZWYJQFZQFZXYGAXUKWNXWHDQFZWYJQFZQFZXYJAXUKWNDXW
      HQFZWYJQFZQFZXYMAXUKWNWYJXYNQFZQFZXYPAXUKWNWYJQFZXYNQFZXYRAXUKXYSDQFZXWHQ
      FZXYTAXUKYUADQFZBQFZYUBAXUKXUIDQFZBQFZYUDAXUKXUJBQFYUFABXUJUXNADXUIUXKAXU
      HDAWYJWNAWPUXQUOZUXOKZUXKKZKSAXUJYUEBQADXUIUXKYUISNOAYUEYUCBQAXUIYUADQAXU
      HXYSDQAWYJWNYUGUXOSZNNNOAYUADBAXYSDAWNWYJUXOYUGKZUXKKUXKUXNTOAXYSDXWHYUKU
      XKXXGTOAWNWYJXYNUXOYUGADXWHUXKXXGKZTOAXYQXYOWNQAWYJXYNYUGYULSLOAXYOXYLWNQ
      AXYNXYKWYJQADXWHUXKXXGSZNLOAXYLXYIWNQAXYKXYHWYJQAXWHXWBDQXXINZNLOAXYIXYFW
      NQAXWBDWYJXXJUXKYUGTLOAXYFXUEWNQABDWYKUXNUXKADWYJUXKYUGKZTLOLOAXUCXUFWYOH
      AWNBWYLUXOUXNADWYKUXKYUOKZTLPAXUCWYTWYOHAXUBWYSWYLQXXLNLOAWYTWYPWYOHAWYSX
      OWYLQXXNNLOAWYNWYQAXOXMWYLABDUXNUXLJZADUBUXKUBUJUHAVNIZJZYUPUTVCOAWYMWYHX
      OQAWYLWYGXMHAWYLDWYEEFZDQFZWYGAWYLDYUTQFZYVAAWYLDDWYDEFZDQFZQFZYVBAWYLDDY
      VCQFZQFZYVEAYVGWYLAYVFWYKDQAYVCWYJDQADGGUXKVUMVUMVOZLLVCAYVFYVDDQADYVCUXK
      ADWYDUXKAGGVUMVUMURZJSLOAYUTYVDDQADWYDUXKYVIVGLPADYUTUXKADWYEUXKAWYDRYVIR
      UJUHAVQIZVFZJSOADWYEUXKYVKVGPLLOAWYHWYBXOQAWYGWYAXMHAWYFWXTDEAWYEWWDRHAWY
      DUFRHWYDUFVHAVRIZNNZLLLOAWYBWXRXOQAWYAWXQXMHXYBLLOAWXRXPXOQAWXQXMXMHXYDLL
      ONLLLLOAUVAUUIYLHAUUTUUHYQHAUUSYCUUGHAUURXNYBHAUURXJXLQFZXJXMQFZHFZXNAUUR
      YVNXJDGDQFZEFZQFZHFZYVPAUURYVNXJWPDEFZQFZHFZYVTAUURYVNBDRHFZEFZYWAQFZHFZY
      WCAUURYVNXOBQFZYWAQFZHFZYWGAUURYVNXOBYWAQFZQFZHFZYWJAUURYVNBYWAXOQFZQFZHF
      ZYWMAUURYVNUUQHFZYWPAUURXJDUBRHFZEFZGQFZQFZUUQHFZYWQAUURXJDWXPRHFZEFZGQFZ
      QFZUUQHFZYXBAUURXJDDXRQFZQFZGQFZQFZUUQHFZYXGAUURXJDYXHGQFZQFZQFZUUQHFZYXL
      AUURXJDDXRGQFZQFZQFZQFZUUQHFZYXPAUURXJDDGXRQFZQFZQFZQFZUUQHFZYYAAUURXJDDG
      DDGHFZEFZQFZQFZQFZQFZUUQHFZYYFAUURXJDDGWMWPQFZQFZQFZQFZQFZUUQHFZYYMAUURYW
      EYYQQFZUUQHFZYYSAUURBWYRRHFZEFZYYQQFZUUQHFZUUUAAUURXUBBQFZYYQQFZUUQHFZUUU
      EAUURXUBBYYQQFZQFZUUQHFZUUUHAUURWNBUUUIQFZQFZUUQHFUUUKAUUOUUUMUUQHAUUOWNB
      BDUUKYYNQFZQFZQFZQFZQFZUUUMAUUOWNBXWBUUUNQFZQFZQFZUUURAUUOWNBXWBUUKQFZYYN
      QFZQFZQFZUUVAAUUOWNBUUVBWMQFZWPQFZQFZQFZUUVEAUUOWNBXWHUUKQFZWMQFZWPQFZQFZ
      QFZUUVIAUUOWNBUUKXWHQFZWMQFZWPQFZQFZQFZUUVNAUUOWNBWPUUVPQFZQFZQFZUUVSAUUO
      WNWWTUUVPQFZQFZUUWBAUUOWNWWTUUVOQFZWMQFZQFZUUWDAUUOWNWQUUVOQFZWMQFZQFZUUW
      GAUUOWNWMUUWHQFZQFZUUWJAUUOXWQUUWHQFZUUWLAUUOXWQWQQFZUUVOQFZUUWMAUUOUUWNU
      UKQFZXWHQFZUUWOAUUOUUWPDQFZBQFZUUWQAUUOUULUUKQFZDQFZBQFZUUWSAUUOUUNBQFUUX
      BABUUNUXNVUQSAUUNUUXABQAUUMUUWTDQAUUKUULVUOVUPSNNOAUUXAUUWRBQAUUWTUUWPDQA
      UULUUWNUUKQAWOXWQWQQXXENNNNOAUUWPDBAUUWNUUKAXWQWQXXFUXRKZVUOKUXKUXNTOAUUW
      NUUKXWHUUXCVUOXXGTOAXWQWQUUVOXXFUXRAUUKXWHVUOXXGKZTOAWNWMUUWHUXOUXMAWQUUV
      OUXRUUXDKZTOAUUWKUUWIWNQAWMUUWHUXMUUXESLOAUUWIUUWFWNQAUUWHUUWEWMQAWQWWTUU
      VOQWXGNNLOAUUWFUUWCWNQAWWTUUVOWMWXHUUXDUXMTLOAUUWCUUWAWNQABWPUUVPUXNUXQAU
      UVOWMUUXDUXMKZTLOAUUWAUUVRWNQAUUVTUUVQBQAWPUUVPUXQUUXFSLLOAUUVRUUVMWNQAUU
      VQUUVLBQAUUVPUUVKWPQAUUVOUUVJWMQAUUKXWHVUOXXGSNNLLOAUUVMUUVHWNQAUUVLUUVGB
      QAUUVKUUVFWPQAUUVJUUVBWMQAXWHXWBUUKQXXINNNLLOAUUVHUUVDWNQAUUVGUUVCBQAUUVB
      WMWPAXWBUUKXXJVUOKUXMUXQTLLOAUUVDUUUTWNQAUUVCUUUSBQAXWBUUKYYNXXJVUOAWMWPU
      XMUXQKZTLLOAUUUTUUUQWNQAUUUSUUUPBQABDUUUNUXNUXKAUUKYYNVUOUUXGKTLLOAUUUQUU
      ULWNQAUUUPUUUIBQAUUUOYYQBQAUUUNYYPDQADGYYNUXKXXSUUXGTLLLLONAUUUJUUUMUUQHA
      WNBUUUIUXOUXNABYYQUXNADYYPUXKADYYOUXKAGYYNXXSUUXGKKKZKTNPAUUUGUUUJUUQHAXU
      BBYYQAWNBUXOUXNKUXNUUXHTNPAUUUGUUUDUUQHAUUUFUUUCYYQQAUUUFWYSBQFUUUCAXUBWY
      SBQXXLNABWYRUXNAGRVUMYVJVFVGPNNOAUUUDYYTUUQHAUUUCYWEYYQQAUUUBYWDBEAWYRDRH
      XXMNLNNOAYYTYYRUUQHAYWEXJYYQQAYWDUFBEYWDUFVHAVSIZLZNNOAYYRYYLUUQHAYYQYYKX
      JQAYYKYYQAYYJYYPDQAYYIYYODQAYYHYYNGQADDGUXKVUMUXLVDLLLVCLNOAYYLYYEUUQHAYY
      KYYDXJQAYYJYYCDQAYYIYYBDQAYYHXRGQAYYGUDDEYYGUDVHAVTILLLLLNOAYYEYXTUUQHAYY
      DYXSXJQAYYCYXRDQAYYBYXQDQAGXRXXSADUDUXKUDUJUHAWAIZJZSLLLNOAYXOYXTUUQHAYXN
      YXSXJQAYXMYXRDQADXRGUXKUUXLXXSTLLNPAYXKYXOUUQHAYXJYXNXJQADYXHGUXKADXRUXKU
      UXLKXXSTLNPAYXKYXFUUQHAYXJYXEXJQAYXIYXDGQAYXIWXQDQFZYXDAYXIDWXQQFZUUXMAYX
      IDXRDQFZQFUUXNAYXHUUXODQADXRUXKUUXLSLAWXQUUXODQADUDUXKUUXKVGLPADWXQUXKADW
      XPUXKAUDRUUXKYVJVFZJSOADWXPUXKUUXPVGPNLNOAYXFYXAUUQHAYXEYWTXJQAYXDYWSGQAY
      XCYWRDEAWXPUBRHXYCNLNLNOAYXAYVNUUQHAYWTXLXJQAYWSXKGQAYWRUADEYWRUAVHAWBIZL
      NLNOAUUQYWOYVNHAUUPYWNBQAWPBDUXQUXNUXLVMLLOAYWOYWLYVNHAYWOXOYWABQFZQFZYWL
      AYWOXOYWAQFZBQFZUUXSAYWOYWNBQFUUYAABYWNUXNAYWAXOAWPDUXQUXLJZYUQKSAYWNUUXT
      BQAYWAXOUUYBYUQSNOAXOYWABYUQUUYBUXNTOAUUXRYWKXOQAYWABUUYBUXNSLOLOAYWIYWLY
      VNHAXOBYWAYUQUXNUUYBTLPAYWIYWFYVNHAYWHYWEYWAQAYWEYWHABDUXNUXLVGVCNLOAYWFY
      WBYVNHAYWEXJYWAQUUXJNLOAYWBYVSYVNHAYWAYVRXJQAYVRYWAADGDUXKUXLVUMVOVCLLOAY
      VSYVOYVNHAYVRXMXJQAYVQUBDEYVQUBVHAWCIZLLLOAXNYVPAXJXLXMABUFUXNUFUJUHAWDIZ
      JZAXKGADUAUXKUAUJUHAWEIJXXSKYUSUTVCONLLLOAUUIYRYLHAUUHYDYQHAUUGXIYCHAUUGX
      GXHQFZUUYFHFZXIAUUGUUYFXGDUARHFZEFZQFZHFZUUYGAUUGUUYFXGDYWRRHFZEFZQFZHFZU
      UYKAUUGUUYFXGDDXMQFZQFZQFZHFZUUYOAUUGUUYFBWWDEFZUUYQQFZHFZUUYSAUUGUUYFXJB
      QFZUUYQQFZHFZUVUBAUUGUUYFXJBUUYQQFZQFZHFZUVUEAUUGUUYFBDXMXJQFZDQFZQFZQFZH
      FZUVUHAUUGUUYFBDXMBWYDEFZQFZDQFZQFZQFZHFZUVUMAUUGUUYFBDDUUKEFZUVUNQFZDQFZ
      QFZQFZHFZUVUSAUUGUUYFBDWMGEFZWNGEFZQFZDQFZQFZQFZHFZUVVEAUUGUUYFUUFHFZUVVL
      AUUGUUYJUUFHFZUVVMAUUGUUYNUUFHFZUVVNAUUGXGDDDHFZRHFZRHFZEFZQFZUUFHFZUVVOA
      UUGXGDDYWDHFZRHFZEFZQFZUUFHFZUVWAAUUGXGDDUFHFZRHFZEFZQFZUUFHFZUVWFAUUGXGD
      DWYDHFZRHFZEFZQFZUUFHFZUVWKAUUGXGDWMWYJQFZQFZQFZUUFHFZUVWPAUUGUUYTUVWRQFZ
      UUFHFZUVWTAUUGBWWHEFZUVWRQFZUUFHFZUVXBAUUGWNWNQFZBQFZUVWRQFZUUFHFZUVXEAUU
      GUVXFBUVWRQFZQFZUUFHFZUVXIAUUGWNWNUVXJQFZQFZUUFHFZUVXLAUUGBDWOXUHQFZQFZQF
      ZUUFHFUVXOAUUCUVXRUUFHAUUBUVXQBQAUUAUVXPDQAYTXUHWOQXYELLLNAUVXRUVXNUUFHAU
      VXRWNWNXWBUVWQQFZQFZQFZUVXNAUVXRWNWNXWBWMQFZWYJQFZQFZQFZUVYAAUVXRWNWNXWHW
      MQFZWYJQFZQFZQFZUVYEAUVXRWNWNWYJUVYFQFZQFZQFZUVYIAUVXRWNXYSUVYFQFZQFZUVYL
      AUVXRWNXYSXWHQFZWMQFZQFZUVYNAUVXRWNXUHXWHQFZWMQFZQFZUVYQAUVXRWNWMUVYRQFZQ
      FZUVYTAUVXRXWQUVYRQFZUWUBAUVXRXWQXUHQFZXWHQFZUWUCAUVXRUWUDDQFZBQFZUWUEAUV
      XRUVXPDQFZBQFZUWUGAUVXRUVXQBQFUWUIABUVXQUXNADUVXPUXKAWOXUHUXPYUHKZKSAUVXQ
      UWUHBQADUVXPUXKUWUJSNOAUWUHUWUFBQAUVXPUWUDDQAWOXWQXUHQXXENNNOAUWUDDBAXWQX
      UHXXFYUHKUXKUXNTOAXWQXUHXWHXXFYUHXXGTOAWNWMUVYRUXOUXMAXUHXWHYUHXXGKZTOAUW
      UAUVYSWNQAWMUVYRUXMUWUKSLOAUVYSUVYPWNQAUVYRUVYOWMQAXUHXYSXWHQYUJNNLOAUVYP
      UVYMWNQAXYSXWHWMYUKXXGUXMTLOAUVYMUVYKWNQAWNWYJUVYFUXOYUGAXWHWMXXGUXMKZTLO
      AUVYKUVYHWNQAUVYJUVYGWNQAWYJUVYFYUGUWULSLLOAUVYHUVYDWNQAUVYGUVYCWNQAUVYFU
      VYBWYJQAXWHXWBWMQXXINNLLOAUVYDUVXTWNQAUVYCUVXSWNQAXWBWMWYJXXJUXMYUGTLLOAU
      VXTUVXMWNQAUVXSUVXJWNQABDUVWQUXNUXKAWMWYJUXMYUGKZTLLONOAUVXKUVXNUUFHAWNWN
      UVXJUXOUXOABUVWRUXNADUVWQUXKUWUMKZKTNPAUVXHUVXKUUFHAUVXFBUVWRAWNWNUXOUXOK
      UXNUWUNTNPAUVXHUVXDUUFHAUVXGUVXCUVWRQAUVXGBWWGEFZBQFZUVXCAUWUPUVXGAUWUOUV
      XFBQABGGUXNVUMVUMVDNVCABWWGUXNWXMVGPNNOAUVXDUVXAUUFHAUVXCUUYTUVWRQAWWHWWD
      BEWXNLNNOAUVXAUVWSUUFHAUUYTXGUVWRQAWWDUDBEWXOLZNNOAUVWSUVWOUUFHAUVWRUVWNX
      GQAUVWRDUVWLEFZDQFZUVWNAUVWRDUWURQFZUWUSAUVWRDWMYVCQFZQFZUWUTAUWVBUVWRAUW
      VAUVWQDQAYVCWYJWMQYVHLLVCAUWURUWVADQADDWYDUXKYVIUXLVDLPADUWURUXKADUVWLUXK
      ADWYDUXLYVIVFZJSOADUVWLUXKUWVCVGPLNOAUVWOUVWJUUFHAUVWNUVWIXGQAUVWMUVWHDEA
      UVWLUVWGRHAWYDUFDHYVLLNLLNOAUVWEUVWJUUFHAUVWDUVWIXGQAUVWCUVWHDEAUVWBUVWGR
      HAYWDUFDHUUXILNLLNPAUVVTUVWEUUFHAUVVSUVWDXGQAUVVRUVWCDEAUVVQUVWBRHADDRUXK
      UXKXXTVANLLNPAUVVTUUYNUUFHAUVVSUUYMXGQAUVVRUUYLDEAUVVQYWRRHAUVVPUBRHUVVPU
      BVHAWFINNLLNOAUUYNUUYJUUFHAUUYMUUYIXGQAUUYLUUYHDEAYWRUARHUUXQNLLZNOAUUYJU
      UYFUUFHAUUYIXHXGQAUUYHUEDEUUYHUEVHAWGILLZNOAUUFUVVKUUYFHAUUEUVVJBQAUUDUVV
      IDQAYNUVVHDQAWMWNGUXMUXOVUMVMZNLLLOAUVVKUVVDUUYFHAUVVKBDUVUTUVVGQFZDQFZQF
      ZQFZUVVDAUWVJUVVKAUWVIUVVJBQAUWVHUVVIDQAUWVGUVVHDQAUVUTUVVFUVVGQADDGUXKVU
      MUXLVOZNNLLVCAUVVCUWVIBQAUVVBUWVHDQAUVVAUWVGDQAUVUNUVVGUVUTQABGGUXNVUMVUM
      VOZLNLLPLOAUVVDUVURUUYFHAUVVCUVUQBQAUVVBUVUPDQAUVVAUVUODQAUVUTXMUVUNQAUUK
      UBDEUUKUBVHAWIIZLNNLLLOAUVURUVULUUYFHAUVUQUVUKBQAUVUPUVUJDQAUVUOUVUIDQAUV
      UNXJXMQAWYDUFBEYVLLLNLLLOAUVULUVUGUUYFHAUVULXJXWBUUYPQFZQFZUVUGAUVULXJXYH
      XMQFZQFZUWVOAUVULXJXYKXMQFZQFZUWVQAUVULXJXYNXMQFZQFZUWVSAUVULXJXMXYNQFZQF
      ZUWWAAUVULYVOXYNQFZUWWCAUVULYVODQFZXWHQFZUWWDAUVULUWWEDQFZBQFZUWWFAUVULUV
      UJDQFZBQFZUWWHAUVULUVUKBQFUWWJABUVUKUXNADUVUJUXKAUVUIDAXMXJYUSUUYEKUXKKZK
      SAUVUKUWWIBQADUVUJUXKUWWKSNOAUWWIUWWGBQAUVUJUWWEDQAUVUIYVODQAXMXJYUSUUYES
      NNNOAUWWEDBAYVODAXJXMUUYEYUSKZUXKKUXKUXNTOAYVODXWHUWWLUXKXXGTOAXJXMXYNUUY
      EYUSYULTOAUWWBUWVTXJQAXMXYNYUSYULSLOAUWVTUWVRXJQAXYNXYKXMQYUMNLOAUWVRUWVP
      XJQAXYKXYHXMQYUNNLOAUWVPUWVNXJQAXWBDXMXXJUXKYUSTLOAUWVNUVUFXJQABDUUYPUXNU
      XKADXMUXKYUSKZTLOLOAUVUDUVUGUUYFHAXJBUUYQUUYEUXNADUUYPUXKUWWMKTLPAUVUDUVU
      AUUYFHAUVUCUUYTUUYQQAUUYTUVUCABUFUXNUUYDVGVCNLOAUVUAUUYRUUYFHAUUYTXGUUYQQ
      UWUQNLOAUUYRUUYNUUYFHAUUYQUUYMXGQAUUYQYWSDQFZUUYMAUUYQDYWSQFZUWWNAUUYQDXM
      DQFZQFUWWOAUUYPUWWPDQADXMUXKYUSSLAYWSUWWPDQADUBUXKYURVGLPADYWSUXKADYWRUXK
      AUBRYURYVJVFZJSOADYWRUXKUWWQVGPLLOAUUYNUUYJUUYFHUWVDLOAUUYJUUYFUUYFHUWVEL
      OAXIUUYGAXGXHXHABUDUXNUUXKJADUEUXKUEUJUHAWHIJZUWWRUTVCONLLOAYRYEYLHAYQXFY
      DHAYQXDDUERHFZEFZQFZXFAYQXDDUBGHFZRHFZEFZQFZUWXAAYQXDDUUKGHFZRHFZEFZQFZUW
      XEAYQXDDUVVFWPQFZQFZQFZUWXIAYQBWXPEFZUWXKQFZUWXLAYQBWXTEFZUWXKQFZUWXNAYQB
      WYFEFZUWXKQFZUWXPAYQUVVGBQFZBQFZUWXKQFZUWXRAYQUWXSBUWXKQFZQFZUWYAAYQUVVGB
      UWYBQFZQFZUWYCAYQBDUVVHWQQFZQFZQFZUWYEAYPUWYGBQAYOUWYFDQAYNUVVHWQQUWVFNLL
      AUWYHUVVGBXWBUWXJQFZQFZQFZUWYEAUWYHUVVGBXWBUVVFQFZWPQFZQFZQFZUWYKAUWYHUVV
      GBXWHUVVFQFZWPQFZQFZQFZUWYOAUWYHUVVGBWPUWYPQFZQFZQFZUWYSAUWYHUVVGWWTUWYPQ
      FZQFZUXUBAUWYHUVVGWWTXWHQFZUVVFQFZQFZUXUDAUWYHUVVGWQXWHQFZUVVFQFZQFZUXUGA
      UWYHUVVGUVVFUXUHQFZQFZUXUJAUWYHUVVGUVVFQFZUXUHQFZUXULAUWYHUXUMWQQFZXWHQFZ
      UXUNAUWYHUXUODQFZBQFZUXUPAUWYHUWYFDQFZBQFZUXURAUWYHUWYGBQFUXUTABUWYGUXNAD
      UWYFUXKAUVVHWQAUVVFUVVGAWMUXMUOZAWNUXOUOZKUXRKZKSAUWYGUXUSBQADUWYFUXKUXVC
      SNOAUXUSUXUQBQAUWYFUXUODQAUVVHUXUMWQQAUVVFUVVGUXVAUXVBSNNNOAUXUODBAUXUMWQ
      AUVVGUVVFUXVBUXVAKZUXRKUXKUXNTOAUXUMWQXWHUXVDUXRXXGTOAUVVGUVVFUXUHUXVBUXV
      AAWQXWHUXRXXGKZTOAUXUKUXUIUVVGQAUVVFUXUHUXVAUXVESLOAUXUIUXUFUVVGQAUXUHUXU
      EUVVFQAWQWWTXWHQWXGNNLOAUXUFUXUCUVVGQAWWTXWHUVVFWXHXXGUXVATLOAUXUCUXUAUVV
      GQABWPUWYPUXNUXQAXWHUVVFXXGUXVAKZTLOAUXUAUWYRUVVGQAUWYTUWYQBQAWPUWYPUXQUX
      VFSLLOAUWYRUWYNUVVGQAUWYQUWYMBQAUWYPUWYLWPQAXWHXWBUVVFQXXINNLLOAUWYNUWYJU
      VVGQAUWYMUWYIBQAXWBUVVFWPXXJUXVAUXQTLLOAUWYJUWYDUVVGQAUWYIUWYBBQABDUWXJUX
      NUXKAUVVFWPUXVAUXQKZTLLOOAUVVGBUWYBUXVBUXNABUWXKUXNADUWXJUXKUXVGKZKTPAUWX
      SBUWXKAUVVGBUXVBUXNKUXNUXVHTPAUWXTUWXQUWXKQAUWXTBWYEEFZBQFZUWXQAUWXTUVUNB
      QFZBQFZUXVJAUXVLUWXTAUXVKUWXSBQAUVUNUVVGBQUWVLNNVCAUXVIUXVKBQABWYDUXNYVIV
      GNPABWYEUXNYVKVGPNOAUWXQUWXOUWXKQAWYFWXTBEYVMLNOAUWXOUWXMUWXKQAWXTWXPBEXY
      ALNOAUWXMXDUWXKQAWXPUBBEXYCLNOAUWXKUWXHXDQAUWXKDUWXFEFZDQFZUWXHAUWXKDUXVM
      QFZUXVNAUWXKDUVUTWPQFZQFZUXVOAUXVQUWXKAUXVPUWXJDQAUVUTUVVFWPQUWVKNLVCAUXV
      MUXVPDQADUUKGUXKVUMVUNVDLPADUXVMUXKADUWXFUXKAUUKGVUNVUMVFZJSOADUWXFUXKUXV
      RVGPLOAUWXHUWXDXDQAUWXGUWXCDEAUWXFUWXBRHAUUKUBGHUWVMNNLLOAUWXDUWWTXDQAUWX
      CUWWSDEAUWXBUERHUWXBUEVHAWJINLLOAUWWTXEXDQAUWWSUCDEUWWSUCVHAWKILLONLOAYLY
      IYEHAYLBYWREFZYHQFZYIAYLBYVQRHFZEFZYHQFZUXVTAYLBWNDEFZQFZYHQFZUXWCAYLBUXW
      DYHQFZQFZUXWFAYLBYHUXWDQFZQFUXWHAYKUXWIBQAWMWNDUXMUXOUXLVMLAUXWIUXWGBQAYH
      UXWDAWMDUXMUXLJZAWNDUXOUXLJZSLOABUXWDYHUXNUXWKUXWJTPAUXWEUXWBYHQAUXWEBYVQ
      EFZBQFZUXWBAUXWEBUXWLQFZUXWMAUXWNUXWEAUXWLUXWDBQABGDUXNUXLVUMVOLVCABUXWLU
      XNABYVQUXNAGDVUMUXLURZJSOABYVQUXNUXWOVGPNOAUXWBUXVSYHQAUXWAYWRBEAYVQUBRHU
      UYCNLNOAUXVSWTYHQAYWRUABEUUXQLNONOAYIXCYEHAYHXBWTQAXBYHADDDUXKUXLUXLVOVCL
      NOAXCYGYEHAXBXEWTQAXAUCDEXAUCVHAWLILLNO $.

    $( Lemma for ~ 3cubes .  (Contributed by Igor Ieskov, 22-Jan-2024.) $)
    3cubeslem3r $p |- ( ph ->
        ( ( ( ( ( ( 3 ^ 3 ) x. ( A ^ 3 ) ) - 1 ) ^ 3 )
          + ( ( ( -u ( ( 3 ^ 3 ) x. ( A ^ 3 ) )
          + ( ( 3 ^ 2 ) x. A ) ) + 1 ) ^ 3 ) )
          + ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) ) ^ 3 ) )
      = ( ( ( A ^ 7 ) x. ( 3 ^ 9 ) )
          + ( ( ( A ^ 6 ) x. ( 3 ^ 9 ) )
          + ( ( ( A ^ 5 ) x. ( ( 3 ^ 8 ) + ( 3 ^ 8 ) ) )
          + ( ( ( A ^ 4 ) x. ( ( ( 3 ^ 7 ) x. 2 ) + ( 3 ^ 6 ) ) )
          + ( ( ( A ^ 3 ) x. ( ( 3 ^ 6 ) + ( 3 ^ 6 ) ) )
          + ( ( ( A ^ 2 ) x. ( 3 ^ 5 ) )
          + ( A x. ( 3 ^ 3 ) ) ) ) ) ) ) ) ) $=
      ( c3 cexp co cmul c1 caddc oveq1d oveq2d a1i mulcld eqtrd addassd mulcomd
      c2 addcld mulassd 3eqtrd cmin cneg c7 c9 c6 c5 c8 c4 cc0 eqidd cc 3cn cn0
      wcel 3nn0 expcld cq qcn ax-1cn negsubd eqtr4d wa wceq negcld binom3 sqcld
      syl jca cu3addd 2nn0 nn0mulcld nn0cnd addcomd eqcomd cn nnexpcld nnred cr
      3nn qre reexpcld remulcld cdvds wn n2dvds3 negexpidd addlidd 1red addridd
      wbr sqnegd sqmuld expmuld 3t2e6 6p1e7 3eqtr2rd 1nn0 nn0addcld expaddd 7cn
      expp1d df-2 7p1e8 8p1e9 6nn0 adddid mulridd mulexpd 2cn mulcomli 3eqtr4rd
      eqtr2d 3t3e9 3eqtr4d 7nn0 9nn0 mulm1d negidd 8nn0 mullidd negeqd mulneg1d
      4p4e8 4p1e5 oveq12d 3p2e5 3p1e4 2t2e4 5nn0 4nn0 exp1d 1p2e3 adddird 2p2e4
      eqtr3d 2timesd 4p2e6 df-8 df-3 df-7 sq1 mulneg2d 3eqtr2d 2p1e3 ) ADDEFZBD
      EFZGFZHUAFZDEFZUUGUBZDQEFZBGFZIFHIFDEFZIFZUUEBQEFZGFZUULIFZDEFZIFZBUCEFZD
      UDEFZGFZBUEEFZUVAGFZBUFEFZDUGEFZUVFIFZGFZBUHEFZDUCEFZQGFZDUEEFZIFZGFZUUFU
      VLUVLIFZGFZUUODUFEFZGFZDUULHQEFZGFZGFZIFZIFZIFZIFZIFZIFZUVBUVDUVHUVNUVPUV
      RBUUEGFZIFZIFZIFZIFZIFZIFAUUSUVBUVDUVHUVNUVPDUULQEFZHGFZGFZUWAIFZIFZIFZIF
      ZIFZIFZUWGAUUSUVBUVDUVHUVNUULDEFZDUUJUVSGFZGFZIFZDUUGHUBZQEFZGFZGFZIFZUXC
      IFZUWQIFZIFZIFZIFZIFZUXBAUUSUVBUVDUVHDUUPUWNGFZGFZDQGFZUUJUULGFZGFZHGFZIF
      ZUXMIFZIFZIFZIFZUXQAUUSUVBUVDDUUJUWNGFZGFZDUUPQEFZUULGFZGFZIFZUYEIFZIFZIF
      ZUYHAUUSUVBDUUJQEFZHGFZGFZUUPDEFZIFZDUUGQEFZUXGGFZGFZIFZUYOIFZIFZUYQAUUSD
      UYRUULGFZGFZVUGIFZVUHAUUSVUJVUFUYNUYDUXLUWPUWAUIIFZIFZIFZIFZIFZIFZIFZVUKA
      UUSVUJVUFUYNUYDUXLUWPUWAHDEFZUXGDEFZIFZIFZIFZIFZIFZIFZIFZIFZVURAUUSUIVVHI
      FZVVHAUUSUUGDEFZUUJDEFZIFZVVHIFZVVIAUUSVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCU
      XEUXJUXCVVCIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZVVMAUUSVVJVUEIFZUXJV
      UTIFZIFZVVKVUJIFZUYJUXCIFZIFZUYTUYCIFZUWPIFZIFZUXEUWAIFZVUSIFZIFZIFZVUAUY
      MIFZUXSUXCIFZIFZIFZVWGAUUSVWTUURIFZVXDAUUSVWJUUMIFZUURIFZVXEAUUSUUGUXGIFZ
      DEFZUUMIFZUURIFZVXGAUUSUUSVXKAUURUURUUNIAUUQUUQDEAUUQUJJKAVXJUUNUURIAVXIU
      UIUUMIAVXHUUHDEAUUGHAUUEUUFADDDUKUNAULLZDUMUNAUOLZUPZABDABUQUNZBUKUNCBURV
      GZVXMUPZMZHUKUNAUSLZUTJJJVAAVXJVXFUURIAVXIVWJUUMIAUUGUKUNZUXGUKUNZVBVXIVW
      JVCAVXTVYAVXRAHVXSVDZVHUUGUXGVEVGJJNAVXFVWTUURIAUUMVWSVWJIAUUJUULHAUUGVXR
      VDZAUUKBADVXLVFZVXPMZVXSVIKJNAUURVXCVWTIAUUPUKUNZUULUKUNZVBUURVXCVCAVYFVY
      GAUUEUUOVXNABVXPVFZMZVYEVHUUPUULVEVGKNAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCU
      XCUXEUXJUXCUWPUWAVUSIFZVUTIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIF
      ZVWGAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCUXEUXJUXCUWPVUSUWAIFZVUTIFZIFZIF
      ZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZWUFAVXDVVJVVKVUJUYTVUAVUEUYJUYMUX
      SUYCUXCUXEUXJUXCUWPWUGIFZVUTIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZ
      WVCAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCUXEUXJUXCWVDIFZVUTIFZIFZIFZIFZIFZ
      IFZIFZIFZIFZIFZIFZIFZIFZIFZWVSAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCUXEUXJ
      VUTWVTIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZWWNAVXDVVJVVKVUJUYTVUAVUE
      UYJUYMUXSUYCUXCUXEVWIWVTIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZWXHAVXDVVJ
      VVKVUJUYTVUAVUEUYJUYMUXSUYCUXCUXEVWIUXCIFZWVDIFZIFZIFZIFZIFZIFZIFZIFZIFZI
      FZIFZIFZIFZWYAAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCUXEWYBUWPIFZWUGIFZIFZI
      FZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZWYOAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCU
      XEWYPVUSIFZUWAIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZXUIAVXDVVJVVKVUJUYTV
      UAVUEUYJUYMUXSUYCUXCUXEVUSWYPIFZUWAIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIF
      ZXVCAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCUXEUWAXVDIFZIFZIFZIFZIFZIFZIFZIF
      ZIFZIFZIFZIFZIFZXVQAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCVWQXVDIFZIFZIFZIF
      ZIFZIFZIFZIFZIFZIFZIFZIFZXWJAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUXCVWRWYPIF
      ZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZXXBAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUYCUX
      CVWRWYBIFZUWPIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZXXNAVXDVVJVVKVUJUYTVUAVU
      EUYJUYMUXSUYCUXCXXOIFZUWPIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZXYGAVXDVVJVVKVU
      JUYTVUAVUEUYJUYMUXSUYCUWPXYHIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZXYSAVXDVVJVV
      KVUJUYTVUAVUEUYJUYMUXSUYCUWPIFZXYHIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZYUJAVXDVV
      JVVKVUJUYTVUAVUEUYJUYMUXSYUKUXCIFZXXOIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZYVAAVX
      DVVJVVKVUJUYTVUAVUEUYJUYMUXSYVBVWRIFZWYBIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZYVL
      AVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSYVMVWIIFZUXCIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZ
      YWCAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUWPUYCIFZUXCIFZVWRIFZVWIIFZUXCIFZIFZIFZ
      IFZIFZIFZIFZIFZIFZIFZYWNAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSVWRYWPIFZVWIIFZUXC
      IFZIFZIFZIFZIFZIFZIFZIFZIFZIFZYXHAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSVWIYXIIFZ
      UXCIFZIFZIFZIFZIFZIFZIFZIFZIFZIFZYXTAVXDVVJVVKVUJUYTVUAVUEUYJUYMUXSUXCYYA
      IFZIFZIFZIFZIFZIFZIFZIFZIFZIFZYYKAVXDVVJVVKVUJUYTVUAVUEUYJUYMVXBYYAIFZIFZ
      IFZIFZIFZIFZIFZIFZIFZUUUAAVXDVVJVVKVUJUYTVUAVUEUYJUYMVXBIFZYYAIFZIFZIFZIF
      ZIFZIFZIFZIFZUUUJAVXDVVJVVKVUJUYTVUAVUEUYJUUUKVWIIFZYXIIFZIFZIFZIFZIFZIFZ
      IFZIFZUUUSAVXDVVJVVKVUJUYTVUAVUEUYJUUUTVWRIFZYWPIFZIFZIFZIFZIFZIFZIFZIFZU
      UVHAVXDVVJVVKVUJUYTVUAVUEUYJUUVIYWOIFZUXCIFZIFZIFZIFZIFZIFZIFZIFZUUVQAVXD
      VVJVVKVUJUYTVUAVUEUYJVXBUYMIFZVWIIFZVWRIFZYWOIFZUXCIFZIFZIFZIFZIFZIFZIFZI
      FZUUWFAVXDVVJVVKVUJUYTVUAVUEUYJVWRUUWHIFZYWOIFZUXCIFZIFZIFZIFZIFZIFZIFZIF
      ZUUWRAVXDVVJVVKVUJUYTVUAVUEUYJYWOUUWSIFZUXCIFZIFZIFZIFZIFZIFZIFZIFZUUXHAV
      XDVVJVVKVUJUYTVUAVUEUYJUXCUUXIIFZIFZIFZIFZIFZIFZIFZIFZUUXQAVXDVVJVVKVUJUY
      TVUAVUEVWLUUXIIFZIFZIFZIFZIFZIFZIFZUUYEAVXDVVJVVKVUJUYTVUAVUEVWLYWOIFZUUW
      SIFZIFZIFZIFZIFZIFZIFZUUYLAVXDVVJVVKVUJUYTVUAVUEUUYMVWRIFZUUWHIFZIFZIFZIF
      ZIFZIFZIFZUUYTAVXDVVJVVKVUJUYTVUAVUEUVUAUUWGIFZVWIIFZIFZIFZIFZIFZIFZIFZUV
      UHAVXDVVJVVKVUJUYTVUAVUEVWRUUYMIFZUUWGIFZVWIIFZIFZIFZIFZIFZIFZIFZUVUPAVXD
      VVJVVKVUJUYTVUAVUEVWIUVURIFZIFZIFZIFZIFZIFZIFZUVVEAVXDVVJVVKVUJUYTVUAVUEV
      WIIFZUVURIFZIFZIFZIFZIFZIFZUVVLAVXDVVJVVKVUJUYTVUAUVVMUVUQIFZUUWGIFZIFZIF
      ZIFZIFZIFZUVVSAVXDVVJVVKVUJUYTVUAUVVTVXBIFZUYMIFZIFZIFZIFZIFZIFZUVWFAVXDV
      VJVVKVUJUYTVUAVWIVUEIFZUVUQIFZVXBIFZUYMIFZIFZIFZIFZIFZIFZUVWMAVXDVVJVVKVU
      JUYTVUAVXBUVWOIFZUYMIFZIFZIFZIFZIFZIFZUVXBAVXDVVJVVKVUJUYTVUAUYMUVXCIFZIF
      ZIFZIFZIFZIFZUVXIAVXDVVJVVKVUJUYTVXAUVXCIFZIFZIFZIFZIFZUVXOAVXDVVJVVKVUJU
      YTVXCUVWOIFZIFZIFZIFZIFZUVXTAVXDVVJVVKVUJUYTVXCUVWNIFZUVUQIFZIFZIFZIFZIFZ
      UVYEAVXDVVJVVKVUJUYTUVYFVWRIFZUUYMIFZIFZIFZIFZIFZUVYKAVXDVVJVVKVUJUYTUVYL
      VWLIFZYWOIFZIFZIFZIFZIFZUVYQAVXDVVJVVKVUJUYTUVYRUWPIFZUYCIFZIFZIFZIFZIFZU
      WUCAVXDVVJVVKVUJUYTVWRUVYFIFZVWLIFZUWPIFZUYCIFZIFZIFZIFZIFZUWUIAVXDVVJVVK
      VUJUYTUWPUWUKIFZUYCIFZIFZIFZIFZIFZUWUQAVXDVVJVVKVUJUYTUYCUWURIFZIFZIFZIFZ
      IFZUWVCAVXDVVJVVKVUJVWNUWURIFZIFZIFZIFZUWVHAVXDVVJVVKVUJVWOUWUKIFZIFZIFZI
      FZUWVLAVXDVVJVVKVUJVWOUWUJIFZVWLIFZIFZIFZIFZUWVPAVXDVVJVVKVUJVWLUWVQIFZIF
      ZIFZIFZUWWAAVXDVVJVWKUWWBIFZIFZUWWEAVXDVVJVWMUWVQIFZIFZUWWGAVXDVVJVWPUWUJ
      IFZIFZUWWIAVXDVVJVWSUVYFIFZIFZUWWKAVXDVVJVWSVXCIFZUVWNIFZIFZUWWMAVXDVVJUW
      WNVWIIFZVUEIFZIFZUWWPAVXDVVJVWIUWWNIFZVUEIFZIFZUWWSAVXDVVJVUEUWWTIFZIFZUW
      XBAVXDVWHUWWTIFZUWXDAVXDVWJUWWNIFUWXEAVWJVWSVXCAVWHVWIAVVJVUEAUUGDVXRVXMU
      PZADVUDVXLAVUCUXGAUUGVXRVFZVYBMMZRZAUXJVUTADUXIVXLAUUGUXHVXRAUXGVYBVFMMZA
      UXGDVYBVXMUPZRZRAVWPVWRAVWMVWOAVWKVWLAVVKVUJAUUJDVYCVXMUPZADVUIVXLAUYRUUL
      AUUJVYCVFZVYEMMZRZAUYJUXCADUYIVXLAUUJUWNVYCAUULVYEVFZMMZAUULDVYEVXMUPZRZR
      ZAVWNUWPAUYTUYCADUYSVXLAUYRHUWXNVXSMMZAUYBHAUXTUYAAUXTADQVXMQUMUNAVJLZVKZ
      VLZAUUJUULVYCVYEMMVXSMZRZADUWOVXLAUWNHUWXQVXSMMZRZRZAVWQVUSAUXEUWAADUXDVX
      LAUUJUVSVYCAHVXSVFZMMZADUVTVXLAUULUVSVYEUWYKMMZRZAHDVXSVXMUPZRZRZAVXAVXBA
      VUAUYMAUUPDVYIVXMUPZADUYLVXLAUYKUULAUUPVYIVFVYEMMZRZAUXSUXCADUXRVXLAUUPUW
      NVYIUWXQMMZUWXSRZRZOAVWHVWIUWWNUWXIUWXLAVWSVXCUWYQUXUCRZONAVVJVUEUWWTUWXF
      UWXHAVWIUWWNUWXLUXUDRZONAUWXCUWXAVVJIAVUEUWWTUWXHUXUEVMKNAUWXAUWWRVVJIAUW
      WTUWWQVUEIAVWIUWWNUWXLUXUDVMJKNAUWWRUWWOVVJIAUWWNVWIVUEUXUDUWXLUWXHOKNAUW
      WOUWWLVVJIAVWSVXCUVWNUWYQUXUCAVWIVUEUWXLUWXHRZOKNAUWWLUWWJVVJIAVWPVWRUVYF
      UWYJUWYPAVXCUVWNUXUCUXUFRZOKNAUWWJUWWHVVJIAVWMVWOUWUJUWYAUWYIAVWRUVYFUWYP
      UXUGRZOKNAUWWHUWWFVVJIAVWKVWLUWVQUWXPUWXTAVWOUWUJUWYIUXUHRZOKNAUWWFUWWDVV
      JIAVVKVUJUWWBUWXMUWXOAVWLUWVQUWXTUXUIROKNAUWWDUWVTVVJIAUWWCUWVSVVKIAUWWBU
      WVRVUJIAVWLUWVQUWXTUXUIVMKKKNAUWVTUWVOVVJIAUWVSUWVNVVKIAUWVRUWVMVUJIAVWOU
      WUJVWLUWYIUXUHUWXTOKKKNAUWVOUWVKVVJIAUWVNUWVJVVKIAUWVMUWVIVUJIAVWNUWPUWUK
      UWYGUWYHAUWUJVWLUXUHUWXTRZOKKKNAUWVKUWVGVVJIAUWVJUWVFVVKIAUWVIUWVEVUJIAUY
      TUYCUWURUWYBUWYFAUWPUWUKUWYHUXUJRZOKKKNAUWVGUWVBVVJIAUWVFUWVAVVKIAUWVEUWU
      TVUJIAUWVDUWUSUYTIAUYCUWURUWYFUXUKVMKKKKNAUWVBUWUPVVJIAUWVAUWUOVVKIAUWUTU
      WUNVUJIAUWUSUWUMUYTIAUWURUWULUYCIAUWPUWUKUWYHUXUJVMJKKKKNAUWUPUWUHVVJIAUW
      UOUWUGVVKIAUWUNUWUFVUJIAUWUMUWUEUYTIAUWULUWUDUYCIAUWUKUVYRUWPIAUWUJUVYLVW
      LIAVWRUVYFUWYPUXUGVMJJJKKKKNAUWUHUWUBVVJIAUWUGUWUAVVKIAUWUFUVYTVUJIAUWUEU
      VYSUYTIAUVYRUWPUYCAUVYLVWLAUVYFVWRUXUGUWYPRZUWXTRUWYHUWYFOKKKKNAUWUBUVYPV
      VJIAUWUAUVYOVVKIAUVYTUVYNVUJIAUVYSUVYMUYTIAUVYLVWLYWOUXULUWXTAUWPUYCUWYHU
      WYFRZOKKKKNAUVYPUVYJVVJIAUVYOUVYIVVKIAUVYNUVYHVUJIAUVYMUVYGUYTIAUVYFVWRUU
      YMUXUGUWYPAVWLYWOUWXTUXUMRZOKKKKNAUVYJUVYDVVJIAUVYIUVYCVVKIAUVYHUVYBVUJIA
      UVYGUVYAUYTIAVXCUVWNUVUQUXUCUXUFAVWRUUYMUWYPUXUNRZOKKKKNAUVYDUVXSVVJIAUVY
      CUVXRVVKIAUVYBUVXQVUJIAUVYAUVXPUYTIAVXAVXBUVWOUWYTUXUBAUVWNUVUQUXUFUXUORZ
      OKKKKNAUVXSUVXNVVJIAUVXRUVXMVVKIAUVXQUVXLVUJIAUVXPUVXKUYTIAVUAUYMUVXCUWYR
      UWYSAVXBUVWOUXUBUXUPRZOKKKKNAUVXNUVXHVVJIAUVXMUVXGVVKIAUVXLUVXFVUJIAUVXKU
      VXEUYTIAUVXJUVXDVUAIAUYMUVXCUWYSUXUQVMKKKKKNAUVXHUVXAVVJIAUVXGUVWTVVKIAUV
      XFUVWSVUJIAUVXEUVWRUYTIAUVXDUVWQVUAIAUVXCUVWPUYMIAVXBUVWOUXUBUXUPVMJKKKKK
      NAUVXAUVWLVVJIAUVWTUVWKVVKIAUVWSUVWJVUJIAUVWRUVWIUYTIAUVWQUVWHVUAIAUVWPUV
      WGUYMIAUVWOUVVTVXBIAUVWNUVVMUVUQIAVWIVUEUWXLUWXHVMJJJKKKKKNAUVWLUVWEVVJIA
      UVWKUVWDVVKIAUVWJUVWCVUJIAUVWIUVWBUYTIAUVWHUVWAVUAIAUVVTVXBUYMAUVVMUVUQAV
      UEVWIUWXHUWXLRZUXUORUXUBUWYSOKKKKKNAUVWEUVVRVVJIAUVWDUVVQVVKIAUVWCUVVPVUJ
      IAUVWBUVVOUYTIAUVWAUVVNVUAIAUVVMUVUQUUWGUXURUXUOAVXBUYMUXUBUWYSRZOKKKKKNA
      UVVRUVVKVVJIAUVVQUVVJVVKIAUVVPUVVIVUJIAUVVOUVVHUYTIAUVVNUVVGVUAIAVUEVWIUV
      URUWXHUWXLAUVUQUUWGUXUOUXUSRZOKKKKKNAUVVKUVVDVVJIAUVVJUVVCVVKIAUVVIUVVBVU
      JIAUVVHUVVAUYTIAUVVGUVUTVUAIAUVVFUVUSVUEIAVWIUVURUWXLUXUTVMKKKKKKNAUVVDUV
      UOVVJIAUVVCUVUNVVKIAUVVBUVUMVUJIAUVVAUVULUYTIAUVUTUVUKVUAIAUVUSUVUJVUEIAU
      VURUVUIVWIIAUVUQUVUAUUWGIAVWRUUYMUWYPUXUNVMJJKKKKKKNAUVUOUVUGVVJIAUVUNUVU
      FVVKIAUVUMUVUEVUJIAUVULUVUDUYTIAUVUKUVUCVUAIAUVUJUVUBVUEIAUVUAUUWGVWIAUUY
      MVWRUXUNUWYPRUXUSUWXLOKKKKKKNAUVUGUUYSVVJIAUVUFUUYRVVKIAUVUEUUYQVUJIAUVUD
      UUYPUYTIAUVUCUUYOVUAIAUVUBUUYNVUEIAUUYMVWRUUWHUXUNUWYPAUUWGVWIUXUSUWXLRZO
      KKKKKKNAUUYSUUYKVVJIAUUYRUUYJVVKIAUUYQUUYIVUJIAUUYPUUYHUYTIAUUYOUUYGVUAIA
      UUYNUUYFVUEIAVWLYWOUUWSUWXTUXUMAVWRUUWHUWYPUXVARZOKKKKKKNAUUYKUUYDVVJIAUU
      YJUUYCVVKIAUUYIUUYBVUJIAUUYHUUYAUYTIAUUYGUUXTVUAIAUUYFUUXSVUEIAUYJUXCUUXI
      UWXRUWXSAYWOUUWSUXUMUXVBRZOKKKKKKNAUUYDUUXPVVJIAUUYCUUXOVVKIAUUYBUUXNVUJI
      AUUYAUUXMUYTIAUUXTUUXLVUAIAUUXSUUXKVUEIAUUXRUUXJUYJIAUXCUUXIUWXSUXVCVMKKK
      KKKKNAUUXPUUXGVVJIAUUXOUUXFVVKIAUUXNUUXEVUJIAUUXMUUXDUYTIAUUXLUUXCVUAIAUU
      XKUUXBVUEIAUUXJUUXAUYJIAUUXIUUWTUXCIAYWOUUWSUXUMUXVBVMJKKKKKKKNAUUXGUUWQV
      VJIAUUXFUUWPVVKIAUUXEUUWOVUJIAUUXDUUWNUYTIAUUXCUUWMVUAIAUUXBUUWLVUEIAUUXA
      UUWKUYJIAUUWTUUWJUXCIAUUWSUUWIYWOIAVWRUUWHUWYPUXVAVMJJKKKKKKKNAUUWQUUWEVV
      JIAUUWPUUWDVVKIAUUWOUUWCVUJIAUUWNUUWBUYTIAUUWMUUWAVUAIAUUWLUUVTVUEIAUUWKU
      UVSUYJIAUUWJUUVRUXCIAUUWIUUVIYWOIAUUWHUUUTVWRIAUUWGUUUKVWIIAVXBUYMUXUBUWY
      SVMJJJJKKKKKKKNAUUWEUUVPVVJIAUUWDUUVOVVKIAUUWCUUVNVUJIAUUWBUUVMUYTIAUUWAU
      UVLVUAIAUUVTUUVKVUEIAUUVSUUVJUYJIAUUVIYWOUXCAUUUTVWRAUUUKVWIAUYMVXBUWYSUX
      UBRZUWXLRZUWYPRUXUMUWXSOKKKKKKKNAUUVPUUVGVVJIAUUVOUUVFVVKIAUUVNUUVEVUJIAU
      UVMUUVDUYTIAUUVLUUVCVUAIAUUVKUUVBVUEIAUUVJUUVAUYJIAUUUTVWRYWPUXVEUWYPAYWO
      UXCUXUMUWXSRZOKKKKKKKNAUUVGUUURVVJIAUUVFUUUQVVKIAUUVEUUUPVUJIAUUVDUUUOUYT
      IAUUVCUUUNVUAIAUUVBUUUMVUEIAUUVAUUULUYJIAUUUKVWIYXIUXVDUWXLAVWRYWPUWYPUXV
      FRZOKKKKKKKNAUUURUUUIVVJIAUUUQUUUHVVKIAUUUPUUUGVUJIAUUUOUUUFUYTIAUUUNUUUE
      VUAIAUUUMUUUDVUEIAUUULUUUCUYJIAUYMVXBYYAUWYSUXUBAVWIYXIUWXLUXVGRZOKKKKKKK
      NAUUUIYYTVVJIAUUUHYYSVVKIAUUUGYYRVUJIAUUUFYYQUYTIAUUUEYYPVUAIAUUUDYYOVUEI
      AUUUCYYNUYJIAUUUBYYMUYMIAUXSUXCYYAUXUAUWXSUXVHOKKKKKKKKNAYYTYYJVVJIAYYSYY
      IVVKIAYYRYYHVUJIAYYQYYGUYTIAYYPYYFVUAIAYYOYYEVUEIAYYNYYDUYJIAYYMYYCUYMIAY
      YLYYBUXSIAUXCYYAUWXSUXVHVMKKKKKKKKKNAYYJYXSVVJIAYYIYXRVVKIAYYHYXQVUJIAYYG
      YXPUYTIAYYFYXOVUAIAYYEYXNVUEIAYYDYXMUYJIAYYCYXLUYMIAYYBYXKUXSIAYYAYXJUXCI
      AVWIYXIUWXLUXVGVMJKKKKKKKKKNAYXSYXGVVJIAYXRYXFVVKIAYXQYXEVUJIAYXPYXDUYTIA
      YXOYXCVUAIAYXNYXBVUEIAYXMYXAUYJIAYXLYWTUYMIAYXKYWSUXSIAYXJYWRUXCIAYXIYWQV
      WIIAVWRYWPUWYPUXVFVMJJKKKKKKKKKNAYXGYWMVVJIAYXFYWLVVKIAYXEYWKVUJIAYXDYWJU
      YTIAYXCYWIVUAIAYXBYWHVUEIAYXAYWGUYJIAYWTYWFUYMIAYWSYWEUXSIAYWRYWDUXCIAYWQ
      YVMVWIIAYWPYVBVWRIAYWOYUKUXCIAUWPUYCUWYHUWYFVMJJJJKKKKKKKKKNAYWMYWBVVJIAY
      WLYWAVVKIAYWKYVTVUJIAYWJYVSUYTIAYWIYVRVUAIAYWHYVQVUEIAYWGYVPUYJIAYWFYVOUY
      MIAYWEYVNUXSIAYVMVWIUXCAYVBVWRAYUKUXCAUYCUWPUWYFUWYHRZUWXSRZUWYPRUWXLUWXS
      OKKKKKKKKKNAYWBYVKVVJIAYWAYVJVVKIAYVTYVIVUJIAYVSYVHUYTIAYVRYVGVUAIAYVQYVF
      VUEIAYVPYVEUYJIAYVOYVDUYMIAYVNYVCUXSIAYVBVWRWYBUXVJUWYPAVWIUXCUWXLUWXSRZO
      KKKKKKKKKNAYVKYUTVVJIAYVJYUSVVKIAYVIYURVUJIAYVHYUQUYTIAYVGYUPVUAIAYVFYUOV
      UEIAYVEYUNUYJIAYVDYUMUYMIAYVCYULUXSIAYUKUXCXXOUXVIUWXSAVWRWYBUWYPUXVKRZOK
      KKKKKKKKNAYUTYUIVVJIAYUSYUHVVKIAYURYUGVUJIAYUQYUFUYTIAYUPYUEVUAIAYUOYUDVU
      EIAYUNYUCUYJIAYUMYUBUYMIAYULYUAUXSIAUYCUWPXYHUWYFUWYHAUXCXXOUWXSUXVLRZOKK
      KKKKKKKNAYUIXYRVVJIAYUHXYQVVKIAYUGXYPVUJIAYUFXYOUYTIAYUEXYNVUAIAYUDXYMVUE
      IAYUCXYLUYJIAYUBXYKUYMIAYUAXYJUXSIAXYTXYIUYCIAUWPXYHUWYHUXVMVMKKKKKKKKKKN
      AXYRXYFVVJIAXYQXYEVVKIAXYPXYDVUJIAXYOXYCUYTIAXYNXYBVUAIAXYMXYAVUEIAXYLXXT
      UYJIAXYKXXSUYMIAXYJXXRUXSIAXYIXXQUYCIAUXCXXOUWPUWXSUXVLUWYHOKKKKKKKKKKNAX
      YFXXMVVJIAXYEXXLVVKIAXYDXXKVUJIAXYCXXJUYTIAXYBXXIVUAIAXYAXXHVUEIAXXTXXGUY
      JIAXXSXXFUYMIAXXRXXEUXSIAXXQXXDUYCIAXXPXXCUXCIAVWRWYBUWPUWYPUXVKUWYHOKKKK
      KKKKKKKNAXXMXXAVVJIAXXLXWTVVKIAXXKXWSVUJIAXXJXWRUYTIAXXIXWQVUAIAXXHXWPVUE
      IAXXGXWOUYJIAXXFXWNUYMIAXXEXWMUXSIAXXDXWLUYCIAXXCXWKUXCIAVWQVUSWYPUWYNUWY
      OAWYBUWPUXVKUWYHRZOKKKKKKKKKKKNAXXAXWIVVJIAXWTXWHVVKIAXWSXWGVUJIAXWRXWFUY
      TIAXWQXWEVUAIAXWPXWDVUEIAXWOXWCUYJIAXWNXWBUYMIAXWMXWAUXSIAXWLXVTUYCIAXWKX
      VSUXCIAUXEUWAXVDUWYLUWYMAVUSWYPUWYOUXVNRZOKKKKKKKKKKKNAXWIXVPVVJIAXWHXVOV
      VKIAXWGXVNVUJIAXWFXVMUYTIAXWEXVLVUAIAXWDXVKVUEIAXWCXVJUYJIAXWBXVIUYMIAXWA
      XVHUXSIAXVTXVGUYCIAXVSXVFUXCIAXVRXVEUXEIAUWAXVDUWYMUXVOVMKKKKKKKKKKKKNAXV
      PXVBVVJIAXVOXVAVVKIAXVNXUTVUJIAXVMXUSUYTIAXVLXURVUAIAXVKXUQVUEIAXVJXUPUYJ
      IAXVIXUOUYMIAXVHXUNUXSIAXVGXUMUYCIAXVFXULUXCIAXVEXUKUXEIAXVDXUJUWAIAVUSWY
      PUWYOUXVNVMJKKKKKKKKKKKKNAXVBXUHVVJIAXVAXUGVVKIAXUTXUFVUJIAXUSXUEUYTIAXUR
      XUDVUAIAXUQXUCVUEIAXUPXUBUYJIAXUOXUAUYMIAXUNWYTUXSIAXUMWYSUYCIAXULWYRUXCI
      AXUKWYQUXEIAWYPVUSUWAUXVNUWYOUWYMOKKKKKKKKKKKKNAXUHWYNVVJIAXUGWYMVVKIAXUF
      WYLVUJIAXUEWYKUYTIAXUDWYJVUAIAXUCWYIVUEIAXUBWYHUYJIAXUAWYGUYMIAWYTWYFUXSI
      AWYSWYEUYCIAWYRWYDUXCIAWYQWYCUXEIAWYBUWPWUGUXVKUWYHAVUSUWAUWYOUWYMRZOKKKK
      KKKKKKKKNAWYNWXTVVJIAWYMWXSVVKIAWYLWXRVUJIAWYKWXQUYTIAWYJWXPVUAIAWYIWXOVU
      EIAWYHWXNUYJIAWYGWXMUYMIAWYFWXLUXSIAWYEWXKUYCIAWYDWXJUXCIAWYCWXIUXEIAVWIU
      XCWVDUWXLUWXSAUWPWUGUWYHUXVPRZOKKKKKKKKKKKKNAWXTWXGVVJIAWXSWXFVVKIAWXRWXE
      VUJIAWXQWXDUYTIAWXPWXCVUAIAWXOWXBVUEIAWXNWXAUYJIAWXMWWTUYMIAWXLWWSUXSIAWX
      KWWRUYCIAWXJWWQUXCIAWXIWWPUXEIAUXJVUTWVTUWXJUWXKAUXCWVDUWXSUXVQRZOKKKKKKK
      KKKKKNAWXGWWMVVJIAWXFWWLVVKIAWXEWWKVUJIAWXDWWJUYTIAWXCWWIVUAIAWXBWWHVUEIA
      WXAWWGUYJIAWWTWWFUYMIAWWSWWEUXSIAWWRWWDUYCIAWWQWWCUXCIAWWPWWBUXEIAWWOWWAU
      XJIAVUTWVTUWXKUXVRVMKKKKKKKKKKKKKNAWWMWVRVVJIAWWLWVQVVKIAWWKWVPVUJIAWWJWV
      OUYTIAWWIWVNVUAIAWWHWVMVUEIAWWGWVLUYJIAWWFWVKUYMIAWWEWVJUXSIAWWDWVIUYCIAW
      WCWVHUXCIAWWBWVGUXEIAWWAWVFUXJIAUXCWVDVUTUWXSUXVQUWXKOKKKKKKKKKKKKKNAWVRW
      VBVVJIAWVQWVAVVKIAWVPWUTVUJIAWVOWUSUYTIAWVNWURVUAIAWVMWUQVUEIAWVLWUPUYJIA
      WVKWUOUYMIAWVJWUNUXSIAWVIWUMUYCIAWVHWULUXCIAWVGWUKUXEIAWVFWUJUXJIAWVEWUIU
      XCIAUWPWUGVUTUWYHUXVPUWXKOKKKKKKKKKKKKKKNAWVBWUEVVJIAWVAWUDVVKIAWUTWUCVUJ
      IAWUSWUBUYTIAWURWUAVUAIAWUQVYTVUEIAWUPVYSUYJIAWUOVYRUYMIAWUNVYQUXSIAWUMVY
      PUYCIAWULVYOUXCIAWUKVYNUXEIAWUJVYMUXJIAWUIVYLUXCIAWUHVYKUWPIAWUGVYJVUTIAV
      USUWAUWYOUWYMVMJKKKKKKKKKKKKKKKNAWUEVWFVVJIAWUDVWEVVKIAWUCVWDVUJIAWUBVWCU
      YTIAWUAVWBVUAIAVYTVWAVUEIAVYSVVTUYJIAVYRVVSUYMIAVYQVVRUXSIAVYPVVQUYCIAVYO
      VVPUXCIAVYNVVOUXEIAVYMVVNUXJIAVYLVVCUXCIAVYKVVBUWPIAUWAVUSVUTUWYMUWYOUWXK
      OKKKKKKKKKKKKKKKNNAVWGVVLVUJVUFUYNUYDUXKVVNIFZIFZIFZIFZIFZIFZVVMAVWGVVLVU
      JVUFUYNUYDUXFVVOIFZIFZIFZIFZIFZIFZUXWDAVWGVVLVUJVUFUYNUYDVVQIFZIFZIFZIFZI
      FZUXWJAVWGVVLVUJVUFUYNVVSIFZIFZIFZIFZUXWOAVWGVVLVUJVUFVWAIFZIFZIFZUXWSAVW
      GVVLVUJVUBVWBIFZIFZIFZUXXBAVWGVVLVWEIFZUXXEAUXXFVWGAVVJVVKVWEUWXFUWXMAVUJ
      VWDUWXOAUYTVWCUWYBAVUAVWBUWYRAVUEVWAUWXHAUYJVVTUWXRAUYMVVSUWYSAUXSVVRUXUA
      AUYCVVQUWYFAUXCVVPUWXSAUXEVVOUWYLAUXJVVNUWXJAUXCVVCUWXSAUWPVVBUWYHAUWAVVA
      UWYMAVUSVUTUWYOUWXKRRRZRZRZRRZRRZRRZRZRRROVNAUXXDVWEVVLIAUXXCVWDVUJIAUYTV
      UAVWBUWYBUWYRUXXMOKKVAAUXXAUXXDVVLIAUXWTUXXCVUJIAVUBVUEVWAAUYTVUAUWYBUWYR
      RZUWXHUXXLOKKVAAUXWRUXXAVVLIAUXWQUXWTVUJIAUXWPVWAVUFIAUYJUYMVVSUWXRUWYSUX
      XKOKKKVAAUXWNUXWRVVLIAUXWMUXWQVUJIAUXWLUXWPVUFIAUXWKVVSUYNIAUXSUYCVVQUXUA
      UWYFUXXJOKKKKVAAUXWIUXWNVVLIAUXWHUXWMVUJIAUXWGUXWLVUFIAUXWFUXWKUYNIAUXWEV
      VQUYDIAUXCUXEVVOUWXSUWYLUXXIOKKKKKVAAUXWCUXWIVVLIAUXWBUXWHVUJIAUXWAUXWGVU
      FIAUXVTUXWFUYNIAUXVSUXWEUYDIAUXFUXJVVNAUXCUXEUWXSUWYLRZUWXJUXXHOKKKKKVAAV
      VHUXWCVVLIAVVGUXWBVUJIAVVFUXWAVUFIAVVEUXVTUYNIAVVDUXVSUYDIAUXKUXCVVCAUXFU
      XJUXXOUWXJRZUWXSUXXGOKKKKKVANAVVLUIVVHIAUUGDAUUEUUFAUUEADDDVOUNAVSLVXMVPV
      QABDAVXOBVRUNCBVTVGVXMWAWBVXMQDWCWJWDAWELZWFJNAVVHAVUJVVGUWXOAVUFVVFAVUBV
      UEUXXNUWXHRAUYNVVEAUYJUYMUWXRUWYSRAUYDVVDAUXSUYCUXUAUWYFRAUXLVVCAUXKUXCUX
      XPUWXSRUXXGRRRRRWGNAVVGVUQVUJIAVVFVUPVUFIAVVEVUOUYNIAVVDVUNUYDIAVVCVUMUXL
      IAVVBVULUWPIAVVAUIUWAIAHDAWHVXMUXXQWFKKKKKKKNAVUQVUGVUJIAVUPUYOVUFIAVUOUY
      EUYNIAVUNUXMUYDIAVUMUWQUXLIAVULUWAUWPIAUWAUWYMWIKKKKKKNAVUJUVBVUGIAVUJUUT
      DUCHIFZHIFZEFZGFZUUTDUGHIFZEFZGFUVBAVUJUUTDUCHHIFZIFZEFZGFZUXYAAVUJUUTDQU
      CIFZEFZGFZUUTDUCQIFZEFZGFUXYGAVUJUUTDQUXTHIFZIFZEFZGFZUUTDQUEHIFZIFZEFZGF
      UXYJAVUJBUXYQEFZUUKDUUEQEFZGFZGFZGFZUUTUYUCGFUXYPAVUJUUFQEFZBGFZUYUCGFZBU
      XYMEFZUYUCGFUYUDAVUJUYUEBUYUCGFZGFZUYUGAVUJDVUCUULGFZGFDUYUAUYUEGFZUULGFZ
      GFZUYUJAVUIUYUKDGAUYRVUCUULGAUUGVXRWKZJKAUYUKUYUMDGAVUCUYULUULGAUUEUUFVXN
      VXQWLZJKAUYUNUYUEBUUKGFZDGFZUYUAGFZGFZUYUEUYUQUYUBGFZGFUYUJAUYUNUYUEUYUAU
      ULDGFZGFZGFZUYUEUYVBUYUAGFZGFUYUTAUYUNUYUEUYUAGFZUULGFZDGFZUYVFUYVBGFUYVD
      AUYUNUYUMDGFUYVHADUYUMVXLAUYULUULAUYUAUYUEAUUEVXNVFZAUUFVXQVFZMZVYEMPAUYU
      MUYVGDGAUYULUYVFUULGAUYUAUYUEUYVIUYVJPZJJNAUYVFUULDAUYUEUYUAUYVJUYVIMZVYE
      VXLSAUYUEUYUAUYVBUYVJUYVIAUULDVYEVXLMZSTAUYVCUYVEUYUEGAUYUAUYVBUYVIUYVNPZ
      KAUYVEUYUSUYUEGAUYVBUYURUYUAGAUULUYUQDGAUUKBVYDVXPPZJJZKTAUYUSUYVAUYUEGAU
      YUQDUYUAABUUKVXPVYDMZVXLUYVISZKAUYVAUYUIUYUEGABUUKUYUBVXPVYDADUYUAVXLUYVI
      MZSZKTTAUYUEBUYUCUYVJVXPAUUKUYUBVYDUYVTMZSVAAUYUFUYUHUYUCGAUYUFBUXTEFZBGF
      ZUYUHAUYWDUYUFAUYWCUYUEBGABDQVXPUWYCVXMWMZJVNABUXTVXPUWYDXAVAJAUYUHUXYTUY
      UCGAUXYMUXYQBEAUXTUEHIUXTUEVCAWNLZJZKJTAUXYTUUTUYUCGAUXYQUCBEUXYQUCVCAWOL
      ZKJAUYUCUXYOUUTGAUYUCUUKDUXYMEFZGFZUXYOAUYWJUUKDUXTEFZDGFZGFUUKDUYWKGFZGF
      UYUCAUYWIUYWLUUKGADUXTVXLUWYDXAZKAUYWMUYWLUUKGADUYWKVXLADUXTVXLUWYDUPPKAU
      YWMUYUBUUKGAUYWKUYUADGADDQVXLUWYCVXMWMZKKWPADQUXYMVXLAUXTHUWYDHUMUNAWQLZW
      RUWYCWSVAZKTAUXYOUXYSUUTGAUXYNUXYRDEAUXYMUXYQQIUYWGKKZKAUXYSUXYIUUTGAUXYR
      UXYHDEAUXYQUCQIUYWHKKZKTAUXYIUXYLUUTGAUXYHUXYKDEAQUCAQUWYCVLZUCUKUNAWTLZV
      MKKAUXYLUXYFUUTGAUXYKUXYEDEAQUXYDUCIQUXYDVCAXBLZKKKTAUXXTUXYFUUTGAUXXSUXY
      EDEAUCHHUYXAVXSVXSOKKVAAUXXTUXYCUUTGAUXXSUXYBDEAUXXRUGHIUXXRUGVCAXCLZJKKA
      UXYCUVAUUTGAUXYBUDDEUXYBUDVCAXDLKKTJNAVUGUYPUVBIAVUFUVDUYOIAVUFUVCUVAUVJU
      VJUBZIFZIFZGFZUVCUVAUIIFZGFUVDAVUFUVCUVAUVJUVJUXGGFZIFZIFZGFZUVCUVAUVJUXG
      UVJGFZIFZIFZGFUYXGAVUFUVCUVJUVAIFZUYXIIFZGFZUVCUVAUVJIFZUYXIIFZGFUYXLAVUF
      UVCUYXPUVLDGFZUXGGFZIFZGFZUVCUYXPDUXYQEFZUXGGFZIFZGFUYXRAUVCUYXPUVLUXGDGF
      ZGFZIFZGFZUVCUYXPUVLDUXGGFZGFZIFZGFVUFUYYDAUYYJUYYNUVCGAUYYIUYYMUYXPIAUYY
      HUYYLUVLGAUXGDVYBVXLPKKKAVUFUVCUVJDDDGFZEFZIFZUYWKUYYHGFZIFZGFZUVCUYXPUYY
      RIFZGFUYYKAVUFUVCUYWIUYYPIFZUYYRIFZGFZUVCUYYEUYYPIFZUYYRIFZGFUYYTAVUFUVCU
      YUADGFZUUEDEFZIFZUYUAUYYHGFZIFZGFZVUUDAUVCVUUIGFZUVCVUUJGFZIFUVCVUUGGFZUV
      CVUUHGFZIFZVUUNIFZVUULVUFAVUUMVUUQVUUNIAUVCVUUGVUUHABUEVXPUEUMUNAXELZUPZA
      UYUADUYVIVXLMZAUUEDVXNVXMUPZXFJAUVCVUUIVUUJVUUTAVUUGVUUHVUVAVUVBRAUYUAUYY
      HUYVIAUXGDVYBVXLMZMXFAVUFVUUQUYUEVUUJGFZIFZVUUQUYWCVUUJGFZIFVUURAVUFUYWCV
      UUGGFZBQDGFZEFZVUUHGFZIFZVUVDIFZVUUOVUVJIFZVUVDIFVUVEAVUFUYUEVUUGGFZUUODE
      FZVUUHGFZIFZVUVDIFZVUVGVUVPIFZVUVDIFVUVLAVUFVUVNVUUHVUVOGFZIFZDUYULUXGGFZ
      GFZIFZVUVQVUWCIFVUVRAVUFDVUCGFZVUAIFZVUEIFZDUYULGFZVUVTIFZVUWCIFZVUWDAVUF
      DVUCHGFZGFZVUAIFZVUEIFVUWGAVUBVUWMVUEIAUYTVUWLVUAIAUYSVUWKDGAUYRVUCHGUYUO
      JKJJAVUWMVUWFVUEIAVUWLVUWEVUAIAVUWKVUCDGAVUCUWXGXGKJJNAVUWGVUWHVUAIFZVUEI
      FVUWIVUEIFVUWJAVUWFVUWNVUEIAVUWEVUWHVUAIAVUCUYULDGUYUPKJJAVUWNVUWIVUEIAVU
      AVUVTVUWHIAUUEUUODVXNVYHVXMXHKJAVUEVUWCVUWIIAVUDVUWBDGAVUCUYULUXGGUYUPJKK
      TAVUWIVUWAVUWCIAVUWHVUVNVUVTIAVUWHUYULDGFUYVFDGFVUVNADUYULVXLUYVKPAUYULUY
      VFDGUYVLJAUYUEUYUADUYVJUYVIVXLSTJJTAVUWAVUVQVUWCIAVUVTVUVPVUVNIAVUUHVUVOV
      UVBAUUODVYHVXMUPPKJAVUWCVUVDVUVQIAVUWCUYVFUXGGFZDGFZUYVFUYYHGFVUVDAVUWCVU
      WBDGFVUWPADVUWBVXLAUYULUXGUYVKVYBMPAVUWBVUWODGAUYULUYVFUXGGUYVLJJNAUYVFUX
      GDUYVMVYBVXLSAUYUEUYUAUYYHUYVJUYVIVUVCSTKTAVUVQVUVSVUVDIAVUVNVUVGVUVPIAUY
      UEUYWCVUUGGAUYWCUYUEUYWEVNZJJJAVUVSVUVKVUVDIAVUVPVUVJVUVGIAVUVOVUVIVUUHGA
      VUVIVUVOABQDVXPVXMUWYCWMVNJKJTAVUVKVUVMVUVDIAVUVGVUUOVUVJIAUYWCUVCVUUGGAU
      XTUEBEUYWFKZJJJAVUVMVUUQVUVDIAVUVJVUUPVUUOIAVUVIUVCVUUHGAVUVHUEBEVUVHUEVC
      ADQUEULXIWNXJLZKJKJTAVUVDVUVFVUUQIAUYUEUYWCVUUJGVUWQJKAVUVFVUUNVUUQIAUYWC
      UVCVUUJGVUWRJKTXKAVUUKVUUCUVCGAVUUBVUUJIFUYWIVUUHIFZVUUJIFZVUUCVUUKAVUUBV
      UWTVUUJIAUYYPVUUHUYWIIADDDVXLVXMVXMWMKJAUYYRVUUJVUUBIAUYWKUYUAUYYHGUYWOJK
      AVUXAUYWLVUUHIFZVUUJIFVUUKAVUWTVUXBVUUJIAUYWIUYWLVUUHIUYWNJJAVUXBVUUIVUUJ
      IAUYWLVUUGVUUHIAUYWKUYUADGUYWOJJJXLXKKNAVUUCVUUFUVCGAVUUBVUUEUYYRIAUYWIUY
      YEUYYPIAUXYMUXYQDEUYWGKJJKAVUUFUYYSUVCGAVUUEUYYQUYYRIAUYYEUVJUYYPIAUXYQUC
      DEUYWHKZJJKTAUYYSVUUAUVCGAUYYQUYXPUYYRIAUYYPUVAUVJIAUYYOUDDEUYYOUDVCAXMLK
      KJKAVUUAUYYJUVCGAUYYRUYYIUYXPIAUYWKUVLUYYHGAUXTUEDEUYWFKJKKTAUYYCUYYNUVCG
      AUYYBUYYMUYXPIAUVLDUXGADUEVXLVUUSUPZVXLVYBSKKXNAUYYCUYYGUVCGAUYYBUYYFUYXP
      IAUYYFUYYBAUYYEUYYAUXGGADUEVXLVUUSXAJVNKKAUYYGUYXQUVCGAUYYFUYXIUYXPIAUYYE
      UVJUXGGVUXCJKKTAUYXQUYXTUVCGAUYXPUYXSUYXIIAUVJUVAADUCVXLUCUMUNAXOLZUPZADU
      DVXLUDUMUNAXPLUPZVMJKAUYXTUYXKUVCGAUVAUVJUYXIVUXGVUXFAUVJUXGVUXFVYBMOKTAU
      YXKUYXOUVCGAUYXJUYXNUVAIAUYXIUYXMUVJIAUVJUXGVUXFVYBPKKKAUYXOUYXFUVCGAUYXN
      UYXEUVAIAUYXMUYXDUVJIAUVJVUXFXQKKKTAUYXFUYXHUVCGAUYXEUIUVAIAUVJVUXFXRKKAU
      YXHUVAUVCGAUVAVUXGWIKTJKNAUYPUYGUVBIAUYOUYFUVDIAUYNUVHUYEIAUYNUVEUIQUVFGF
      ZIFZGFZUVEVUXHGFUVHAUYNUVEUVFUBZUVFIFZVUXHIFZGFZUVEUVFVUXKIFZVUXHIFZGFVUX
      JAUVEVUXKHUVFGFZVUXHIFZIFZGFZUVEVUXKUVFVUXHIFZIFZGFUYNVUXNAVUXSVUYBUVEGAV
      UXRVUYAVUXKIAVUXQUVFVUXHIAUVFADUGVXLUGUMUNAXSLZUPZXTJKKAUYNUVEVUXKHQIFZUV
      FGFZIFZGFZVUXTAUVEDUHUHIFZEFZUBZDUVFGFZIFZGFZUVEVUXKVUYLIFZGFUYNVUYHAVUYM
      VUYOUVEGAVUYKVUXKVUYLIAVUYJUVFAVUYIUGDEVUYIUGVCAYCLKZYAJKAUYNUVEDUHEFZUBZ
      VUYQGFZVUYLIFZGFZUVEVUYQVUYQGFZUBZVUYLIFZGFVUYNAUYNUVEVUYQVUYRGFZDHEFZUVF
      GFZIFZGFZUVEVVUEVUYLIFZGFVVUAAUYNUVEVVUEDHUXXRIFZEFZIFZGFZUVEVVUEDHUGIFZE
      FZIFZGFVVUIAUYNUVEVVUEDUXYDUCIFZEFZIFZGFZUVEVVUEDHHUCIFZIFZEFZIFZGFVVUNAU
      YNUVEVVUEUXYSIFZGFZUVEVVUEUXYIIFZGFVVVAAUYNUVEVVUEUYUCIFZGFZUVEVVUEUXYOIF
      ZGFVVVGAUVEVVUEGFZBUHHIFZEFZUYUCGFZIFZVVVLUVEUYUCGFZIFUYNVVVJAVVVOVVVQVVV
      LIAVVVNUVEUYUCGAVVVMUFBEVVVMUFVCAYDLZKJKAUYNVVVLUUOQEFZBGFZUYUCGFZIFZVVVL
      BQQGFZHIFZEFZUYUCGFZIFVVVPAVVVLDUYUAVVVSGFZUULGFZGFZIFZVVVLVVVSUYUIGFZIFU
      YNVVWBAVVWIVVWKVVVLIAVVWIVVVSUYUSGFZVVVSUYVAGFVVWKAVVWIVVVSUYVCGFZVVVSUYV
      EGFVVWLAVVWIVVVSUYUAGFZUULGFZDGFZVVWNUYVBGFVVWMAVVWIVVWHDGFVVWPADVVWHVXLA
      VVWGUULAUYUAVVVSUYVIAUUOVYHVFZMVYEMPAVVWHVVWODGAVVWGVVWNUULGAUYUAVVVSUYVI
      VVWQPJJNAVVWNUULDAVVVSUYUAVVWQUYVIMVYEVXLSAVVVSUYUAUYVBVVWQUYVIUYVNSTAUYV
      CUYVEVVVSGUYVOKAUYVEUYUSVVVSGUYVQKTAUYUSUYVAVVVSGUYVSKAUYVAUYUIVVVSGUYWAK
      TKAUYNUVEDVVWCEFZDDHIFZEFZUBZGFZGFZVVWIIFZUVEVVWRVUYRGFZGFZVVWIIFVVWJAUYN
      UVEUUKQEFZUUEUBZDGFZGFZGFZVVWIIFZUVEVVXGUUEDGFZUBZGFZGFZVVWIIFVVXDAUYNBDQ
      IFZEFZVVXGDVVXHGFZGFZGFZVVWIIFZUVEVVXTGFZVVWIIFVVXLAUYNUUFUUOGFZVVXTGFZVV
      WIIFZVVYBADVVXHUUFGFZVVXGUUOGFZGFZGFZVVWIIFZUUFUUOVVXTGFZGFZVVWIIFUYNVVYF
      AVVYJVVYMVVWIIAVVYJUUFUUOVVXGGFZDGFZVVXHGFZGFZUUFVVYNVVXSGFZGFVVYMAVVYJUU
      FVVXHVVYHDGFZGFZGFZUUFVVYSVVXHGFZGFVVYQAVVYJUUFVVXHGFZVVYHGFZDGFZVWUCVVYS
      GFVWUAAVVYJVVYIDGFVWUEADVVYIVXLAVVYGVVYHAVVXHUUFAUUEVXNVDZVXQMZAVVXGUUOAU
      UKVYDVFZVYHMZMPAVVYIVWUDDGAVVYGVWUCVVYHGAVVXHUUFVWUFVXQPZJJNAVWUCVVYHDAUU
      FVVXHVXQVWUFMZVWUIVXLSAUUFVVXHVVYSVXQVWUFAVVYHDVWUIVXLMZSTAVVYTVWUBUUFGAV
      VXHVVYSVWUFVWULPKAVWUBVVYPUUFGAVVYSVVYOVVXHGAVVYHVVYNDGAVVXGUUOVWUHVYHPJZ
      JKTAVVYPVVYRUUFGAVVYNDVVXHAUUOVVXGVYHVWUHMZVXLVWUFSKAVVYRVVYLUUFGAUUOVVXG
      VVXSVYHVWUHADVVXHVXLVWUFMZSKTJADVVYGUWNGFZGFZUYMIFUYNVVYKAVWUQUYJUYMIAVWU
      PUYIDGAVVYGUUJUWNGAUUEUUFVXNVXQYBZJKJAVWUQVVYJUYMVVWIIAVWUPVVYIDGAUWNVVYH
      VVYGGAUUKBVYDVXPWLZKKAUYLVVWHDGAUYKVVWGUULGAUUEUUOVXNVYHWLJKYEYOAVVYEVVYM
      VVWIIAUUFUUOVVXTVXQVYHAVVXGVVXSVWUHVWUOMSJXNAVVYEVVYAVVWIIAVVYDVVXRVVXTGA
      VVXRVVYDABDQVXPUWYCVXMWSVNJJNAVVYAVVYCVVWIIAVVXRUVEVVXTGAVVXQUFBEVVXQUFVC
      AYFLKJJAVVYCVVXKVVWIIAVVXTVVXJUVEGAVVXSVVXIVVXGGADVVXHVXLVWUFPKKJTAVVXKVV
      XPVVWIIAVVXJVVXOUVEGAVVXIVVXNVVXGGAUUEDVXNVXLYBKKJAVVXPVVXCVVWIIAVVXOVVXB
      UVEGAVVXBVVWRVVXNGFVVXOAVVXAVVXNVVWRGAVVWTVVXMADDVXLVXMXAZYAKAVVWRVVXGVVX
      NGADQQVXLUWYCUWYCWMZJXLKJTAVVXCVVXFVVWIIAVVXBVVXEUVEGAVVXAVUYRVVWRGAVVWTV
      UYQAVVWSUHDEVVWSUHVCAYGLZKYAKKJAVVXFVVVLVVWIIAVVXEVVUEUVEGAVVWRVUYQVUYRGA
      VVWCUHDEVVWCUHVCAYHLZKJKJTAVVWAVVWKVVVLIAVVVSBUYUCVVWQVXPUYWBSKXNAVVWAVVW
      FVVVLIAVVVTVVWEUYUCGAVVWEBVVWCEFZBGFVVVTABVVWCVXPAQQUWYCUWYCVKZXAAVWVDVVV
      SBGABQQVXPUWYCUWYCWMJXLJKAVVWFVVVOVVVLIAVVWEVVVNUYUCGAVVWDVVVMBEAVVWCUHHI
      VWVCJZKJKTAUVEVVUEUYUCABUFVXPUFUMUNAYILUPAVUYQVUYRADUHVXLUHUMUNAYJLZUPZAV
      UYQVWVHVDZMUYWBXFXNAVVVIVVVKUVEGAUYUCUXYOVVUEIUYWQKKAVVVKVVVFUVEGAUXYOUXY
      SVVUEIUYWRKKTAVVVFVVVHUVEGAUXYSUXYIVVUEIUYWSKKAVVVHVVUTUVEGAUXYIVVUSVVUEI
      AUXYHVVURDEAQUXYDUCIUYXBJKKKTAVVUTVVVEUVEGAVVUSVVVDVVUEIAVVURVVVCDEAHHUCV
      XSVXSUYXAOKKKAVVVEVVUMUVEGAVVVDVVULVVUEIAVVVCVVUKDEAVVVBUXXRHIAHUCVXSUYXA
      VMKKKKTAVVUMVVUQUVEGAVVULVVUPVVUEIAVVUKVVUODEAUXXRUGHIUYXCKKKKAVVUQVVUHUV
      EGAVVUPVVUGVVUEIADHUGVXLVUYCUYWPWSKKTAVVUHVVUJUVEGAVVUGVUYLVVUEIAVVUFDUVF
      GADVXLYKZJKKAVVUJVUYTUVEGAVVUEVUYSVUYLIAVUYQVUYRVWVHVWVIPJKTAVUYTVVUDUVEG
      AVUYSVVUCVUYLIAVUYQVUYQVWVHVWVHYBJKAVVUDVUYMUVEGAVVUCVUYKVUYLIAVVUBVUYJAV
      UYJVVUBADUHUHVXLVWVGVWVGWSVNYAJKTAVUYGVUYOUVEGAVUYFVUYLVUXKIAVUYEDUVFGVUY
      EDVCAYLLZJKKXNAVUYGVUXSUVEGAVUYFVUXRVUXKIAHQUVFVXSUYWTVUYDYMKKNAVUXMVUYBU
      VEGAVUXKUVFVUXHAUVFVUYDVDZVUYDAQUVFUYWTVUYDMZOKXNAVUXMVUXPUVEGAVUXLVUXOVU
      XHIAVUXKUVFVWVLVUYDVMJKAVUXPVUXIUVEGAVUXOUIVUXHIAUVFVUYDXRJKTAVUXIVUXHUVE
      GAVUXHVWVMWGKAVUXHUVGUVEGAUVFVUYDYPKTJKKNAUYGUXPUVBIAUYFUXOUVDIAUYEUXNUVH
      IAUYDUVNUXMIAUYDUVIUVMUVLQGFZVWVNUBZIFZIFZGFZUVIUVMUIIFZGFUVNAUYDUVIUVMVW
      VNIFZVWVOIFZGFZVWVRAUVIUVKUVLHGFZVWVNIFZIFZVWVOIFZGFZUVIUVKUVLVWVNIFZIFZV
      WVOIFZGFUYDVWWBAVWWFVWWJUVIGAVWWEVWWIVWVOIAVWWDVWWHUVKIAVWWCUVLVWVNIAUVLV
      UXDXGJKJKAUYDUVIUVKUVLVUYEGFZIFZVWVOIFZGFZVWWGAUVIUVKUVLVVUFGFZIFZVWVOIFZ
      GFZUVIUVKUYYAIFZVWVOIFZGFUYDVWWNAVWWQVWWTUVIGAVWWPVWWSVWVOIAVWWOUYYAUVKIA
      VVUFDUVLGVWVJKKJKAUYDUVIUVKUVJIFZVWVOIFZGFZUVIUVKUYYEIFZVWVOIFZGFVWWRAUYD
      UVIUVJQHIFZGFZVWVOIFZGFZUVIUVKUVJHGFZIFZVWVOIFZGFVWXCAUYDUVIUVJVVUFGFZVWV
      OIFZGFZUVIUVJDGFZVWVOIFZGFVWXIAUYDUVIUVFVWVOIFZGFZUVIDUXXREFZVWVOIFZGFVWX
      OAUYDUVIUVFDVVWSQIFZEFZQGFZUBZIFZGFZUVIUVFDUHQIFZEFZQGFZUBZIFZGFVWXSAUYDU
      VIUVFVVXMUUKGFZQGFZUBZIFZGFZVWYGAUVIUVFVVXMQUUKGFZGFZUBZIFZGFZUVIUVFVVXMU
      UKQGFZGFZUBZIFZGFUYDVWYQAVXUAVXUFUVIGAVWYTVXUEUVFIAVWYSVXUDAVWYRVXUCVVXMG
      AQUUKUYWTVYDPKYAKKAUYDUVIUVFVVXMQGFZUBZUUKGFZIFZGFZUVIUVFVXUGUUKGFZUBZIFZ
      GFVXUBAUYDUVIUVFUUKVXUHGFZIFZGFZVXUKAUVIUVFUUKUUEVUVHGFZUBZGFZIFZGFZUVIUV
      FUUKUUEUXTGFZUBZGFZIFZGFUYDVXUQAVXVAVXVFUVIGAVXUTVXVEUVFIAVXUSVXVDUUKGAVX
      URVXVCAVUVHUXTUUEGAQDUYWTVXLPKYAKKKAUYDUVIUVFUUKUUEQGFZUBZDGFZGFZIFZGFZUV
      IUVFUUKVXVGDGFZUBZGFZIFZGFVXVBAUYDUVIUVFUUKDVVXHQGFZGFZGFZIFZGFZUVIUVFUUK
      DVXVHGFZGFZIFZGFVXVLAUYDUVIUVFUUKDQHVVXHGFZGFZGFZGFZIFZGFZUVIUVFUUKDQVVXH
      GFZGFZGFZIFZGFVXWAAUVIUVFGFZBVVWSEFZVXWHGFZIFZVXWOUVIVXWHGFZIFUYDVXWJAVXW
      QVXWSVXWOIAVXWPUVIVXWHGAVVWSUHBEVWVBKJKAUYDVXWOUUFBGFZVXWHGFZIFZVXWRAVXWO
      UXTVVYGUULGFZGFZHGFZIFZVXWOUUFBVXWHGFZGFZIFUYDVXXBAVXXEVXXHVXWOIAVXXEUUFB
      UUKUXTHGFZVVXHGFZGFZGFZGFZUUFBUUKUXTVXWEGFZGFZGFZGFVXXHAVXXEUUFUYUQVXXIGF
      ZVVXHGFZGFZUUFUYUQVXXJGFZGFVXXMAVXXEUUFVVXHUULVXXIGFZGFZGFZUUFVXYAVVXHGFZ
      GFVXXSAVXXEVWUCUULGFZVXXIGFZVWUCVXYAGFVXYCAVXXEVXXCUXTGFZHGFVXYEUXTGFZHGF
      VXYFAVXXDVXYGHGAUXTVXXCUWYEAVVYGUULVWUGVYEMPJAVXYGVXYHHGAVXXCVXYEUXTGAVVY
      GVWUCUULGVWUJJJJAVXYEUXTHAVWUCUULVWUKVYEMUWYEVXSSTAVWUCUULVXXIVWUKVYEAUXT
      HUWYEVXSMZSAUUFVVXHVXYAVXQVWUFAUULVXXIVYEVXYIMZSTAVXYBVXYDUUFGAVVXHVXYAVW
      UFVXYJPKAVXYDVXXRUUFGAVXYAVXXQVVXHGAUULUYUQVXXIGUYVPJJKTAVXXRVXXTUUFGAUYU
      QVXXIVVXHUYVRVXYIVWUFSKAVXXTVXXLUUFGABUUKVXXJVXPVYDAVXXIVVXHVXYIVWUFMSKTA
      VXXLVXXPUUFGAVXXKVXXOBGAVXXJVXXNUUKGAUXTHVVXHUWYEVXSVWUFSKKKAVXXPVXXGUUFG
      AVXXOVXWHBGAVXXNVXWGUUKGADQVXWEVXLUYWTAHVVXHVXSVWUFMZSKKKTKAUYDUVIDUHVVWS
      IFZEFZGFZVXXEIFZUVIVUYJGFZVXXEIFVXXFAUYDUVIVVXGDUUEGFZGFZGFZVXXEIFZUVIDVV
      WCVVWSIFZEFZGFZVXXEIFVXYOAUYDUUOUUOGFZVXYRGFZVXXEIFZBQQIFZEFZVXYRGFZVXXEI
      FVXYTADUUPVVYHGFZGFZVXXEIFZUUOUUOVXYRGFZGFZVXXEIFUYDVYUFAVYUKVYUNVXXEIAVY
      UKUUOVVYOUUEGFZGFZUUOVVYNVXYQGFZGFVYUNAVYUKUUOUUEVVYSGFZGFZUUOVVYSUUEGFZG
      FVYUPAVYUKUUOUUEGFZVVYHGFZDGFZVYVAVVYSGFVYUSAVYUKVYUJDGFVYVCADVYUJVXLAUUP
      VVYHVYIVWUIMPAVYUJVYVBDGAUUPVYVAVVYHGAUUEUUOVXNVYHPJJNAVYVAVVYHDAUUOUUEVY
      HVXNMVWUIVXLSAUUOUUEVVYSVYHVXNVWULSTAVYURVYUTUUOGAUUEVVYSVXNVWULPKAVYUTVY
      UOUUOGAVVYSVVYOUUEGVWUMJKTAVYUOVYUQUUOGAVVYNDUUEVWUNVXLVXNSKAVYUQVYUMUUOG
      AUUOVVXGVXYQVYHVWUHADUUEVXLVXNMZSKTJAUXSVXXEIFUYDVYULAVXXEUYCUXSIAVXXDUYB
      HGAVXXCUYAUXTGAVVYGUUJUULGVWURJKJKAUXSVYUKVXXEIAUXRVYUJDGAUWNVVYHUUPGVWUS
      KKJYOAVYUEVYUNVXXEIAUUOUUOVXYRVYHVYHAVVXGVXYQVWUHVYVDMSJXNAVYUEVYUIVXXEIA
      VYUDVYUHVXYRGAVYUHVYUDABQQVXPUWYCUWYCWSVNJJAVYUIVXYSVXXEIAVYUHUVIVXYRGAVY
      UGUHBEVYUGUHVCAYNLKJJTAVXYSVYUCVXXEIAVXYRVYUBUVIGAVXYRVVWRVVWTGFZVYUBAVVW
      RVXYQGFZVVWRVVXMGFVXYRVYVEAVXYQVVXMVVWRGADUUEVXLVXNPKAVYVFVXYRAVVWRVVXGVX
      YQGVWVAJVNAVVWTVVXMVVWRGVWUTKXNADVVWCVVWSVXLADHVXMUYWPWRZVWVEWSVAKJAVYUCV
      XYNVXXEIAVYUBVXYMUVIGAVYUAVXYLDEAVVWCUHVVWSIVWVCJKKJTAVXYNVXYPVXXEIAVXYMV
      UYJUVIGAVXYLVUYIDEAVVWSUHUHIVWVBKKKJAVXYPVXWOVXXEIAVUYJUVFUVIGVUYPKJTAVXX
      AVXXHVXWOIAUUFBVXWHVXQVXPAUUKVXWGVYDADVXWFVXLAQVXWEUYWTVXYKMMMZSKXNAVXXAV
      XWQVXWOIAVXWTVXWPVXWHGAVXWPVXWTABDVXPVXMXAVNJKNAUVIUVFVXWHABUHVXPVWVGUPVU
      YDVYVHXFXNAVXWIVXWNUVIGAVXWHVXWMUVFIAVXWGVXWLUUKGAVXWFVXWKDGAVXWEVVXHQGAV
      VXHVWUFXTKKKKKAVXWNVXVTUVIGAVXWMVXVSUVFIAVXWLVXVRUUKGAVXWKVXVQDGAQVVXHUYW
      TVWUFPKKKKTAVXVTVXWDUVIGAVXVSVXWCUVFIAVXVRVXWBUUKGAVXVQVXVHDGAUUEQVXNUYWT
      YBKKKKAVXWDVXVKUVIGAVXWCVXVJUVFIAVXWBVXVIUUKGADVXVHVXLAVXVGAUUEQVXNUYWTMZ
      VDPKKKTAVXVKVXVPUVIGAVXVJVXVOUVFIAVXVIVXVNUUKGAVXVGDVYVIVXLYBKKKAVXVPVXVA
      UVIGAVXVOVXUTUVFIAVXVNVXUSUUKGAVXVMVXURAUUEQDVXNUYWTVXLSYAKKKTAVXUPVXVFUV
      IGAVXUOVXVEUVFIAVXUHVXVDUUKGAVXUGVXVCAUUEDQVXNVXLUYWTSYAKKKXNAVXUPVXUJUVI
      GAVXUOVXUIUVFIAUUKVXUHVYDAVXUGAVVXMQAUUEDVXNVXLMZUYWTMZVDPKKNAVXUJVXUNUVI
      GAVXUIVXUMUVFIAVXUGUUKVYVKVYDYBKKAVXUNVXUAUVIGAVXUMVWYTUVFIAVXULVWYSAVVXM
      QUUKVYVJUYWTVYDSYAKKTAVWYPVXUFUVIGAVWYOVXUEUVFIAVWYNVXUDAVVXMUUKQVYVJVYDU
      YWTSYAKKXNAVWYPVWYFUVIGAVWYOVWYEUVFIAVWYNVWYDAVWYMVWYCQGAVWYCVVWTUUKGFVWY
      MADVVWSQVXLUWYCVYVGWSAVVWTVVXMUUKGVWUTJXLJYAKKNAVWYFVWYLUVIGAVWYEVWYKUVFI
      AVWYDVWYJAVWYCVWYIQGAVWYBVWYHDEAVVWSUHQIVWVBJKJYAKKAVWYLVWXRUVIGAVWYKVWVO
      UVFIAVWYJVWVNAVWYIUVLQGAVWYHUEDEVWYHUEVCAYQLKJYAKKTAVWXRVWYAUVIGAUVFVWXTV
      WVOIAUGUXXRDEUGUXXRVCAYRLKJKAVWYAVWXNUVIGAVWXTVWXMVWVOIADUCHVXLUYWPVUXEWS
      JKTAVWXNVWXQUVIGAVWXMVWXPVWVOIAVVUFDUVJGVWVJKJKAVWXQVWXHUVIGAVWXPVWXGVWVO
      IADVWXFUVJGDVWXFVCAYSLKJKTAVWXHVWXLUVIGAVWXGVWXKVWVOIAUVJQHVUXFUYWTVXSXFJ
      KAVWXLVWXBUVIGAVWXKVWXAVWVOIAVWXJUVJUVKIAUVJVUXFXGKJKTAVWXBVWXEUVIGAVWXAV
      WXDVWVOIAUVJUYYEUVKIAUCUXYQDEUCUXYQVCAYTLKKJKAVWXEVWWQUVIGAVWXDVWWPVWVOIA
      UYYEVWWOUVKIADUEHVXLUYWPVUUSWSKJKTAVWWMVWWTUVIGAVWWLVWWSVWVOIAVWWKUYYAUVK
      IAVUYEDUVLGVWVKKKJKXNAVWWMVWWFUVIGAVWWLVWWEVWVOIAVWWKVWWDUVKIAUVLHQVUXDVX
      SUYWTXFKJKNAVWWAVWWJUVIGAVWVTVWWIVWVOIAUVKUVLVWVNAUVJQVUXFUYWTMZVUXDAUVLQ
      VUXDUYWTMZOJKXNAVWWAVWVQUVIGAUVMVWVNVWVOAUVKUVLVYVLVUXDRZVYVMAVWVNVYVMVDO
      KNAVWVQVWVSUVIGAVWVPUIUVMIAVWVNVYVMXRKKAVWVSUVMUVIGAUVMVYVNWIKTJKKKNAUXPU
      XAUVBIAUXOUWTUVDIAUXNUWSUVHIAUXMUWRUVNIAUXLUVPUWQIAUXLUUFDVUVHEFZVYVOIFZG
      FZUUFUVLVYVOIFZGFUVPAUXLUUFUUKDEFZGFZVYVTIFZUUFVYVSVYVSIFZGFVYVQAUXLVYVSU
      UFGFZVYWCIFZVYVTVYWCIFVYWAAUXLUXCUIIFZUXCIFZUXCUXCIFVYWDAUXLUXCDUUGGFZUBZ
      VYWGIFZIFZUXCIFZUXCVYWGVYWHIFZIFZUXCIFVYWFAUXLUXCDUUJGFZIFZVYWGIFZUXCIFZU
      XCVYWNVYWGIFZIFZUXCIFVYWKAUXLUXCDUUJHGFZGFZIFZDUUGHGFZGFZIFZUXCIFZVYWOVYX
      DIFZUXCIFVYWQAUXLUXFDUUGUVSGFZGFZIFZUXCIFUXFVYXDIFZUXCIFVYXFAUXKVYXJUXCIA
      UXJVYXIUXFIAUXIVYXHDGAUXHUVSUUGGAHVXSWKKKKJAVYXJVYXKUXCIAVYXIVYXDUXFIAVYX
      HVYXCDGAUVSHUUGGUVSHVCAUUALZKKKJAVYXKVYXEUXCIAUXFVYXBVYXDIAUXEVYXAUXCIAUX
      DVYWTDGAUVSHUUJGVYXLKKKJJTAVYXEVYXGUXCIAVYXBVYWOVYXDIAVYXAVYWNUXCIAVYWTUU
      JDGAUUJVYCXGKKJJAVYXGVYWPUXCIAVYXDVYWGVYWOIAVYXCUUGDGAUUGVXRXGKKJTAVYWPVY
      WSUXCIAUXCVYWNVYWGUWXSADUUJVXLVYCMADUUGVXLVXRMZOJAVYWSVYWJUXCIAVYWRVYWIUX
      CIAVYWNVYWHVYWGIADUUGVXLVXRUUBJKJTAVYWJVYWMUXCIAVYWIVYWLUXCIAVYWHVYWGAVYW
      GVYXMVDVYXMVMKJAVYWMVYWEUXCIAVYWLUIUXCIAVYWGVYXMXRKJTAVYWEUXCUXCIAUXCUWXS
      WIJAUXCVYWCUXCVYWCIAUUKBDVYDVXPVXMXHZVYXNYETAVYWCVYVTVYWCIAVYVSUUFAUUKDVY
      DVXMUPZVXQPZJAVYWCVYVTVYVTIVYXPKTAUUFVYVSVYVSVXQVYXOVYXOXFAVYWBVYVPUUFGAV
      YVPVYVOVYVSIFVYWBAVYVOVYVSVYVOIADQDVXLVXMUWYCWMZKAVYVOVYVSVYVSIVYXQJXLKUU
      CAVYVPVYVRUUFGAVYVOUVLVYVOIAVUVHUEDEVUWSKZJKAVYVRUVOUUFGAVYVOUVLUVLIVYXRK
      KTJKKKKNAUXAUWFUVBIAUWTUWEUVDIAUWSUWDUVHIAUWRUWCUVNIAUWQUWBUVPIAUWPUVRUWA
      IAUWPUUODVVWDEFZGFZUUODVVVMEFZGFUVRAUWPDVVXGGFZUUOGFZUUOVYYBGFVYXTADUWNGF
      DVVYHGFUWPVYYCAUWNVVYHDGVWUSKAUWOUWNDGAUWNUWXQXGKADVVXGUUOVXLVWUHVYHSXNAV
      YYBUUOADVVXGVXLVWUHMVYHPAVYYBVYXSUUOGAVYXSVVWRDGFDVVWRGFVYYBADVVWCVXLVWVE
      XAADVVWRVXLADVVWCVXLVWVEUPPAVVWRVVXGDGVWVAKWPKTAVYXSVYYAUUOGAVVWDVVVMDEVW
      VFKKAVYYAUVQUUOGAVVVMUFDEVVVRKKTJKKKKKNAUWFUWMUVBIAUWEUWLUVDIAUWDUWKUVHIA
      UWCUWJUVNIAUWBUWIUVPIAUWAUWHUVRIAUWAUUEBGFZUWHAUWADVWXFEFZBGFZVYYDAUWADUU
      KGFZBGFZVYYFAUWADUULGFZVYYHAUWADUULHGFZGFVYYIAUVTVYYJDGAUVSHUULGVYXLKKAVY
      YJUULDGAUULVYEXGKNADUUKBVXLVYDVXPSVAAVYYGVYYEBGAVYYGUUKDGFVYYEADUUKVXLVYD
      PADQVXLUWYCXAVAJNAVYYEUUEBGAVWXFDDEVWXFDVCAUUDLKJNAUUEBVXNVXPPNKKKKKKN $.

    $( Lemma for ~ 3cubes .  (Contributed by Igor Ieskov, 22-Jan-2024.) $)
    3cubeslem3 $p |- ( ph ->
         ( A x. ( ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) )
                + ( ( 3 ^ 2 ) x. A ) ) + 3 ) ^ 3 ) )
      = ( ( ( ( ( ( 3 ^ 3 ) x. ( A ^ 3 ) ) - 1 ) ^ 3 )
          + ( ( ( -u ( ( 3 ^ 3 ) x. ( A ^ 3 ) )
          + ( ( 3 ^ 2 ) x. A ) ) + 1 ) ^ 3 ) )
          + ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) ) ^ 3 ) ) ) $=
      ( c3 cexp co c2 cmul caddc c7 c9 c6 c5 c8 c4 cmin 3cubeslem3l 3cubeslem3r
      c1 cneg eqtr4d ) ABDDEFZBGEFZHFDGEFBHFZIFZDIFDEFHFBJEFDKEFZHFBLEFUFHFBMEF
      DNEFZUGIFHFBOEFDJEFGHFDLEFZIFHFBDEFZUHUHIFHFUCDMEFHFBUBHFIFIFIFIFIFIFUBUI
      HFZSPFDEFUJTUDIFSIFDEFIFUEDEFIFABCQABCRUA $.

    $( Lemma for ~ 3cubes .  This is Ryley's explicit formula for decomposing a
       rational ` A ` into a sum of three rational cubes.  (Contributed by Igor
       Ieskov, 22-Jan-2024.) $)
    3cubeslem4 $p |- ( ph -> A = ( (
          ( ( ( ( ( 3 ^ 3 ) x. ( A ^ 3 ) ) - 1 )
        / ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) ) + 3 ) ) ^ 3 )
      +
          ( ( ( ( -u ( ( 3 ^ 3 ) x. ( A ^ 3 ) ) + ( ( 3 ^ 2 ) x. A ) ) + 1 )
        / ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) ) + 3 ) ) ^ 3 ) )
      +
          ( ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) )
        / ( ( ( ( 3 ^ 3 ) x. ( A ^ 2 ) ) + ( ( 3 ^ 2 ) x. A ) ) + 3 ) ) ^ 3
      ) ) ) $=
      ( c3 cexp co cmul c1 caddc cdiv cr wcel wtru a1i 3nn0 recnd expcld addcld
      oveq1d expdivd cmin cneg 3re cn0 reexpcld mptru qre syl remulcld resubcld
      c2 cq 1red renegcld sqcld cc qcn mulcld 1cnd 3cubeslem2 neqned cz expne0d
      cc0 3z divdird oveq2d 3eqtrd 3eqtr4rd 3cubeslem3 divcan4d 3eqtr2rd ) ADDE
      FZBDEFZGFZHUAFZVMBUKEFZGFZDUKEFZBGFZIFZDIFZJFDEFZVOUBZVTIFZHIFZWBJFDEFZIF
      ZWAWBJFDEFZIFZVPDEFZWFDEFZIFZWADEFZIFZWBDEFZJFZBWPGFZWPJFBAWMWPJFZWNWPJFZ
      IFWKWPJFZWLWPJFZIFZWTIFZWQWJAWSXCWTIAWKWLWPAVPDAVPAVOHAVMVNVMKLZAXEMDDDKL
      ZMUCNDUDLZMONUEUFNZABULLZVNKLCXIBDBUGXGXIONUEUHUIZAUMUJPZXGAONZQZAWFDAWEH
      AWDVTAWDAVOXJUNPAVSBADADXFAUCNPZUOAXIBUPLCBUQUHZURZRAUSRZXLQZAWBDAWADAVRV
      TAVMVQAVMXHPABXOUOURXPRZXNRZXLQZAWBDXTAWBVDABCUTVAZDVBLAVENVCZVFSAWMWNWPA
      WKWLXMXRRAWADXSXLQYAYCVFAWJXAWGIFZWIIFXCWIIFXDAWHYDWIIAWCXAWGIAVPWBDXKXTY
      BXLTSSAYDXCWIIAWGXBXAIAWFWBDXQXTYBXLTVGSAWIWTXCIAWAWBDXSXTYBXLTVGVHVIAWRW
      OWPJABCVJSABWPXOYAYCVKVL $.
  $}

  ${
    $d a b c A $.
    $( Every rational number is a sum of three rational cubes.  See S. Ryley,
       The Ladies' Diary 122 (1825), 35.  (Contributed by Igor Ieskov,
       22-Jan-2024.) $)
    3cubes $p |- ( A e. QQ <-> E. a e. QQ E. b e. QQ E. c e. QQ
                             A = ( ( ( a ^ 3 ) + ( b ^ 3 ) ) + ( c ^ 3 ) ) ) $=
      ( cq wcel cv c3 cexp co wceq wrex cmul 3nn0 qexpcl syl2anc sylancl qaddcl
      caddc c1 cmin c2 cdiv cneg cc0 wne cn wn 3nn a1i cn0 nnexpcld pm2.18i nnq
      mp1i mpan2 qmulcl 1nn ax-mp qsubcl qsqcl mpancom 3cubeslem2 neqned qdivcl
      syl3anc qnegcl syl 3cubeslem4 oveq1 oveq1d eqeq2d oveq2d rspc3ev syl31anc
      id wi wtru w3a wa 3anass simprl syl2an2r simprr biimtrid rexlimdv3d mptru
      eleq1a impbii ) AEFZABGZHIJZCGZHIJZSJZDGZHIJZSJZKZDELCELBELZWJHHIJZAHIJZM
      JZTUAJZXAAUBIJZMJZHUBIJZAMJZSJZHSJZUCJZEFZXCUDZXHSJZTSJZXJUCJZEFZXIXJUCJZ
      EFZAXKHIJZXPHIJZSJZXRHIJZSJZKZWTWJXDEFZXJEFZXJUEUFZXLWJXCEFZTEFZYFWJXAEFZ
      XBEFZYIXAUGFZYKWJYMYMUHZHHHUGFZYNUIUJHUKFZYNNUJULUMXAUNUOZWJYPYLNAHOUPXAX
      BUQPZTUGFYJURTUNUSZXCTUTQWJXIEFZHEFZYGWJXFEFZXHEFZYTWJYKXEEFUUBYQAVAXAXEU
      QPXGEFZWJUUCUUAUUDWJYOUUAUIHUNUSZHVAUOXGAUQVBZXFXHRPZUUEXIHRQZWJXJUEWJAWJ
      VPZVCVDZXDXJVEVFWJXOEFZYGYHXQWJXNEFZYJUUKWJXMEFZUUCUULWJYIUUMYRXCVGVHUUFX
      MXHRPYSXNTRQUUHUUJXOXJVEVFWJYTYGYHXSUUGUUHUUJXIXJVEVFWJAUUIVIWSYEAXTWNSJZ
      WQSJZKAYBWQSJZKBCDXKXPXREEEWKXKKZWRUUOAUUQWOUUNWQSUUQWLXTWNSWKXKHIVJVKVKV
      LWMXPKZUUOUUPAUURUUNYBWQSUURWNYAXTSWMXPHIVJVMVKVLWPXRKZUUPYDAUUSWQYCYBSWP
      XRHIVJVMVLVNVOWTWJVQVRWSWJBCDEEEWKEFZWMEFZWPEFZVSUUTUVAUVBVTZVTZVRWSWJVQZ
      UUTUVAUVBWAUVDUVEVQVRUVDWREFZUVEUVDWOEFZWQEFZUVFUUTWLEFZUVCWNEFZUVGUUTYPU
      VINWKHOUPUVDUVAYPUVJUUTUVAUVBWBNWMHOQWLWNRWCUVDUVBYPUVHUUTUVAUVBWDNWPHOQW
      OWQRPWREAWHVHUJWEWFWGWI $.
  $}

$( (End of Igor Ieskov's mathbox.) $)
