#!/bin/sh

# Build metamath executable, extract related files, and install the executable.
# This assumes the needed files are downloaded, see download-metamath
# The executable is installed in $prefix/bin; default $prefix is $HOME

set -e -v

# Unzip the .zip file; we presume it unpacks into ONLY "./metamath/"
# To use .bz2 big file, use: tar -jxf ./metamath.tar.bz2
unzip -o metamath-program.zip

cd metamath/

# Compile metamath, a C verifier (and more) of metamath files by Norm Megill.
# We could just run "gcc *.c -O2 -o metamath", but this will do some
# auto-detection to try to find the best available options.
autoreconf -i
./configure


# We can't just "build everything", because that would require .mm files
# not included in this subset distribution.  So ask to build *just*
# metamath.  We have to extract the extension and use it so the build request
# will work on Cygwin.
rm -f metamath metamath.exe
extension=$( gawk '/^EXEEXT = / { print $3 }' < Makefile )
make "metamath${extension}"

# install metamath to $prefix/bin (by default, $HOME/bin); this honors DESTDIR:
make prefix="${prefix:-"$HOME"}" install-binPROGRAMS

# If there's no more recent mmbiblio.html, use this one.
if ! [ -e ../mmbiblio.html ] ; then
  cp -p mmbiblio.html ../
fi

cd ../

# Untar this in the directory with the .mm files (such as set.mm)
# so we can test gif symbol usage.
tar --strip-components=1 -jxf symbols.tar.bz2
