#!/bin/sh
# check-theorem-list - check when that generating the theorem list,
# metamath.exe does not encounter any error or warning, including
# missing bibliographic references
#
# $1 = MMFILE

mmfile="$1"
shift

error=0

generate_metamath_commands () {
  echo "read \"$mmfile\""
  echo 'set scroll continuous'
  echo "write theorem_list/alt_html"
  echo quit
}

generate_metamath_commands | metamath | tee ,check-theorem-list-log

if grep -E '^\?(Warning|Error): ' ,check-theorem-list-log ; then
  error=1
fi

rm -fr ,*.TRASH
rm -fr ,check-theorem-list-log

exit "$error"
