#!/bin/sh
# Creates a file which lists all the theorems ($p-statements) of the
# mmfile argument.  Each line is a label with two spaces in front.
# First parameter is the mmfile (default set.mm).
# Second parameter is the output file (default 1.tmp).
# This can be a useful step to take before using scripts/min.cmd.

mmfile="${1:-set.mm}"
output="${2:-1.tmp}"

metamath "read \"${mmfile}\"" \
         'set scroll continuous' \
         'open log 0.tmp' \
         'show labels * /linear' \
         'close log' \
         quit > /dev/null

grep -E ' \$p' < 0.tmp | \
  sed -E -e 's/ \$p//' -e 's/^[0-9]+ /  /' > "${output}"
