def P(x): return '|- ' + x
def D(x,y): return '( %s | %s )' % (x,y)

x,y,z,w,t,u,v,v6,v7 = 'p','q','r','s','t','u','v','w','x'

print 'lem-49 $p', P(D(D(x,D(D(y,z),D(D(z,y),D(u,y)))),D(D(D(D(y,z),D(D(z,y),D(u,y))),x),D(D(u,D(v,z)),x)))), '$= $.'
print 'lem-50 $p', P(D(D(x,D(D(y,D(z,u)),v)),D(D(D(D(y,D(z,u)),v),x),D(D(v,D(D(w,u),D(D(u,w),D(y,w)))),x)))), '$= $.'
print 'lem-52 $p', P(D(D(x,D(D(y,D(D(z,u),D(D(u,z),D(v,z)))),w)),D(D(D(D(y,D(D(z,u),D(D(u,z),D(v,z)))),w),x),D(D(w,D(D(v,D(v6,u)),y)),x)))), '$= $.'
print 'lem-54 $p', P(D(D(D(D(x,y),D(D(y,x),D(z,x))),D(D(u,y),D(D(y,u),D(z,u)))),D(z,D(v,y)))), '$= $.'
print 'lem-57 $p', P(D(D(x,D(D(y,D(D(z,D(u,v)),w)),v6)),D(D(D(D(y,D(D(z,D(u,v)),w)),v6),x),D(D(v6,D(D(w,D(D(v7,v),D(D(v,v7),D(z,v7)))),y)),x)))), '$= $.'
print 'lem-67 $p', P(D(D(x,D(y,z)),D(D(D(u,D(x,v)),D(D(D(x,v),u),D(D(v,z),u))),D(D(w,D(x,v)),D(D(D(x,v),w),D(D(v,z),w)))))), '$= $.'
print 'lem-68 $p', P(D(D(x,D(y,z)),D(D(D(y,z),x),D(D(D(D(u,z),D(D(z,u),D(v,u))),D(D(w,z),D(D(z,w),D(v,w)))),x)))), '$= $.'
print 'lem-78 $p', P(D(D(D(D(x,y),D(D(y,x),D(z,x))),D(D(y,D(D(u,v),D(D(v,u),D(w,u)))),z)),D(z,D(D(w,D(v6,v)),y)))), '$= $.'
print 'lem-79 $p', P(D(D(x,D(D(y,D(z,u)),v)),D(D(D(D(y,D(z,u)),v),x),D(D(v,D(D(w,D(y,v6)),D(D(D(y,v6),w),D(D(v6,u),w)))),x)))), '$= $.'
print 'lem-84 $p', P(D(D(x,D(D(D(D(y,z),D(D(z,y),D(u,y))),D(D(v,z),D(D(z,v),D(u,v)))),w)),D(D(D(D(D(D(y,z),D(D(z,y),D(u,y))),D(D(v,z),D(D(z,v),D(u,v)))),w),x),D(D(w,D(v6,z)),x)))), '$= $.'
print 'lem-96 $p', P(D(D(D(D(D(D(x,y),D(D(y,x),D(z,x))),D(D(u,y),D(D(y,u),D(z,u)))),D(v,w)),D(D(v6,w),D(D(w,v6),D(D(v7,y),v6)))),D(D(v,w),D(v7,y)))), '$= $.'
print 'lem-111 $p', P(D(D(x,D(y,z)),D(D(D(u,D(x,D(v,w))),D(D(D(x,D(v,w)),u),D(D(D(v,w),z),u))),D(D(D(x,D(v,w)),D(D(v6,w),D(D(w,v6),D(z,v6)))),D(D(v,w),z))))), '$= $.'
print 'lem-130 $p', P(D(D(D(D(x,y),D(D(y,x),D(z,x))),D(D(u,D(z,v)),D(D(D(z,v),u),D(D(v,y),u)))),D(z,D(w,y)))), '$= $.'
print 'lem-155 $p', P(D(D(D(D(x,D(y,z)),D(D(u,z),D(D(z,u),D(x,u)))),D(v,z)),D(D(D(u,z),D(D(z,u),D(x,u))),D(D(w,z),D(D(z,w),D(x,w)))))), '$= $.'
print 'lem-172 $p', P(D(D(x,D(D(D(y,D(z,u)),D(D(v,u),D(D(u,v),D(w,v)))),D(D(z,u),w))),D(D(D(D(D(y,D(z,u)),D(D(v,u),D(D(u,v),D(w,v)))),D(D(z,u),w)),x),D(D(y,D(v6,w)),x)))), '$= $.'
print 'lem-210 $p', P(D(D(x,D(y,z)),D(D(D(y,z),x),D(D(z,z),x)))), '$= $.'
print 'lem-234 $p', P(D(D(D(D(x,x),y),D(D(x,x),y)),D(y,D(z,x)))), '$= $.'
print 'lem-264 $p', P(D(D(D(x,y),D(x,y)),D(D(D(y,y),z),D(D(y,y),z)))), '$= $.'
print 'lem-276 $p', P(D(D(D(D(x,x),x),D(D(x,x),x)),y)), '$= $.'
print 'lem-298 $p', P(D(D(x,D(y,z)),D(D(D(u,u),u),D(D(u,u),u)))), '$= $.'
print 'lem-304 $p', P(D(D(x,x),x)), '$= $.'
print 'lem-305 $p', P(D(D(x,D(D(y,y),y)),D(D(D(D(y,y),y),x),D(z,x)))), '$= $.'
print 'lem-313 $p', P(D(D(x,x),D(D(y,x),D(y,x)))), '$= $.'
print 'lem-334 $p', P(D(D(D(x,y),D(x,y)),D(y,D(D(z,z),z)))), '$= $.'
print 'lem-343 $p', P(D(D(x,D(y,z)),D(D(D(y,z),x),D(D(z,D(D(u,u),u)),x)))), '$= $.'
print 'lem-412 $p', P(D(D(D(x,y),D(D(z,z),z)),D(y,y))), '$= $.'
print 'lem-461 $p', P(D(D(x,D(y,z)),D(D(D(y,z),x),D(D(y,z),x)))), '$= $.'
print 'lem-493 $p', P(D(D(D(D(x,y),z),D(D(u,u),u)),D(z,D(x,y)))), '$= $.'
print 'lem-585 $p', P(D(D(x,D(y,z)),D(D(D(y,z),x),D(D(u,u),u)))), '$= $.'
print 'lem-602 $p', P(D(D(x,D(y,z)),D(D(D(u,z),D(D(z,u),D(z,u))),D(x,D(z,z))))), '$= $.'
print 'lem-609 $p', P(D(D(D(D(x,y),D(D(y,x),D(y,x))),D(z,D(y,y))),D(z,D(u,y)))), '$= $.'
print 'lem-697 $p', P(D(D(x,y),D(D(y,x),D(y,x)))), '$= $.'
print 'lem-714 $p', P(D(D(x,D(y,z)),D(D(D(u,D(x,v)),D(D(D(x,v),u),D(D(x,v),u))),D(D(v,z),D(D(x,v),D(x,v)))))), '$= $.'
print 'lem-716 $p', P(D(D(D(x,y),D(x,y)),D(y,x))), '$= $.'
print 'lem-745 $p', P(D(D(x,D(y,z)),D(D(D(z,y),x),D(D(z,y),x)))), '$= $.'
print 'lem-853 $p', P(D(D(x,D(D(y,z),u)),D(D(D(u,D(z,y)),x),D(D(u,D(z,y)),x)))), '$= $.'
print 'lem-949 $p', P(D(D(x,D(y,z)),D(D(x,D(z,y)),D(x,D(z,y))))), '$= $.'
print 'lem-994 $p', P(D(D(x,D(y,D(z,u))),D(D(D(y,D(u,z)),x),D(D(y,D(u,z)),x)))), '$= $.'
print 'lem-1092 $p', P(D(D(x,D(y,D(y,y))),D(D(z,x),D(z,x)))), '$= $.'
print 'lem-1125 $p', P(D(D(x,D(y,z)),D(D(D(z,D(u,D(u,u))),x),D(D(z,D(u,D(u,u))),x)))), '$= $.'
print 'lem-1173 $p', P(D(D(D(D(x,y),D(D(z,x),D(z,x))),D(u,D(u,u))),D(z,D(v,y)))), '$= $.'
print 'lem-1239 $p', P(D(D(x,D(y,z)),D(D(D(u,y),D(D(x,u),D(x,u))),D(v,D(v,v))))), '$= $.'
print 'lem-1267 $p', P(D(D(x,D(y,z)),D(D(u,D(u,u)),D(D(v,y),D(D(x,v),D(x,v)))))), '$= $.'
