
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x80\xbe\xa8T\xf9\x7f (\x84\xd3JA\x92\xbf@\xa0'
    
_lr_action_items = {'AND':([4,5,6,11,16,17,18,19,23,24,],[-1,-6,7,15,-2,-4,-5,-3,-7,-8,]),'RPAREN':([4,5,11,12,13,14,16,17,18,19,21,22,23,24,],[-1,-6,16,17,18,19,-2,-4,-5,-3,23,24,-7,-8,]),'IMP':([4,5,6,16,17,18,19,23,24,],[-1,-6,8,-2,-4,-5,-3,-7,-8,]),'NOT':([0,1,3,7,8,9,10,15,20,],[1,1,1,1,1,1,1,1,1,]),'IFF':([4,5,6,16,17,18,19,23,24,],[-1,-6,9,-2,-4,-5,-3,-7,-8,]),'LPAREN':([0,1,3,7,8,9,10,15,20,],[3,3,3,3,3,3,3,3,3,]),'VAR':([0,1,3,7,8,9,10,15,20,],[4,4,4,4,4,4,4,4,4,]),'OR':([4,5,6,14,16,17,18,19,23,24,],[-1,-6,10,20,-2,-4,-5,-3,-7,-8,]),'$end':([2,4,5,16,17,18,19,23,24,],[0,-1,-6,-2,-4,-5,-3,-7,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'wff':([0,1,3,7,8,9,10,15,20,],[2,5,6,11,12,13,14,21,22,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> wff","S'",1,None,None,None),
  ('wff -> VAR','wff',1,'p_wff_var','../completeness.py',438),
  ('wff -> LPAREN wff AND wff RPAREN','wff',5,'p_wff_and2','../completeness.py',442),
  ('wff -> LPAREN wff OR wff RPAREN','wff',5,'p_wff_or2','../completeness.py',446),
  ('wff -> LPAREN wff IMP wff RPAREN','wff',5,'p_wff_imp','../completeness.py',450),
  ('wff -> LPAREN wff IFF wff RPAREN','wff',5,'p_wff_iff','../completeness.py',454),
  ('wff -> NOT wff','wff',2,'p_wff_not','../completeness.py',458),
  ('wff -> LPAREN wff AND wff AND wff RPAREN','wff',7,'p_wff_and3','../completeness.py',462),
  ('wff -> LPAREN wff OR wff OR wff RPAREN','wff',7,'p_wff_or3','../completeness.py',466),
]
