#!/bin/sh

# Verify mmfile $1 (default "set.mm") and discouraged file $2 (default
# "discouraged") using metamath-knife.
# Usage:
# verify-knife [source=set.mm] [discouraged_file=discouraged]

source="${1:-set.mm}"
discouraged_file="${2:-discouraged}"

metamath-knife ${source} --verify \
                         --verify-parse-stmt \
                         --verify-usage \
                         --verify-markup \
                         || exit 1

metamath-knife ${source} -D discouraged.new >/dev/null \
  && diff ${discouraged_file} discouraged.new >/dev/null

if [ $? -ne 0 ]; then
  echo "The file '${discouraged_file}' needs to be regenerated."
  rm discouraged.new
  exit 1
fi

rm discouraged.new
exit 0
