$(
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
                          Euler's partition theorem
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
$)

  ${
    $d a k l m n o x y z $. $d a F $. $d a x y J $.
    oddpwdc.j $e |- J = { z e. NN | -. 2 || z } $.
    oddpwdc.f $e |- F = ( x e. J , y e. NN0 |-> ( ( 2 ^ y ) x. x ) ) $.

    $( Lemma for ~ eulerpart .  The function ` F ` that decomposes a number
       into its "odd" and "even" parts, which is to say the largest power of
       two and largest odd divisor of a number, is a bijection from
       pairs of a natural number and an odd number to natural numbers.
       (Contributed by Thierry Arnoux, 15-Aug-2017.) $)
    oddpwdc $p |- F : ( J X. NN0 ) -1-1-onto-> NN $=
      ( cn0 cn c2 cexp co cdivides wbr clt wcel wa a1i cc0 wceq va vk vm vn cxp
      vo vl wf1o wtru cv cmul crab csup cdiv 2nn simpl nnexpcld wn ssrab2 simpr
      eqsstri sseldi nnmulcld ancoms adantl id wor cr wss nn0ssre ltso soss mp2
      cz cle wral wrex wi nnz oveq2 breq1d elrab simprl nn0red nnred 2re nexple
      0z leidi mp3an23 ad2antrl nnzd simprr dvdsle imp syl21anc letrd ralrimiva
      sylan2b breq2 ralbidv syl2anc syl3anc supcl cfn wne adantr ex sylancr syl
      nn0zd c1 cc sylibr jca biimpa caddc supub eleq2i sylnib mpd eqcomd breq2d
      mtbid nncnd wb notbid eqeltrd nn0cnd oveq2d oveq1d 3eqtr3d expcld expne0d
      bitri eqtrd divcan3d mulcomd eqtr4d mpbird rspcev uzsupss c0 fzfi nn0ge0d
      nn0uz cfz elfz2 biimpri syl32anc ssrdv ssfi 0nn0 1dvds recni ax-mp breq1i
      w3a exp0 ne0i fisupcl syl13anc cbvrabv syl6eleq sylib nndivdvds nn0addcld
      simprd 1nn0 ltp1 mt2d imnan expp1 nncn divcan2d dvdscmulr syl112anc bitrd
      nnne0d simplr sseli ad2antrr simplll simprbi cmin znnsub iddvdsexp nnnn0d
      2z zexpcl dvdsmultr2 pncan3d expaddd eqtr3d nnne0i divcld mulcld pm2.65da
      mulassd nsyl3 dvds0lem syl31anc sylanbrc nnexpcl mpan nnne0 ad3antlr jcai
      lttri3 divmul2 ancomd oveq12d jca31 impbii f1od2 trud ) EHUEIDUHUIABUAEHJ
      BUJZKLZAUJZUKLZIDUAUJZJJUBUJZKLZUYAMNZUBHULZHOUMZKLZUNLZUYFIEHGUXSEPZUXQH
      PZQZUXTIPZUIUYJUYIUYLUYJUYIQZUXRUXSUYMJUXQJIPZUYMUORUYJUYIUPUQUYMEIUXSEJC
      UJZMNZURZCIULZIFUYQCIUSVAZUYJUYIUTVBVCVDVEUYAIPZUYHEPZUYFHPZQUIUYTVUAVUBU
      YTUYHIPZJUYHMNZURZQZVUAUYTVUCVUEUYTUYTUYGIPZUYGUYAMNZVUCUYTVFUYTJUYFUYNUY
      TUORZUYTUCUDUFHUYEOHOVGZUYTHVHVIVHOVGVUJVJVKHVHOVLVMZRZUYTSVNPZUYEHVIZUDU
      JZUCUJZVONZUDUYEVPZUCVNVQZVUPVUOONURUDUYEVPVUOVUPONVUOUFUJONUFUYEVQVRUDHV
      PQUCHVQZVUMUYTWHRVUNUYTUYDUBHUSRZUYTUYAVNPZVUOUYAVONZUDUYEVPZVUSUYAVSZUYT
      VVCUDUYEVUOUYEPZUYTVUOHPZJVUOKLZUYAMNZQZVVCUYDVVIUBVUOHUYBVUOTUYCVVHUYAMU
      YBVUOJKVTWAWBZUYTVVJQZVUOVVHUYAVVLVUOUYTVVGVVIWCZWDVVLVVHVVLJVUOUYNVVLUOR
      VVMUQZWEVVLUYAUYTVVJUPZWEVVGVUOVVHVONZUYTVVIVVGJVHPJJVONVVPWFJWFWIVUOJWGW
      JWKVVLVVHVNPZUYTVVIVVHUYAVONZVVLVVHVVNWLVVOUYTVVGVVIWMVVQUYTQVVIVVRVVHUYA
      WNWOWPWQWSZWRVURVVDUCUYAVNVUPUYATVUQVVCUDUYEVUPUYAVUOVOWTXAUUAXBUCUDUFUYE
      SHUUFUUBXCZXDZUQZUYTVUBVUHUYTUYFJUGUJZKLZUYAMNZUGHULZPVUBVUHQUYTUYFUYEVWF
      UYTVUJUYEXEPZUYEUUCXFZVUNUYFUYEPVULUYTSUYAUUGLZXEPUYEVWIVIVWGSUYAUUDUYTUD
      UYEVWIUYTVVFVUOVWIPZUYTVVFQZVUMVVBVUOVNPZSVUOVONZVVCVWJVUMVWKWHRUYTVVBVVF
      VVEXGVWKVUOVVFUYTVVJVVGVVKVVMWSZXKVWKVUOVWNUUEVVSVWJVUMVVBVWLUURVWMVVCQQV
      UOSUYAUUHUUIUUJXHUUKVWIUYEUULXIUYTSUYEPZVWHUYTSHPZJSKLZUYAMNZQVWOUYTVWPVW
      RVWPUYTUUMRUYTXLUYAMNZVWRUYTVVBVWSVVEUYAUUNXJVWQXLUYAMJXMPZVWQXLTJWFUUOZJ
      UUSUUPUUQXNXOUYDVWRUBSHUYBSTUYCVWQUYAMUYBSJKVTWAWBXNUYESUUTXJVVAHUYEOUVAU
      VBUYDVWEUBUGHUYBVWCTUYCVWDUYAMUYBVWCJKVTWAUVCZUVDVWEVUHUGUYFHVWCUYFTVWDUY
      GUYAMVWCUYFJKVTWAWBUVEUVHUYTVUGQVUHVUCUYAUYGUVFXPWPZUYTUYGJUKLZUYAMNZVUDU
      YTJUYFXLXQLZKLZUYAMNZVXEUYTVXFHPZVXHURZUYTUYFXLVWAXLHPUYTUVIRUVGUYTVXIVXH
      QZURVXIVXJVRUYTVXFVWFPZVXKUYTVXFUYEPZVXLUYTVXMUYFVXFONZUYTUYFVHPZVXNUYTHV
      HUYFVJVWAVBZUYFUVJXJUYTUCUDUFHUYEVXFOVULVVTXRUVKUYEVWFVXFVXBXSXTVWEVXHUGV
      XFHVWCVXFTVWDVXGUYAMVWCVXFJKVTWAWBXTVXIVXHUVLXNYAUYTVXGVXDUYAMUYTVWTVUBVX
      GVXDTVXAVWAJUYFUVMXIWAYDUYTVXEVXDUYGUYHUKLZMNZVUDUYTUYAVXQVXDMUYTVXQUYAUY
      TUYAUYGUYAUVNZUYTUYGVWBYEZUYTUYGVWBUVSZUVOYBZYCUYTJVNPZUYHVNPZUYGVNPUYGSX
      FVXRVUDYFUYTJVUIWLUYTUYHVXCWLZUYTUYGVWBWLVYAUYGJUYHUVPUVQUVRYDXOVUAUYHUYR
      PVUFEUYRUYHFXSUYQVUECUYHIUYOUYHTUYPVUDUYOUYHJMWTYGWBYOXNZVWAXOVEUYKUYAUXT
      TZQZUYTUXSUYHTZUXQUYFTZQZQZYFUIVYHVYLVYHUYTVYKVYHUYAUXTIUYKVYGUTZVYHUXRUX
      SVYHJUXQUYNVYHUORUYIUYJVYGUVTZUQZUYIUXSIPZUYJVYGEIUXSUYSUWAUWBZVCYHZVYHVY
      JVYIVYHVYJVYIVYHVYJUXQUYFONZURZUYFUXQONURZQZVYHVYTWUAVYHVYSUYIUYIUYJVYGVY
      SUWCUYIJUXSMNZVYHVYSQZUYIVYPWUCURZUYIUXSUYRPVYPWUEQEUYRUXSFXSUYQWUECUXSIU
      YOUXSTUYPWUCUYOUXSJMWTYGWBYOUWDWUDWUCJUYHJUYFUXQUWELZKLZUKLZMNZWUDJWUGMNZ
      WUIWUDVYCWUFIPZWUJVYCWUDUWIRZWUDUXQVNPZUYFVNPZVYSWUKWUDUXQVYHUYJVYSVYNXGZ
      XKZWUDUYFWUDUCUDUFHUYEOVUJWUDVUKRVYHVUTVYSVYHUYTVUTVYRVVTXJZXGXDZXKZVYHVY
      SUTWUMWUNQVYSWUKUXQUYFUWFXPWPZJWUFUWGXBWUDVYCVYDWUGVNPZWUJWUIVRWULVYHVYDV
      YSVYHUYTVYDVYRVYEXJXGWUDVYCWUFHPWVAWULWUDWUFWUTUWHZJWUFUWJXBJUYHWUGUWKXCY
      AWUDUXSWUHJMWUDUXSWUGUYHUKLZWUHWUDUXTUXRUNLUXRWVCUKLZUXRUNLUXSWVCWUDUXTWV
      DUXRUNWUDUXTUXRWUGUKLZUYHUKLZWVDWUDUYAVXQUXTWVFWUDUYTUYAVXQTZVYHUYTVYSVYR
      XGZVYBXJVYHVYGVYSVYMXGWUDUYGWVEUYHUKWUDJUXQWUFXQLZKLUYGWVEWUDWVIUYFJKWUDU
      XQUYFWUDUXQWUOYIWUDUYFWURYIUWLYJWUDJUXQWUFVWTWUDVXARZWVBWUOUWMUWNYKYLWUDU
      XRWUGUYHWUDJUXQWVJWUOYMZWUDJWUFWVJWVBYMZWUDUYAUYGWUDUYTUYAXMPZWVHVXSXJWUD
      UYTUYGXMPWVHVXTXJWUDJUYFWVJJSXFWUDJUOUWORZWUSYNUWPZUWSYPYKWUDUXSUXRWUDUXS
      VYHVYPVYSVYQXGYEWVKWUDJUXQWVJWVNWUPYNZYQWUDWVCUXRWUDWUGUYHWVLWVOUWQWVKWVP
      YQYLWUDUYHWUGWVOWVLYRYSYCYTUWTUWRVYHUXQUYEPZWUAVYHUYJUXRUYAMNZWVQVYNVYHUX
      SVNPUXRVNPVVBUXSUXRUKLZUYATWVRVYHUXSVYQWLVYHUXRVYOWLVYHUYTVVBVYRVVEXJVYHU
      YAWVSVYHUYAUXTWVSVYMVYHUXRUXSVYHUXRVYOYEVYHUXSVYQYEYRYPYBUXSUXRUYAUXAUXBU
      YDWVRUBUXQHUYBUXQTUYCUXRUYAMUYBUXQJKVTWAWBUXCVYHUCUDUFHUYEUXQOVUJVYHVUKRW
      UQXRYAXOVYHUXQVHPVXOVYJWUBYFVYHHVHUXQVJVYNVBVYHUYTVXOVYRVXPXJUXQUYFUXIXBY
      TVYHVYJVYIVYHVYJQZUXSUYAUXRUNLZUYHWVTWWAUXSWVTWWAUXSTZVYGVYHVYGVYJVYMXGWV
      TWVMUXSXMPUXRXMPZUXRSXFZQZWWBVYGYFWVTUYAVYHUYTVYJVYRXGYEWVTUXSVYHVYPVYJVY
      QXGYEUYJWWEUYIVYGVYJUYJWWCWWDUYJUXRUYNUYJUXRIPZUOJUXQUXDUXEZYEUYJWWFWWDWW
      GUXRUXFXJXOUXGUYAUXSUXRUXJXCYTYBWVTUXRUYGUYAUNWVTVYJUXRUYGTVYHVYJUTUXQUYF
      JKVTXJYJYPXHUXHUXKXOVYLUYIUYJVYGVYLUXSUYHEUYTVYIVYJWCZUYTVUAVYKVYFXGYHVYL
      UXQUYFHUYTVYIVYJWMZUYTVUBVYKVWAXGYHVYLUYAVXQUXTUYTWVGVYKVYBXGVYLUXRUYGUXS
      UYHUKVYLUXQUYFJKWWIYJWWHUXLYSUXMUXNRUXOUXP $.

      $d x y W $.
      $( Lemma for ~ eulerpart : value of the ` F ` function.
         (Contributed by Thierry Arnoux, 9-Sep-2017.) $)
      oddpwdcv $p |- ( W e. ( J X. NN0 ) ->
        ( F ` W ) = ( ( 2 ^ ( 2nd ` W ) ) x. ( 1st ` W ) ) ) $=
        ( cn0 cxp wcel cfv c1st co c2 cexp cmul wceq cv oveq2 c2nd cop wa elxp6
        simplbi fveq2d df-ov a1i simprbi oveq1d ovex ovmpt2 syl 3eqtr2d ) FEIJK
        ZFDLFMLZFUALZUBZDLZUPUQDNZOUQPNZUPQNZUOFURDUOFURRZUPEKUQIKUCZFEIUDZUEUF
        UTUSRUOUPUQDUGUHUOVDUTVBRUOVCVDVEUIABUPUQEIOBSZPNZASZQNVBDVGUPQNVHUPVGQ
        TVFUQRVGVAUPQVFUQOPTUJHVAUPQUKULUMUN $.
  $}

  ${
    $( Define the set of finitely supported functions into nonnegative natural
       numbers. We'll first prove some of their properties.  $)
    eulerpartlems.r $e |- R = { f | ( `' f " NN ) e. Fin } $.

    $( ` S ` recovers the sum of a partition. $)
    eulerpartlems.s $e |- S = ( f e. ( ( NN0 ^m NN ) i^i R )
      |-> sum_ k e. NN ( ( f ` k ) x. k ) ) $.

    $d f k A $.  $d f k R $.
    $( Lemma for ~ eulerpart .  Value of the sum of a partition ` A ` .
       (Contributed by Thierry Arnoux, 26-Aug-2018.) $)
    eulerpartlemsv1 $p |- ( A e. ( ( NN0 ^m NN ) i^i R )
      -> ( S ` A ) = sum_ k e. NN ( ( A ` k ) x. k ) ) $=
      ( cn0 cn cmap co wcel cv cfv cmul csu cvv wceq a1i wa cin simplr sumeq2dv
      cmpt fveq1d oveq1d id sumex fvmptd ) AHIJKBUAZLZDAIEMZDMZNZULOKZEPZIULANZ
      ULOKZEPZUJCQCDUJUPUDRUKGSUKUMARZTZIUOUREVAULILZTZUNUQULOVCULUMAUKUTVBUBUE
      UFUCUKUGUSQLUKIUREUHSUI $.

    $( Lemma for ~ eulerpart .  (Contributed by Thierry Arnoux, 8-Aug-2018.) $)
    eulerpartlemelr $p |- ( A e. ( ( NN0 ^m NN ) i^i R )
      -> ( A : NN --> NN0 /\ ( `' A " NN ) e. Fin ) ) $=
      ( cn0 cn cmap co cin wcel wf ccnv cima cfn inss1 sseli elmapi syl cv wceq
      inss2 cnveq imaeq1d eleq1d elab2g mpbid jca ) AHIJKZBLZMZIHANZAOZIPZQMZUM
      AUKMUNULUKAUKBRSAHITUAUMABMUQULBAUKBUDSDUBZOZIPZQMUQDABULURAUCZUTUPQVAUSU
      OIURAUEUFUGFUHUIUJ $.

    $( Lemma for ~ eulerpart .  Value of the sum of a finite partition ` A `
       (Contributed by Thierry Arnoux, 19-Aug-2018.) $)
    eulerpartlemsv2 $p |- ( A e. ( ( NN0 ^m NN ) i^i R )
      -> ( S ` A ) = sum_ k e. ( `' A " NN ) ( ( A ` k ) x. k ) ) $=
      ( cn0 cn co wcel cfv cmul csu c1 wceq wa adantr cc0 wn cmap cin ccnv cima
      cv eulerpartlemsv1 cdm cnvimass cfn eulerpartlemelr simpld fdm syl sselda
      wf syl5sseq ffvelrnd nnnn0d nn0mulcld nn0cnd cdif wo simpr eldifad wi wfn
      eldifbd ffn elpreima 3syl notbid mpbid imnan sylibr mpd elnn0 sylib orel1
      wb imp syl2anc oveq1d nncnd mul02d eqtrd cuz wss eqimssi a1i sumss eqtr4d
      nnuz ) AHIUAJBUBKZACLIEUEZALZWNMJZENAUCIUDZWPENABCDEFGUFWMWQIWPEOWMAUGZWQ
      IAIUHWMIHAUOZWRIPWMWSWQUIKABCDEFGUJUKZIHAULUMUPZWMWNWQKZQZWPXCWOWNXCIHWNA
      WMWSXBWTRWMWQIWNXAUNZUQXCWNXDURUSUTWMWNIWQVAKZQZWPSWNMJSXFWOSWNMXFWOIKZTZ
      XGWOSPZVBZXIXFWNIKZXHXFWNIWQWMXEVCZVDZXFXKXGQZTZXKXHVEXFXBTXOXFWNIWQXLVGX
      FXBXNXFWSAIVFXBXNVSWMWSXEWTRZIHAVHIWNIAVIVJVKVLXKXGVMVNVOXFWOHKXJXFIHWNAX
      PXMUQWOVPVQXHXJXIXGXIVRVTWAWBXFWNXFWNXMWCWDWEIOWFLZWGWMIXQWLWHWIWJWK $.

    $d f g k R $.
    $( Lemma for ~ eulerpart .  (Contributed by Thierry Arnoux, 8-Aug-2018.) $)
    eulerpartlemsf $p |- S : ( ( NN0 ^m NN ) i^i R ) --> NN0 $=
      ( vg cn cv cfv cmul co csu cn0 wcel cmap wf wi wceq wa cin wral vex eleq1
      simpl fveq1d oveq1d sumeq2dv imbi12d ccnv eulerpartlemsv2 eulerpartlemsv1
      eleq1d cima eqtr3d cfn eulerpartlemelr simprd simpld cdm cnvimass fdm syl
      adantr syl5sseq sselda ffvelrnd nnnn0d nn0mulcld fsumnn0cl eqeltrrd vtocl
      rgen fmpt mpbi ) HDIZCIZJZVPKLZDMZNOZCNHPLAUAZUBWBNBQWACWBGIZWBOZHVPWCJZV
      PKLZDMZNOZRVQWBOZWARGVQCUCWCVQSZWDWIWHWAWCVQWBUDWJWGVTNWJHWFVSDWJVPHOZTZW
      EVRVPKWLVPWCVQWJWKUEUFUGUHUMUIWDWCUJHUNZWFDMZWGNWDWCBJWNWGWCABCDEFUKWCABC
      DEFULUOWDWMWFDWDHNWCQZWMUPOZWCABCDEFUQZURWDVPWMOZTZWEVPWSHNVPWCWDWOWRWDWO
      WPWQUSZVDWDWMHVPWDWCUTZWMHWCHVAWDWOXAHSWTHNWCVBVCVEVFZVGWSVPXBVHVIVJVKVLV
      MCWBNVTBFVNVO $.

    $( This proof could be shortened, at least by using finite sum theorems $)
    $d k l m t A $.  $d l t R $.  $d l t S $.
    $( Lemma for ~ eulerpart .  (Contributed by Thierry Arnoux, 6-Aug-2018.) $)
    eulerpartlems $p |- ( ( A e. ( ( NN0 ^m NN ) i^i R )
      /\ t e. ( ZZ>= ` ( ( S ` A ) + 1 ) ) ) -> ( A ` t ) = 0 ) $=
      ( cn0 cn co wcel cfv c1 wa cc0 wceq clt wbr cmul vl vm cmap cin caddc cuz
      cv cfz wb eulerpartlemsf ffvelrni nndiffz1 eleq2d syl pm5.32i simpr eldif
      cdif wn sylib simpld ccnv cima cfn eulerpartlemelr ffvelrnda syldan simpl
      wf adantr simprd cz nnuz syl6eleq nn0zd elfz5 syl2anc notbid nn0red nnred
      cle ltnled bitr4d biimpa syl21anc wral wrex fveq2 oveq12d eulerpartlemsv1
      wi csu id cbvsumv eqcomd syl5eqr breq2 breq2d anbi12d cbvrexv cr ad2antrr
      wne cmpt 1z a1i eqidd fveq2d ffvelrn nnnn0d nn0mulcld fvmptd cc wss fmptd
      cbvmptv nn0sscn fss sylancl cvv csn eqid ffs2 dfn2 eqeltrd ffn w3a oveq1d
      simp3 simp2 nncnd mul02d eqtrd suppss3 ssfi eqeltrrd sylbir ex imp sylibr
      fsumcvg4 isumrecl simprl remulcld nn0ge0 simprr elnnnn0b nnge1 lemulge12d
      nn0cnd sumsn snfi snssd nn0ge0d isumless eqbrtrrd letrd ltletrd rexlimdva
      mulcld syl6breq ltne neeq1i syl5bi necon2bd mpd ralnex imnan ralbii nn0re
      r19.21bi 0re lenltd nn0le0eq0 bitr3d ) BIJUCKCUDZLZAUGZBDMZNUEKUFMZLZOUVQ
      UVRJNUVSUHKZURZLZOZUVRBMZPQZUVQUWDUWAUVQUVSILZUWDUWAUIUVPIBDCDEFGHUJUKZUW
      HUWCUVTUVRUVSULUMUNUOUWEUWFILZPUWFRSZUSZUWGUVQUWDUVRJLZUWJUWEUWMUVRUWBLZU
      SZUWEUWDUWMUWOOUVQUWDUPUVRJUWBUQUTZVAZUVQJIUVRBUVQJIBVIZBVBZJVCZVDLZBCDEF
      GHVEZVAZVFVGUWEUVQUWMUVSUVRRSZUWLUVQUWDVHUWQUWEUWMUWHUWOUXDUWQUVQUWHUWDUW
      IVJUWEUWMUWOUWPVKUWMUWHOZUWOUXDUXEUWOUVRUVSWASZUSUXDUXEUWNUXFUXEUVRNUFMZL
      UVSVLLUWNUXFUIUXEUVRJUXGUWMUWHVHZVMVNUXEUVSUWMUWHUPZVOUVRNUVSVPVQVRUXEUVS
      UVRUXEUVSUXIVSUXEUVRUXHVTWBWCWDWEUVQUWMOUXDUWLUVQUXDUWLWKZAJUVQUXDUWKOZUS
      ZAJWFZUXJAJWFUVQUXKAJWGZUSZUXMUVQJUWFUVRTKZAWLZUVSQUXOUVQUXQJFUGZBMZUXRTK
      ZFWLZUVSJUXTUXPFAUXRUVRQZUXSUWFUXRUVRTUXRUVRBWHUYBWMWIWNUVQUVSUYABCDEFGHW
      JWOWPUVQUXNUXQUVSUXNUVSUAUGZRSZPUYCBMZRSZOZUAJWGZUVQUXQUVSXCZUXKUYGAUAJUV
      RUYCQZUXDUYDUWKUYFUVRUYCUVSRWQUYJUWFUYEPRUVRUYCBWHZWRWSWTUVQUYHUYIUVQUYHO
      ZUVSXALZUVSJUYEUYCTKZUAWLZRSZUYIUYLUVSUVQUWHUYHUWIVJVSUYLUVSUXQUYORUVQUYH
      UVSUXQRSZUVQUYGUYQUAJUVQUYCJLZOZUYGUYQUYSUYGOZUVSUYCUXQUYTUVSUVQUWHUYRUYG
      UWIXBVSUYTUYCUYSUYRUYGUVQUYRUPZVJZVTZUYSUXQXALUYGUYSUXPAUBJUBUGZBMZVUDTKZ
      XDZNJVMNVLLUYSXEXFZUYSUWMOZUWRUWMUVRVUGMUXPQUVQUWRUYRUWMUXCXBUYSUWMUPZUWR
      UWMOZUBUVRVUFUXPJVUGIVUKVUGXGVUKVUDUVRQZOZVUEUWFVUDUVRTVUMVUDUVRBVUKVULUP
      ZXHVUNWIUWRUWMUPZVUKUWFUVRJIUVRBXIVUKUVRVUOXJXKXLVQZVUIUXPVUIUWFUVRUYSJIU
      VRBUVQUWRUYRUXCVJZVFVUIUVRVUJXJXKZVSZUYSJVUGNVMVUHUYSJIVUGVIIXMXNJXMVUGVI
      ZUYSAJUXPIVUGVURUBAJVUFUXPVULVUEUWFVUDUVRTVUDUVRBWHVULWMWIXPZXOXQJIXMVUGX
      RXSZUYSVUGVBZXTPYAZURZVCZVVCXMVVDURZVCZVDUYSVUTVVFVVHQVVBJXMVVGVUGPVVGYBY
      CUNUYSUWSVVEVCZVDLVVFVVIXNZVVFVDLUYSVVIUWTVDUYSUWRVVIUWTQVUQJIJBPYDYCUNUV
      QUXAUYRUVQUWRUXAUXBVKVJYEUYSUWRVVJVUQUWRAJUXPBVUGPVVAJIBYFUWRUWMUWGYGZUXP
      PUVRTKPVVKUWFPUVRTUWRUWMUWGYIYHVVKUVRVVKUVRUWRUWMUWGYJYKYLYMYNUNVVIVVFYOV
      QYPUUAZUUBVJZUYSUYDUYFUUCUYTUYCUYNUXQVUCUYTUYEUYCUYTUYEUYSUYEILZUYGUVQJIU
      YCBUXCVFZVJZVSZVUCUUDVVMUYTUYCUYEVUCVVQUYTUYCILPUYCWASUYTUYCVUBXJUYCUUEUN
      UYTVVNUYFNUYEWASZVVPUYSUYDUYFUUFVVNUYFOUYEJLVVRUYEUUGUYEUUHYQVQUUIUYSUYNU
      XQWASUYGUYSUYCYAZUXPAWLZUYNUXQWAUYSUYRUYNXMLVVTUYNQVUAUYSUYEUYCUYSUYEVVOU
      UJUYSUYCVUAYKUUTUXPUYNAUYCJUYJUWFUYEUVRUYCTUYKUYJWMWIZUUKVQUYSVVSUXPAVUGN
      JVMVUHVVSVDLUYSUYCUULXFUYSUYCJVUAUUMVUPVUSVUIUXPVURUUNVVLUUOUUPVJUUQUURYR
      UUSYSJUXPUYNAUAVWAWNZUVAUYMUYPOUYOUVSXCUYIUVSUYOUVBUXQUYOUVSVWBUVCYTVQYRU
      VDUVEUVFUXKAJUVGYTUXJUXLAJUXDUWKUVHUVIYTUVKYSWEUWJUWLUWGUWJUWFPWASUWLUWGU
      WJUWFPUWFUVJPXALUWJUVLXFUVMUWFUVNUVOWDVQYQ $.

    $d k t S $.
    $( Lemma for ~ eulerpart .  Value of the sum of a finite partition ` A `
       (Contributed by Thierry Arnoux, 19-Aug-2018.) $)
    eulerpartlemsv3 $p |- ( A e. ( ( NN0 ^m NN ) i^i R )
      -> ( S ` A ) = sum_ k e. ( 1 ... ( S ` A ) ) ( ( A ` k ) x. k ) ) $=
      ( vt cn0 cn co wcel cfv cv cmul csu c1 cc0 wceq wral cmap eulerpartlemsv1
      cin cfz wss cuz fzssuz nnuz sseqtr4i a1i wa ccnv cima cfn eulerpartlemelr
      wf simpld adantr sselda ffvelrn syl2anc nn0cnd nncnd mulcld eulerpartlems
      cdif caddc ralrimiva fveq2 eqeq1d sylibr eulerpartlemsf ffvelrni nndiffz1
      cbvralv syl raleq mpbird r19.21bi oveq1d simpr eldifad mul02d eqtrd sumss
      wb eqimssi eqtr4d ) AIJUAKBUCZLZACMZJENZAMZWLOKZEPQWKUDKZWNEPABCDEFGUBWJW
      OJWNEQWOJUEWJWOQUFMZJQWKUGUHUIUJZWJWLWOLZUKZWMWLWSWMWSJIAUPZWLJLWMILWJWTW
      RWJWTAULJUMUNLABCDEFGUOUQURWJWOJWLWQUSZJIWLAUTVAVBWSWLXAVCVDWJWLJWOVFZLZU
      KZWNRWLOKRXDWMRWLOWJWMRSZEXBWJXEEXBTZXEEWKQVGKUFMZTZWJHNZAMZRSZHXGTXHWJXK
      HXGHABCDEFGVEVHXEXKEHXGWLXISWMXJRWLXIAVIVJVOVKWJXBXGSZXFXHWFWJWKILXLWIIAC
      BCDEFGVLVMWKVNVPXEEXBXGVQVPVRVSVTXDWLXDWLXDWLJWOWJXCWAWBVCWCWDJWPUEWJJWPU
      HWGUJWEWH $.

    $d i n $.  $d i t A $.  $d i t R $.
    $( Lemma for ~ eulerpart .  (Contributed by Thierry Arnoux, 9-Aug-2018.) $)
    eulerpartlemgc $p |- ( ( A e. ( ( NN0 ^m NN ) i^i R ) /\ ( t e. NN
      /\ n e. ( bits ` ( A ` t ) ) ) ) -> ( ( 2 ^ n ) x. t ) <_ ( S ` A ) ) $=
      ( vi cn0 cn co wcel wa c2 cmul cc0 cle wbr cmap cin cv cfv cbits cexp 2re
      a1i wss bitsss simprr sseldd reexpcld simprl nnred remulcld ccnv cima cfn
      cr wf eulerpartlemelr simpld simpr ffvelrn syl2anc adantrr eulerpartlemsf
      adantr nn0red ffvelrni w3a nnrpd rprege0d 3jca csn csu bitsfi sselda 2pos
      syl clt 0re ltlei ax-mp expge0d snssd fsumless recnd oveq2 sumsn bitsinv1
      cc wceq 3brtr3d lemul1a c1 cfz wn fzfid simpl elfznn syl2an adantlr nngt0
      nn0ge0d ltled mulge0d fveq2 oveq12d fsumge1 cdif eldif caddc cuz nndiffz1
      id wb eleq2d pm5.32i eulerpartlems sylbi oveq1d nncnd syldan mul02d eqtrd
      eldifad fsumge0 eqbrtrd sylan2br wo exmid mpjaodan eulerpartlemsv3 eqcomd
      anassrs breqtrd letrd ) BKLUAMCUBZNZAUCZLNZGUCZUUBBUDZUEUDZNZOZOZPUUDUFMZ
      UUBQMZUUEUUBQMZBDUDZUUIUUJUUBUUIPUUDPUTNZUUIUGUHUUIUUFKUUDUUFKUIUUIUUEUJU
      HZUUAUUCUUGUKZULUMZUUIUUBUUAUUCUUGUNZUOZUPUUIUUEUUBUUIUUEUUAUUCUUEKNZUUGU
      UAUUCOZLKBVAZUUCUUTUUAUVBUUCUUAUVBBUQLURUSNBCDEFHIVBVCZVIUUAUUCVDZLKUUBBV
      EVFZVGZVJUUSUPUUIUUMUUAUUMKNZUUHYTKBDCDEFHIVHVKZVIVJUUIUUJUTNZUUEUTNZUUBU
      TNRUUBSTOZVLUUJUUESTUUKUULSTUUIUVIUVJUVKUUQUUAUUCUVJUUGUVAUUEUVEVJVGUUIUU
      BUUIUUBUURVMVNVOUUIUUDVPZPJUCZUFMZJVQZUUFUVNJVQZUUJUUESUUIUUFUVNUVLJUUIUU
      TUUFUSNUVFUUEVRWAUUIUVMUUFNOZPUVMUUNUVQUGUHZUUIUUFKUVMUUOVSZUMUVQPUVMUVRU
      VSRPSTZUVQRPWBTUVTVTRPWCUGWDWEUHWFUUIUUDUUFUUPWGWHUUIUUGUUJWMNUVOUUJWNUUP
      UUIUUJUUQWIUVNUUJJUUDUUFUVMUUDPUFWJWKVFUUIUUTUVPUUEWNUVFJUUEWLWAWOUUJUUEU
      UBWPVFUUAUUHUUCUULUUMSTUURUVAUULWQUUMWRMZFUCZBUDZUWBQMZFVQZUUMSUVAUUBUWAN
      ZUULUWESTZUWFWSZUUAUWFUWGUUCUUAUWFOZUWAUWDUULFUUBUWIWQUUMWTUUAUWBUWANZUWD
      UTNUWFUUAUWJOZUWCUWBUWKUWCUWKUUAUWJUWCKNZUUAUWJXAUUAUWJVDZUUAUVBUWBLNZUWL
      UWJUVCUWBUUMXBZLKUWBBVEXCVFZVJZUWKUWBUWKUWJUWNUWMUWOWAZUOZUPZXDUUAUWJRUWD
      STUWFUWKUWCUWBUWQUWSUWKUWCUWPXFUWKRUWBRUTNUWKWCUHUWSUWKUWNRUWBWBTUWRUWBXE
      WAXGXHZXDUWBUUBWNZUWCUUEUWBUUBQUWBUUBBXIUXBXQXJUUAUWFVDXKXDUUAUUCUWHUWGUU
      CUWHOUUAUUBLUWAXLZNZUWGUUBLUWAXMUUAUXDOZUULRUWESUXEUULRUUBQMRUXEUUERUUBQU
      XEUUAUUBUUMWQXNMXOUDZNZOUUERWNUUAUXDUXGUUAUVGUXDUXGXRUVHUVGUXCUXFUUBUUMXP
      XSWAXTABCDEFHIYAYBYCUXEUUBUUAUXDUUCUUBWMNUXEUUBLUWAUUAUXDVDYHUVAUUBUVDYDY
      EYFYGUUARUWESTUXDUUAUWAUWDFUUAWQUUMWTUWTUXAYIVIYJYKYQUWFUWHYLUVAUWFYMUHYN
      UVAUUMUWEUUAUUMUWEWNUUCBCDEFHIYOVIYPYRYEYS $.
  $}

  ${
    $( Given a natural number ` N ` , consider ` P ` , the set of partitions
       of ` N ` , whereas partitions are represented as functions ` f `
       associating a finite set of natural numbers ` k ` with the number of
       times ` k ` appears in the partition. $)
    eulerpart.p $e |- P = { f e. ( NN0 ^m NN ) | ( ( `' f " NN ) e. Fin /\
      sum_ k e. NN ( ( f ` k ) x. k ) = N ) } $.

    ${
      $d f k A $. $d f N $.
      $( Lemma for ~ eulerpart . (Contributed by Mario Carneiro, 26-Jan-2015.)
         $)
      eulerpartleme $p |- ( A e. P <-> ( A : NN --> NN0 /\ ( `' A " NN ) e. Fin
        /\ sum_ k e. NN ( ( A ` k ) x. k ) = N ) ) $=
        ( cn0 cn cmap co wcel ccnv cima cfn cv cfv cmul csu wceq wa wf w3a nnex
        nn0ex elmap anbi1i cnveq imaeq1d eleq1d oveq1d sumeq2sdv eqeq1d anbi12d
        fveq1 elrab2 3anass 3bitr4i ) AGHIJZKZALZHMZNKZHDOZAPZVCQJZDRZESZTZTHGA
        UAZVHTABKVIVBVGUBUSVIVHGHAUDUCUEUFCOZLZHMZNKZHVCVJPZVCQJZDRZESZTVHCAURB
        VJASZVMVBVQVGVRVLVANVRVKUTHVJAUGUHUIVRVPVFEVRHVOVEDVRVNVDVCQVCVJAUNUJUK
        ULUMFUOVIVBVGUPUQ $.
    $}

    ${
      $d f k A $.  $d f k N $.  $d k P $.
      $( Lemma for ~ eulerpart (Contributed by Thierry Arnoux, 19-Aug-2018.) $)
      eulerpartlemv $p |- ( A e. P <-> ( A : NN --> NN0 /\ ( `' A " NN ) e. Fin
        /\ sum_ k e. ( `' A " NN ) ( ( A ` k ) x. k ) = N ) ) $=
        ( wcel cn cn0 cfv cmul co csu wceq w3a wa c1 simpl cc0 wn ccnv cima cfn
        wf cv eulerpartleme cdm cnvimass fdm syl5sseq sselda ffvelrnd nn0mulcld
        nnnn0d nn0cnd cdif wo simpr eldifad wi eldifbd wfn wb ffn elpreima 3syl
        notbid mpbid imnan sylibr mpd elnn0 sylib orel1 imp oveq1d nncnd mul02d
        syl2anc eqtrd cuz wss eqimssi sumss eqcomd adantr eqeq1d pm5.32i df-3an
        nnuz a1i 3bitr4i bitri ) ABGHIAUDZAUAHUBZUCGZHDUEZAJZWQKLZDMZENZOZWNWPW
        OWSDMZENZOZABCDEFUFWNWPPZXAPXFXDPXBXEXFXAXDXFWTXCEWNWTXCNWPWNXCWTWNWOHW
        SDQWNAUGWOHAHUHHIAUIUJZWNWQWOGZPZWSXIWRWQXIHIWQAWNXHRWNWOHWQXGUKZULXIWQ
        XJUNUMUOWNWQHWOUPGZPZWSSWQKLSXLWRSWQKXLWRHGZTZXMWRSNZUQZXOXLWQHGZXNXLWQ
        HWOWNXKURZUSZXLXQXMPZTZXQXNUTXLXHTYAXLWQHWOXRVAXLXHXTXLWNAHVBXHXTVCWNXK
        RZHIAVDHWQHAVEVFVGVHXQXMVIVJVKXLWRIGXPXLHIWQAYBXSULWRVLVMXNXPXOXMXOVNVO
        VSVPXLWQXLWQXSVQVRVTHQWAJZWBWNHYCWJWCWKWDWEWFWGWHWNWPXAWIWNWPXDWIWLWM
        $.
    $}

    $( Define odd partitions ` O ` , in which only odd numbers appear, and
       distinct partitions ` D ` , in which numbers appear at most once. $)
    eulerpart.o $e |- O = { g e. P | A. n e. ( `' g " NN ) -. 2 || n } $.
    eulerpart.d $e |- D = { g e. P | A. n e. NN ( g ` n ) <_ 1 } $.

    ${
      $d g n A $.  $d g P $.
      $( Lemma for ~ eulerpart : ` O ` is the set of odd partitions of ` N ` .
         (Contributed by Thierry Arnoux, 10-Aug-2017.) $)
      eulerpartlemo $p |- ( A e. O <->
        ( A e. P /\ A. n e. ( `' A " NN ) -. 2 || n ) ) $=
        ( c2 cv cdivides wbr ccnv cn cima wral wn cnveq imaeq1d raleqdv elrab2
        wceq ) MGNOPUAZGENZQZRSZTUGGAQZRSZTEACIUHAUFZUGGUJULUMUIUKRUHAUBUCUDKUE
        $.
    $}

    ${
      $d f g k n A $.  $d f N $.  $d g n P $.
      $( Lemma for ~ eulerpart : ` D ` is the set of distinct part. of ` N ` .
         (Contributed by Thierry Arnoux, 11-Aug-2017.) $)
      eulerpartlemd $p |- ( A e. D <-> ( A e. P /\ ( A " NN ) C_ { 0 , 1 } ) )
        $=
        ( wcel c1 cn wa cc0 wceq co cn0 cv cfv cle wbr wral cima cpr wss breq1d
        fveq1 ralbidv elrab2 wb c2 cfzo cmin cz 2z fzoval ax-mp fzo0to2pr 2m1e1
        cfz oveq2i 3eqtr3i eleq2i a1i ccnv cfn cmul csu eulerpartleme ffvelrnda
        wf simp1bi 1nn0 jctr w3a elfz2nn0 df-3an bitri baib syl bitr2d ralbidva
        wfun cdm ffun fdm eqimss2 3syl funimass4 syl2anc bitr4d pm5.32i ) ABMAC
        MZGUAZAUBZNUCUDZGOUEZPWPAOUFQNUGZUHZPWQEUAZUBZNUCUDZGOUEWTEACBXCARZXEWS
        GOXFXDWRNUCWQXCAUJUIUKLULWPWTXBWPWTWRXAMZGOUEZXBWPWSXGGOWPWQOMPZXGWRQNV
        CSZMZWSXGXKUMXIXAXJWRQUNUOSZQUNNUPSZVCSZXAXJUNUQMXLXNRURQUNUSUTVAXMNQVC
        VBVDVEVFVGXIWRTMZXKWSUMZWPOTWQAWPOTAVNZAVHOUFVIMOFUAZAUBXRVJSFVKHRACDFH
        JVLVOZVMXOXONTMZPZXPXOXTVPVQXKYAWSXKXOXTWSVRYAWSPWRNVSXOXTWSVTWAWBWCWCW
        DWEWPAWFZOAWGZUHZXBXHUMWPXQYBXSOTAWHWCWPXQYCORYDXSOTAWIOYCWJWKGOXAAWLWM
        WNWOWA $.
    $}

    ${
      $( $d a k l m n o x y z $. $d a F $. $d a x y J $. $)
      $( We will use the set of odd natural numbers ` J ` . $)
      eulerpart.j $e |- J = { z e. NN | -. 2 || z } $.
      eulerpart.f $e |- F = ( x e. J , y e. NN0 |-> ( ( 2 ^ y ) x. x ) ) $.
      eulerpart.h $e |- H = { r e. ( ( ~P NN0 i^i Fin ) ^m J ) |
        ( `' r " ( _V \ { (/) } ) ) e. Fin } $.

      $( ` ( bits o. ( A |`` J ) ) ` results in a function from ` J ` , the odd
         natural numbers, to the subset of ` NN0 ` . Applying ` M ` helps to
         convert this back to a relation. $)
      eulerpart.m $e |- M = ( r e. H |->
        { <. x , y >. | ( x e. J /\ y e. ( r ` x ) ) } ) $.

      ${
        $d r x y J $. $d r H $.
        $( Lemma for ~ eulerpart (Contributed by Thierry Arnoux, 27-Aug-2017.)
           $)
        eulerpartlem1 $p |- M : H -1-1-onto-> ( ~P ( J X. NN0 ) i^i Fin ) $=
          ( cn0 cxp cpw cfn cin wf1o cmap co cv wcel cfv wa copab cmpt cres wss
          cn cvv c2 cdivides wbr crab ssrab2 eqsstri nnex ssex ax-mp nn0ex eqid
          wn fpwrelmapffs wceq wb ccnv c0 csn cdif cima inss1 mapss mp2an sstri
          pwex resmpt eqtr4i f1oeq1 mpbir ) KLUDUEUFUGUHZMUIZKWKPUDUFZLUJUKZAUL
          ZLUMBULWOPULZUNUMUOABUPZUQZKURZUIZABLUDKPWRLUTUSLVAUMLVBCULVCVDVMZCUT
          VEUTTXACUTVFVGLUTVHVIVJVKWRVLUBVNMWSVOWLWTVPMPKWQUQZWSUCKWNUSWSXBVOKW
          PVQVAVRVSVTWAUGUMZPWMUGUHZLUJUKZVEZWNUBXFXEWNXCPXEVFWMVAUMXDWMUSXEWNU
          SUDVKWFWMUGWBXDWMLVAWCWDWEVGPWNKWQWGVJWHKWKMWSWIVJWJ $.
      $}

      ${
        $d f g k x y $. $d f k A $. $d f g x N $. $d g P $.
        $( Lemma for ~ eulerpart .  The set of all partitions of ` N ` is
           finite. (Contributed by Mario Carneiro, 26-Jan-2015.) $)
        eulerpartlemb $p |- P e. Fin $=
          ( cn cv c1 cfz co wcel cc0 csn cif cixp cfn wtru fzfid wa fzfi keepel
          wss snfi a1i cdif wn wceq eldifn adantl iffalse eqimss 3syl ixpfi2 wf
          trud cn0 ccnv cima cfv csu w3a eulerpartleme wfn ffn 3ad2ant1 cle wbr
          cmul wral cr simp1 ffvelrn sylan nn0re syl wi idi remulcl syl2anc cdm
          nnre cnvimass adantr syl5sseq cc sselda adantlr syldan nnnn0 nn0mulcl
          fdm nn0cn simpl cvv nn0supp suppssr oveq1d eldifi nncn mul02 cuz nnuz
          eqtrd eqimssi sumss nn0sscn caddc nn0addcl simpr 0nn0 eqeltrrd nn0ge0
          fsumcllem nnge1 expr ralrimiva breqtrd syl6eleq elfz5 eleqtrrd syld
          wb eleq1 syl5ibcom 3impia lemulge11 syl22anc fveq2 id oveq12d fsumge1
          simprr eldif eqeq1d rspccva sylan2br fsumge0 adantrr eqbrtrd 3adantl3
          pm2.61d simpl3 letrd nn0uz nn0z mpbird iftrue lemulge12 syl21anc letr
          cz syl3anc mpan2d syl5 sylibrd con3d elnn0 sylib ord imp elsnc sylibr
          wo fvex pm2.61dan vex elixp sylanbrc sylbi ssriv ssfi mp2an ) AUDAUEZ
          UFNUGUHZUIZUJNUGUHZUJUKZULZUMZUNUIZEUWQUTEUNUIUWRUOAUDUWPUWLUJUOUFNUP
          UWPUNUIUOUWKUDUIZUQUWMUWNUWOUNUJNURUJVAUSVBUOUWKUDUWLVCUIZUQUWMVDZUWP
          UWOVEZUWPUWOUTUWTUXAUOUWKUDUWLVFVGUWMUWNUWOVHZUWPUWOVIVJVKVMGEUWQGUEZ
          EUIUDVNUXDVLZUXDVOZUDVPZUNUIZUDHUEZUXDVQZUXIWFUHZHVRZNVEZVSZUXDUWQUIZ
          UXDEFHNQVTUXNUXDUDWAZUWKUXDVQZUWPUIZAUDWGUXOUXEUXHUXPUXMUDVNUXDWBWCUX
          NUXRAUDUXNUWSUQZUWMUXRUXSUWMUQUXQUWNUWPUXSUXQUWNUIZUWMUXSUXTUXQNWDWEZ
          UXSUXQUXQUWKWFUHZNUXSUXQVNUIZUXQWHUIZUXNUXEUWSUYCUXEUXHUXMWIUDVNUWKUX
          DWJWKZUXQWLWMZUXSUYDUWKWHUIZUYBWHUIZUXSUYDWNUYFWOUXSUYGWNUWSUYGUXNUWK
          WSVGZWOZUXQUWKWPWQZUXSNVNUIZNWHUIZUXNUYLUWSUXEUXHUXMUYLUXEUXHUQZUXLVN
          UIUXMUYLUYNUXGUXKHVRZUXLVNUYNUXGUDUXKHUFUYNUXDWRZUXGUDUXDUDWTUXEUYPUD
          VEUXHUDVNUXDXIXAXBZUYNUXIUXGUIZUQZUXKVNUIZUXKXCUIUYSUXJVNUIZUXIVNUIZU
          YTUYNUYRUXIUDUIZVUAUYNUXGUDUXIUYQXDZUXEVUCVUAUXHUDVNUXIUXDWJXEXFUYSVU
          CVUBVUDUXIXGWMUXJUXIXHWQZUXKXJWMUYNUXIUDUXGVCZUIZUQZUXKUJUXIWFUHZUJVU
          HUXJUJUXIWFUYNUDVNUXDUXGUXIUJUXEUXHXKUYNUXFXLUWOVCVPZUXGVEZVUJUXGUTUX
          EVUKUXHUXDUDXMXAVUJUXGVIWMXNXOVUHVUCUXIXCUIVUIUJVEVUGVUCUYNUXIUDUXGXP
          VGUXIXQUXIXRVJYAZUDUFXSVQZUTUYNUDVUMXTYBVBYCZUYNABUXGUXKVNHVNXCUTUYNY
          DVBUWKVNUIZBUEZVNUIUQUWKVUPYEUHVNUIUYNUWKVUPYFVGUXEUXHYGZVUEUJVNUIUYN
          YHVBYKYIUXLNVNUUAUUBUUCXAZNWLWMZUXSUYDUYGUJUXQWDWEZUFUWKWDWEZUXQUYBWD
          WEUYFUYIUXSUYCVUTUXSUYCWNUYEWOUXQYJWMUWSVVAUXNUWKYLVGUXQUWKUUDUUEUXSU
          YBUXLNWDUXEUXHUWSUYBUXLWDWEUXMUYNUWSUQZUYBUYOUXLWDVVBUWKUXGUIZUYBUYOW
          DWEZUYNUWSVVCVVDUYNUWSVVCUQZUQUXGUXKUYBHUWKUYNUXHVVEVUQXAUYNUYRUXKWHU
          IZVVEUYSUYTVVFVUEUXKWLZWMXEUYNUYRUJUXKWDWEZVVEUYSUYTVVHVUEUXKYJZWMXEU
          XIUWKVEZUXJUXQUXIUWKWFUXIUWKUXDUUFVVJUUGUUHZUYNUWSVVCUUJUUIYMUYNUWSVV
          CVDZVVDUYNUWSVVLUQZUQUYBUJUYOWDVVMUYNUWKVUFUIZUYBUJVEZUWKUDUXGUUKUYNU
          XKUJVEZHVUFWGVVNVVOUYNVVPHVUFVULYNVVPVVOHUWKVUFVVJUXKUYBUJVVKUULUUMWK
          UUNUYNUWSUJUYOWDWEVVLVVBUXGUXKHUYNUXHUWSVUQXAVVBUYRUQZUYTVVFUYNUYRUYT
          UWSVUEXEZVVGWMVVQUYTVVHVVRVVIWMUUOUUPUUQYMUUSUYNUYOUXLVEUWSVUNXAYOUUR
          UXEUXHUXMUWSUUTYOZUVAUXSUXQUJXSVQZUINUVIUIZUXTUYAYTUXSUXQVNVVTUYEUVBY
          PUXSUYLVWAVURNUVCWMZUXQUJNYQWQUVDXAUWMUWPUWNVEUXSUWMUWNUWOUVEVGYRUXSU
          XAUQZUXQUWOUWPVWCUXQUJVEZUXQUWOUIUXSUXAVWDUXSUXAUXQUDUIZVDVWDUXSVWEUW
          MUXSVWEUWKNWDWEZUWMVWEUFUXQWDWEZUXSVWFUXQYLUXSVWGUWKUYBWDWEZVWFUXSUYG
          UYDUJUWKWDWEZVWGVWHWNUYIUYFUXSVUOVWIUWSVUOUXNUWKXGVGUWKYJWMUYGUYDUQVW
          IVWGVWHUWKUXQUVFYMUVGUXSVWHUYBNWDWEZVWFVVSUXSUYGUYHUYMVWHVWJUQVWFWNUY
          JUXSUYHWNUYKWOUXSUYMWNVUSWOUWKUYBNUVHUVJUVKYSUVLUXSUWKVUMUIVWAUWMVWFY
          TUXSUWKUDVUMUXNUWSYGXTYPVWBUWKUFNYQWQUVMUVNUXSVWEVWDUXSUYCVWEVWDUWAUY
          EUXQUVOUVPUVQYSUVRUXQUJUWKUXDUWBUVSUVTUXAUXBUXSUXCVGYRUWCYNAUDUWPUXDG
          UWDUWEUWFUWGUWHUWQEUWIUWJ $.
      $}

      $( Define the set of finitely supported functions.  $)
      eulerpart.r $e |- R = { f | ( `' f " NN ) e. Fin } $.

      $( Define the set of functions into ` NN0 ` with odd-valued support. $)
      eulerpart.t $e |- T = { f e. ( NN0 ^m NN ) | ( `' f " NN ) C_ J } $.

      ${
        $d f A $. $d f J $.
        $( Lemma for ~ eulerpart  (Contributed by Thierry Arnoux,
           19-Sep-2017.) $)
        eulerpartlemt0 $p |- ( A e. ( T i^i R ) <-> ( A e. ( NN0 ^m NN ) /\
          ( `' A " NN ) e. Fin /\ ( `' A " NN ) C_ J ) ) $=
          ( wcel wa cn0 cn cmap co ccnv cima wss cvv cfn cin wceq cnveq imaeq1d
          w3a cv sseq1d elrab2 eleq1d elab4g anbi12i elin pm4.71i anbi1i 3anass
          elex an42 3bitr4i ) DHUIZDGUIZUJDUKULUMUNZUIZDUOZULUPZOUQZUJZDURUIZWC
          USUIZUJZUJZDHGUTUIWAWGWDVDZVRWEVSWHIVEZUOZULUPZOUQWDIDVTHWKDVAZWMWCOW
          NWLWBULWKDVBVCZVFUHVGWMUSUIWGIDGWNWMWCUSWOVHUGVIVJDHGVKWAWGWDUJZUJWAW
          FUJZWPUJWJWIWAWQWPWAWFDVTVOVLVMWAWGWDVNWAWDWFWGVPVQVQ $.
      $}

      ${
        $d t z $.  $d f g k n t A $.  $d f J  $.  $d f N $.  $d g P $.
        $( Lemma for ~ eulerpart : Odd partitions are zero for even numbers.
           (Contributed by Thierry Arnoux, 9-Sep-2017.) $)
        eulerpartlemf $p |- ( ( A e. ( T i^i R ) /\ t e. ( NN \ J ) )
          -> ( A ` t ) = 0 )
          $=
          ( cin wcel cv cn cdif wa cfv wn cc0 wceq wo cdivides wbr eldif notbid
          c2 breq2 elrab2 simplbi2 con1d imp sylbi adantl adantr ccnv simpll wb
          cima id simplbi cn0 wf wfn cmap cfn wss eulerpartlemt0 simp1bi elmapi
          co syl ffn elpreima 3syl baibd syl2an biimpar simp3bi simprbi syl2anc
          sselda pm2.65da simpl ffvelrnd elnn0 sylib orel1 sylc ) EIHUJUKZDULZU
          MPUNUKZUOZXIEUPZUMUKZUQXMXLURUSZUTZXNXKXMVEXIVAVBZXKXPXMXJXPXHXJXIUMU
          KZXIPUKZUQZUOXPXIUMPVCZXQXSXPXQXPXRXRXQXPUQZVECULZVAVBZUQYACXIUMPYBXI
          USYCXPYBXIVEVAVFVDUDVGZVHVIVJVKVLVMXKXMUOXHXIEVNUMVQZUKZYAXHXJXMVOXKY
          FXMXHXHXQYFXMVPXJXHVRXJXQXSXTVSZXHYFXQXMXHUMVTEWAZEUMWBYFXQXMUOVPXHEV
          TUMWCWIUKZYHXHYIYEWDUKZYEPWEZABCEFGHIJKLMNOPQRSTUAUBUCUDUEUFUGUHUIWFZ
          WGEVTUMWHWJZUMVTEWKUMXIUMEWLWMWNWOWPXHYFUOXRYAXHYEPXIXHYIYJYKYLWQWTXR
          XQYAYDWRWJWSXAXKXLVTUKXOXKUMVTXIEXKXHYHXHXJXBYMWJXJXQXHYGVLXCXLXDXEXM
          XNXFXG $.
      $}

      ${
        $d f m o J $. $d m o R $. $d m o T $.
        $( Lemma for ~ eulerpart  (Contributed by Thierry Arnoux,
           19-Sep-2017.) $)
        eulerpartlemt $p |- ( ( NN0 ^m J ) i^i R ) =
          ran ( m e. ( T i^i R ) |-> ( m |` J ) ) $=
          ( vo cv cn0 cmap co wcel cab cres wceq cin wrex cmpt crn cdif cc0 csn
          wa cn cxp cun ccnv cima cfn wss wf c0 elmapi adantr 0nn0 elexi fconst
          w3a a1i disjdif fun syl21anc c2 cdivides wn crab ssrab2 eqsstri undif
          wbr mpbi snssi ax-mp ssequn2 feq23i sylib cvv nn0ex nnex elmapg mp2an
          wb sylibr cnvun imaeq1i imaundir eqtri vex cnveq imaeq1d eleq1d elab2
          biimpi adantl cdm cnvxp dmeqi wne 2nn nnzi iddvds breq2 notbid elrab2
          cz simprbi mt2 eldif mpbir2an mp2b mpbir incom eqeltri eulerpartlemt0
          syl2anc syl wfn eqeltrd ne0i dmxp ineq1i 0nnn disjsn eqeq1i 0fin unfi
          imadisj syl5eqel cnvimass fdm syl5sseq 0ss syl5eqss 3jca resundir ffn
          unssd fnresdm fnconstg fnresdisj uneq12d syl6eq syl5req reseq1 eqeq2d
          un0 rspcev simpr simpl simp1d fssres rabex wfun ffun respreima simp2d
          3syl infi resex jca rexlimiva impbii abbii df-in eqid rnmpt 3eqtr4i )
          UIUJZUKOULUMZUNZUWJFUNZVEZUIUOUWJKUJZOUPZUQZKGFURZUSZUIUOUWKFURKUWRUW
          PUTZVAUWNUWSUIUWNUWSUWNUWJVFOVBZVCVDZVGZVHZUWRUNZUWJUXDOUPZUQZUWSUWNU
          XDUKVFULUMZUNZUXDVIZVFVJZVKUNZUXKOVLZVTUXEUWNUXIUXLUXMUWNVFUKUXDVMZUX
          IUWNOUXAVHZUKUXBVHZUXDVMZUXNUWNOUKUWJVMZUXAUXBUXCVMZOUXAURZVNUQZUXQUW
          LUXRUWMUWJUKOVOVPZUXSUWNUXAVCVCUKVQVRVSWAUYAUWNOVFWBZWAOUXAUKUXBUWJUX
          CWCWDUXOUXPVFUKUXDOVFVLZUXOVFUQOWECUJZWFWLZWGZCVFWHZVFUCUYGCVFWIWJZOV
          FWKWMUXBUKVLZUXPUKUQVCUKUNZUYJVQVCUKWNWOUXBUKWPWMWQWRUKWSUNZVFWSUNZUX
          IUXNXDWTXAUKVFUXDWSWSXBXCXEUWNUXKUWJVIZVFVJZUXCVIZVFVJZVHZVKUXKUYNUYP
          VHZVFVJUYRUXJUYSVFUWJUXCXFXGUYNUYPVFXHXIZUWNUYOVKUNZUYQVKUNZUYRVKUNUW
          MVUAUWLUWMVUAHUJZVIZVFVJZVKUNZVUAHUWJFUIXJVUCUWJUQZVUEUYOVKVUGVUDUYNV
          FVUCUWJXKXLXMUGXNXOXPVUBUWNUYQVNVKUYQVNUQUYPXQZVFURZVNUQVUIUXBVFURZVN
          VUHUXBVFVUHUXBUXAVGZXQZUXBUYPVUKUXAUXBXRXSWEUXAUNZUXAVNXTVULUXBUQVUMW
          EVFUNZWEOUNZWGYAVUOWEWEWFWLZWEYGUNVUPWEYAYBWEYCWOVUOVUNVUPWGZUYGVUQCW
          EVFOUYEWEUQUYFVUPUYEWEWEWFYDYEUCYFYHYIWEVFOYJYKUXAWEUUAUXBUXAUUBYLXIU
          UCVFUXBURZVNUQZVUJVNUQVUSVCVFUNWGUUDVFVCUUEYMVURVUJVNVFUXBYNUUFWMXIUY
          PVFUUIYMZUUGYOWAUYOUYQUUHYQUUJUWNUXKUYROUYTUWNUYOUYQOUWNUWJXQZUYOOUWJ
          VFUUKUWNUXRVVAOUQUYBOUKUWJUULYRUUMUYQOVLUWNUYQVNOVUTOUUNWJWAUUSUUOUUP
          ABCUXDDEFGHIJLMNOPQRSTUAUBUCUDUEUFUGUHYPXEUWNUXFUWJOUPZUXCOUPZVHZUWJU
          WJUXCOUUQUWNVVDUWJVNVHZUWJUWNUWJOYSZVVDVVEUQUWNUXRVVFUYBOUKUWJUURYRVV
          FVVBUWJVVCVNOUWJUUTVVCVNUQZVVFUXAOURZVNUQZVVGVVHUXTVNUXAOYNUYCXIUYKUX
          CUXAYSVVIVVGXDVQUXAVCUKUVAUXAOUXCUVBYLWMWAUVCYRUWJUVHUVDUVEUWQUXGKUXD
          UWRUWOUXDUQUWPUXFUWJUWOUXDOUVFUVGUVIYQUWQUWNKUWRUWOUWRUNZUWQVEZUWLUWM
          VVKUWJUWPUWKVVJUWQUVJZVVKOUKUWPVMZUWPUWKUNZVVKVFUKUWOVMZUYDVVMVVKUWOU
          XHUNZVVOVVKVVPUWOVIVFVJZVKUNZVVQOVLZVVKVVJVVPVVRVVSVTVVJUWQUVKABCUWOD
          EFGHIJLMNOPQRSTUAUBUCUDUEUFUGUHYPWRZUVLUYLUYMVVPVVOXDWTXAUKVFUWOWSWSX
          BXCWRZUYDVVKUYIWAVFUKOUWOUVMYQUYLOWSUNVVNVVMXDWTOUYHWSUCUYGCVFXAUVNYO
          UKOUWPWSWSXBXCXEYTVVKUWJUWPFVVLVVKUWPVIZVFVJZVKUNZUWPFUNVVKVWCVVQOURZ
          VKVVKVVOUWOUVOVWCVWEUQVWAVFUKUWOUVPVFOUWOUVQUVSVVKVVRVWEVKUNVVKVVPVVR
          VVSVVTUVRVVQOUVTYRYTVUFVWDHUWPFUWOOKXJUWAVUCUWPUQZVUEVWCVKVWFVUDVWBVF
          VUCUWPXKXLXMUGXNXEYTUWBUWCUWDUWEUIUWKFUWFKUIUWRUWPUWTUWTUWGUWHUWI $.
      $}

      $( Define the function ` G ` which we will prove to be a bijection
         between ` O ` and ` D ` . $)
      eulerpart.g $e |- G = ( o e. ( T i^i R ) |->
                ( ( _Ind ` NN ) ` ( F " ( M ` ( bits o. ( o |` J ) ) ) ) ) ) $.

      ${
        $d a f g k l m n o x y z $. $d f k A $. $d a b o F $.
        $d a b f m o r x y J $. $d a b o r M $. $d f g x N $. $d g P $.
        $d f m o R $. $d o r H $. $d f m o T $.
        $( Lemma for ~ eulerpart : The ` G ` function is a bijection.
           (Contributed by Thierry Arnoux, 27-Aug-2017.) $)
        eulerpartgbij $p |-
                   G : ( T i^i R ) -1-1-onto-> ( ( { 0 , 1 } ^m NN ) i^i R ) $=
          ( va vm vb cin cc0 c1 cpr cn cmap co wf1o cind cfv cres cbits cv ccom
          cfn cima cmpt cpw ccnv csn wcel crab cvv nnex indf1ofs ax-mp wceq cab
          wb incom ineq2i dfrab2 3eqtr4i crn wss wf elmapi syl frn wa c0 cun wn
          wfun mpbir mpbi eqcom 3eqtri syl2anc eleq1d rabbiia eqtr2i f1oeq3 cn0
          bitri wtru cdif a1i c2 nn0ex 0nn0 dfn2 eqtr4i eqid inss1 sseli f1oeq1
          mp1i trud eqtri mp2an wrex wfn vex resex f1oco f1of mp2b eqidd fmptco
          cz ffvelrnda eqeltrrd f1ofn dffn5 fveq2 fvmpt2 ffun fimacnvinrn2 indi
          df-pr 0nnn disjsn 1nn 1ex snss dfss eqeq1i uneq12i un0 imaeq2i syl6eq
          uncom cxp oddpwdc f1opwfi eulerpartlem1 bitsf1o cdivides eqeltri pwex
          wbr rabex inex1 fvres 0bits 3eqtr4ri ffs2 fcobijfs 3syl eqcomi mpbird
          cores mpteq2ia wf1 w3a ssrab2 eqsstri 3pm3.2i imaeq12d sseq1d cbvrabv
          cnveq resf1o f1of1 f1ores fnmpti fvelimab eulerpartlemt eleq2i reseq1
          elrnmpti fvmpt eqeq1d bitrd rexbiia 3bitr4ri resmpt wral fmpt biimpri
          eqriv r19.21bi coeq2 eqcomd f1oeq123d mpbiri bitsf zex fex coex simpr
          fvmpt2d fvex imaeq2 cexp cmul mpt2exg imaexg indf1o reseq1i resmpt3 )
          GFUNZUOUPUQZURUSUTZFUNZNVAZUYFUYIURVBVCZVHVDZLUYFMVELVFZPVDZVGZQVCZVI
          ZVJZVGZVAZURVKZVHUNZUYIUYLVAZUYFVUBUYRVAZUYTVUBHVFZVLZUPVMZVIZVHVNZHU
          YHVOZUYLVAZVUCURVPVNZVUKVQHURVPVRVSVUJUYIVTVUKVUCWBUYIVUFURVIZVHVNZHU
          YHVOZVUJUYHVUNHWAZUNVUPUYHUNUYIVUOUYHVUPWCFVUPUYHUHWDVUNHUYHWEWFVUNVU
          IHUYHVUEUYHVNZVUMVUHVHVUQVUEWQZVUEWGZUYGWHZVUMVUHVTVUQURUYGVUEWIZVURV
          UEUYGURWJZURUYGVUEUUAWKVUQVVAVUTVVBURUYGVUEWLWKVURVUTWMVUMVUFURUYGUNZ
          VIVUHURUYGVUEUUBVVCVUGVUFVVCWNVUGWOZVUGWNWOVUGVVCURUOVMZVUGWOZUNURVVE
          UNZURVUGUNZWOVVDUYGVVFURUOUPUUDWDURVVEVUGUUCVVGWNVVHVUGVVGWNVTUOURVNW
          PUUEURUOUUFWRVUGVUGURUNZVTZVVHVUGVTZVUGURWHZVVJUPURVNVVLUUGUPURUUHUUI
          WSVUGURUUJWSVVJVVIVUGVTVVKVUGVVIWTVVIVVHVUGVUGURWCUUKXHWSUULXAWNVUGUU
          PVUGUUMXAUUNUUOXBXCXDXEVUJUYIVUBUYLXFVSWSUYFVUBUKPXGUUQZVKVHUNZMUKVFZ
          VIZVJZLUYFUYPVJZVGZVAZVUDVVNVUBVVQVAZUYFVVNVVRVAZVVTVVMURMVAVWAABCMPU
          DUEUURVVMURMUKUUSVSUYFVVNQLUYFUYOVJZVGZVAZVWBOVVNQVAZUYFOVWCVAZVWEABC
          DEHIJKMOPQRSTUAUBUCUDUEUFUGUUTZVWGXIVWGUYFTVFZVLVPWNVMXJVIVHVNTXGVKZV
          HUNZPUSUTVOZHXGPUSUTZFUNZVEVUEVGZVJZLUYFUYNVJZVGZVAZVWNVWLVWPVAZUYFVW
          NVWQVAZVWSVWTXIVWTVWNVWLHVWNVEXGVDZVUEVGZVJZVAZXIWNPXGVWKVPHHTVXBUOVP
          VPVWNVWLXGVWKVXBVAXIUVAXKPVPVNZXIPXLCVFUVBUVEWPZCURVOZVPUDVXGCURVQUVF
          UVCZXKXGVPVNZXIXMXKVWKVPVNXIVWJVHXGXMUVDUVGXKUOXGVNZXIXNXKUOVXBVCZUOV
          EVCZWNVXKVXLVXMVTXNUOXGVEUVHVSUVIXEVWNVUNHVWMVOZVUFVPVVEXJVIZVHVNZHVW
          MVOVUPVWMUNVWMVUPUNVXNVWNVUPVWMWCVUNHVWMWEFVUPVWMUHWDUVJVXPVUNHVWMVUE
          VWMVNZVXOVUMVHVXQPXGVUEWIZVXOVUMVTVUEXGPWJZPXGURVUEUOXOUVKWKXCXDXPVWL
          XQUVLVWPVXDVTVWTVXEWBXIVXDVWPHVWNVXCVWOVUEVWNVNZVXQVXCVWOVTZVWNVWMVUE
          VWMFXRXSVXQVXRVUSXGWHVYAVXSPXGVUEWLVEVUEXGUVPUVMWKUVQUVNVWNVWLVWPVXDX
          TYAUVOYBUYFLGUYNVJZUYFVIZVYBUYFVDZVAZVXAGVWMVYBUVRZUYFGWHZVYEGVWMVYBV
          AZVYFVULVXJPURWHZUVSVXKVYHVULVXJVYIVQXMPVXHURUDVXGCURUVTUWAUWBXNURXGP
          LVYBVPVPGUOGVUMPWHZHXGURUSUTZVOUYMVLZXGVVEXJZVIZPWHZLVYKVOUIVYJVYOHLV
          YKVUEUYMVTZVUMVYNPVYPVUFVYLURVYMVUEUYMUWFURVYMVTVYPXOXKUWCUWDUWEYCVYB
          XQZUWGYDGVWMVYBUWHVSGFXRZGVWMUYFVYBUWIYDVYEUYFVWNVYDVAZVXAVYCVWNVTVYE
          VYSWBHVYCVWNVUEVYCVNZULVFZVYBVCZVUEVTZULUYFYEZVXTVYBGYFVYGVYTWUDWBLGU
          YNVYBUYMPLYGYHZVYQUWJVYRULGUYFVUEVYBUWKYDVUEULUYFWUAPVDZVJZWGZVNVUEWU
          FVTZULUYFYEVXTWUDULUYFWUFVUEWUGWUGXQWUAPULYGYHZUWOVWNWUHVUEABCDEFGHIJ
          ULKMOPQRSTUAUBUCUDUEUFUGUHUIUWLUWMWUCWUIULUYFWUAUYFVNZWUCWUFVUEVTZWUI
          WUKWUAGVNZWUCWULWBUYFGWUAVYRXSWUMWUBWUFVUELWUAUYNWUFGVYBUYMWUAPUWNVYQ
          WUJUWPUWQWKWULWUIWBWUKWUFVUEWTXKUWRUWSUWTXHUXEVYCVWNUYFVYDXFVSVYDVWQV
          TZVYSVXAWBVYGWUNVYRLGUYFUYNUXAVSUYFVWNVYDVWQXTVSXHWSZUYFVWNVWLVWPVWQY
          IYDXIUYFUYFOVWLVWCVWRXIVWRVWCXILHUYFVWNUYNVWOUYOVWQVWPXIUYNVWNVNZLUYF
          WUPLUYFUXBZXIVXAUYFVWNVWQWIZWUQWUOUYFVWNVWQYJWUQWURLUYFVWNUYNVWQVWQXQ
          UXCUXDYKXKUXFXIVWQYLXIVWPYLVUEUYNVEUXGYMUXHXIUYFYLOVWLVTXIUFXKUXIUXJY
          BZUYFOVVNQVWCYIYDVWDVVRVTZVWEVWBWBWUTXILTUYFOUYOVWIQVCZUYPVWCQXIUYMUY
          FVNZWMZUYMVWCVCUYOOXILUYFUYOVWCVPXIVWCYLZUYOVPVNWVCVEUYNYNVWJVEWIYNVP
          VNVEVPVNUXKUXLYNVWJVPVEUXMYDWUEUXNXKUXPXIUYFOUYMVWCVWGUYFOVWCWIXIWUSU
          YFOVWCYJYAYOYPWVDQTOWVAVJVTZXIQOYFZWVEVWFWVFVWHOVVNQYQVSTOQYRWSXKVWIU
          YOQYSYMYBUYFVVNVWDVVRXTVSWSZUYFVVNVUBVVQVVRYIYDVVSUYRVTZVVTVUDWBWVHXI
          LUKUYFVVNUYPVVPUYQVVRVVQWVCUYMVVRVCZUYPVVNWVCWVBUYPVPVNZWVIUYPVTXIWVB
          UXOZWVJWVCUYOQUXQXKLUYFUYPVPVVRVVRXQYTXBXIUYFVVNUYMVVRVWBUYFVVNVVRWIX
          IWVGUYFVVNVVRYJYAYOYPXIVVRYLXIVVQYLVVOUYPMUXRYMYBUYFVUBVVSUYRXTVSWSZU
          YFVUBUYIUYLUYRYIYDNUYSVTUYJUYTWBNLUYFUYQUYKVCZVJZUYSUJUYSWVNVTXILUMUY
          FVUBUYQUMVFZUYKVCZWVMUYRUYLWVCUYMUYRVCZUYQVUBWVCWVBUYQVPVNZWVQUYQVTWV
          KWVRWVCMVPVNZWVRVXFVXJWVSVXIXMABPXGXLBVFUXSUTAVFUXTUTVPVPMUEUYAYDMUYP
          VPUYBVSXKLUYFUYQVPUYRUYRXQYTXBXIUYFVUBUYMUYRVUDUYFVUBUYRWIXIWVLUYFVUB
          UYRYJYAYOYPXIUYRYLUYLUMVUBWVPVJZVTXIUYLUMVUAWVPVJZVHVDWVTUYKWWAVHUYKV
          UAYFZUYKWWAVTVULVUAUYHUYKVAWWBVQURVPUYCVUAUYHUYKYQYKUMVUAUYKYRWSUYDUM
          VUAVHWVPUYEYCXKWVOUYQUYKYSYMYBXPUYFUYINUYSXTVSWR $.
      $}

      ${
        $d o A $. $d o F $. $d o J $. $d o M $. $d o R $. $d o T $.
        $( Lemma for ~ eulerpart : value of the function ` G ` . (Contributed
           by Thierry Arnoux, 13-Nov-2017.) $)
        eulerpartlemgv $p |- ( A e. ( T i^i R ) -> ( G ` A ) =
          ( ( _Ind ` NN ) ` ( F " ( M ` ( bits o. ( A |` J ) ) ) ) ) ) $=
          ( cbits cres ccom cfv cima cind cin wceq reseq1 coeq2d fveq2d imaeq2d
          cv cn fvex fvmpt ) MDNULMVDZQUMZUNZRUOZUPZVEUQUOZUONULDQUMZUNZRUOZUPZ
          VMUOHGUROVHDUSZVLVQVMVRVKVPNVRVJVORVRVIVNULVHDQUTVAVBVCVBUKVQVMVFVG
          $.
      $}

      ${
        $d f h k n z $. $d f n J $. $d f N $. $d g h n P $. $d h O $. $d h R $.
        $d h T $.
        $( Lemma for ~ eulerpart  (Contributed by Thierry Arnoux,
           13-Nov-2017.) $)
        eulerpartlemr $p |- O = ( ( T i^i R ) i^i P ) $=
          ( vh cin cv wcel wa elin anbi1i c2 cdivides wn ccnv cn cima wral wceq
          wbr cnveq imaeq1d raleqdv elrab2 cn0 cmap wss cfn cfv cmul csu eleq1d
          co fveq1 oveq1d ralrimivw sumeq2d eqeq1d anbi12d simplbi cdm cnvimass
          wf nn0ex nnex elmap fdm sylbi syl5sseq syl sselda ralrimiva biantrurd
          simpld biantrud 3bitrd dfss3 breq2 notbid ralbii r19.26 3bitri anbi2i
          simprbi syl6bbr sseq1d vex elab2 anbi12i pm5.32i ancom 3bitr4ri eqriv
          ) UKSGFULZEULZUKUMZXTUNZYBEUNZUOYBGUNZYBFUNZUOZYDUOZYBYAUNYBSUNZYCYGY
          DYBGFUPUQYBXTEUPYIYDURKUMZUSVFZUTZKYBVAZVBVCZVDZUOYDYGUOYHYLKIUMZVAZV
          BVCZVDYOIYBESYPYBVEZYLKYRYNYSYQYMVBYPYBVGVHVIUBVJYDYOYGYDYOYBVKVBVLVS
          ZUNZYNPVMZUOZYNVNUNZUOZYGYDYOUUAYJVBUNZKYNVDZYOUOZUOZUUDUOZUUEYDYOUUH
          UUIUUJYDUUGYOYDUUFKYNYDYNVBYJYDUUAYNVBVMYDUUAUUDVBJUMZYBVOZUUKVPVSZJV
          QZRVEZUOZHUMZVAZVBVCZVNUNZVBUUKUUQVOZUUKVPVSZJVQZRVEZUOUUPHYBYTEUUQYB
          VEZUUTUUDUVDUUOUVEUUSYNVNUVEUURYMVBUUQYBVGVHZVRZUVEUVCUUNRUVEVBUVBUUM
          JUVEUVBUUMVEJVBUVEUVAUULUUKVPUUKUUQYBVTWAWBWCWDWEUAVJZWFZUUAYBWGZYNVB
          YBVBWHUUAVBVKYBWIUVJVBVEVKVBYBWJWKWLVBVKYBWMWNWOWPWQWRWSYDUUAUUHUVIWS
          YDUUDUUIYDUUDUUOYDUUAUUPUVHXJWTXAXBUUCUUIUUDUUBUUHUUAUUBYJPUNZKYNVDUU
          FYLUOZKYNVDUUHKYNPXCUVKUVLKYNURCUMZUSVFZUTYLCYJVBPUVMYJVEUVNYKUVMYJUR
          USXDXEUDVJXFUUFYLKYNXGXHXIUQXKYEUUCYFUUDUUSPVMUUBHYBYTGUVEUUSYNPUVFXL
          UIVJUUTUUDHYBFUKXMUVGUHXNXOXKXPYDYGXQXHXRXS $.
      $}

      ${
        $d f k n t x y z $.  $d f o r w A $.  $d w B $.  $d o w F $.  $d r H $.
        $d f n o r w x y J $.  $d o w M $.  $d f N $.  $d g n P $.  $d o R $.
        $d o T $.
        $( Lemma for ~ eulerpart (Contributed by Thierry Arnoux, 30-Aug-2018.)
           $)
        eulerpartlemmf $p |- ( A e. ( T i^i R ) -> ( bits o. ( A |` J ) ) e. H
          ) $=
          ( cin wcel cbits cres ccom cn0 cpw cfn cmap co ccnv cvv csn cdif cima
          c0 wa wf wf1o bitsf1o f1of ax-mp wss w3a eulerpartlemt0 biimpi simp1d
          cn nn0ex nnex elmap sylib c2 cv cdivides wbr wn ssrab2 eqsstri fssres
          crab sylancl fco2 sylancr pwex inex1 ssexi sylibr simp2d wceq wb dfn2
          cc0 ffs2 eleq1 3syl mpbird resss cnvss imass1 mp2b ssfi mpan2 imaeq1i
          syl cnvco imaco eqtri wfun funres ssv ssdif cz bitsf difpreima bitsf1
          ffun wf1 snssi f1imacnv mp2an cfv wfn ffn fnsnfv 0bits sneqi eqtr3i
          0z imaeq2i difeq2i 3sstr4i sspreima syl5eqss syl2anc jca cnveq eleq1d
          imaeq1d elrab2 ) DHGULUMZUNDQUOZUPZUQURZUSULZQUTVAZUMZUUNVBZVCVGVDZVE
          ZVFZUSUMZVHUUNPUMUULUURUVCUULQUUPUUNVIZUURUULUQUUPUNUQUOZVIZQUQUUMVIZ
          UVDUQUUPUVEVJUVFVKUQUUPUVEVLVMUULVSUQDVIZQVSVNUVGUULDUQVSUTVAUMZUVHUU
          LUVIDVBZVSVFZUSUMZUVKQVNZUULUVIUVLUVMVOABCDEFGHIJKLNPQRSTUAUBUCUDUEUF
          UGUHUIUJVPVQZVRUQVSDVTWAWBWCZQWDCWEWFWGWHZCVSWLVSUEUVPCVSWIWJZVSUQQDW
          KWMQUQUUPUNUUMWNWOUUPQUUNUUOUSUQVTWPWQQVSWAUVQWRWBWSUULUUMVBZVCXDVDZV
          EZVFZUSUMZUVBUWAVNUVCUULUVJUVTVFZUSUMZUWBUULUWDUVLUULUVIUVLUVMUVNWTUU
          LUVHUWCUVKXAUWDUVLXBUVOVSUQVSDXDXCXEUWCUVKUSXFXGXHUWDUWAUWCVNZUWBUUMD
          VNUVRUVJVNUWEDQXIUUMDXJUVRUVJUVTXKXLUWCUWAXMXNXPUULUVBUVRUNVBZUVAVFZV
          FZUWAUVBUVRUWFUPZUVAVFUWHUUSUWIUVAUNUUMXQXOUVRUWFUVAXRXSUULUUMXTZUWGU
          VTVNUWHUWAVNUULUVHDXTUWJUVOVSUQDYHQDYAXGUWFVCVFZUWFUUTVFZVEZVCUWLVEZU
          WGUVTUWKVCVNUWMUWNVNUWKYBUWKVCUWLYCVMUNXTZUWGUWMXAYDUUOUNVIZUWOYEYDUU
          OUNYHVMVCUUTUNYFVMUVSUWLVCUWFUNUVSVFZVFZUVSUWLYDUUOUNYIUVSYDVNZUWRUVS
          XAYGXDYDUMZUWSYTXDYDYJVMYDUUOUVSUNYKYLUWQUUTUWFXDUNYMZVDZUWQUUTUNYDYN
          ZUWTUXBUWQXAUWPUXCYEYDUUOUNYOVMYTYDXDUNYPYLUXAVGYQYRYSUUAYSUUBUUCUWGU
          VTUUMUUDWMUUEUWAUVBXMUUFUUGUAWEZVBZUVAVFZUSUMUVCUAUUNUUQPUXDUUNXAZUXF
          UVBUSUXGUXEUUSUVAUXDUUNUUHUUJUUIUGUUKWS $.

        $d t n w x y A $.  $d n t x y B $.  $d n t x y F $.  $d t w x y J $.
        $d r H $.  $d n t x y M $.  $d n r t w x y R $.  $d n r t w x y T $.
        $( Lemma for ~ eulerpart : value of the function ` G ` evaluated
           (Contributed by Thierry Arnoux, 10-Aug-2018.) $)
        eulerpartlemgvv $p |- ( ( A e. ( T i^i R ) /\ B e. NN )
          -> ( ( G ` A ) ` B ) = if ( E. t e. NN E. n e. ( bits ` ( A ` t ) )
          ( ( 2 ^ n ) x. t ) = B , 1 , 0 ) ) $=
          ( vw cin wcel cn wa cfv cbits cima c1 cc0 cif c2 cv cexp co cmul wceq
          wrex adantr cvv wss nnex a1i cn0 wf1o wf f1of mp2b simpr wfn wb ax-mp
          ffn cfn syl nfv nfre1 nfan cop eleq2d opabbidv adantl cdivides wbr wn
          copab simpl eleq1d fveq2d syl6eq wfun sylib 3syl biimpar fvco syl2anc
          wex fvres eqtrd syl6bb df-rex exbii bitrd biimpa adantlr wi fveq2 imp
          ex reximdva eqeq2 rexbidv mpbid r19.29af simplr oveq2 eqeq12d imbi12d
          vex oveq1d chvar eqeq1d c0 wral breq2 notbid elrab2 cres ccom imassrn
          eulerpartlemgv fveq1d crn cxp oddpwdc frn sstri indfval syl3anc inss1
          cind cpw eulerpartlemmf eulerpartlem1 ffvelrni sseldi elpwid fvelimab
          sylancr cmpt fveq1 anbi2d crab ssrab2 eqsstri ssexi cab abid2 eqeltri
          fvex opabex3 fvmptd eleq12d anbi12d cbvopabv cmap ccnv eulerpartlemt0
          cdm w3a biimpi simp1d nn0ex elmap ffun funres fssres sylancl pm5.32da
          fdm elopab ancom anass bitri 2exbii anbi2i 19.42v bitr4i bitsss sseli
          3bitr4i anim2i ad2antlr opelxp c2nd c1st oddpwdcv op2nd op1st oveq12i
          oveq2i sylbir eqtr2d anassrs ssrexv adantllr simp-5l simpllr eleqtrrd
          mpd opabid syl12anc ad4antr sseldd opeq1 opeq2 sylan2 rspcev sylan9bb
          cbvrexdva2 cbvrexv n0i 0bits con3i ffvelrn sylan elnn0 orcomd orcanai
          mpdan simp3bi sselda simprbi ralrimiva elpreima imbi1d impexp cbvralv
          ralbidv2 sylibr r19.21bi syldan sylanbrc adantlrr simprr jca reximdv2
          wo r19.29_2a impbida ifbid 3eqtrd ) EJIUOUPZFUQUPZURZFEQUSZUSZFPUTESU
          UAZUUBZTUSZVAZUQUUNUSUSZUSZFVVNUPZVBVCVDZVENVFZVGVHZDVFZVIVHZFVJZNVWA
          EUSZUTUSZVKZDUQVKZVBVCVDVVFVVJVVPVJVVGVVFFVVIVVOABCEGHIJKLMNOPQRSTUAU
          BUCUDUEUFUGUHUIUJUKULUMUUDUUEVLVVHUQVMUPZVVNUQVNZVVGVVPVVRVJVWHVVHVOV
          PVWIVVHVVNPUUFZUQPVVMUUCSVQUUGZUQPVRZVWKUQPVSZVWJUQVNABCPSUGUHUUHZVWK
          UQPVTZVWKUQPUUIWAUUJVPVVFVVGWBVVNUQVMFUUKUULVVHVVQVWGVBVCVVHVVQUNVFZP
          USZFVJZUNVVMVKZVWGVVHPVWKWCZVVMVWKVNZVVQVWSWDVWLVWMVWTVWNVWOVWKUQPWFW
          AVVHVVMVWKVVFVVMVWKUUOZUPVVGVVFVXBWGUOZVXBVVMVXBWGUUMVVFVVLRUPVVMVXCU
          PABCEGHIJKLMNOPQRSTUAUBUCUDUEUFUGUHUIUJUKULUMUUPZRVXCVVLTRVXCTVRRVXCT
          VSABCGHKLMNPRSTUAUBUCUDUEUFUGUHUIUJUUQRVXCTVTWEUURWHUUSVLUUTZUNVWKVVM
          FPUVAUVBVVHVWSVWGVVHVWSURVWRVWGUNVVMVVHVWSUNVVHUNWIVWRUNVVMWJWKVVHVWP
          VVMUPZVWRVWGVWSVVHVXFURZVWRURZVWBVWQVJZNVWEVKZDUQVKZVWGVXGVXKVWRVXGVX
          JDSVKZVXKVXGVWPVWAVVSWLZVJZNVWEVKZDSVKZVXLVVFVXFVXPVVGVVFVXFVXPVVFVXF
          VWPVWASUPZVVSVWAVVLUSZUPZURZDNWSZUPZVXPVVFVVMVYAVWPVVFVVMAVFZSUPZBVFZ
          VYCVVLUSZUPZURZABWSZVYAVVFUCVVLVYDVYEVYCUCVFZUSZUPZURZABWSZVYIRTVMTUC
          RVYNUVCVJVVFUJVPVYJVVLVJZVYNVYIVJVVFVYOVYMVYHABVYOVYLVYGVYDVYOVYKVYFV
          YEVYCVYJVVLUVDWMUVEWNWOVXDVYIVMUPVVFVYGABSSUQVOSVECVFZWPWQZWRZCUQUVFU
          QUGVYRCUQUVGUVHZUVIVYGBUVJZVMUPVYDVYTVYFVMBVYFUVKVYCVVLUVMUVLVPUVNVPU
          VOZVYHVXTABDNVYCVWAVJZVYEVVSVJZURZVYDVXQVYGVXSWUDVYCVWASWUBWUCWTZXAWU
          DVYEVVSVYFVXRWUBWUCWBWUDVYCVWAVVLWUEXBUVPUVQUVRXCWMVVFVYBVXNVXQVVSVWE
          UPZURZURZNXJDXJZVXPVVFVYBVWPWUGDNWSZUPWUIVVFVYAWUJVWPVVFVXTWUGDNVVFVX
          QVXSWUFVVFVXQURZVXRVWEVVSWUKVXRVWAVVKUSZUTUSZVWEWUKVVKXDZVWAVVKUWBZUP
          ZVXRWUMVJVVFWUNVXQVVFUQVQEVSZEXDWUNVVFEVQUQUVSVHUPZWUQVVFWUREUVTUQVAZ
          WGUPZWUSSVNZVVFWURWUTWVAUWCABCEGHIJKLMNPRSTUAUBUCUDUEUFUGUHUIUJUKULUW
          AZUWDUWEVQUQEUWFVOUWGXEZUQVQEUWHSEUWIXFZVLVVFWUPVXQVVFSVQVVKVSZWUPVXQ
          WDVVFWUQSUQVNZWVEWVCVYSUQVQSEUWJUWKZWVEWUOSVWASVQVVKUWMZWMWHXGVWAUTVV
          KXHXIVXQWUMVWEVJVVFVXQWULVWDUTVWASEXKXBWOXLWMUWLWNWMWUGDNVWPUWNXMWUIV
          XQWUFVXNURZURZNXJZDXJZVXPWUHWVJDNWUHWUGVXNURWVJVXNWUGUWOVXQWUFVXNUWPU
          WQUWRVXQVXOURZDXJVXQWVINXJZURZDXJVXPWVLWVMWVODVXOWVNVXQVXNNVWEXNUWSXO
          VXODSXNWVKWVODVXQWVINUWTXOUXDUXAXMXPXQXRVXGVXOVXJDSVXGVXQURVXNVXINVWE
          VXGVXQWUFVXNVXIXSVXGWUGURZVXNVXIWVPVXNURZVWQVXMPUSZVWBWVPVXNVWQWVRVJZ
          VXNWVSXSWVPVWPVXMPXTVPYAWVQVXQVVSVQUPZURZWVRVWBVJZWUGWWAVXGVXNWUFWVTV
          XQVWEVQVVSVWDUXBUXCUXEUXFWWAVXMVWKUPZWWBVWAVVSSVQUXGWWCWVRVEVXMUXHUSZ
          VGVHZVXMUXIUSZVIVHVWBABCPSVXMUGUHUXJWWEVVTWWFVWAVIWWDVVSVEVGVWAVVSDYL
          ZNYLZUXKUXNVWAVVSWWGWWHUXLUXMXCZUXOWHUXPYBUXQYCYCUYCWVFVXLVXKXSVYSVXJ
          DSUQUXRWEWHVLVXHVXJVWFDUQVWRVXJVWFWDVXGVWRVXIVWCNVWEVWQFVWBYDYEWOYEYF
          UXSVVHVWSWBYGVVHVWGURZVEVYEVGVHZVYCVIVHZFVJZVWSABSVYCEUSZUTUSZWWJVYDU
          RZVYEWWOUPZURZWWMURZVYCVYEWLZVVMUPZWWTPUSZFVJZVWSWWSVVFVYDVYGWXAVVFVV
          GVWGVYDWWQWWMUXTZWWJVYDWWQWWMUYAZWWSVYEWWOVYFWWPWWQWWMYHWWSVVFVYDVYFW
          WOVJWXDWXEVVFVYDURZVYFVYCVVKUSZUTUSZWWOWXFWUNVYCWUOUPZVYFWXHVJVVFWUNV
          YDWVDVLVVFWXIVYDVVFWVEWXIVYDWDWVGWVEWUOSVYCWVHWMWHXGVYCUTVVKXHXIVYDWX
          HWWOVJVVFVYDWXGWWNUTVYCSEXKXBWOXLXIUYBVVFWXAVYHVVFWXAWWTVYIUPVYHVVFVV
          MVYIWWTWUAWMVYHABUYDXMXGUYEZWWSWWMWWTVWKUPZWXCWWRWWMWBWWSVVMVWKWWTVVH
          VXAVWGVYDWWQWWMVXEUYFWXJUYGWXKWWMWXBWWLVJZWXCVWAVYEWLZVWKUPZWXMPUSZWW
          KVWAVIVHZVJZXSZWXKWXLXSZDAWXSDWIVWAVYCVJZWXNWXKWXQWXLWXTWXMWWTVWKVWAV
          YCVYEUYHZXAWXTWXOWXBWXPWWLWXTWXMWWTPWYAXBVWAVYCWWKVIYIYJYKWWCWWBXSWXR
          NBWXRNWIVVSVYEVJZWWCWXNWWBWXQWYBVXMWXMVWKVVSVYEVWAUYIZXAWYBWVRWXOVWBW
          XPWYBVXMWXMPWYCXBWYBVVTWWKVWAVIVVSVYEVEVGYIZYMYJYKWWIYNYNWWMWXLWXCWWL
          FWXBYDXQUYJXIVWRWXCUNWWTVVMVWPWWTVJVWQWXBFVWPWWTPXTYOUYKXIVVHVWGWWMBW
          WOVKZAUQVKZWYEASVKZWWJVWGWYFVVHVWGWBVWFWYEDAUQWXTVWCWWMNBVWEWWOWXTVWC
          VVTVYCVIVHZFVJWYBWWMWXTVWBWYHFVWAVYCVVTVIYIYOWYBWYHWWLFWYBVVTWWKVYCVI
          WYDYMYOUYLWXTWYBURZVWDWWNUTWYIVWAVYCEWXTWYBWTXBXBUYMUYNXEVVFWYFWYGVVG
          VVFWYFWYGVVFWYEWYEAUQSVVFVYCUQUPZWYEURZVYDWYEURVVFWYKURZVYDWYEWYLWWMV
          YDBWWOVVFWYKBVVFBWIWYJWYEBWYJBWIWWMBWWOWJWKWKWYLWWQURVYDWWMVVFWYJWWQV
          YDWYEVVFWYJURZWWQURZWYJVEVYCWPWQZWRZVYDVVFWYJWWQYHWYMWWQWWNUQUPZWYPWY
          NWWNVCVJZWRZWYQWYNWWOYPVJZWRZWYSWWQXUAWYMWWOVYEUYOWOWYRWYTWYRWWOVCUTU
          SYPWWNVCUTXTUYPXCUYQWHWYNWYRWYQWYNWYQWYRWYNWWNVQUPZWYQWYRVVAWYMXUBWWQ
          VVFWUQWYJXUBWVCUQVQVYCEUYRUYSVLWWNUYTXEVUAVUBVUCWYMWYQWYPVVFWYQWYPXSZ
          AUQVVFVVSEUSZUQUPZVEVVSWPWQZWRZXSZNUQYQZXUCAUQYQVVFXUGNWUSYQXUIVVFXUG
          NWUSVVFVVSWUSUPZURVVSSUPZXUGVVFWUSSVVSVVFWURWUTWVAWVBVUDVUEXUKVVSUQUP
          ZXUGVYRXUGCVVSUQSVYPVVSVJVYQXUFVYPVVSVEWPYRYSUGYTVUFWHVUGVVFXUGXUHNWU
          SUQVVFXUJXUGXSXULXUEURZXUGXSXULXUHXSVVFXUJXUMXUGVVFWUQEUQWCXUJXUMWDWV
          CUQVQEWFUQVVSUQEVUHXFVUIXULXUEXUGVUJXMVULYFXUCXUHANUQVYCVVSVJZWYQXUEW
          YPXUGXUNWWNXUDUQVYCVVSEXTXAXUNWYOXUFVYCVVSVEWPYRYSYKVUKVUMVUNYAVUOVYR
          WYPCVYCUQSVYPVYCVJVYQWYOVYPVYCVEWPYRYSUGYTVUPVUQVLVVFWYJWYEVURZYGXUOV
          USYBVUTYAXRVUOVVBVVCXPVVDVVE $.
      $}

      ${
        $d t z $.  $d f g k n t w A $.  $d f n t w J $.  $d f k n t w N $.
        $d n t w O $.  $d g k P $.  $d f k n t w R $.  $d n t w T $.
        eulerpartlemgh.1 $e |- U = U_ t e. ( ( `' A " NN ) i^i J )
                                     ( { t } X. ( bits ` ( A ` t ) ) ) $.
        $( Lemma for ~ eulerpart : Rewriting the ` U ` set for an odd partition
           Note that interestingly, this proof reuses ~ marypha2lem2 .
           (Contributed by Thierry Arnoux, 10-Aug-2018.) $)
        eulerpartlemgu $p |- ( A e. ( T i^i R ) -> U = { <. t , n >. |
          ( t e. ( ( `' A " NN ) i^i J ) /\ n e. ( ( bits o. A ) ` t ) ) } ) $=
          ( cin wcel ccnv cn cima cv csn cfv cbits cxp ciun ccom copab wfun cdm
          wa wceq cn0 wf cmap co cfn wss eulerpartlemt0 simp1bi elmapi syl ffun
          adantr inss1 cnvimass syl5sseq syl5ss sselda wb eleq2d mpbird syl2anc
          fdm fvco xpeq2d iuneq2dv eqid marypha2lem2 a1i eqtr3d syl5eq ) EIHUOU
          PZJDEUQURUSZSUOZDUTZVAZXEEVBVCVBZVDZVEZXEXDUPZNUTXEVCEVFZVBZUPVJDNVGZ
          UNXBDXDXFXLVDZVEZXIXMXBDXDXNXHXBXJVJZXLXGXFXPEVHZXEEVIZUPZXLXGVKXPURV
          LEVMZXQXBXTXJXBEVLURVNVOUPZXTXBYAXCVPUPXCSVQABCEFGHIKLMNPRSTUAUBUCUDU
          EUFUGUHUIUJUKULVRVSEVLURVTWAZWCURVLEWBWAXPXSXEURUPZXBXDURXEXBXDXCURXC
          SWDXBXRXCUREURWEXBXTXRURVKYBURVLEWMWAZWFWGWHXBXSYCWIXJXBXRURXEYDWJWCW
          KXEVCEWNWLWOWPXOXMVKXBDNXDXOXKXOWQWRWSWTXA $.

        $d t x y z $.  $d f g k m n p t x A $.  $d n p t x F $.
        $d f n t x y w J $.  $d f k n t w N $.  $d n p t w O $.  $d g k t P $.
        $d n p t R $.  $d n p t N $.  $d p U $.  $d p T $.
        $( Lemma for ~ eulerpart : The ` F ` function is a bijection on the
           ` U ` subsets.  (Contributed by Thierry Arnoux, 15-Aug-2018.) $)
        eulerpartlemgh $p |- ( A e. ( T i^i R ) ->
          ( F |` U ) : U -1-1-onto-> { m e. NN |
          E. t e. NN E. n e. ( bits ` ( A ` t ) ) ( ( 2 ^ n ) x. t ) = m } ) $=
          ( vp cin wcel cima cres wf1o c2 cv cexp cmul wceq cfv cbits wrex crab
          co cn0 cxp wf1 wss oddpwdc f1of1 ax-mp ccnv csn ciun wral inss2 sseli
          cn vex snss sylib bitsss xpss12 sylancl rgen iunss mpbir f1ores mp2an
          eqsstri wb wa 2nn adantl nnexpcld simplr nnmulcld adantr simpr eleq1d
          a1i mpbid exp31 rexlimdv rexlimdva pm4.71rd wn c0 rex0 cc0 wo wi cmap
          wf wfn cfn eulerpartlemt0 simp1bi elmapi ad2antrr notbid fveq2d 0bits
          syl ffn imp syl6eq rexeqdv mpbiri ex con4d anasss rexbidv 3syl sylibr
          elpreima imnan mpd ffvelrnd elnn0 syl2anc cdif eulerpartlemf sylan2br
          orel1 eldif anassrs elin sylanbrc simprr jca reximdv2 cdivides ssrab2
          wbr sstri ssrexv impbid bitr3d eqeq2 elrab imaeq2i imaiun eqtri eliun
          eleq2i f1ofn biimpi ovelimab sylancr oveq1 eqeq2d rexsn syl6bb eqeq1i
          cop df-ov eqcom bitr3i opelxpi c2nd c1st oddpwdcv op2nd op1st oveq12i
          oveq2i eqeq1d syl5bbr sylan2 rexbidva bitrd 3bitri eqrdv f1oeq3 mpbii
          rexbiia 3bitr4rd ) EIHUQURZJQJUSZQJUTZVAZJVBOVCZVDVKZDVCZVEVKZNVCZVFZ
          OUXLEVGZVHVGZVIZDWEVIZNWEVJZUXHVAZTVLVMZWEQVNZJUYBVOUXIUYBWEQVAZUYCAB
          CQTUHUIVPZUYBWEQVQVRJDEVSWEUSZTUQZUXLVTZUXQVMZWAZUYBUOUYJUYBVOUYIUYBV
          OZDUYGWBUYKDUYGUXLUYGURZUYHTVOZUXQVLVOZUYKUYLUXLTURZUYMUYGTUXLUYFTWCZ
          WDZUXLTDWFZWGZWHUXPWIZUYHTUXQVLWJZWKWLDUYGUYIUYBWMWNWQUYBWEJQWOWPUXFU
          XGUXTVFUXIUYAWRUXFUPUXGUXTUXFUPVCZWEURZUXMVUBVFZOUXQVIZDWEVIZWSZVUEDU
          YGVIZVUBUXTURZVUBUXGURZUXFVUFVUGVUHUXFVUFVUCUXFVUEVUCDWEUXFUXLWEURZWS
          ZVUDVUCOUXQVULUXJUXQURZVUDVUCVULVUMWSZVUDWSZUXMWEURZVUCVUNVUPVUDVUNUX
          KUXLVUNVBUXJVBWEURVUNWTXHVUMUXJVLURZVULUXQVLUXJUYTWDZXAXBUXFVUKVUMXCX
          DXEVUOUXMVUBWEVUNVUDXFXGXIXJXKXLXMUXFVUFVUHUXFVUEVUEDWEUYGUXFVUKVUEWS
          ZUYLVUEWSUXFVUSWSZUYLVUEVUTUXLUYFURZUYOUYLUXFVUKVUEVVAVULVUEVVAVULVVA
          VUEVULVVAXNZVUEXNZVULVVBWSZVVCVUDOXOVIZXNZVUDOXPZVVDVUEVVEVVDVUDOUXQX
          OVVDUXQXQVHVGZXOVVDUXPXQVHVVDUXPWEURZXNZVVIUXPXQVFZXRZVVKVVDVUKVVJUXF
          VUKVVBXCZVVDVUKVVIWSZXNZVUKVVJXSVVDVVBVVOVULVVBXFVVDVVAVVNVVDWEVLEYAZ
          EWEYBVVAVVNWRUXFVVPVUKVVBUXFEVLWEXTVKURZVVPUXFVVQUYFYCURUYFTVOABCEFGH
          IKLMOQSTUAUBUCUDUEUFUGUHUIUJUKULUMYDYEEVLWEYFYKYGZWEVLEYLWEUXLWEEUUCU
          UAYHXIVUKVVIUUDUUBUUEVVDUXPVLURVVLVVDWEVLUXLEVVRVVMUUFUXPUUGWHVVJVVLV
          VKVVIVVKUULYMUUHYIYJYNYOYHYPYQYRYMYSUXFVUKVUEUYOVULVUEUYOVULUYOVUEVUL
          UYOXNZVVCVULVVSWSZVVCVVFVVGVVTVUEVVEVVTVUDOUXQXOVVTUXQVVHXOVVTUXPXQVH
          UXFVUKVVSVVKVUKVVSWSUXFUXLWETUUIURVVKUXLWETUUMABCDEFGHIKLMOQSTUAUBUCU
          DUEUFUGUHUIUJUKULUMUUJUUKUUNYIYJYNYOYHYPYQYRYMYSUXLUYFTUUOUUPUXFVUKVU
          EUUQUURYQUUSVUHVUFXSZUXFUYGWEVOVWAUYGTWEUYPTVBCVCUUTUVBXNZCWEVJWEUHVW
          BCWEUVAWQUVCVUEDUYGWEUVDVRXHUVEUVFVUIVUGWRUXFUXSVUFNVUBWEUXNVUBVFZUXR
          VUEDWEVWCUXOVUDOUXQUXNVUBUXMUVGYTYTUVHXHVUJVUHWRUXFVUJVUBDUYGQUYIUSZW
          AZURVUBVWDURZDUYGVIVUHUXGVWEVUBUXGQUYJUSVWEJUYJQUOUVIDQUYGUYIUVJUVKUV
          MDVUBUYGVWDUVLVWFVUEDUYGUYLUYOVWFVUEWRUYQUYOVWFVUBUXLUXJQVKZVFZOUXQVI
          ZVUEUYOVWFVUBAVCZUXJQVKZVFZOUXQVIZAUYHVIZVWIUYOQUYBYBZUYKVWFVWNWRUYDV
          WOUYEUYBWEQUVNVRUYOUYMUYNUYKUYOUYMUYSUVOUYTVUAWKAOUYBUYHUXQVUBQUVPUVQ
          VWMVWIAUXLUYRVWJUXLVFZVWLVWHOUXQVWPVWKVWGVUBVWJUXLUXJQUVRUVSYTUVTUWAU
          YOVWHVUDOUXQVUMUYOVUQVWHVUDWRVURVWHUXLUXJUWCZQVGZVUBVFZUYOVUQWSZVUDVW
          SVWGVUBVFVWHVWGVWRVUBUXLUXJQUWDUWBVWGVUBUWEUWFVWTVWRUXMVUBVWTVWQUYBUR
          ZVWRUXMVFUXLUXJTVLUWGVXAVWRVBVWQUWHVGZVDVKZVWQUWIVGZVEVKUXMABCQTVWQUH
          UIUWJVXCUXKVXDUXLVEVXBUXJVBVDUXLUXJUYROWFZUWKUWNUXLUXJUYRVXEUWLUWMYNY
          KUWOUWPUWQUWRUWSYKUXDUWTXHUXEUXAUXGUXTJUXHUXBYKUXC $.
      $}

      ${
        $d f g k n o x y z $.  $d f o r A $.  $d o F $.  $d o r H $.
        $d f n o r x y J $.  $d o r M $.  $d f g x N $.  $d g n P $.
        $d f o R $.   $d f o T $.
        $( Lemma for ~ eulerpart : Images under ` G ` have finite support.
           (Contributed by Thierry Arnoux, 29-Aug-2018.) $)
        eulerpartlemgf $p |- ( A e. ( T i^i R ) ->
          ( `' ( G ` A ) " NN ) e. Fin ) $=
          ( cin wcel cfv ccnv c1 csn cima cfn cn cbits cres ccom eulerpartlemgv
          wss cind cnveqd imaeq1d cvv wceq nnex crn imassrn cn0 wf1o wf oddpwdc
          cxp f1of frn mp2b sstri indpi1 mp2an cpw eulerpartlemmf eulerpartlem1
          syl6eq inss2 ax-mp ffvelrni syl wfun ffun imafi mpan eqeltrd cc0 cdif
          sseldi cpr cmap eulerpartgbij elin simplbi elmapi 3syl ssv dfn2 ssdif
          co syl5eqss sspreima sylancl wne ax-1ne0 necomi difprsn1 ffs2 sseqtrd
          eqcomi ssfi syl2anc ) DHGULZUMZDOUNZUOZUPUQZURZUSUMYGUTURZYIVEYJUSUMY
          EYINVADQVBVCZRUNZURZUSYEYIYMUTVFUNUNZUOZYHURZYMYEYGYOYHYEYFYNABCDEFGH
          IJKLMNOPQRSTUAUBUCUDUEUFUGUHUIUJUKVDVGVHUTVIUMYMUTVEYPYMVJVKYMNVLZUTN
          YLVMQVNVRZUTNVOZYRUTNVPZYQUTVEABCNQUEUFVQZYRUTNVSZYRUTNVTWAWBYMUTVIWC
          WDWHYEYLUSUMZYMUSUMZYEYRWEZUSULZUSYLUUEUSWIYEYKPUMYLUUFUMABCDEFGHIJKL
          MNOPQRSTUAUBUCUDUEUFUGUHUIUJUKWFPUUFYKRPUUFRVOPUUFRVPABCEFIJKLNPQRSTU
          AUBUCUDUEUFUGUHWGPUUFRVSWJWKWLWTNWMZUUCUUDYSYTUUGUUAUUBYRUTNWNWANYLWO
          WPWLWQYEYJYGVIWRUQZWSZURZYIYEYFWMZUTUUIVEZYJUUJVEYEUTWRUPXAZYFVPZUUKY
          EYFUUMUTXBXKZGULZUMZYFUUOUMZUUNYDUUPDOYDUUPOVOYDUUPOVPABCEFGHIJKLMNOP
          QRSTUAUBUCUDUEUFUGUHUIUJUKXCYDUUPOVSWJWKUUQUURYFGUMYFUUOGXDXEYFUUMUTX
          FXGZUTUUMYFWNWLVNVIVEZUULVNXHUUTUTVNUUHWSUUIXIVNVIUUHXJXLWJUTUUIYFXMX
          NYEUUNUUJYIVJUUSUTUUMYHYFWRUUMUUHWSZYHWRUPXOUVAYHVJUPWRXPXQWRUPXRWJYA
          XSWLXTYIYJYBYC $.
      $}

      $( ` S ` recovers the sum of a partition. $)
      eulerpart.s $e |- S = ( f e. ( ( NN0 ^m NN ) i^i R )
        |-> sum_ k e. NN ( ( f ` k ) x. k ) ) $.

      ${
        $d f g k n o t x y z $.  $d f g k m n o r t w x y A $.  $d f k G $.
        $d n o t w x y F $.  $d o r H $.  $d f n o r t w x y J $.
        $d n o r t x y M $.  $d f g k n t x N $.  $d n r t x y O $.
        $d g k n t P $.  $d f k n o r t x y R $.  $d w x y R $.
        $d f k n o r t w x y T $.
        $( Lemma for ~ eulerpart : The ` G ` function also preserves partition
           sums. (Contributed by Thierry Arnoux, 10-Sep-2017.) $)
        eulerpartlemgs2 $p |- ( A e. ( T i^i R )
          -> ( S ` ( G ` A ) ) = ( S ` A ) ) $=
          ( vt vw vm cin wcel cfv ccnv cn cima cv cmul co csu c2 cexp wceq wrex
          cbits c1 cc0 cif csn cxp ciun c2nd c1st cdm cnvimass cpr cmap wf wf1o
          wa eulerpartgbij f1of ax-mp ffvelrni sylib simpld elmapi fdm syl5sseq
          elin 3syl sselda eulerpartlemgvv oveq1d syldan sumeq2dv eqeq2 rexbidv
          crab elrab simprbi iftrue syl cc nnsscn simplbi sseldi mulid2 sumeq2i
          eqtrd id cfn wss adantl jca ssfi syl2anc cvv wral cn0 inss2 simpr a1i
          sylibr mp2an mulcld eqtr3d adantr inss1 oveq12d sseli eulerpartlemsv2
          wn vex cres cen wbr eulerpartlemgf 1nn syl6eqel wb simpl wfn elpreima
          ffn mpbird ex eqid eulerpartlemgh cnvexg imaexg inex1g snex fvex xpex
          ssrdv rgenw iunexg f1oeng sylan mpdan enfii fvres snssd bitsss xpss12
          sylancl ralrimiva oddpwdcv fsumf1o syl5eq ax-1cn 0cn ifcl ssrab2 cdif
          iunss eldifbd ssdifssd notbii bitr4i biimpi imp iffalse syl6ss mul02d
          imnan fsumss eulerpartlemt0 simp1bi sseldd ffvelrnd bitsfi 2cn simprr
          wi expcl anassrs fsummulc1 bitsinv1 op2ndd oveq2d op1std cnveq eleq1d
          cop imaeq1d elab2g mpbid adantrr fsum2d 3eqtr3d sseq1d elrab2 sumeq1d
          df-ss 3eqtr2d fveq2 cbvsumv syl6eqr 0nn0 1nn0 prssi mpan2 nn0ex elmap
          fss nnex biimpri anim1i 3imtr4i 3eqtr4d ) DIGUQZURZDPUSZUTVAVBZLVCZVU
          AUSZVUCVDVEZLVFZDUTZVAVBZVUCDUSZVUCVDVEZLVFZVUAHUSZDHUSZUYTVUFVUHUNVC
          ZDUSZVUNVDVEZUNVFZVUKUYTVUFVUBVGMVCZVHVEZVUNVDVEZVUCVIZMVUOVKUSZVJZUN
          VAVJZVLVMVNZVUCVDVEZLVFZUNVUHRUQZVUNVOZVVBVPZVQZVGUOVCZVRUSZVHVEZVVLV
          SUSZVDVEZUOVFZVUQUYTVUBVUEVVFLUYTVUCVUBURZVUCVAURZVUEVVFVIUYTVUBVAVUC
          UYTVUAVTZVUBVAVUAVAWAUYTVUAVMVLWBZVAWCVEZURZVAVWAVUAWDZVVTVAVIUYTVWCV
          UAGURZUYTVUAVWBGUQZURZVWCVWEWFZUYSVWFDPUYSVWFPWEUYSVWFPWDABCEFGIJKLMN
          OPQRSTUAUBUCUDUEUFUGUHUIUJUKULWGUYSVWFPWHWIWJZVUAVWBGWPZWKWLZVUAVWAVA
          WMZVAVWAVUAWNWQWOZWRUYTVVSWFVUDVVEVUCVDABCUNDVUCEFGIJKLMNOPQRSTUAUBUC
          UDUEUFUGUHUIUJUKULWSZWTXAXBUYTVUTUPVCZVIZMVVBVJZUNVAVJZUPVAXEZVVFLVFZ
          VVQVVGUYTVWTVWSVUCLVFVVQVWSVVFVUCLVUCVWSURZVVFVLVUCVDVEZVUCVXAVVEVLVU
          CVDVXAVVDVVEVLVIZVXAVVSVVDVWRVVDUPVUCVAVWOVUCVIZVWQVVCUNVAVXDVWPVVAMV
          VBVWOVUCVUTXCXDXDXFZXGZVVDVLVMXHZXIWTVXAVUCXJURVXBVUCVIVXAVAXJVUCXKVX
          AVVSVVDVXEXLZXMVUCXNXIXPXOUYTVWSVUCVVKVVPLUOOVVKUUAZVVPVUCVVPVIXQUYTV
          WSXRURZVVKVWSUUBUUCZVVKXRURUYTVUBXRURVWSVUBXSVXJABCDEFGIJKLMNOPQRSTUA
          UBUCUDUEUFUGUHUIUJUKULUUDZUYTLVWSVUBUYTVXAVVRUYTVXAWFZVVRVVSVUDVAURZW
          FZVXMVVSVXNVXAVVSUYTVXHXTZVXMVUDVLVAVXMVUDVVEVLUYTVXAVVSVUDVVEVIVXPVW
          NXAVXMVVDVXCVXAVVDUYTVXFXTVXGXIXPUUEUUFYAVXMUYTVVRVXOUUGZUYTVXAUUHUYT
          VWDVUAVAUUIVXQUYTVWCVWDVWKVWLXIVAVWAVUAUUKVAVUCVAVUAUUJWQXIUULUUMUVBZ
          VUBVWSYBYCUYTVVKVWSVXIWEZVXKABCUNDEFGIVVKJKLUPMNOPQRSTUAUBUCUDUEUFUGU
          HUIUJUKULVVKUUNUUOZUYTVVKYDURZVXSVXKUYTVVHYDURZVVJYDURZUNVVHYEVYAUYTV
          UGYDURVUHYDURVYBDUYSUUPVUGVAYDUUQVUHRYDUURWQVYCUNVVHVVIVVBVUNUUSVUOVK
          UUTUVAUVCUNVVHVVJYDYDUVDUVMVVKVWSYDVXIUVEUVFUVGVVKVWSUVHYCVXTUYTVVLVV
          KURZWFZVVLVXIUSZVVLOUSZVVPVYDVYFVYGVIUYTVVLVVKOUVIXTVYEVVLRYFVPZURVYG
          VVPVIUYTVVKVYHVVLUYTVVJVYHXSZUNVVHYEVVKVYHXSUYTVYIUNVVHUYTVUNVVHURZWF
          ZVVIRXSVVBYFXSZVYIVYKVUNRVYKVVHRVUNVUHRYGUYTVYJYHZXMUVJVYLVYKVUOUVKZY
          IVVIRVVBYFUVLYCUVNUNVVHVVJVYHUWCYJWRABCORVVLUFUGUVOXIXPVXMVAXJVUCXKVX
          PXMUVPUVQUYTVWSVUBVVFLVXRVXMVVEVUCVVEXJURZVXMVLXJURVMXJURVYOUVRUVSVVD
          VLVMXJUVTYKYIVXMVAXJVUCXKVXMVWSVAVUCVWRUPVAUWAUYTVXAYHXMXMYLUYTVUCVUB
          VWSUWBZURZWFZVVFVMVUCVDVEVMVYRVVEVMVUCVDVYRVVDYSZVVEVMVIVYRVXAYSZVVSV
          YSVYRVUCVUBVWSUYTVYQYHUWDUYTVYPVAVUCUYTVUBVAVWSVWMUWEZWRVYTVVSVYSVYTV
          VSVYSUXBZVYTVVSVVDWFZYSWUBVXAWUCVXEUWFVVSVVDUWMUWGUWHUWIYCVVDVLVMUWJX
          IWTVYRVUCUYTVYPXJVUCUYTVYPVAXJWUAXKUWKWRUWLXPVXLUWNYMUYTVVHVUPUNVFZVV
          QVUQUYTVVHVVBVUSMVFZVUNVDVEZUNVFVVHVVBVUTMVFZUNVFWUDVVQUYTVVHWUFWUGUN
          VYKVVBVUSVUNMVYKVUOYFURZVVBXRURVYKVAYFVUNDUYTVAYFDWDZVYJUYTDYFVAWCVEZ
          URZWUIUYTWUKVUHXRURZVUHRXSZABCDEFGIJKLMOQRSTUAUBUCUDUEUFUGUHUIUJUKUWO
          UWPZDYFVAWMXIZYNVYKVUHVAVUNUYTVUHVAXSVYJUYTDVTZVUHVADVAWAUYTWUIWUPVAV
          IWUOVAYFDWNXIWOYNVYKVVHVUHVUNVUHRYOZVYMXMUWQZUWRZVUOUWSXIZVYKVAXJVUNX
          KWURXMZUYTVYJVURVVBURZVUSXJURZUYTVYJWVBWFWFZVGXJURZVURYFURWVCWVEWVDUW
          TYIWVDVVBYFVURVYNUYTVYJWVBUXAXMVGVURUXCYCZUXDUXEXBUYTVVHWUFVUPUNVYKWU
          HWUFVUPVIWUSWUHWUEVUOVUNVDMVUOUXFWTXIXBUYTUOVVHVVBVUTVVPUNMVVLVUNVURU
          XLVIZVVNVUSVVOVUNVDWVGVVMVURVGVHVUNVURVVLUNYTZMYTZUXGUXHVUNVURVVLWVHW
          VIUXIYPUYTWULVVHVUHXSZVVHXRURUYTDGURZWULUYSGDIGYGYQZJVCZUTZVAVBZXRURW
          ULJDGUYSWVMDVIZWVOVUHXRWVPWVNVUGVAWVMDUXJUXMZUXKUJUXNUXOWVJUYTWUQYIVU
          HVVHYBYCWUTWVDVUSVUNWVFUYTVYJVUNXJURWVBWVAUXPYLUXQUXRUYTVVHVUHVUPUNUY
          TWUMVVHVUHVIUYTDIURZWUMUYSIDIGYOYQWVRWUKWUMWVORXSWUMJDWUJIWVPWVOVUHRW
          VQUXSUKUXTXGXIVUHRUYBWKUYAYMUYCVUHVUJVUPLUNVUCVUNVIZVUIVUOVUCVUNVDVUC
          VUNDUYDWVSXQYPUYEUYFUYTVWGVUAWUJGUQZURZVULVUFVIVWIVWHVUAWUJURZVWEWFVW
          GWWAVWCWWBVWEVWCVWDVAYFVUAWDZWWBVWLVWDVWAYFXSZWWCVMYFURVLYFURWWDUYGUY
          HVMVLYFUYIYKVAVWAYFVUAUYMUYJWWBWWCYFVAVUAUYKUYNUYLUYOWQUYPVWJVUAWUJGW
          PUYQVUAGHJLUJUMYRWQUYTDWVTURZVUMVUKVIUYTWUKWVKWFWWEUYTWUKWVKWUNWVLYAD
          WUJGWPYJDGHJLUJUMYRXIUYR $.
      $}


      $d d f g k n o q r x y z $.  $d d D $.  $d d k n o q x y F $.
      $d f k o q G $.  $d o q r H $.  $d d f k n o q r x y J $.
      $d d k n o q r x y M $.  $d d f g k n o q x N $.  $d n r x y O $.
      $d g k n q P $.  $d d f k n o q r x y R $.  $d q S $.
      $d d f k n o q r x y T $.
      $( Lemma for ~ eulerpart .
         (Contributed by Thierry Arnoux, 30-Aug-2018.) $)
      eulerpartlemn $p |- ( G |` O ) : O -1-1-onto-> D $=
        ( vq vd cres wf1o wtru cn cv cfv cmul co csu wceq cin crab cc0 cpr cmap
        c1 wi vex wcel wa simpl fveq1d oveq1d sumeq2dv eqeq1d cbvrabv a1i eqidd
        reseq2d f1oeq123d imbi2d cbits ccom cima cind eulerpartgbij simp2 eleq1
        fveq2 reseq1 coeq2d fveq2d imaeq2d eqeq12d imbi12d eulerpartlemgv vtocl
        w3a syl cn0 wss cvv nn0ex mp2an ax-mp wf eulerpartlemsv1 eulerpartlemt0
        ccnv cfn elin c2 cdivides wbr wral nfcv nfv cnveq imaeq1d nfrab1 df-3an
        wn anbi1i eulerpartleme an32 3bitr4i wb nnex dfss3 3bitri pm5.32i rabid
        bitr4i eqri df-f 3bitr4ri simp3 eqtr4d eulerpartlemgs2 0nn0 prssi mapss
        sumeq2sdv 1nn0 ssrin f1of ffvelrni simp1bi inss2 sseli sylanbrc 3eqtr3d
        sseldi 3ad2ant2 eqtr3d frabbijd raleqdv cbvrabcsf elmapg bitri cnvimass
        3anbi1i cdm fdm sseq2d mpbii sylib biantrurd breq2 notbid elrab2 ralbii
        r19.26 syl6rbbr adantr 3eqtri reseq2i wfn crn fnima sseq1d anbi2d mpan2
        sstr pm4.71ri bicomi syl6bb anass prex elmap eleq1d elab2 eulerpartlemd
        anbi12i mpbird trud ) TDOTUOZUPZUQUXBURKUSZUMUSZUTZUXCVAVBZKVCZSVDZUMHF
        VEZVFZURUXCUNUSZUTZUXCVAVBZKVCZSVDZUNVGVJVHZURVIVBZFVEZVFZOUXJUOZUPZUQU
        RUXCMUSZUTZUXCVAVBZKVCZSVDZMUXIVFZUXSOUYGUOZUPZVKUQUYAVKMUXDUMVLUYBUXDV
        DZUYIUYAUQUYJUYGUXJUXSUXSUYHUXTUYJUYGUXJOUYGUXJVDUYJUYFUXHMUMUXIUYJUYEU
        XGSUYJURUYDUXFKUYJUXCURVMZVNZUYCUXEUXCVAUYLUXCUYBUXDUYJUYKVOVPVQVRVSVTW
        AZWCUYMUYJUXSWBWDWEUQUYFUXOMUNUXIUXRNWFUYBQUOZWGZRUTZWHZURWIUTZUTZOUKUX
        IUXROUPZUQABCDEFHIJKLMNOPQRSTUAUBUCUDUEUFUGUHUIUJUKWJZWAUQUYBUXIVMZUXKU
        YSVDZXBZUXNUYESVUDURUXCUYBOUTZUTZUXCVAVBZKVCZUXNUYEVUDURVUGUXMKVUDVUFUX
        LUXCVAVUDUXCVUEUXKVUDVUEUYSUXKVUDVUBVUEUYSVDZUQVUBVUCWKUXDUXIVMZUXDOUTZ
        NWFUXDQUOZWGZRUTZWHZUYRUTZVDZVKVUBVUIVKUMUYBMVLZUXDUYBVDZVUJVUBVUQVUIUX
        DUYBUXIWLZVUSVUKVUEVUPUYSUXDUYBOWMZVUSVUOUYQUYRVUSVUNUYPNVUSVUMUYORVUSV
        ULUYNWFUXDUYBQWNWOWPWQWPWRWSABCUXDDEFHIJKLMNOPQRSTUAUBUCUDUEUFUGUHUIUJU
        KWTXAXCUQVUBVUCUUAUUBVPVQUUGVUBUQVUHUYEVDVUCVUBVUEGUTZUYBGUTZVUHUYEVUJV
        UKGUTZUXDGUTZVDZVKVUBVVBVVCVDZVKUMUYBVURVUSVUJVUBVVFVVGVUTVUSVVDVVBVVEV
        VCVUSVUKVUEGVVAWPUXDUYBGWMWRWSABCUXDDEFGHIJKLMNOPQRSTUAUBUCUDUEUFUGUHUI
        UJUKULUUCXAVUBVUEXDURVIVBZFVEZVMVVBVUHVDVUBUXRVVIVUEUXQVVHXEZUXRVVIXEXD
        XFVMZUXPXDXEZVVJXGVGXDVMVJXDVMVVLUUDUUHVGVJXDUUEXHZUXPXDURXFUUFXHUXQVVH
        FUUIXIUXIUXRUYBOUYTUXIUXROXJVUAUXIUXROUUJXIUUKUUQVUEFGIKUIULXKXCVUBUYBV
        VIVMZVVCUYEVDVUBUYBVVHVMZUYBFVMVVNVUBVVOUYBXMURWHZXNVMVVPQXEABCUYBDEFHI
        JKLNPQRSTUAUBUCUDUEUFUGUHUIUJXLUULUXIFUYBHFUUMUUNUYBVVHFXOUUOUYBFGIKUIU
        LXKXCUUPUURUUSVSUUTXAUQTUXJDUXSUXAUXTUXAUXTVDUQTUXJOTXPLUSZXQXRZYFZLJUS
        ZXMZURWHZXSZJEVFVVSLUXDXMZURWHZXSZUMEVFZUXJUCVWCVWFJUMEEUMEXTJEXTVWCUMY
        AVWFJYAVVTUXDVDZEWBVWHVVSLVWBVWEVWHVWAVWDURVVTUXDYBYCUVAUVBUMVWGUXJVWFU
        MEYDUXHUMUXIYDUXDEVMZVWFVNZVUJUXHVNZUXDVWGVMUXDUXJVMVWJURXDUXDXJZVWEXNV
        MZVNZVWFVNZUXHVNZVWKVWLVWMUXHXBZVWFVNVWNUXHVNZVWFVNVWJVWPVWQVWRVWFVWLVW
        MUXHYEYGVWIVWQVWFUXDEIKSUBYHYGVWNVWFUXHYIYJVUJVWOUXHVUJVWLVWMVWEQXEZXBZ
        VWNVWSVNVWOVUJUXDVVHVMZVWMVWSXBVWTABCUXDDEFHIJKLNPQRSTUAUBUCUDUEUFUGUHU
        IUJXLVXAVWLVWMVWSVVKURXFVMVXAVWLYKXGYLXDURUXDXFXFUVCXHUVFUVDVWLVWMVWSYE
        VWNVWSVWFVWLVWSVWFYKVWMVWLVWFVVQURVMZLVWEXSZVWFVNZVWSVWLVXCVWFVWLVWEURX
        EZVXCVWLVWEUXDUVGZXEVXEUXDURUVEVWLVXFURVWEURXDUXDUVHUVIUVJLVWEURYMUVKUV
        LVWSVVQQVMZLVWEXSVXBVVSVNZLVWEXSVXDLVWEQYMVXGVXHLVWEXPCUSZXQXRZYFVVSCVV
        QURQVXIVVQVDVXJVVRVXIVVQXPXQUVMUVNUEUVOUVPVXBVVSLVWEUVQYNUVRUVSYOYNYGYQ
        VWFUMEYPUXHUMUXIYPYJYRUVTZUWAWATUXJVDUQVXKWADUXSVDUQUNDUXSUNDXTUXOUNUXR
        YDUXKUXRVMZUXOVNZUXKEVMZUXKURWHZUXPXEZVNZUXKUXSVMUXKDVMVXMURXDUXKXJZUXK
        XMZURWHZXNVMZVNZVXPVNZUXOVNZVXQVXLVYCUXOUXKUXQVMZUXKFVMZVNVXRVXPVNZVYAV
        NVXLVYCVYEVYGVYFVYAURUXPUXKXJZUXKURUWBZUXKUWCZXDXEZVNZVXPVNZVYEVYGVYIVY
        KVXPVNZVNVYIVYJUXPXEZVNVYMVYHVYIVYNVYOVYIVYNVYKVYOVNZVYOVYIVXPVYOVYKVYI
        VXOVYJUXPURUXKUWDUWEUWFVYOVYPVYOVYKVYOVVLVYKVVMVYJUXPXDUWHUWGUWIUWJUWKY
        OVYIVYKVXPUWLURUXPUXKYSYTUXPURUXKVGVJUWMYLUWNVXRVYLVXPURXDUXKYSYGYJIUSZ
        XMZURWHZXNVMVYAIUXKFUNVLVYQUXKVDZVYSVXTXNVYTVYRVXSURVYQUXKYBYCUWOUIUWPU
        WRUXKUXQFXOVXRVYAVXPYIYJYGVXQVXRVYAUXOXBZVXPVNVYBUXOVNZVXPVNVYDVXNWUAVX
        PUXKEIKSUBYHYGWUAWUBVXPVXRVYAUXOYEYGVYBUXOVXPYIYNYQUXOUNUXRYPUXKDEIJKLS
        TUBUCUDUWQYTYRWAWDUWSUWT $.
   $}

   $d a b f g h k n m o q r s t x y z $.  $d g D $.  $d f g k n q x N $.
   $d g n r x y O $.  $d g k n P $.
   $( Euler's theorem on partitions, also known as a special case of
       Glaisher's theorem. Let ` P ` be the set of all partitions of ` N ` ,
       represented as multisets of natural numbers, which is to say functions
       from ` NN ` to ` NN0 ` where the value of the function represents the
       number of repetitions of an individual element, and the sum of all the
       elements with repetition equals ` N ` . Then the set ` O ` of all
       partitions that only consist of odd numbers and the set ` D ` of all
       partitions which have no repeated elements have the same cardinality.
       (Contributed by Thierry Arnoux, 14-Aug-2018.) $)
    eulerpart $p |- ( # ` O ) = ( # ` D ) $=
      ( vr va vb cv cfv wceq cima cfn wcel vo vh vz vx vy vq vm vt vs wex chash
      wf1o ccnv cn c2 cdivides wbr wn crab wss cn0 cmap cab cin cexp cmul cmpt2
      co cbits cres ccom cvv c0 csn cdif cpw wa copab cmpt cind csu eqid oveq1d
      oveq2 cbvmpt2v nfcv nfv eqidd cnveq imaeq1d eleq1d cbvrabcsf eqcomi fveq1
      eleq2d anbi2d opabbidv cbvmptv simpl simpr eleq12d anbi12d cbvopabv eqtri
      fveq2d mpteq12i cbvabv sseq1d cbvrabv reseq1 coeq2d imaeq2d eqtr4i fveq1i
      imaeq1i imaeq2i fveq2i mpteq2i eulerpartlemn ovex rabex inex1 mptex resex
      f1oeq1 spcev ax-mp cen bren hasheni sylbir ) HADOZULZDUJZHUKPAUKPQZHAUAUB
      OZUMZUNRZUOUCOUPUQURUCUNUSZUTZUBVAUNVBVHZUSZYRSTZUBVCZVDZUDUEYSVAUOUEOZVE
      VHZUDOZVFVHZVGZVIUAOZYSVJZVKZLLOZUMZVLVMVNVOZRZSTZLVAVPSVDYSVBVHZUSZUUHYS
      TZUUFUUHUUNPZTZVQZUDUEVRZVSZPZRZUNVTPZPZVSZHVJZULZYNUDUEUCABUUDCUUAUUDVDU
      NEOZCOZPUVNVFVHEWAVSZUUBCDEFUFMNYSVAUONOZVEVHZMOZVFVHZVGZUVKUGOZUMZUUPRZS
      TZUGUUSUSZYSUHUIOZUMZUUPRZSTZUIUUSUSZUVSYSTZUVQUVSUHOZPZTZVQZMNVRZVSZGHLI
      JKYSWBMNUDUEYSVAUVTUUIUVRUUHVFVHUVSUUHUVRVFWDUVQUUFQZUVRUUGUUHVFUVQUUFUOV
      EWDWCWEZUUTUWFUURUWELUGUUSUUSUGUUSWFZLUUSWFUURUGWGUWELWGUUNUWBQZUUSWHUXBU
      UQUWDSUXBUUOUWCUUPUUNUWBWIWJWKWLZWMUWRLUWKUWLUVQUVSUUNPZTZVQZMNVRZVSZLUWF
      UVEVSZUHLUWKUWQUXGUWMUUNQZUWPUXFMNUXJUWOUXEUWLUXJUWNUXDUVQUVSUWMUUNWNWOWP
      WQWRLUWKUXGUWFUVEUWFUWKUWEUWJUGUIUUSUUSUIUUSWFUXAUWEUIWGUWJUGWGUWBUWGQZUU
      SWHUXKUWDUWISUXKUWCUWHUUPUWBUWGWIWJWKWLWMUXFUVDMNUDUEUVSUUHQZUWSVQZUWLUVA
      UXEUVCUXMUVSUUHYSUXLUWSWSZWKUXMUVQUUFUXDUVBUXLUWSWTUXMUVSUUHUUNUXNXEXAXBX
      CXFZXDUUCUVOUMZUNRZSTUBCYPUVOQZYRUXQSUXRYQUXPUNYPUVOWIWJZWKXGYTUXQYSUTUBC
      UUAUXRYRUXQYSUXSXHXIUVKUFUUEUUJVIUFOZYSVJZVKZUVFPZRZUVIPZVSUFUUEUWAUYBUWR
      PZRZUVIPZVSUAUFUUEUVJUYEUUKUXTQZUVHUYDUVIUYIUVGUYCUUJUYIUUMUYBUVFUYIUULUY
      AVIUUKUXTYSXJXKXEXLXEWRUFUUEUYEUYHUYDUYGUVIUYDUWAUYCRUYGUUJUWAUYCUWAUUJUW
      TWMXOUYCUYFUWAUYBUVFUWRUVFUXHUWRUVFUXIUXHLUUTUVEUWFUVEUXCUVEWBXFUXOXMLUHU
      WKUXGUWQUUNUWMQZUXFUWPMNUYJUXEUWOUWLUYJUXDUWNUVQUVSUUNUWMWNWOWPWQWRXDXNXP
      XDXQXRXDUVPWBXSYMUVMDUVLUVKHUAUUEUVJUUBUUDYTUBUUAVAUNVBXTYAYBYCYDHAYLUVLY
      EYFYGYNHAYHUQYOHADYIHAYJYKYG $.
 $}
