$( -*-text-*- $)

  $c ( $.  $( Left parenthesis $)
  $c ) $.  $( Right parenthesis $)
  $c -> $. $( Right arrow (read:  "implies") $)
  $c -. $. $( Right handle (read:  "not") $)
  $c wff $. $( Well-formed formula symbol (read:  "the following symbol
               sequence is a wff") $)
  $c |- $. $( Turnstile (read:  "the following symbol sequence is provable" or
              'a proof exists for") $)

  $( wff variable sequence:  ph ps ch th ta et ze si rh mu la ka $)
  $( Introduce some variable names we will use to represent well-formed
     formulas (wff's). $)
  $v ph $.  $( Greek phi $)
  $v ps $.  $( Greek psi $)
  $v ch $.  $( Greek chi $)
  $v th $.  $( Greek theta $)
  $v ta $.  $( Greek tau $)
  $v et $.  $( Greek eta $)
  $v ze $.  $( Greek zeta $)
  $v si $.  $( Greek sigma $)
  $v rh $.  $( Greek rho $)
  $v mu $.  $( Greek mu $)
  $v la $.  $( Greek lambda $)
  $v ka $.  $( Greek kappa $)
  wph $f wff ph $.
  wps $f wff ps $.
  wch $f wff ch $.
  wth $f wff th $.
  wta $f wff ta $.
  wet $f wff et $.
  wze $f wff ze $.
  wsi $f wff si $.
  wrh $f wff rh $.
  wmu $f wff mu $.
  wla $f wff la $.
  wka $f wff ka $.

  wn $a wff -. ph $.
  wi $a wff ( ph -> ps ) $.

  ax-mer $a |- ( ( ( ( ( ph -> ps ) -> ( -. ch -> -. th ) ) -> ch ) ->
       ta ) -> ( ( ta -> ph ) -> ( th -> ph ) ) ) $.

  ${
    ax-mp.min $e |- ph $.
    ax-mp.maj $e |- ( ph -> ps ) $.

    ax-mp $a |- ps $.
  $}


  pm2.24 $p |- ( ph -> ( -. ph -> ps ) ) $=
    ( wch wn wi ax-mer ax-mp ) BDZADZEZBEZIBEZEZALEZBCEZIDZPEZEZIEJEZMICECDZHDE
    ECEZREZSQQEZREZUBQCEZPDZODZEZEZPEQEZUDPUFEUHDZUFEEZUHEUIEZUJUHUFUEDEZDUKDEZ
    EUNEPEULEUMUFUGUNUKPFUHUOPUEULFGPUFUHPUIFGQCPOQFGRCEZQDZUADZEZEZQEUCEZUDUBE
    QUQEUSDZUQEEZUSEUTEZVAUSUQUPDEZDVBDEZEVEEQEVCEVDUQURVEVBQFUSVFQUPVCFGQUQUSQ
    UTFGRCQUAUCFGGICCHRFGBCIIJFGLCEZJEZBEKEZMNEOJDZVJEZEZJEVHEZVIJCETVGDEECEZVL
    EZVMVKVKEZVLEZVOVKCEZVJDZUGEZEZVJEVKEZVQVJVSEVTDZVSEEZVTEWAEZWBVTVSVRDEZDWC
    DEZEWFEVJEWDEWEVSUGWFWCVJFVTWGVJVRWDFGVJVSVTVJWAFGVKCVJOVKFGVLCEZVKDZVNDZEZ
    EZVKEVPEZVQVOEVKWIEWKDZWIEEZWKEWLEZWMWKWIWHDEZDWNDEZEWQEVKEWOEWPWIWJWQWNVKF
    WKWRVKWHWOFGVKWIWKVKWLFGVLCVKVNVPFGGJCCVGVLFGBCJJVHFGLCBAKFGG $.
    $( [?] $) $( [5-Feb-2013] $)

  imim1 $p |- ( ( ph -> ps ) -> ( ( ps -> ch ) -> ( ph -> ch ) ) ) $=
    ( wth wi wn ax-mer ax-mp ) CDEAFZFZFZIEZEJEZBEZBCEACEEZEZABEZOEZCDJABGODEQF
    ZFZFZSEZETEZNEZPREQNEZUDBDEIMFZEZEAEZAEZUEUHUIEZUIUGUJDDFZFZDEZEZUFEZUFEZUG
    UOUPEZUPUNUQDDEZUMEZUNURUKUKEZEDEDEURUREEZUSDDDDDGZURUKULFEEDEZDEZUSEZVAUSE
    ZDDDULDGUSVAFZEUKVGEZEZDEVDEZVEVFEURUKVCFEEDEZVIEZVJVIVLVGULEUMFZULEEZUMEUS
    EZVIUMVGFURFEZFVMFEZEVPEVGEVNEVOULDVPVMVGGUMVQVGURVNGHVGULUMUKUSGHVAVIVLEZV
    BVIVIEZVLEZVREZVAVREZVLDEZVIFZWDEZEZVIEVSEZWAVIWDEWEFZWDEEZWEEWFEZWGWEWDWCF
    EZFWHFEZEWKEVIEWIEWJWDWDWKWHVIGWEWLVIWCWIGHVIWDWEVIWFGHVLDVIVIVSGHVRWDVGEZF
    VKFEZEWMEVIEVTEWAWBEVIVLWMVKVIGVRWNVIVAVTGHHHHDDDVCVIGHUSVGDVAVDGHHHUMDEZUT
    EZDEUREZUSUNEDUKEUTFZUKEEZUTEWPEZWQUTUKWOFEZFWRFEZEXAEDEWSEWTUKUKXAWRDGUTXB
    DWOWSGHDUKUTDWPGHUMDDDURGHHUFDEUKUOFZEEDEZUNEZUQEZUNUQEZUFDDUOUNGUQDEZUNFZX
    IEZEZUNEXEEZXFXGEUNDEUKXDFEEDEZXKEZXLXJXJEZXKEZXNXJDEZXIFZXHFZEZEZXIEXJEZXP
    XIXREXTFZXREEZXTEYAEZYBXTXRXQFEZFYCFEZEYFEXIEYDEYEXRXSYFYCXIGXTYGXIXQYDGHXI
    XRXTXIYAGHXJDXIXHXJGHXKDEZXJFZXMFZEZEZXJEXOEZXPXNEXJYIEYKFZYIEEZYKEYLEZYMYK
    YIYHFEZFYNFEZEYQEXJEYOEYPYIYJYQYNXJGYKYRXJYHYOGHXJYIYKXJYLGHXKDXJXMXOGHHUND
    DXDXKGHUQDUNUNXEGHHHVAUQUPEZVBUQYSEZVAYSEZVAYTVBUPDEUKUQFZEZEDEZUOEZYTEZVAY
    TEZUPDDUQUOGYTVGEXCVGEEZUOEUUEEZUUFUUGEUPUUHFUUBEZFUUDFEEUUJEUUHEZUUIYSUUHE
    ZUUKYTUUHEZUULVGDEZUKXCFEEDEZYTEZUUHEZUUMVGDDXCYTGUUHDEZYTFZUUSEZEZYTEUUPEZ
    UUQUUMEYTDEUKUUOFEEDEZUVAEZUVBUUTUUTEZUVAEZUVDUUTDEZUUSFZUURFZEZEZUUSEUUTEZ
    UVFUUSUVHEUVJFZUVHEEZUVJEUVKEZUVLUVJUVHUVGFEZFUVMFEZEUVPEUUSEUVNEUVOUVHUVIU
    VPUVMUUSGUVJUVQUUSUVGUVNGHUUSUVHUVJUUSUVKGHUUTDUUSUURUUTGHUVADEZUUTFZUVCFZE
    ZEZUUTEUVEEZUVFUVDEUUTUVSEUWAFZUVSEEZUWAEUWBEZUWCUWAUVSUVRFEZFUWDFEZEUWGEUU
    TEUWEEUWFUVSUVTUWGUWDUUTGUWAUWHUUTUVRUWEGHUUTUVSUWAUUTUWBGHUVADUUTUVCUVEGHH
    YTDDUUOUVAGHUUHDYTYTUUPGHHUURYSFZUWIEZEZYSEYTEZUUMUULEYSDEZUUCEDEZUWKEZUWLU
    WJUWJEZUWKEZUWOUWJDEZUWIFZUVIEZEZUWIEUWJEZUWQUWIUWSEUWTFZUWSEEZUWTEUXAEZUXB
    UWTUWSUWRFEZFUXCFEZEUXFEUWIEUXDEUXEUWSUVIUXFUXCUWIGUWTUXGUWIUWRUXDGHUWIUWSU
    WTUWIUXAGHUWJDUWIUURUWJGHUWKDEZUWJFZUWNFZEZEZUWJEUWPEZUWQUWOEUWJUXIEUXKFZUX
    IEEZUXKEUXLEZUXMUXKUXIUXHFEZFUXNFEZEUXQEUWJEUXOEUXPUXIUXJUXQUXNUWJGUXKUXRUW
    JUXHUXOGHUWJUXIUXKUWJUXLGHUWKDUWJUWNUWPGHHYSDDUQUWKGHUUHDYSYSYTGHHVAUULUUKE
    ZVB?VAUXSEZ???DD??GZ?????????????????GZUYBHZUYBHZ?D???GZHZUYFHZUYAHZUYEHZHZ
    ??UXTE??????VGDD??G???E??UYGUYBHZUYEHH????????UYDUYBHZUYLHZUYAHUYEHZHUYBH?V
    G?VA?GHHHHUOUFUUJUUDUUHGHYTVGUOVAUUEGHHHVAYTUUAEZVBUWMVHEDEZUQEZUYOEZVAUYOE
    ZYSDDVAUQG?UYRUYSE??????UYJUYIHZVA?VB??UYJ????????UYA??UYKUYEHHUYNHUYBHUYBH
    HHHUQ??UYP?GHUYO?UQVAUYQGHHHHHH?UPUGE????????IIEZLEZ?VAVUBVBIDEUKKFEEDEZIEZ
    VUBEZVAVUBEZIDDKIG?VUEVUFE????????KI?LF?GL??VUA?GH?KLJVUBGHVA?VB??UYFUYCHHZ
    HIDDVUC?GHVUB?IVAVUDGHHH??????J?JLDEZFE?IG??IVUH?GHIJ?I?GHLDI?VUAGHH??JDD??
    GZUYIHHVA?VB??VA?VB??UYA??????????UYA????UYMUYBHUYEHZHUYNHVA?VB????UYA??UYK
    UYBHHZ????????UYBUYIH??UYHUYBHHUYBHUYBHHHHZ?J???GZHUYBHHHVA?VB??UYA????VULU
    YBHUYBHHHZHHHVA?VB??VUI??????????VUMUYBHUYBHVUGHUYAHUYBHHHHUYTHUFD?IUOGHH?U
    GUJE??ADD??GUYIHUYIHHVAUJUIEZVB?VAVUOEVA?VB??UYA??????UYTVA?VB??UYJ????????
    UYAUYNHZUYIHUYBHUYBHHHHZ?A???GHUYBHHHVA?VB??UYA????VUQUYBHUYBHHHHHHBDAMAGHN
    DESUCFEEQEZQEZUEUDEVURVUSEZVUS?VUT????????VA?VB??UYA??????????UYEUYBHUYBHVU
    GHUYAHUYBHHH??UYD?D?D?GHHUYJHVA?VB??VA?VB??UYA??????UYTVA?VB??VUP??????VUKV
    UJHUYBHUYBHHHHUYBHUYBHHHZVVAHHH??????????SSEZUBEZ?VAVVCVBSDEUKUAFEEDEZSEZVV
    CEZVAVVCEZSDDUASG?VVFVVGE????????UAS?UBF?GUB??VVB?GH?UAUBTVVCGHVUGHSDDVVD?G
    HVVC?SVAVVEGHHH??????T?TUBDEZFE?SG??SVVH?GHST?S?GHUBDS?VVBGHH??TDD??GZUYIHH
    VA?VB??VA?VB??UYA????VUL?T???GZHUYBHHHVUNHHHVA?VB??VVI??????????VVJUYBHUYBH
    VUGHUYAHUYBHHHHUYTH?D?S?GHH????QDD??GUYIHUYIHHVAVUTVUSEZVBVUTVVKEZVAVVKEZVA
    VVLVBVUSDEUKVUTFZEEDEZVUREZVVLEZVAVVLEZVUSDDVUTVURG?VVQVVRE??VUQVURQ?VVO?GH
    VVL?VURVAVVPGHHHVAVVLVVMEZVBVVKDEVHEDEZVUTEZVVSEZVAVVSEZVVKDDVAVUTGVVSVGEVV
    NVGEEZVUTEVWAEZVWBVWCEVVKVWDFVGEZFVVTFEZEVWFEZVWDEZVWEVVMVWDEZVWI?VWJUYJUYI
    HVAVWJVWIEZVBVVMVWKEZVAVWKEZVWDDEUKVWHFEEDEZVVMEZVWKEZVWLVWDDDVWHVVMGVWKDEZ
    VVMFZVWREEZVVMEVWOEZVWPVWLEVVMDEUKVWNFEEDEVWSEZVWT?VXAUYFUYFHVVMDDVWNVWSGHV
    WKDVVMVVMVWOGHHVWKVGEVVKFZVGEEZVVKEVVMEZVWLVWMEVWIVXCEZVXDVWKVXCEZVXEUUNUKV
    XBFEEDEZVWKEZVXCEZVXFVGDDVXBVWKGVXCDEZVWKFZVXKEZEZVWKEVXHEZVXIVXFEVWQUKVXGF
    EEDEZVXMEZVXNVXLVXLEZVXMEZVXP?VXR????VXKFZVXJFZ?VXSVXTEZFZVXKGVYA?VXK?VXKVX
    SEVYBVXSEEGHVXKVXSVYAVXK?GHVXL?VXKVXJVXLGHVXMDEZVXLFZVXOFZEZEZVXLEVXQEZVXRV
    XPEVXLVYDEVYFFZVYDEEZVYFEVYGEZVYHVYFVYDVYCFEZFVYIFEZEVYLEVXLEVYJEVYKVYDVYEV
    YLVYIVXLGVYFVYMVXLVYCVYJGHVXLVYDVYFVXLVYGGHVXMDVXLVXOVXQGHHVWKDDVXGVXMGHVXC
    DVWKVWKVXHGHHVXJVWIFZVYNEZEZVWIEVWKEZVXFVXEEVWIDEUKVWJFEEDEZVYPEZVYQVYOVYOE
    ZVYPEZVYSVYODEZVYNFZVXTEZEZVYNEVYOEZWUAVYNWUCEWUDFZWUCEEZWUDEWUEEZWUFWUDWUC
    WUBFEZFWUGFEZEWUJEVYNEWUHEWUIWUCVXTWUJWUGVYNGWUDWUKVYNWUBWUHGHVYNWUCWUDVYNW
    UEGHVYODVYNVXJVYOGHVYPDEZVYOFZVYRFZEZEZVYOEVYTEZWUAVYSEVYOWUMEWUOFZWUMEEZWU
    OEWUPEZWUQWUOWUMWULFEZFWURFEZEWVAEVYOEWUSEWUTWUMWUNWVAWURVYOGWUOWVBVYOWULWU
    SGHVYOWUMWUOVYOWUPGHVYPDVYOVYRVYTGHHVWIDDVWJVYPGHVXCDVWIVWIVWKGHHVVKVWGVWDV
    AVXCGHVWKVGVVKVAVVMGHHHHVUTVUSVWFVVTVWDGHVVSVGVUTVAVWAGHHHHHHNDQUCQGHHODTQN
    GHH $.
    $( [?] $) $( [8-Feb-2013] $)

  pm2.18 $p |- ( ( -. ph -> ph ) -> ph ) $=
    ( wps wn wi ax-mer ax-mp ) ACZADZHADZDZIAHCZDZGCZKDZDZGDZGDZJPQDZQORBBDZBCZ
    TDDBDBDSSDDZOBBBBBEZKBDTMCDDBDZADZODZUAODZKBBMAEOUACZDGUGDDZADUDDZUEUFDABDT
    UCCDDBDZUHDZUIUHUKUGMDNCZMDDZNDODZUHNUGCLCDZCULCDZDUODUGDUMDUNMKUOULUGENUPU
    GLUMEFUGMNGOEFUAUHUKDZUBUHUHDZUKDZUQDZUAUQDZUKBDZUHCZVCDZDZUHDURDZUTUHVCDVD
    CZVCDDZVDDVEDZVFVDVCVBCDZCVGCDZDVJDUHDVHDVIVCVCVJVGUHEVDVKUHVBVHEFUHVCVDUHV
    EEFUKBUHUHUREFUQVCUGDZCUJCDZDVLDUHDUSDUTVADUHUKVLUJUHEUQVMUHUAUSEFFFFABBUCU
    HEFOUGAUAUDEFFFGBDTPCZDDBDZODZRDZORDZGBBPOERBDZOCZVTDZDZODVPDZVQVRDOBDTVOCD
    DBDZWBDZWCWAWADZWBDZWEWABDZVTCZVSCZDZDZVTDWADZWGVTWIDWKCZWIDDZWKDWLDZWMWKWI
    WHCDZCWNCDZDWQDVTDWODWPWIWJWQWNVTEWKWRVTWHWOEFVTWIWKVTWLEFWABVTVSWAEFWBBDZW
    ACZWDCZDZDZWADWFDZWGWEDWAWTDXBCZWTDDZXBDXCDZXDXBWTWSCDZCXECDZDXHDWADXFDXGWT
    XAXHXEWAEXBXIWAWSXFEFWAWTXBWAXCEFWBBWAWDWFEFFOBBVOWBEFRBOOVPEFFFUARQDZUBRXJ
    DZUAXJDZUAXKUBQBDTRCZDZDBDZPDZXKDZUAXKDZQBBRPEXKUGDVNUGDDZPDXPDZXQXRDQXSCXM
    DZCXOCDZDYADZXSDZXTXJXSDZYDXKXSDZYEUGBDZTVNCDDBDZXKDZXSDZYFUGBBVNXKEXSBDZXK
    CZYLDZDZXKDYIDZYJYFDXKBDTYHCDDBDZYNDZYOYMYMDZYNDZYQYMBDZYLCZYKCZDZDZYLDYMDZ
    YSYLUUADUUCCZUUADDZUUCDUUDDZUUEUUCUUAYTCDZCUUFCDZDUUIDYLDUUGDUUHUUAUUBUUIUU
    FYLEUUCUUJYLYTUUGEFYLUUAUUCYLUUDEFYMBYLYKYMEFYNBDZYMCZYPCZDZDZYMDYRDZYSYQDY
    MUULDUUNCZUULDDZUUNDUUODZUUPUUNUULUUKCDZCUUQCDZDUUTDYMDUURDUUSUULUUMUUTUUQY
    MEUUNUVAYMUUKUUREFYMUULUUNYMUUOEFYNBYMYPYREFFXKBBYHYNEFXSBXKXKYIEFFYKXJCZUV
    BDZDZXJDXKDZYFYEDXJBDZXNDBDZUVDDZUVEUVCUVCDZUVDDZUVHUVCBDZUVBCZUUBDZDZUVBDU
    VCDZUVJUVBUVLDZUVMCZUVLDDZUVMDUVNDZUVOUVMUVLUVKCDZCZUVQCDZDUVTDUVBDUVRDUVSU
    VLUUBUVTUVQUVBEUVMUWBUVBUVKUVREFUVBUVLUVMUVBUVNEFUVCBUVBYKUVCEFUVDBDZUVCCZU
    VGCZDZDZUVCDUVIDZUVJUVHDUVCUWDDZUWFCZUWDDDZUWFDUWGDZUWHUWFUWDUWCCDZCUWJCDZD
    UWMDUVCDUWKDUWLUWDUWEUWMUWJUVCEUWFUWNUVCUWCUWKEFUVCUWDUWFUVCUWGEFUVDBUVCUVG
    UVIEFFXJBBRUVDEFXSBXJXJXKEFFUAYEYDDZUBXJUWODZUAUWODZYKTYCCDDBDZXJDZUWODZUWP
    XSBBYCXJEUWOBDZUVCDZXJDUWSDZUWTUWPDUVFTUWRCDDBDZUXBDZUXCUVIUXBDZUXEUVKUVLUX
    ACZDZDZUVBDUVCDZUXFUVPUXHCZUVLDDZUXHDUXIDZUXJUXHUWAUXKCDZDUVTDUVBDUXLDUXMUV
    LUXGUVTUXKUVBEUXHUXNUVBUVKUXLEFUVBUVLUXHUVBUXIEFUVCBUVBUXAUVCEFUXBBDZUWDUXD
    CZDZDZUVCDUVIDZUXFUXEDUWIUXQCZUWDDDZUXQDUXRDZUXSUXQUWDUXOCDZCUXTCDZDUYCDUVC
    DUYADUYBUWDUXPUYCUXTUVCEUXQUYDUVCUXOUYAEFUVCUWDUXQUVCUXREFUXBBUVCUXDUVIEFFX
    JBBUWRUXBEFUWOBXJXJUWSEFFUWOUGDQCZUGDDZQDXJDZUWPUWQDYDUYFDZUYGUWOUYFDZUYHYG
    TUYECDDBDZUWODZUYFDZUYIUGBBUYEUWOEUYFBDZUWOCZUYNDZDZUWODUYKDZUYLUYIDUXATUYJ
    CDDBDZUYPDZUYQUYOUYODZUYPDZUYSUYOBDZUYNCZUYMCZDZDZUYNDUYODZVUAUYNVUCDVUECZV
    UCDDZVUEDVUFDZVUGVUEVUCVUBCDZCVUHCDZDVUKDUYNDVUIDVUJVUCVUDVUKVUHUYNEVUEVULU
    YNVUBVUIEFUYNVUCVUEUYNVUFEFUYOBUYNUYMUYOEFUYPBDZUYOCZUYRCZDZDZUYODUYTDZVUAU
    YSDUYOVUNDVUPCZVUNDDZVUPDVUQDZVURVUPVUNVUMCDZCVUSCDZDVVBDUYODVUTDVVAVUNVUOV
    VBVUSUYOEVUPVVCUYOVUMVUTEFUYOVUNVUPUYOVUQEFUYPBUYOUYRUYTEFFUWOBBUYJUYPEFUYF
    BUWOUWOUYKEFFUYMYDCZVVDDZDZYDDUWODZUYIUYHDYDBDTYECDDBDZVVFDZVVGVVEVVEDZVVFD
    ZVVIVVEBDZVVDCZVUDDZDZVVDDVVEDZVVKVVDVVMDVVNCZVVMDDZVVNDVVODZVVPVVNVVMVVLCD
    ZCVVQCDZDVVTDVVDDVVRDVVSVVMVUDVVTVVQVVDEVVNVWAVVDVVLVVREFVVDVVMVVNVVDVVOEFV
    VEBVVDUYMVVEEFVVFBDZVVECZVVHCZDZDZVVEDVVJDZVVKVVIDVVEVWCDVWECZVWCDDZVWEDVWF
    DZVWGVWEVWCVWBCDZCVWHCDZDVWKDVVEDVWIDVWJVWCVWDVWKVWHVVEEVWEVWLVVEVWBVWIEFVV
    EVWCVWEVVEVWFEFVVFBVVEVVHVVJEFFYDBBYEVVFEFUYFBYDYDUWOEFFQYBXSRUYFEFUWOUGQUA
    XJEFFFFPGYAXOXSEFXKUGPUAXPEFFFUAXKXLDZUBUVFTUGDZDBDZRDZVWMDZUAVWMDZXJBBUARE
    VWMUGDXMUGDDZRDVWPDZVWQVWRDXJVWSCUGDZCVWOCDZDVXADZVWSDZVWTXLVWSDZVXDVWMVWSD
    ZVXEYGTXMCDDBDZVWMDZVWSDZVXFUGBBXMVWMEVWSBDZVWMCZVXKDZDZVWMDVXHDZVXIVXFDVWM
    BDTVXGCDDBDZVXMDZVXNVXLVXLDZVXMDZVXPVXLBDZVXKCZVXJCZDZDZVXKDVXLDZVXRVXKVXTD
    VYBCZVXTDDZVYBDVYCDZVYDVYBVXTVXSCDZCVYECDZDVYHDVXKDVYFDVYGVXTVYAVYHVYEVXKEV
    YBVYIVXKVXSVYFEFVXKVXTVYBVXKVYCEFVXLBVXKVXJVXLEFVXMBDZVXLCZVXOCZDZDZVXLDVXQ
    DZVXRVXPDVXLVYKDVYMCZVYKDDZVYMDVYNDZVYOVYMVYKVYJCDZCVYPCDZDVYSDVXLDVYQDVYRV
    YKVYLVYSVYPVXLEVYMVYTVXLVYJVYQEFVXLVYKVYMVXLVYNEFVXMBVXLVXOVXQEFFVWMBBVXGVX
    MEFVWSBVWMVWMVXHEFFVXJXLCZWUADZDZXLDVWMDZVXFVXEDXLBDZTYLDDBDZWUCDZWUDWUBWUB
    DZWUCDZWUGWUBBDZWUACZVYADZDZWUADWUBDZWUIWUAWUKDZWULCZWUKDDZWULDWUMDZWUNWULW
    UKWUJCDZCZWUPCDZDWUSDWUADWUQDWURWUKVYAWUSWUPWUAEWULWVAWUAWUJWUQEFWUAWUKWULW
    UAWUMEFWUBBWUAVXJWUBEFWUCBDZWUBCZWUFCZDZDZWUBDWUHDZWUIWUGDWUBWVCDZWVECZWVCD
    DZWVEDWVFDZWVGWVEWVCWVBCDZCWVICDZDWVLDWUBDWVJDWVKWVCWVDWVLWVIWUBEWVEWVMWUBW
    VBWVJEFWUBWVCWVEWUBWVFEFWUCBWUBWUFWUHEFFXLBBXKWUCEFVWSBXLXLVWMEFFUAVXEVXDDZ
    UBXLWVNDZUAWVNDZVXJTVXCCDDBDZXLDZWVNDZWVOVWSBBVXCXLEWVNBDZWUBDZXLDWVRDZWVSW
    VODWUETWVQCDDBDZWWADZWWBWUHWWADZWWDWUJWUKWVTCZDZDZWUADWUBDZWWEWUOWWGCZWUKDD
    ZWWGDWWHDZWWIWWGWUTWWJCDZDWUSDWUADWWKDWWLWUKWWFWUSWWJWUAEWWGWWMWUAWUJWWKEFW
    UAWUKWWGWUAWWHEFWUBBWUAWVTWUBEFWWABDZWVCWWCCZDZDZWUBDWUHDZWWEWWDDWVHWWPCZWV
    CDDZWWPDWWQDZWWRWWPWVCWWNCDZCWWSCDZDWXBDWUBDWWTDWXAWVCWWOWXBWWSWUBEWWPWXCWU
    BWWNWWTEFWUBWVCWWPWUBWWQEFWWABWUBWWCWUHEFFXLBBWVQWWAEFWVNBXLXLWVREFFWVNUGDU
    VBUGDDZXJDXLDZWVOWVPDVXDWXDDZWXEWVNWXDDZWXFYGTUVLDDBDZWVNDZWXDDZWXGUGBBUVBW
    VNEWXDBDZWVNCZWXLDZDZWVNDWXIDZWXJWXGDWVTTWXHCDDBDZWXNDZWXOWXMWXMDZWXNDZWXQW
    XMBDZWXLCZWXKCZDZDZWXLDWXMDZWXSWXLWYADWYCCZWYADDZWYCDWYDDZWYEWYCWYAWXTCDZCW
    YFCDZDWYIDWXLDWYGDWYHWYAWYBWYIWYFWXLEWYCWYJWXLWXTWYGEFWXLWYAWYCWXLWYDEFWXMB
    WXLWXKWXMEFWXNBDZWXMCZWXPCZDZDZWXMDWXRDZWXSWXQDWXMWYLDWYNCZWYLDDZWYNDWYODZW
    YPWYNWYLWYKCDZCWYQCDZDWYTDWXMDWYRDWYSWYLWYMWYTWYQWXMEWYNXUAWXMWYKWYREFWXMWY
    LWYNWXMWYOEFWXNBWXMWXPWXREFFWVNBBWXHWXNEFWXDBWVNWVNWXIEFFWXKVXDCZXUBDZDZVXD
    DWVNDZWXGWXFDVXDBDTVXECDDBDZXUDDZXUEXUCXUCDZXUDDZXUGXUCBDZXUBCZWYBDZDZXUBDX
    UCDZXUIXUBXUKDXULCZXUKDDZXULDXUMDZXUNXULXUKXUJCDZCXUOCDZDXURDXUBDXUPDXUQXUK
    WYBXURXUOXUBEXULXUSXUBXUJXUPEFXUBXUKXULXUBXUMEFXUCBXUBWXKXUCEFXUDBDZXUCCZXU
    FCZDZDZXUCDXUHDZXUIXUGDXUCXVADXVCCZXVADDZXVCDXVDDZXVEXVCXVAXUTCDZCXVFCDZDXV
    IDXUCDXVGDXVHXVAXVBXVIXVFXUCEXVCXVJXUCXUTXVGEFXUCXVAXVCXUCXVDEFXUDBXUCXUFXU
    HEFFVXDBBVXEXUDEFWXDBVXDVXDWVNEFFXJVXBVWSUAWXDEFWVNUGXJUAXLEFFFFRQVXAVWOVWS
    EFVWMUGRUAVWPEFFFFFFAKGHGEFUAJIDZUBJXVKDZUAXVKDZUAXVLUBIBDTJCZDZDBDZHDZXVLD
    ZUAXVLDZIBBJHEXVLUGDKUGDDZHDXVQDZXVRXVSDIXVTCXVNDZCXVPCDZDXWBDZXVTDZXWAXVKX
    VTDZXWEXVLXVTDZXWFYGTKCDDBDZXVLDZXVTDZXWGUGBBKXVLEXVTBDZXVLCZXWLDZDZXVLDXWI
    DZXWJXWGDXVLBDTXWHCDDBDZXWNDZXWOXWMXWMDZXWNDZXWQXWMBDZXWLCZXWKCZDZDZXWLDXWM
    DZXWSXWLXXADXXCCZXXADDZXXCDXXDDZXXEXXCXXAXWTCDZCXXFCDZDXXIDXWLDXXGDXXHXXAXX
    BXXIXXFXWLEXXCXXJXWLXWTXXGEFXWLXXAXXCXWLXXDEFXWMBXWLXWKXWMEFXWNBDZXWMCZXWPC
    ZDZDZXWMDXWRDZXWSXWQDXWMXXLDXXNCZXXLDDZXXNDXXODZXXPXXNXXLXXKCDZCXXQCDZDXXTD
    XWMDXXRDXXSXXLXXMXXTXXQXWMEXXNXYAXWMXXKXXREFXWMXXLXXNXWMXXOEFXWNBXWMXWPXWRE
    FFXVLBBXWHXWNEFXVTBXVLXVLXWIEFFXWKXVKCZXYBDZDZXVKDXVLDZXWGXWFDXVKBDZXVODBDZ
    XYDDZXYEXYCXYCDZXYDDZXYHXYCBDZXYBCZXXBDZDZXYBDXYCDZXYJXYBXYLDZXYMCZXYLDDZXY
    MDXYNDZXYOXYMXYLXYKCDZCZXYQCDZDXYTDXYBDXYRDXYSXYLXXBXYTXYQXYBEXYMYUBXYBXYKX
    YREFXYBXYLXYMXYBXYNEFXYCBXYBXWKXYCEFXYDBDZXYCCZXYGCZDZDZXYCDXYIDZXYJXYHDXYC
    YUDDZYUFCZYUDDDZYUFDYUGDZYUHYUFYUDYUCCDZCYUJCDZDYUMDXYCDYUKDYULYUDYUEYUMYUJ
    XYCEYUFYUNXYCYUCYUKEFXYCYUDYUFXYCYUGEFXYDBXYCXYGXYIEFFXVKBBJXYDEFXVTBXVKXVK
    XVLEFFUAXWFXWEDZUBXVKYUODZUAYUODZXWKTXWDCDDBDZXVKDZYUODZYUPXVTBBXWDXVKEYUOB
    DZXYCDZXVKDYUSDZYUTYUPDXYFTYURCDDBDZYVBDZYVCXYIYVBDZYVEXYKXYLYVACZDZDZXYBDX
    YCDZYVFXYPYVHCZXYLDDZYVHDYVIDZYVJYVHYUAYVKCDZDXYTDXYBDYVLDYVMXYLYVGXYTYVKXY
    BEYVHYVNXYBXYKYVLEFXYBXYLYVHXYBYVIEFXYCBXYBYVAXYCEFYVBBDZYUDYVDCZDZDZXYCDXY
    IDZYVFYVEDYUIYVQCZYUDDDZYVQDYVRDZYVSYVQYUDYVOCDZCYVTCDZDYWCDXYCDYWADYWBYUDY
    VPYWCYVTXYCEYVQYWDXYCYVOYWAEFXYCYUDYVQXYCYVREFYVBBXYCYVDXYIEFFXVKBBYURYVBEF
    YUOBXVKXVKYUSEFFYUOUGDICZUGDDZIDXVKDZYUPYUQDXWEYWFDZYWGYUOYWFDZYWHYGTYWECDD
    BDZYUODZYWFDZYWIUGBBYWEYUOEYWFBDZYUOCZYWNDZDZYUODYWKDZYWLYWIDYVATYWJCDDBDZY
    WPDZYWQYWOYWODZYWPDZYWSYWOBDZYWNCZYWMCZDZDZYWNDYWODZYXAYWNYXCDYXECZYXCDDZYX
    EDYXFDZYXGYXEYXCYXBCDZCYXHCDZDYXKDYWNDYXIDYXJYXCYXDYXKYXHYWNEYXEYXLYWNYXBYX
    IEFYWNYXCYXEYWNYXFEFYWOBYWNYWMYWOEFYWPBDZYWOCZYWRCZDZDZYWODYWTDZYXAYWSDYWOY
    XNDYXPCZYXNDDZYXPDYXQDZYXRYXPYXNYXMCDZCYXSCDZDYYBDYWODYXTDYYAYXNYXOYYBYXSYW
    OEYXPYYCYWOYXMYXTEFYWOYXNYXPYWOYXQEFYWPBYWOYWRYWTEFFYUOBBYWJYWPEFYWFBYUOYUO
    YWKEFFYWMXWECZYYDDZDZXWEDYUODZYWIYWHDXWEBDTXWFCDDBDZYYFDZYYGYYEYYEDZYYFDZYY
    IYYEBDZYYDCZYXDDZDZYYDDYYEDZYYKYYDYYMDYYNCZYYMDDZYYNDYYODZYYPYYNYYMYYLCDZCY
    YQCDZDYYTDYYDDYYRDYYSYYMYXDYYTYYQYYDEYYNUUUAYYDYYLYYREFYYDYYMYYNYYDYYOEFYYE
    BYYDYWMYYEEFYYFBDZYYECZYYHCZDZDZYYEDYYJDZYYKYYIDYYEUUUCDUUUECZUUUCDDZUUUEDU
    UUFDZUUUGUUUEUUUCUUUBCDZCUUUHCDZDUUUKDYYEDUUUIDUUUJUUUCUUUDUUUKUUUHYYEEUUUE
    UUULYYEUUUBUUUIEFYYEUUUCUUUEYYEUUUFEFYYFBYYEYYHYYJEFFXWEBBXWFYYFEFYWFBXWEXW
    EYUOEFFIXWCXVTJYWFEFYUOUGIUAXVKEFFFFHAXWBXVPXVTEFXVLUGHUAXVQEFFFUAXVLXVMDZU
    BXYFVWNDBDZJDZUUUMDZUAUUUMDZXVKBBUAJEUUUMUGDXVNUGDDZJDUUUODZUUUPUUUQDXVKUUU
    RCUGDZCUUUNCDZDUUUTDZUUURDZUUUSXVMUUURDZUUVCUUUMUUURDZUUVDYGTXVNCDDBDZUUUMD
    ZUUURDZUUVEUGBBXVNUUUMEUUURBDZUUUMCZUUVJDZDZUUUMDUUVGDZUUVHUUVEDUUUMBDTUUVF
    CDDBDZUUVLDZUUVMUUVKUUVKDZUUVLDZUUVOUUVKBDZUUVJCZUUVICZDZDZUUVJDUUVKDZUUVQU
    UVJUUVSDUUWACZUUVSDDZUUWADUUWBDZUUWCUUWAUUVSUUVRCDZCUUWDCDZDUUWGDUUVJDUUWED
    UUWFUUVSUUVTUUWGUUWDUUVJEUUWAUUWHUUVJUUVRUUWEEFUUVJUUVSUUWAUUVJUUWBEFUUVKBU
    UVJUUVIUUVKEFUUVLBDZUUVKCZUUVNCZDZDZUUVKDUUVPDZUUVQUUVODUUVKUUWJDUUWLCZUUWJ
    DDZUUWLDUUWMDZUUWNUUWLUUWJUUWICDZCUUWOCDZDUUWRDUUVKDUUWPDUUWQUUWJUUWKUUWRUU
    WOUUVKEUUWLUUWSUUVKUUWIUUWPEFUUVKUUWJUUWLUUVKUUWMEFUUVLBUUVKUUVNUUVPEFFUUUM
    BBUUVFUUVLEFUUURBUUUMUUUMUUVGEFFUUVIXVMCZUUWTDZDZXVMDUUUMDZUUVEUUVDDXVMBDZT
    XWLDDBDZUUXBDZUUXCUUXAUUXADZUUXBDZUUXFUUXABDZUUWTCZUUVTDZDZUUWTDUUXADZUUXHU
    UWTUUXJDZUUXKCZUUXJDDZUUXKDUUXLDZUUXMUUXKUUXJUUXICDZCZUUXOCDZDUUXRDUUWTDUUX
    PDUUXQUUXJUUVTUUXRUUXOUUWTEUUXKUUXTUUWTUUXIUUXPEFUUWTUUXJUUXKUUWTUUXLEFUUXA
    BUUWTUUVIUUXAEFUUXBBDZUUXACZUUXECZDZDZUUXADUUXGDZUUXHUUXFDUUXAUUYBDZUUYDCZU
    UYBDDZUUYDDUUYEDZUUYFUUYDUUYBUUYACDZCUUYHCDZDUUYKDUUXADUUYIDUUYJUUYBUUYCUUY
    KUUYHUUXAEUUYDUUYLUUXAUUYAUUYIEFUUXAUUYBUUYDUUXAUUYEEFUUXBBUUXAUUXEUUXGEFFX
    VMBBXVLUUXBEFUUURBXVMXVMUUUMEFFUAUUVDUUVCDZUBXVMUUYMDZUAUUYMDZUUVITUUVBCDDB
    DZXVMDZUUYMDZUUYNUUURBBUUVBXVMEUUYMBDZUUXADZXVMDUUYQDZUUYRUUYNDUUXDTUUYPCDD
    BDZUUYTDZUVUAUUXGUUYTDZUVUCUUXIUUXJUUYSCZDZDZUUWTDUUXADZUVUDUUXNUVUFCZUUXJD
    DZUVUFDUVUGDZUVUHUVUFUUXSUVUICDZDUUXRDUUWTDUVUJDUVUKUUXJUVUEUUXRUVUIUUWTEUV
    UFUVULUUWTUUXIUVUJEFUUWTUUXJUVUFUUWTUVUGEFUUXABUUWTUUYSUUXAEFUUYTBDZUUYBUVU
    BCZDZDZUUXADUUXGDZUVUDUVUCDUUYGUVUOCZUUYBDDZUVUODUVUPDZUVUQUVUOUUYBUVUMCDZC
    UVURCDZDUVVADUUXADUVUSDUVUTUUYBUVUNUVVAUVURUUXAEUVUOUVVBUUXAUVUMUVUSEFUUXAU
    UYBUVUOUUXAUVUPEFUUYTBUUXAUVUBUUXGEFFXVMBBUUYPUUYTEFUUYMBXVMXVMUUYQEFFUUYMU
    GDXYBUGDDZXVKDXVMDZUUYNUUYODUUVCUVVCDZUVVDUUYMUVVCDZUVVEYGTXYLDDBDZUUYMDZUV
    VCDZUVVFUGBBXYBUUYMEUVVCBDZUUYMCZUVVKDZDZUUYMDUVVHDZUVVIUVVFDUUYSTUVVGCDDBD
    ZUVVMDZUVVNUVVLUVVLDZUVVMDZUVVPUVVLBDZUVVKCZUVVJCZDZDZUVVKDUVVLDZUVVRUVVKUV
    VTDUVWBCZUVVTDDZUVWBDUVWCDZUVWDUVWBUVVTUVVSCDZCUVWECDZDUVWHDUVVKDUVWFDUVWGU
    VVTUVWAUVWHUVWEUVVKEUVWBUVWIUVVKUVVSUVWFEFUVVKUVVTUVWBUVVKUVWCEFUVVLBUVVKUV
    VJUVVLEFUVVMBDZUVVLCZUVVOCZDZDZUVVLDUVVQDZUVVRUVVPDUVVLUVWKDUVWMCZUVWKDDZUV
    WMDUVWNDZUVWOUVWMUVWKUVWJCDZCUVWPCDZDUVWSDUVVLDUVWQDUVWRUVWKUVWLUVWSUVWPUVV
    LEUVWMUVWTUVVLUVWJUVWQEFUVVLUVWKUVWMUVVLUVWNEFUVVMBUVVLUVVOUVVQEFFUUYMBBUVV
    GUVVMEFUVVCBUUYMUUYMUVVHEFFUVVJUUVCCZUVXADZDZUUVCDUUYMDZUVVFUVVEDUUVCBDTUUV
    DCDDBDZUVXCDZUVXDUVXBUVXBDZUVXCDZUVXFUVXBBDZUVXACZUVWADZDZUVXADUVXBDZUVXHUV
    XAUVXJDUVXKCZUVXJDDZUVXKDUVXLDZUVXMUVXKUVXJUVXICDZCUVXNCDZDUVXQDUVXADUVXODU
    VXPUVXJUVWAUVXQUVXNUVXAEUVXKUVXRUVXAUVXIUVXOEFUVXAUVXJUVXKUVXAUVXLEFUVXBBUV
    XAUVVJUVXBEFUVXCBDZUVXBCZUVXECZDZDZUVXBDUVXGDZUVXHUVXFDUVXBUVXTDUVYBCZUVXTD
    DZUVYBDUVYCDZUVYDUVYBUVXTUVXSCDZCUVYECDZDUVYHDUVXBDUVYFDUVYGUVXTUVYAUVYHUVY
    EUVXBEUVYBUVYIUVXBUVXSUVYFEFUVXBUVXTUVYBUVXBUVYCEFUVXCBUVXBUVXEUVXGEFFUUVCB
    BUUVDUVXCEFUVVCBUUVCUUVCUUYMEFFXVKUUVAUUURUAUVVCEFUUYMUGXVKUAXVMEFFFFJIUUUT
    UUUNUUUREFUUUMUGJUAUUUOEFFFFFF $.
    $( [?] $) $( [7-Feb-2013] $)
