;; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.

  ${ $d x y z i j n $.
     $( Finally, we define the betweenness relationship. This relationship
     	intuitively holds iff the three points lie in order on a straight
	line. We express this with two requirements: the non-positivity
	requirement ensures that the two outer points are on either side
	of the inner point, and the equality ensures that they are
	colinear (this is ultimately related to the sum of sines formula). $)
     df-btwn $a |- Btwn = ( n e. NN |->
        `' { <. <. x , y >. , z >. | ( ( x e. ( EE ` n ) /\ y e. ( EE ` n ) /\
				         z e. ( EE ` n ) ) /\
          A. i e. ( 1 ... n ) A. j e. ( 1 ... n ) 
	  ( ( ( ( x ` i ) - ( z ` i ) ) x. ( ( y ` i ) - ( z ` i ) ) ) <_ 0 /\
	    ( ( ( x ` i ) - ( z ` i ) ) x. ( ( y ` j ) - ( z ` j ) ) ) =
	    ( ( ( x ` j ) - ( z ` j ) ) x. ( ( y ` i ) - ( z ` i ) ) ) ) ) 
        } ) $.
  $}

  ${ $d A i j x y z $. $d B i j x y z $. $d C i j x y z $.
     $d N i j n x y z $.
     btwnval.1 $e |- N e. NN $.

     $( The value of the betweenness relationship $)
     btwnval $p |- ( ( A e. ( EE ` N ) /\ 
     	     	       B e. ( EE ` N ) /\ C e. ( EE ` N ) ) ->
     	     	     ( A ( Btwn ` N ) <. B , C >. <->
		       A. i e. ( 1 ... N ) A. j e. ( 1 ... N )
                          ( ( ( ( B ` i ) - ( A ` i ) ) x.
			      ( ( C ` i ) - ( A ` i ) ) ) <_ 0 /\
                            ( ( ( B ` i ) - ( A ` i ) ) x.
			      ( ( C ` j ) - ( A ` j ) ) ) =
			    ( ( ( B ` j ) - ( A ` j ) ) x.
			      ( ( C ` i ) - ( A ` i ) ) ) ) ) ) $=
       ( vy vz vx vn cee cfv wcel w3a cop cv cmin co cmul cc0 cle wbr wceq wa 
       c1 cfz wral copab2 ccnv cbtwn wb cvv opex brcnvg mpan2 3ad2ant1 eleq1 
       3anbi1d fveq1 opreq1d breq1d eqeq12d anbi12d 2ralbidv 3anbi2d opreq2d 
       3anbi3d opreq12d eloprabg bianabs 3comr df-br syl5bb bitrd cn fveq2 
       eleq2d 3anbi123d opreq2 raleq1d raleqbidv oprabbidv cnveq syl df-btwn 
       cxp fvex xpex oprabssxp ssexi cnvex fvmpt ax-mp breqi ) AFLMZNZBWPNZCWPN
       ZOZABCPZHQZWPNZIQZWPNZJQZWPNZOZDQZXBMZXIXFMZRSZXIXDMZXKRSZTSZUAUBUCZXLEQ
       ZXDMZXQXFMZRSZTSZXQXBMZXSRSZXNTSZUDZUEZEUFFUGSZUHZDYGUHZUEZHIJUIZUJZUCZX
       IBMZXIAMZRSZXICMZYORSZTSZUAUBUCZYPXQCMZXQAMZRSZTSZXQBMZUUBRSZYRTSZUDZUEZ
       EYGUHDYGUHZAXAFUKMZUCWTYMXAAYKUCZUUJWQWRYMUULULZWSWQXAUMNUUMBCUNAXAWPUMY
       KUOUPUQWTXAAPYKNZUUJUULWRWSWQUUNUUJULWRWSWQOZUUNUUJYJWRXEXGOZYNXKRSZXNTS
       ZUAUBUCZUUQXTTSZUUEXSRSZXNTSZUDZUEZEYGUHDYGUHZUEWRWSXGOZUUQYQXKRSZTSZUAU
       BUCZUUQUUAXSRSZTSZUVAUVGTSZUDZUEZEYGUHDYGUHZUEUUOUUJUEHIJBCAWPWPWPXBBUDZ
       XHUUPYIUVEUVPXCWRXEXGXBBWPURUSUVPYFUVDDEYGYGUVPXPUUSYEUVCUVPXOUURUAUBUVP
       XLUUQXNTUVPXJYNXKRXIXBBUTVAZVAVBUVPYAUUTYDUVBUVPXLUUQXTTUVQVAUVPYCUVAXNT
       UVPYBUUEXSRXQXBBUTVAVAVCVDVEVDXDCUDZUUPUVFUVEUVOUVRXEWSWRXGXDCWPURVFUVRU
       VDUVNDEYGYGUVRUUSUVIUVCUVMUVRUURUVHUAUBUVRXNUVGUUQTUVRXMYQXKRXIXDCUTVAZV
       GVBUVRUUTUVKUVBUVLUVRXTUVJUUQTUVRXRUUAXSRXQXDCUTVAVGUVRXNUVGUVATUVSVGVCV
       DVEVDXFAUDZUVFUUOUVOUUJUVTXGWQWRWSXFAWPURVHUVTUVNUUIDEYGYGUVTUVIYTUVMUUH
       UVTUVHYSUAUBUVTUUQYPUVGYRTUVTXKYOYNRXIXFAUTZVGZUVTXKYOYQRUWAVGZVIVBUVTUV
       KUUDUVLUUGUVTUUQYPUVJUUCTUWBUVTXSUUBUUARXQXFAUTZVGVIUVTUVAUUFUVGYRTUVTXS
       UUBUUERUWDVGUWCVIVCVDVEVDVJVKVLXAAYKVMVNVOAXAUUKYLFVPNUUKYLUDGKFXBKQZLMZ
       NZXDUWFNZXFUWFNZOZYFEUFUWEUGSZUHZDUWKUHZUEZHIJUIZUJZYLVPUKUWEFUDZUWOYKUD
       UWPYLUDUWQUWNYJHIJUWQUWJXHUWMYIUWQUWGXCUWHXEUWIXGUWQUWFWPXBUWEFLVQZVRUWQ
       UWFWPXDUWRVRUWQUWFWPXFUWRVRVSUWQUWLYHDUWKYGUWEFUFUGVTZUWQYFEUWKYGUWSWAWB
       VDWCUWOYKWDWEHIJDEKWFYKYKWPWPWGZWPWGUWTWPWPWPFLWHZUXAWIUXAWIYIHIJWPWPWPW
       JWKWLWMWNWOVN $.
       $( [?] $) $( [10-Sep-2011] $)
  $}

  ${ $d A i j $. $d B i j $. $d N i j $.
     axbtwn.1 $e |- N e. NN $.

     $( An identity law for betweenness. Axiom 6 of [TarskiGivant]. $)
     axbtwnid $p |- ( ( A e. ( EE ` N ) /\ B e. ( EE ` N ) ) ->
     		        ( A ( Btwn ` N ) <. B , B >. ->
			  A = B ) ) $=
       ( vi vj cee cfv wcel wa cv cmin co cmul cc0 cle wbr wceq c1 cfz wral 
       cop cbtwn cr wf wi wb resubcl msqge0 biantrud letri3 axmulrcl anidms 
       0re sylancl bitr4d syl cc recnd msq0 subeq0 recn syl2an 3bitrd eqcom 
       syl6bb ancoms c0 wne cz 1z cn nnz ax-mp elfz mp3an 1re leidi nnge1 
       mpbir2an ne0i r19.28zv pm3.26bi syl5bi ffvelrn adantlr adantll sylanc 
       r19.20dva elee syl2anb btwnval 3anidm23 wfn eqfnfv2 ffn sylbi 3imtr4d ) 
       ACGHZIZBWSIZJEKZBHZXBAHZLMZXENMZOPQZXEFKZBHXHAHLMZNMXIXENMRZJFSCTMZUAZEX
       KUAZXDXCRZEXKUAZABBUBCUCHQZABRZXKUDAUEZXKUDBUEZXMXOUFWTXAXRXSJZXLXNEXKXD
       UDIZXCUDIZXLXNUFXTXBXKIZJYAYBJXGXNXLYBYAXGXNUGYBYAJZXGXCXDRZXNYDXGXFORZX
       EORZYEYDXEUDIZXGYFUGXCXDUHZYHXGXGOXFPQZJZYFYHYJXGXEUIUJXFUDIZOUDIYFYKUGY
       HXFOUKYHYLXEXEULUMUNUOUPUQYDXEURIYFYGUGYDXEYIUSXEUTUQXCURIXDURIYGYEUGYBY
       AXCXDVAXCVBXDVBVCVDXCXDVEVFVGXLXGXJFXKUAZXKVHVIZXLXGYMJUGSXKIZYNYOSSPQZS
       CPQZSVJIZYRCVJIZYOYPYQJUGVKVKCVLIZYSDCVMVNSSCVOVPSVQVRYTYQDCVSVNVTXKSWAV
       NXGXJFXKWBVNWCWDXRYCYAXSXKUDXBAWEWFXSYCYBXRXKUDXBBWEWGWHWIACDWJZBCDWJZWK
       WTXAXPXMUGABBEFCDWLWMAXKWNZBXKWNZXQXOUGWTXAEXKABWOWTXRUUCUUAXKUDAWPWQXAX
       SUUDUUBXKUDBWPWQVCWR $.
       $( [?] $) $( [14-Sep-2011] $)

    ${ $d N a b c i j n $.
      axlowdim2.1 $e |- 2 <_ N $.

      $( For a Euclidean space with dimension at least two, there are three
      	 non-colinear points. Axiom 10(2) of [TarskiGivant]. $)
      axlowdim2 $p |- E. a e. ( EE ` N ) E. b e. ( EE ` N ) E. c e. ( EE ` N )
                      ( -. a ( Btwn ` N ) <. b , c >. /\ 
		        -. b ( Btwn ` N ) <. c , a >. /\
			-. c ( Btwn ` N ) <. a , b >. ) $=
        ( vn vi vj c1 cfz co cv wceq cc0 cif cmpt cee cfv wcel c2 cop cbtwn 
        wbr wn w3a wrex axbtwnlem2 csn cxp axbtwnlem1 cmin cmul cle wa wral 
        cneg cz wb 1z cn nnz ax-mp elfz mp3an 1re leidi nnge1 mpbir2an 2z 2nn 
        wne ax1ne0 necom mpbi ax1cn negcli mulcomi eqeq2i 0cn negne0i mulcani 
        bitri nemtbir fveq2 caddc df-2 addid1i eqcomi eqeq12i addcani eqeq1 
        mtbiri con2i iffalse syl eqid cc elisseti fvmpt syl6eq iftrue opreq12d 
        df-neg syl6eqr opreq1d fvconst2 opreq2d eqeq12d notbid subid1i 
        rcla42ev rexnal rexbii pm3.27 r19.20si mto btwnval mtbir eqeq1i eqcom 
        3bitri mulid1i subcli mul02i 3pm3.2i opeq2 breq2d opeq1 breq1 
        3anbi123d rcla4ev mp2an rexbidv ) GJAKLZGMZJNZJOPZQZARSZTZGYOYPUANZJOPZ
        QZYTTZYSUUDDMZUBZAUCSZUDZUEZUUDUUFYSUBZUUHUDZUEZUUFYSUUDUBZUUHUDZUEZUFZ
        DYTUGZBMZCMZUUFUBZUUHUDZUEZUUTUUFUUSUBZUUHUDZUEZUUFUUSUUTUBZUUHUDZUEZUF
        ZDYTUGZCYTUGBYTUGJGAEUHZUAGAEUHZYOOUIUJZYTTZYSUUDUVNUBZUUHUDZUEZUUDUVNY
        SUBZUUHUDZUEZUVNUUNUUHUDZUEZUFZUURAEUKZUVRUWAUWCUVQHMZUUDSZUWFYSSZULLZU
        WFUVNSZUWHULLZUMLOUNUDZUWIIMZUVNSZUWMYSSZULLZUMLZUWMUUDSZUWOULLZUWKUMLZ
        NZUOZIYOUPZHYOUPZUXDUXAIYOUPZHYOUPZUXAUEZIYOUGZHYOUGZUXFUEZJYOTZUAYOTZJ
        UQZOUMLZJUXMUMLZNZUEZUXIUXKJJUNUDZJAUNUDZJURTZUXTAURTZUXKUXRUXSUOUSUTUT
        AVATZUYAEAVBVCZJJAVDVEJVFVGUYBUXSEAVHVCVIZUXLJUAUNUDZUAAUNUDZUAURTUXTUY
        AUXLUYEUYFUOUSVJUTUYCUAJAVDVEUAVATUYEVKUAVHVCFVIZUXPOJJOVLOJVLVMJOVNVOU
        XPUXNUXMJUMLZNZOJNZUXOUYHUXNJUXMVPJVPVQZVRVSOJUXMVTVPUYKJVPVMWAWBZWCWDU
        XGUXQUXMUWPUMLZUWSUXMUMLZNZUEHIJUAYOYOUWFJNZUXAUYOUYPUWQUYMUWTUYNUYPUWI
        UXMUWPUMUYPUWIOJULLZUXMUYPUWGOUWHJULUYPUWGJUUDSZOUWFJUUDWEUXKUYRONUYDGJ
        UUCOYOUUDYQUUBUEUUCONUUBYQUUBYQUAJNZUYSJOVMUYSJJWFLZJOWFLZNJONZUAUYTJVU
        AWGVUAJJVPWHWIWJJJOVPVPVTWKWCWDYPUAJWLWMZWNUUBJOWOWPUUDWQZOWRVTWSZWTVCX
        AZUYPUWHJYSSZJUWFJYSWEUXKVUGJNUYDGJYRJYOYSYQJOXBYSWQZJWRVPWSZWTVCXAZXCJ
        XDZXEXFUYPUWKUXMUWSUMUYPUWKUYQUXMUYPUWJOUWHJULUYPUWJJUVNSZOUWFJUVNWEUXK
        VULONUYDYOOJVUEXGVCXAZVUJXCVUKXEXHXIXJUWMUANZUYOUXPVUNUYMUXNUYNUXOVUNUW
        POUXMUMVUNUWPOOULLZOVUNUWNOUWOOULVUNUWNUAUVNSZOUWMUAUVNWEUXLVUPONUYGYOO
        UAVUEXGVCXAZVUNUWOUAYSSZOUWMUAYSWEUXLVURONUYGGUAYROYOYSUUBYQUEYRONVUCYQ
        JOWOWPVUHVUEWTVCXAZXCOVTXKZXAXHVUNUWSJUXMUMVUNUWSJOULLZJVUNUWRJUWOOULVU
        NUWRUAUUDSZJUWMUAUUDWEUXLVVBJNUYGGUAUUCJYOUUDUUBJOXBVUDVUIWTVCXAZVUSXCJ
        VPXKZXAXFXIXJXLVEUXIUXEUEZHYOUGUXJUXHVVEHYOUXAIYOXMXNUXEHYOXMWCVOUXCUXE
        HYOUXBUXAIYOUWLUXAXOXPXPXQUUAUUEUVOUVQUXDUSUVLUVMUWEYSUUDUVNHIAEXRVEXSU
        VTUWJUWGULLZUWHUWGULLZUMLOUNUDZVVFUWOUWRULLZUMLZUWNUWRULLZVVGUMLZNZUOZI
        YOUPZHYOUPZVVPVVMIYOUPZHYOUPZVVMUEZIYOUGZHYOUGZVVRUEZUXKUXLOUXMUMLZUYHN
        ZUEZVWAUYDUYGVWDJOVMVWDUYIUYJVUBVWCUXNUYHOUXMVTUYKVRXTUYLOJYAYBWDVVSVWE
        OVVIUMLZVVKJUMLZNZUEHIJUAYOYOUYPVVMVWHUYPVVJVWFVVLVWGUYPVVFOVVIUMUYPVVF
        VUOOUYPUWJOUWGOULVUMVUFXCVUTXAXFUYPVVGJVVKUMUYPVVGVVAJUYPUWHJUWGOULVUJV
        UFXCVVDXAXHXIXJVUNVWHVWDVUNVWFVWCVWGUYHVUNVVIUXMOUMVUNVVIUYQUXMVUNUWOOU
        WRJULVUSVVCXCVUKXEXHVUNVVKUXMJUMVUNVVKUYQUXMVUNUWNOUWRJULVUQVVCXCVUKXEX
        FXIXJXLVEVWAVVQUEZHYOUGVWBVVTVWIHYOVVMIYOXMXNVVQHYOXMWCVOVVOVVQHYOVVNVV
        MIYOVVHVVMXOXPXPXQUUEUVOUUAUVTVVPUSUVMUWEUVLUUDUVNYSHIAEXRVEXSUWBUWHUWJ
        ULLZUWGUWJULLZUMLOUNUDZVWJUWRUWNULLZUMLZUWOUWNULLZVWKUMLZNZUOZIYOUPZHYO
        UPZVWTVWQIYOUPZHYOUPZVWQUEZIYOUGZHYOUGZVXBUEZUXKUXLJJUMLZOVUOUMLZNZUEZV
        XEUYDUYGVXIJOVMVXGJVXHOJVPYCVUOOOVTVTYDYEWJWDVXCVXJJVWMUMLZVWOVUOUMLZNZ
        UEHIJUAYOYOUYPVWQVXMUYPVWNVXKVWPVXLUYPVWJJVWMUMUYPVWJVVAJUYPUWHJUWJOULV
        UJVUMXCVVDXAXFUYPVWKVUOVWOUMUYPUWGOUWJOULVUFVUMXCXHXIXJVUNVXMVXIVUNVXKV
        XGVXLVXHVUNVWMJJUMVUNVWMVVAJVUNUWRJUWNOULVVCVUQXCVVDXAXHVUNVWOOVUOUMVUN
        VWOVUOOVUNUWOOUWNOULVUSVUQXCVUTXAXFXIXJXLVEVXEVXAUEZHYOUGVXFVXDVXNHYOVW
        QIYOXMXNVXAHYOXMWCVOVWSVXAHYOVWRVWQIYOVWLVWQXOXPXPXQUVOUUAUUEUWBVWTUSUW
        EUVLUVMUVNYSUUDHIAEXRVEXSYFUUQUWDDUVNYTUUFUVNNZUUJUVRUUMUWAUUPUWCVXOUUI
        UVQVXOUUGUVPYSUUHUUFUVNUUDYGYHXJVXOUULUVTVXOUUKUVSUUDUUHUUFUVNYSYIYHXJV
        XOUUOUWBUUFUVNUUNUUHYJXJYKYLYMUVKUURYSUVAUUHUDZUEZUUTUUKUUHUDZUEZUUFYSU
        UTUBZUUHUDZUEZUFZDYTUGBCYSUUDYTYTUUSYSNZUVJVYCDYTVYDUVCVXQUVFVXSUVIVYBV
        YDUVBVXPUUSYSUVAUUHYJXJVYDUVEVXRVYDUVDUUKUUTUUHUUSYSUUFYGYHXJVYDUVHVYAV
        YDUVGVXTUUFUUHUUSYSUUTYIYHXJYKYNUUTUUDNZVYCUUQDYTVYEVXQUUJVXSUUMVYBUUPV
        YEVXPUUIVYEUVAUUGYSUUHUUTUUDUUFYIYHXJVYEVXRUULUUTUUDUUKUUHYJXJVYEVYAUUO
        VYEVXTUUNUUFUUHUUTUUDYSYGYHXJYKYNXLVE $.
        $( [?] $) $( [14-Sep-2011] $)
    $}

  $}
