$( -*-text-*- $)


  $( Declare the primitive constant symbols for propositional calculus. $)
  $c ( $.  $( Left parenthesis $)
  $c ) $.  $( Right parenthesis $)
  $c -> $. $( Right arrow (read:  "implies") $)
  $c -. $. $( Right handle (read:  "not") $)
  $c wff $. $( Well-formed formula symbol (read:  "the following symbol
               sequence is a wff") $)
  $c |- $. $( Turnstile (read:  "the following symbol sequence is provable" or
              'a proof exists for") $)

  $( Introduce some variable names we will use to represent well-formed
     formulas (wff's). $)
  $v ph $. $( Greek phi $)
  $v ps $.  $( Greek psi $)
  $v ch $.  $( Greek chi $)
  $v th $.  $( Greek theta $)
  $v ta $.  $( Greek tau $)
  $v et $.  $( Greek eta $)
  $v ze $.  $( Greek zeta $)
  $v ep $.
  $v DUMMY $.

  $( Specify some variables that we will use to represent wff's.
     The fact that a variable represents a wff is relevant only to a theorem
     referring to that variable, so we may use $f hypotheses.  The symbol
     ` wff ` specifies that the variable that follows it represents a wff. $)
  $( Let variable ` ph ` be a wff. $)
  wph $f wff ph $.
  $( Let variable ` ps ` be a wff. $)
  wps $f wff ps $.
  $( Let variable ` ch ` be a wff. $)
  wch $f wff ch $.
  $( Let variable ` th ` be a wff. $)
  wth $f wff th $.
  $( Let variable ` ta ` be a wff. $)
  wta $f wff ta $.
  wet $f wff et $.
  wze $f wff ze $.
  wep $f wff ep $.
  wdummy $f wff DUMMY $.

$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
                           Propositional calculus
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
$)

$(
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        Recursively define primitive wffs for propositional calculus
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
$)

  $( If ` ph ` is a wff, so is ` -. ph ` or "not ` ph ` ."  Part of the
     recursive definition of a wff (well-formed formula).  In classical logic
     (which is our logic), a wff is interpreted as either true or false.
     So if ` ph ` is true, then ` -. ph ` is false; if ` ph ` is false, then
     ` -. ph ` is true.  Traditionally, Greek letters are used to represent
     wffs, and we follow this convention.  In propositional calculus, we define
     only wffs built up from other wffs, i.e. there is no starting or "atomic"
     wff.  Later, in predicate calculus, we will extend the basic wff
     definition by including atomic wffs ( ~ weq and ~ wel ). $)
  wn $a wff -. ph $.

  $( If ` ph ` and ` ps ` are wff's, so is ` ( ph -> ps ) ` or " ` ph ` implies
     ` ps ` ."  Part of the recursive definition of a wff.  The resulting wff
     is (interpreted as) false when ` ph ` is true and ` ps ` is false; it is
     true otherwise.  (Think of the truth table for an OR gate with input
     ` ph ` connected through an inverter.)  The left-hand wff is called the
     antecedent, and the right-hand wff is called the consequent.  In the case
     of ` ( ph -> ( ps -> ch ) ) ` , the middle ` ps ` may be informally called
     either an antecedent or part of the consequent depending on context. $)
  wi $a wff ( ph -> ps ) $.

$(
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        The axioms of propositional calculus
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
$)

  $(
     Postulate the three axioms of classical propositional calculus.
  $)

  $( Axiom _Simp_.  Axiom A1 of [Margaris] p. 49.  One of the 3 axioms of
     propositional calculus.  The 3 axioms are also given as Definition 2.1
     of [Hamilton] p. 28.  This axiom is called _Simp_ or "the principle of
     simplification" in _Principia Mathematica_ (Theorem *2.02 of
     [WhiteheadRussell] p. 100) because "it enables us to pass from the joint
     assertion of ` ph ` and ` ps ` to the assertion of ` ph ` simply."

     _General remarks_:  Propositional calculus (axioms ~ ax-1 through ~ ax-3
     and rule ~ ax-mp ) can be thought of as asserting formulas that are
     universally "true" when their variables are replaced by any combination
     of "true" and "false."  Propositional calculus was first formalized by
     Frege in 1879, using as his axioms (in addition to rule ~ ax-mp ) the
     wffs ~ ax-1 , ~ ax-2 , ~ pm2.04 , ~ con3 , ~ notnot2 , and ~ notnot1 .
     Around 1930, Lukasiewicz simplified the system by eliminating the third
     (which follows from the first two, as you can see by looking at the proof
     of ~ pm2.04 ) and replacing the last three with our ~ ax-3 .  (Thanks to
     Ted Ulrich for this information.)

     The theorems of propositional calculus are also called _tautologies_.
     Tautologies can be proved very simply using truth tables, based on the
     true/false interpretation of propositional calculus.  To do this, we
     assign all possible combinations of true and false to the wff variables
     and verify that the result (using the rules described in ~ wi and ~ wn )
     always evaluates to true.  This is called the _semantic_ approach.  Our
     approach is called the _syntactic_ approach, in which everything is
     derived from axioms.  A metatheorem called the Completeness Theorem for
     Propositional Calculus shows that the two approaches are equivalent and
     even provides an algorithm for automatically generating syntactic proofs
     from a truth table.  Those proofs, however, tend to be long, and the
     much shorter proofs that we show here were found manually.  Truth tables
     grow exponentially with the number of variables, but it is unknown if the
     same is true of proofs - an answer to this would resolve the P=NP
     conjecture in complexity theory. $)
  ax-1 $a |- ( ph -> ( ps -> ph ) ) $.
  $( [ ?] $) $( [ ?] $)

  $( Axiom _Frege_.  Axiom A2 of [Margaris] p. 49.  One of the 3 axioms of
     propositional calculus.  It "distributes" an antecedent over two
     consequents.  This axiom was part of Frege's original system and is known
     as _Frege_ in the literature.  It is also proved as Theorem *2.77 of
     [WhiteheadRussell] p. 108.  The other direction of this axiom also
     turns out to be true, as demonstrated by ~ pm5.41 . $)
  ax-2 $a |- ( ( ph -> ( ps -> ch ) ) -> ( ( ph -> ps ) -> ( ph -> ch ) ) ) $.

  $( Axiom _Transp_.  Axiom A3 of [Margaris] p. 49.  One of the 3 axioms of
     propositional calculus.  It swaps or "transposes" the order of the
     consequents when negation is removed.  An informal example is that the
     statement "if there are no clouds in the sky, it is not raining" implies
     the statement "if it is raining, there are clouds in the sky."  This
     axiom is called _Transp_ or "the principle of transposition" in
     _Principia Mathematica_ (Theorem *2.17 of [WhiteheadRussell] p. 103).
     We will also use the term "contraposition" for this principle, although
     the reader is advised that in the field of philosophical logic,
     "contraposition" has a different technical meaning. $)
  ax-3 $a |- ( ( -. ph -> -. ps ) -> ( ps -> ph ) ) $.

  $(
     Postulate the modus ponens rule of inference.
  $)

  ${
    $( Minor premise for modus ponens. $)
    min $e |- ph $.
    $( Major premise for modus ponens. $)
    maj $e |- ( ph -> ps ) $.
    $( Rule of Modus Ponens.  The postulated inference rule of propositional
       calculus.  See e.g. Rule 1 of [Hamilton] p. 73.  The rule says, "if
       ` ph ` is true, and ` ph ` implies ` ps ` , then ` ps ` must also be
       true."  This rule is sometimes called "detachment," since it detaches
       the minor premise from the major premise.

       Note:  In some web page displays such as the Statement List, the symbols
       "&" and "=>" informally indicate the relationship between the hypotheses
       and the assertion (conclusion), abbreviating the English words "and" and
       "implies."  They are not part of the formal language. $)
    ax-mp $a |- ps $.
  $}

  pm4.39 $p |- ( -. ( -. ( ( ph -> ps ) -> -. ( ch -> th ) ) -> -. -. ( ( ta -> et ) -> -. ( ze -> ep ) ) ) -> -. ( ( ( -. ph -> ta ) -> ( -. ps -> et ) ) -> -. ( ( -. ch -> ze ) -> ( -. th -> ep ) ) ) ) $=
    ( wdummy wi wn ax-1 ax-3 ax-mp ax-2 ) ABJZCDJZKZJZKZEFJZGHJZKZJZKZKZJZKZPUA
    KZJZKZQUCJZKZKZJZKZJZUHAKZEJZBKZFJZJZCKZGJZDKZHJZJZKZJZKZJZUPKZUHKZJZUQVLUG
    JZVNVLUOJZVOVLIVLJZJZVPVLILVLVQUOJZJZVRVPJVLUPVQKZJZJZVTVLWAKZVLJZJZWCVLWDL
    VLWEWBJZJZWFWCJWGWHWAUPMWGVLLNVLWEWBONNVLWBVSJZJZWCVTJWIWJUOVQMWIVLLNVLWBVS
    ONNVLVQUOONNVLUOUGJZJZVPVOJWKWLUOUESJZJZWKUOUMUJJZJZWNUJUMMUOWOWMJZJZWPWNJW
    QWRWOPUMUIJZJZJZWQWOPUMPJZWSJZJZJZXAWOXCJZXEUMPUIOWOXCXDJZJZXFXEJXGXHXCPLXG
    WOLNWOXCXDONNWOXDWTJZJZXEXAJXIXJXDPXBJZJZXIXKXLPUMLXKXDLNXDXKWTJJXLXIJPXBWS
    OXDXKWTONNXIWOLNWOXDWTONNWOWTWMJZJZXAWQJXMXNWTPUERJZJZJZXMWTPUAULJZJZJZXQPW
    SXRJZJZXTYAYBULUAMYAPLNPWSXRONWTXSXPJZJZXTXQJYCYDXSPQUDJZJZJZYCPXRYEJZJZYGY
    HYIXRQUAQJZUDJZJZJZYHXRYKJZYMUAQUCOXRYKYLJZJZYNYMJYOYPYKQLYOXRLNXRYKYLONNXR
    YLYEJZJZYMYHJYQYRYLQYJJZJZYQYSYTQUALYSYLLNYLYSYEJJYTYQJQYJUDOYLYSYEONNYQXRL
    NXRYLYEONNYHPLNPXRYEONXSYFXPJZJZYGYCJUUAUUBPYEXOJZJZUUAUUCUUDYEQUFJZJZUUCQU
    DUFJZJZUUFUUGUUHUFKZUEJZUUGUUIIUUIJZJZUUJUUIILUUIUUKUEJZJZUULUUJJUUIUFUUKKZ
    JZJZUUNUUIUUOKZUUIJZJZUUQUUIUURLUUIUUSUUPJZJZUUTUUQJUVAUVBUUOUFMUVAUUILNUUI
    UUSUUPONNUUIUUPUUMJZJZUUQUUNJUVCUVDUEUUKMUVCUUILNUUIUUPUUMONNUUIUUKUEONNUFU
    DMNZUUGQLNQUDUFONYEUUEXOJZJZUUFUUCJUVFUVGUUERKZUFJZJZUVFUUEUVHUUEJZJZUVJUUE
    UVHLUUEUVKUVIJZJZUVLUVJJUVMUVNUVKUVHQJZJZUVMUVHUUEQJZJZUVPUVHRUUEKZJZJZUVRU
    VHUVSKZUVHJZJZUWAUVHUWBLUVHUWCUVTJZJZUWDUWAJUWEUWFUVSRMUWEUVHLNUVHUWCUVTONN
    UVHUVTUVQJZJZUWAUVRJUWGUWHQUUEMUWGUVHLNUVHUVTUVQONNUVHUUEQONUVKUVOUVIJJUVPU
    VMJUVHQUFOUVKUVOUVIONNUVMUUELNUUEUVKUVIONNUUEUVIXOJZJZUVJUVFJUWIUWJRUEMUWIU
    UELNUUEUVIXOONNUVFYELNYEUUEXOONNUUCPLNPYEXOONUUAXSLNXSYFXPONNYCWTLNWTXSXPON
    NWTXPWMJZJZXQXMJUWKUWLXPUEPUEJZSJZJZJZUWKXPUWNJZUWPPUEROXPUWNUWOJZJZUWQUWPJ
    UWRUWSUWNUELUWRXPLNXPUWNUWOONNXPUWOWMJZJZUWPUWKJUWTUXAUWOUEUWMJZJZUWTUXBUXC
    UEPLUXBUWOLNUWOUXBWMJJUXCUWTJUEUWMSOUWOUXBWMONNUWTXPLNXPUWOWMONNUWKWTLNWTXP
    WMONNXMWOLNWOWTWMONNWQUOLNUOWOWMONNUOWMUGJZJZWNWKJUXDUXEWMUETKZJZJZUXDUESUX
    FJZJZUXHUXIUXJUXFKZTJZUXIUXKIUXKJZJZUXLUXKILUXKUXMTJZJZUXNUXLJUXKUXFUXMKZJZ
    JZUXPUXKUXQKZUXKJZJZUXSUXKUXTLUXKUYAUXRJZJZUYBUXSJUYCUYDUXQUXFMUYCUXKLNUXKU
    YAUXRONNUXKUXRUXOJZJZUXSUXPJUYEUYFTUXMMUYEUXKLNUXKUXRUXOONNUXKUXMTONNUXFSMN
    UXIUELNUESUXFONWMUXGUGJZJZUXHUXDJUYGUYHUXGTUDJZJZUYGUDTMUXGUYIUGJZJZUYJUYGJ
    UYKUYLTUUGJZUYKUUGUYMUVEUUGTLNTUDUFONUYKUXGLNUXGUYIUGONNUYGWMLNWMUXGUGONNUX
    DUOLNUOWMUGONNWKVLLNVLUOUGONNVLUGVMJZJZVOVNJUYNUYOVMKZUHJZUYNUYPIUYPJZJZUYQ
    UYPILUYPUYRUHJZJZUYSUYQJUYPVMUYRKZJZJZVUAUYPVUBKZUYPJZJZVUDUYPVUELUYPVUFVUC
    JZJZVUGVUDJVUHVUIVUBVMMVUHUYPLNUYPVUFVUCONNUYPVUCUYTJZJZVUDVUAJVUJVUKUHUYRM
    VUJUYPLNUYPVUCUYTONNUYPUYRUHONNVMUGMNUYNVLLNVLUGVMONNUPUHMNUHUPVJJZJZUQVKJV
    ULVUMVJKZVLJZVULVUNUOJZVUOVUNVIJZVUPVUNIVUNJZJZVUQVUNILVUNVURVIJZJZVUSVUQJV
    UNVJVURKZJZJZVVAVUNVVBKZVUNJZJZVVDVUNVVELVUNVVFVVCJZJZVVGVVDJVVHVVIVVBVJMVV
    HVUNLNVUNVVFVVCONNVUNVVCVUTJZJZVVDVVAJVVJVVKVIVURMVVJVUNLNVUNVVCVUTONNVUNVU
    RVIONNVUNVIUOJZJZVUQVUPJVVLVVMUKVBJZVVLUKUSUKJZJZVVNUKUSLUKVVOVBJZJZVVPVVNJ
    VVQVVRUSUKVAJZJZVVQUSVAKZUJJZJZVVTUSPVWAUIJZJZJZVWCUSPUAVAJZJZJZVWFUSUTURJZ
    VWGJZJZVWIUSUTUSJZJZVWLUSUTLUSVWMVWKJZJZVWNVWLJVWOVWPVWMVWJUTEJZJZJZVWOUTUR
    EOVWMVWRVWKJZJZVWSVWOJVWTVXAVWJVWQVWGJZJZVWTVXBVXCVWQUAVWQJZJZVXBVWQUALVWQV
    XDVWGJZJZVXEVXBJVXFVXGUAVWQVAJZJZVXFUAUTUAJZJZVXIUAUTLUAVXJVXHJZJZVXKVXIJVX
    LVXMUTEFOVXLUALNUAVXJVXHONNUAVWQVAONVXFVWQLNVWQVXDVWGONNVXBVWJLNVWJVWQVWGON
    VWTVWMLNVWMVWRVWKONNVWOUSLNUSVWMVWKONNUSVWKVWHJZJZVWLVWIJVXNVXOVWKPVWJJZJZV
    XNVXPVXQPAUTKZJZJZVXPABVXRJZJZVXTVYAVYBVXRKZUTJZVYAVYCIVYCJZJZVYDVYCILVYCVY
    EUTJZJZVYFVYDJVYCVXRVYEKZJZJZVYHVYCVYIKZVYCJZJZVYKVYCVYLLVYCVYMVYJJZJZVYNVY
    KJVYOVYPVYIVXRMVYOVYCLNVYCVYMVYJONNVYCVYJVYGJZJZVYKVYHJVYQVYRUTVYEMVYQVYCLN
    VYCVYJVYGONNVYCVYEUTONNVXRBMNVYAALNABVXRONPVXSVWJJZJZVXTVXPJVYSVYTVXSURKZVX
    RJZJZVYSVXSWUAVXSJZJZWUCVXSWUALVXSWUDWUBJZJZWUEWUCJWUFWUGWUDWUAAJZJZWUFWUAV
    XSAJZJZWUIWUAURVXSKZJZJZWUKWUAWULKZWUAJZJZWUNWUAWUOLWUAWUPWUMJZJZWUQWUNJWUR
    WUSWULURMWURWUALNWUAWUPWUMONNWUAWUMWUJJZJZWUNWUKJWUTWVAAVXSMWUTWUALNWUAWUMW
    UJONNWUAVXSAONWUDWUHWUBJJWUIWUFJWUAAVXROWUDWUHWUBONNWUFVXSLNVXSWUDWUBONNVXS
    WUBVWJJZJZWUCVYSJWVBWVCURUTMWVBVXSLNVXSWUBVWJONNVYSPLNPVXSVWJONNVXPVWKLNVWK
    VXPVWHJZJZVXQVXNJVWKPVWKJZJZWVEVWKPLVWKWVFWVDJZJZWVGWVEJWVHWVIPVWJVWGOWVHVW
    KLNVWKWVFWVDONNVWKVXPVWHONNVXNUSLNUSVWKVWHONNUSVWHVWEJZJZVWIVWFJWVJWVKPVWGV
    WDJZJZWVJWVLWVMVWGUAVWAKZJZJZWVLUAVAWVNJZJZWVPWVQWVRWVNKZVWAJZWVQWVSIWVSJZJ
    ZWVTWVSILWVSWWAVWAJZJZWWBWVTJWVSWVNWWAKZJZJZWWDWVSWWEKZWVSJZJZWWGWVSWWHLWVS
    WWIWWFJZJZWWJWWGJWWKWWLWWEWVNMWWKWVSLNWVSWWIWWFONNWVSWWFWWCJZJZWWGWWDJWWMWW
    NVWAWWAMWWMWVSLNWVSWWFWWCONNWVSWWAVWAONNWVNVAMNWVQUALNUAVAWVNONVWGWVOVWDJZJ
    ZWVPWVLJWWOWWPWVOUIKZWVNJZJZWWOWVOWWQWVOJZJZWWSWVOWWQLWVOWWTWWRJZJZWXAWWSJW
    XBWXCWWTWWQUAJZJZWXBWWQWVOUAJZJZWXEWWQUIWVOKZJZJZWXGWWQWXHKZWWQJZJZWXJWWQWX
    KLWWQWXLWXIJZJZWXMWXJJWXNWXOWXHUIMWXNWWQLNWWQWXLWXIONNWWQWXIWXFJZJZWXJWXGJW
    XPWXQUAWVOMWXPWWQLNWWQWXIWXFONNWWQWVOUAONWWTWXDWWRJJWXEWXBJWWQUAWVNOWWTWXDW
    WRONNWXBWVOLNWVOWWTWWRONNWVOWWRVWDJZJZWWSWWOJWXRWXSUIVWAMWXRWVOLNWVOWWRVWDO
    NNWWOVWGLNVWGWVOVWDONNWVLPLNPVWGVWDONWVJUSLNUSVWHVWEONNUSVWEVWBJZJZVWFVWCJW
    XTWYAVWEVWAPVWAJZUJJZJZJZWXTVWEWYCJZWYEPVWAUIOVWEWYCWYDJZJZWYFWYEJWYGWYHWYC
    VWALWYGVWELNVWEWYCWYDONNVWEWYDVWBJZJZWYEWXTJWYIWYJWYDVWAWYBJZJZWYIWYKWYLVWA
    PLWYKWYDLNWYDWYKVWBJJWYLWYIJVWAWYBUJOWYDWYKVWBONNWYIVWELNVWEWYDVWBONNWXTUSL
    NUSVWEVWBONNUSVWBVVSJZJZVWCVVTJWYMWYNVWBVWAUKKZJZJZWYMVWAUJWYOJZJZWYQWYRWYS
    WYOKZUKJZWYRWYTIWYTJZJZXUAWYTILWYTXUBUKJZJZXUCXUAJWYTWYOXUBKZJZJZXUEWYTXUFK
    ZWYTJZJZXUHWYTXUILWYTXUJXUGJZJZXUKXUHJXULXUMXUFWYOMXULWYTLNWYTXUJXUGONNWYTX
    UGXUDJZJZXUHXUEJXUNXUOUKXUBMXUNWYTLNWYTXUGXUDONNWYTXUBUKONNWYOUJMNWYRVWALNV
    WAUJWYOONVWBWYPVVSJZJZWYQWYMJXUPXUQVAUKMXUPVWBLNVWBWYPVVSONNWYMUSLNUSVWBVVS
    ONNUSUKVAONVVQUKLNUKVVOVBONNVHUNJZVVNVVLJZUNKZVHKZJZXURXUTVGJZXVBXUTUMJZXVC
    XUTIXUTJZJZXVDXUTILXUTXVEUMJZJZXVFXVDJXUTUNXVEKZJZJZXVHXUTXVIKZXUTJZJZXVKXU
    TXVLLXUTXVMXVJJZJZXVNXVKJXVOXVPXVIUNMXVOXUTLNXUTXVMXVJONNXUTXVJXVGJZJZXVKXV
    HJXVQXVRUMXVEMXVQXUTLNXUTXVJXVGONNXUTXVEUMONNZXUTUMVGJZJZXVDXVCJXVTXWAUMVDU
    MJZJZXVTUMVDLUMXWBVGJZJZXWCXVTJXWDXWEVDUMVFJZJZXWDVDVFKZULJZJZXWGVDQXWHUCJZ
    JZJZXWJVDQUBVFJZJZJZXWMVDVEVCJZXWNJZJZXWPVDVEVDJZJZXWSVDVELVDXWTXWRJZJZXXAX
    WSJXXBXXCXWTXWQVEGJZJZJZXXBVEVCGOXWTXXEXWRJZJZXXFXXBJXXGXXHXWQXXDXWNJZJZXXG
    XXIXXJXXDUBXXDJZJZXXIXXDUBLXXDXXKXWNJZJZXXLXXIJXXMXXNUBXXDVFJZJZXXMUBVEUBJZ
    JZXXPUBVELUBXXQXXOJZJZXXRXXPJXXSXXTVEGHOXXSUBLNUBXXQXXOONNUBXXDVFONXXMXXDLN
    XXDXXKXWNONNXXIXWQLNXWQXXDXWNONXXGXWTLNXWTXXEXWRONNXXBVDLNVDXWTXWRONNVDXWRX
    WOJZJZXWSXWPJXYAXYBXWRQXWQJZJZXYAXYCXYDQCVEKZJZJZXYCCDXYEJZJZXYGXYHXYIXYEKZ
    VEJZXYHXYJIXYJJZJZXYKXYJILXYJXYLVEJZJZXYMXYKJXYJXYEXYLKZJZJZXYOXYJXYPKZXYJJ
    ZJZXYRXYJXYSLXYJXYTXYQJZJZYUAXYRJYUBYUCXYPXYEMYUBXYJLNXYJXYTXYQONNXYJXYQXYN
    JZJZXYRXYOJYUDYUEVEXYLMYUDXYJLNXYJXYQXYNONNXYJXYLVEONNXYEDMNXYHCLNCDXYEONQX
    YFXWQJZJZXYGXYCJYUFYUGXYFVCKZXYEJZJZYUFXYFYUHXYFJZJZYUJXYFYUHLXYFYUKYUIJZJZ
    YULYUJJYUMYUNYUKYUHCJZJZYUMYUHXYFCJZJZYUPYUHVCXYFKZJZJZYURYUHYUSKZYUHJZJZYV
    AYUHYVBLYUHYVCYUTJZJZYVDYVAJYVEYVFYUSVCMYVEYUHLNYUHYVCYUTONNYUHYUTYUQJZJZYV
    AYURJYVGYVHCXYFMYVGYUHLNYUHYUTYUQONNYUHXYFCONYUKYUOYUIJJYUPYUMJYUHCXYEOYUKY
    UOYUIONNYUMXYFLNXYFYUKYUIONNXYFYUIXWQJZJZYUJYUFJYVIYVJVCVEMYVIXYFLNXYFYUIXW
    QONNYUFQLNQXYFXWQONNXYCXWRLNXWRXYCXWOJZJZXYDXYAJXWRQXWRJZJZYVLXWRQLXWRYVMYV
    KJZJZYVNYVLJYVOYVPQXWQXWNOYVOXWRLNXWRYVMYVKONNXWRXYCXWOONNXYAVDLNVDXWRXWOON
    NVDXWOXWLJZJZXWPXWMJYVQYVRQXWNXWKJZJZYVQYVSYVTXWNUBXWHKZJZJZYVSUBVFYWAJZJZY
    WCYWDYWEYWAKZXWHJZYWDYWFIYWFJZJZYWGYWFILYWFYWHXWHJZJZYWIYWGJYWFYWAYWHKZJZJZ
    YWKYWFYWLKZYWFJZJZYWNYWFYWOLYWFYWPYWMJZJZYWQYWNJYWRYWSYWLYWAMYWRYWFLNYWFYWP
    YWMONNYWFYWMYWJJZJZYWNYWKJYWTYXAXWHYWHMYWTYWFLNYWFYWMYWJONNYWFYWHXWHONNYWAV
    FMNYWDUBLNUBVFYWAONXWNYWBXWKJZJZYWCYVSJYXBYXCYWBUCKZYWAJZJZYXBYWBYXDYWBJZJZ
    YXFYWBYXDLYWBYXGYXEJZJZYXHYXFJYXIYXJYXGYXDUBJZJZYXIYXDYWBUBJZJZYXLYXDUCYWBK
    ZJZJZYXNYXDYXOKZYXDJZJZYXQYXDYXRLYXDYXSYXPJZJZYXTYXQJYYAYYBYXOUCMYYAYXDLNYX
    DYXSYXPONNYXDYXPYXMJZJZYXQYXNJYYCYYDUBYWBMYYCYXDLNYXDYXPYXMONNYXDYWBUBONYXG
    YXKYXEJJYXLYXIJYXDUBYWAOYXGYXKYXEONNYXIYWBLNYWBYXGYXEONNYWBYXEXWKJZJZYXFYXB
    JYYEYYFUCXWHMYYEYWBLNYWBYXEXWKONNYXBXWNLNXWNYWBXWKONNYVSQLNQXWNXWKONYVQVDLN
    VDXWOXWLONNVDXWLXWIJZJZXWMXWJJYYGYYHXWLXWHQXWHJZULJZJZJZYYGXWLYYJJZYYLQXWHU
    COXWLYYJYYKJZJZYYMYYLJYYNYYOYYJXWHLYYNXWLLNXWLYYJYYKONNXWLYYKXWIJZJZYYLYYGJ
    YYPYYQYYKXWHYYIJZJZYYPYYRYYSXWHQLYYRYYKLNYYKYYRXWIJJYYSYYPJXWHYYIULOYYKYYRX
    WIONNYYPXWLLNXWLYYKXWIONNYYGVDLNVDXWLXWIONNVDXWIXWFJZJZXWJXWGJYYTUUUAXWIXWH
    UNJZJZYYTXWHULUNJZJZUUUCUUUDUUUEXVDUUUDXVSUNULMNUUUDXWHLNXWHULUNONXWIUUUBXW
    FJZJZUUUCYYTJUUUFUUUGVFUMMUUUFXWILNXWIUUUBXWFONNYYTVDLNVDXWIXWFONNVDUMVFONX
    WDUMLNUMXWBVGONNXVTXUTLNXUTUMVGONNXUTVGXVAJZJZXVCXVBJUUUHUUUIXVAKZVHJZUUUHU
    UUJIUUUJJZJZUUUKUUUJILUUUJUUULVHJZJZUUUMUUUKJUUUJXVAUUULKZJZJZUUUOUUUJUUUPK
    ZUUUJJZJZUUURUUUJUUUSLUUUJUUUTUUUQJZJZUUVAUUURJUUVBUUVCUUUPXVAMUUVBUUUJLNUU
    UJUUUTUUUQONNUUUJUUUQUUUNJZJZUUURUUUOJUUVDUUVEVHUUULMUUVDUUUJLNUUUJUUUQUUUN
    ONNUUUJUUULVHONNXVAVGMNUUUHXUTLNXUTVGXVAONNUNVHMNXURVVNVIUKVHJZJZJZJZXURXUS
    JZUUVHUUVIVVNVIVVNJZJZUUVHVVNVILVVNUUVKUUVGJZJZUUVLUUVHJUUVMUUVNVIVVNUUVFJZ
    JZUUVMVIUKVIJZJZUUVPVIUKLVIUUVQUUVOJZJZUUVRUUVPJUUVSUUVTUKVBVHOUUVSVILNVIUU
    VQUUVOONNVIVVNUUVFONUUVMVVNLNVVNUUVKUUVGONNUUVHXURLNXURUUVHXUSJZJZUUVIUUVJJ
    XURVVNUUVGVVLJZJZJZUUWBXURUUWCJZUUWEXURVIUUVFUOJZJZJZUUWFXURUUWGJZUUWIXURUK
    XURJZJZUUWJXURUKLXURUUWKUUWGJZJZUUWLUUWJJUUWMUUWNUKVHUNOUUWMXURLNXURUUWKUUW
    GONNXURUUWGUUWHJZJZUUWJUUWIJUUWOUUWPUUWGVILUUWOXURLNXURUUWGUUWHONNXURUUWHUU
    WCJZJZUUWIUUWFJUUWQUUWRVIUUVFUOOUUWQXURLNXURUUWHUUWCONNXURUUWCUUWDJZJZUUWFU
    UWEJUUWSUUWTUUWCVVNLUUWSXURLNXURUUWCUUWDONNXURUUWDUUWAJZJZUUWEUUWBJUUXAUUXB
    VVNUUVGVVLOUUXAXURLNXURUUWDUUWAONNXURUUVHXUSONNNNVVLVUNLNVUNVIUOONNVUNUOVLJ
    ZJZVUPVUOJUUXCUUXDVLKZUPJZUUXCUUXEIUUXEJZJZUUXFUUXEILUUXEUUXGUPJZJZUUXHUUXF
    JUUXEVLUUXGKZJZJZUUXJUUXEUUXKKZUUXEJZJZUUXMUUXEUUXNLUUXEUUXOUUXLJZJZUUXPUUX
    MJUUXQUUXRUUXKVLMUUXQUUXELNUUXEUUXOUUXLONNUUXEUUXLUUXIJZJZUUXMUUXJJUUXSUUXT
    UPUUXGMUUXSUUXELNUUXEUUXLUUXIONNUUXEUUXGUPONNVLUOMNUUXCVUNLNVUNUOVLONNVJUPM
    NVULUHLNUHUPVJONN $.
    $( [?] $) $( [14-Jan-2013] $)
